>input_001.bnk
G---TGGTCCAGGAGGTGGCgCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-Tc-tcCTCCT--------------ATCTTT-------------
------CTC----AT-------AAT-AAATAAATAAA----T-----aAtTAAAaAAAtA
A-----------------------------------------------------------
----------------------------------------------------
>input_029.bnk
G---TGGTCCAGGAGGTGGCGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCgGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-Tc-TCCTCCT--------------ATCTTT-------------
------CTC----AT-------AAT-AAATAAATAAA----A-----TTTtAAAAAAAa-
------------------------------------------------------------
----------------------------------------------------
>input_033.bnk
G---TGGTCCgGGAGGTGGtGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT-------AAT-AAATAAATAAA----a-----TTTTTAAAAAAAA
------------------------------------------------------------
----------------------------------------------------
>input_031.bnk
G---TGGTCcGGGAGGTGGCGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCGATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT-------AAT-AAATAAATAAA----A-----TCTTTTaAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_153.bnk
G---TGGTCcGGGAGGTGGTGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCtGAGTTCAATCCCCaGC--AGCACA-TGTACCAGAGTG---ATG-tctgG-TTCT
TTC---------TCTC-Tc-TCttCCT--------------aTCTTT-------------
------CTC----AT-------aat-AAATAAATAAA----a-----TTTAAAAAAAaa-
------------------------------------------------------------
----------------------------------------------------
>input_120.bnk
G---TGGTCcaGGAGGTGGCaCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCtGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------atctTT-------------
------CTC----AT-------AAT-AAATAAAtaaT----T-----TtAAAAAAAa---
------------------------------------------------------------
----------------------------------------------------
>input_139.bnk
G---TGGTCCAGGAGGTGGCGCAGTGG----ATAAAGCATTGGAtTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCtGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCcTCCT--------------ATCTTT-------------
------CTC----AT------AATA-AATAAAaTAAA----A-----TCTTAAAAAAaaA
------------------------------------------------------------
----------------------------------------------------
>input_002.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----ATAAaGCAcTGGACTCTCAA---GCATGA
GGTCCTGAGTTCGATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TcCTCCT--------------ATCTTT-------------
------CTC----AT------GAAT-AAATAAATAAA----A-----TaTTaAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_063.bnk
G---TGGTCCGGGAGGTGGcGCAGTGG----ATAAAGCATTGGAcTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----tCcTCCT--------------ATCTTT-------------
------CTC----AT------gAAT-AAATAAATAAA----a-----TCTTaAAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_060.bnk
G---TGGTCtGGGAGGTGGCaCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCcTCCT--------------ATCTTT-------------
------CTC----AT------GAAT-AAATAAATAAA----A-----tTtaAAAAAAAAa
------------------------------------------------------------
----------------------------------------------------
>input_007.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----ATAAAGCATCGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGGGTG---ATG-CCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATGTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_035.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGgGTG---ATG-tCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATGTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_009.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----ATAAAGCATCGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-CTCT
TTC---------TCTC----TCCTCCT--------------ATGTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TcTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_036.bnk
G---TGGTCCGGGAGGTGGCaCAGTGG----ATAAAGCATcGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-CTCT
TTC---------TCTC----TCCTCCT--------------ATGTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_027.bnk
G---TGGTCCAGGAGGTGGTGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TcTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_091.bnk
G---TGGTCtGGGAGGTGGCGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCtGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TcTTTAAAAAAAA
Aa----------------------------------------------------------
----------------------------------------------------
>input_070.bnk
G---TGGTCcgGGAGGTGGcgCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCAGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TcCTCCT--------------ATCTTT-------------
------CTC----AT------tAAT-AAATAAATAAA----A-----TcTTTTAAAAAAA
Aaa---------------------------------------------------------
---------------------------------------------------a
>input_048.bnk
G---TGGTCCAGGAGGTGGCgCAGTGG----CTAAGGCACTgGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCtTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TTTTtaAAAAAAa
------------------------------------------------------------
----------------------------------------------------
>input_090.bnk
G---TGGTCcGGGAGGTGGCACAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC----AT-------AAT-AAATAAAtaaA----A-----TCTTAAAAAAAaA
A-----------------------------------------------------------
----------------------------------------------------
>input_122.bnk
G---TGGTCtGGGAGGTGGcgCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCtGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
T-c---------TCTC-Tc-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTtAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_041.bnk
G---TGGTCCAGGAGGTGGCGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTCTC-------TCTC-tc-tcCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_072.bnk
G---TGGTCCAGGAGGTGGCaCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
tTCTC-------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TTTTtAAAAAaa-
------------------------------------------------------------
----------------------------------------------------
>input_155.bnk
g---TGgTCTGGGAGGTGGTGCAGTGG----ATAAAGcATTGGACTCTCAA---GCATGA
GGTCCtgAGTTCAATCCCtaGC--AGCACA-TGTACCAGAGTG---ATG-tCTGG-TTCT
cTCTC-------TCTC-TC-TCctCCT--------------aTCTcT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TcTTTAAAAAAaa
a-----------------------------------------------------------
----------------------------------------------------
>input_143.bnk
G---TGGTCcgGGAGGTGGCACAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCcGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTcTt-------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----a-----tTTAAAAAAAAA-
------------------------------------------------------------
----------------------------------------------------
>input_003.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----CTAAGGCACTAGACTCTCAA---GCATGA
GGTCCTGAGTTCGATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-GCTGG-TTCT
TTC---------TCTC------CTCCT--------------ATCTTT-------------
------CTC----AT------GAAT-AAATAAATAAA----T-----TcTTTAAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_004.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----ATAAAGCACTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCAGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC------CTCCT--------------ATCTTT-------------
------CTC----AT------GAAT-AAATAAATAAA----T-----TCTTTAAAAAAAa
a-----------------------------------------------------------
----------------------------------------------------
>input_020.bnk
G---TGGTCCGGGAGGTGGCACAGTGG----ATAAAGCATTGGATTCTCAA---CCATGA
GGTCCTGAGTTCGATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC------CTCCT--------------ATCTTT-------------
------CTC----AT------GAAT-AAATAAATAAA----T-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_124.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----ATAAAGCATTGGATTCTCAA---CCATGA
GGTCCcGAGTTCAATCCCcGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC------tTCCT--------------aTCTTT-------------
------CTC----AT------GAAT-AAATAAATAAA----t-----TTTTAAAAAAAaa
------------------------------------------------------------
----------------------------------------------------
>input_018.bnk
G---TGGTCCGGGAGGTGGCACAGTGG----ATAAAGCATTGGATTCTCAA---CCATGA
GGTCCTGAGTTCGATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC------CTCCT--------------ATCTTT-------------
------CTC----AT------GAAT-AAATAAATAaa----t-----AATTTTAAAAAAA
AA----------------------------------------------------------
----------------------------------------------------
>input_019.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----ATAAAGCATTGGATTCTCAA---CCATGA
GGTCCTGAGTTCGATCCCtGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC------CTCCT--------------ATCTTT-------------
------CTC----AT------GAAT-AAATAAATAaa----a-----aTTcTTTAAAAAA
AAA---------------------------------------------------------
----------------------------------------------------
>input_021.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----ATAAAGCATTGGATTCTCAA---CCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC--tcTCCT--------------ATCTTT-------------
------CTC----AT------GAAT-AAATAAATAAA----t-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_024.bnk
G---TGGTCCgGGAGGTGGCGCAGTGG----ATAAAGCATTGGATTCTCAA---GCATGA
GGTCCtGAGTTCAATCCCtGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC--TCCTCT--------------ATCTtT-------------
------CTC----AT------GAAT-AAATAAATAAA----A-----TcTTTAAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_043.bnk
G---TGGTCCAGGAGGTGGCGCAGTGG----CTAAGGCACTAGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC--TCCCCT--------------ATCTTT-------------
------CTC----AT------aAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_025.bnk
G---TGGTCCAGGAGGTGGCACAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC--TCTCCT--------------ATCTTT-------------
------CTC----AT------tAAT-AAATAAATAAA----A-----TTTTtAAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_126.bnk
G---TGGTCCaGGAGGTGGtGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-Tc--CCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TtTTTAAAAAAAa
a-----------------------------------------------------------
----------------------------------------------------
>input_084.bnk
G---TGGTCTGGGAGGTGGCACAGTGG----ATAAaGCATTGGACTCTCAA---GCATGA
GGTCCCAAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC--cCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TTTTAAAAAAAa-
------------------------------------------------------------
----------------------------------------------------
>input_146.bnk
G---TGGTCtGGGAGGTGGcaCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCaGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC--TCcCCT--------------ATCTTT-------------
------cTC----AT------tAAT-AAATAAATAAA----A-----TTTaAAAAAAAAa
------------------------------------------------------------
----------------------------------------------------
>input_145.bnk
G---TGGTCCaGGAGGTGGCACAGTGG----ATAAAGCAtTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
tTC---------TCTc-TC--TCCTcC--------------TTCTcT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TTTtAAAAAAaAA
------------------------------------------------------------
----------------------------------------------------
>input_022.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----ATAAAGCACTGGATTCTCAA---CCATGA
GGTCCTGAGTTCAATCCCcGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-----TCtCCT--------------ATCTTT-------------
------CTC----AT------GAAT-AAATAAATaat----T-----TCTTTAAAAAAAa
a-----------------------------------------------------------
----------------------------------------------------
>input_064.bnk
G---TGGTCCGGGAGGTGGtGCAGTGG----ATAAAGCACTGGATTCTCAA---CCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-----TCTCCT--------------ATCTTT-------------
------CTC----AT------GAAT-AAATAAATAAA----T-----TcTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_023.bnk
G---TGGTCcGGGAGGTGGCaCAGTGG----ATAAAGCATTGGATTCTCAA---CCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-----TCTCCT--------------ATCTTT-------------
------CTC----AT------GAAT-AAATAAATAAA----T-----TCTTtAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_065.bnk
G---TGGTCCaGGAGGTGGCGCAGTGG----ATAAAGCACTGGATTCTCAA---CCATGA
GGTCCTGAGTTCAATCCCtGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCtT-----CCTCCT--------------ATCTTT-------------
------CTC----AT------GAAT-AAATAAATAAA----T-----TCTTTAAAAAAaA
a-----------------------------------------------------------
----------------------------------------------------
>input_061.bnk
G---TGGTCCgGGAGGTGGCACAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-T--tCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----t-----tATTTtAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_005.bnk
G---TGGTCCGGGAGGTGGCaCAGTGG----ATAAAGCATTGGATTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCtGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTc---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----a-----TTTTAAAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_008.bnk
G---TGGTCCGGGAGGTGGCgCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCAGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
Ttc---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TcTTAAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_032.bnk
G---TGGTCCgGGAGGTGGCgCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCgGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-tc-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TcTTaAAAAAAAa
a-----------------------------------------------------------
----------------------------------------------------
>input_095.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTaAAAAAAAA
------------------------------------------------------------
----------------------------------------------------
>input_135.bnk
G---TGGTCTGGGAGGTGGCgCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCAGC--AGCACA-TGTACCAGAGTG---ATg-TCTGG-TTCT
TTC---------TCTc-Tc-TCctCCT--------------ATCTTT-------------
------CTC----AT------tAAT-AAATAAATAAA----A-----TCTTaAAAAAAAa
A-----------------------------------------------------------
----------------------------------------------------
>input_049.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----ATAAAGCAtTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
Ttc---------TCTC-TC-TCCTCCT--------------ATcTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TTTtAAAAAAAAa
------------------------------------------------------------
----------------------------------------------------
>input_069.bnk
G---TGGTCcGGGAGGTGGtGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCgGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
tTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAa----A-----TTTTAAAAAAaaa
------------------------------------------------------------
----------------------------------------------------
>input_089.bnk
G---TGGTCtGGGAGGTGGtGCAGTGG----ATAAAGCAtTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCgGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCtcCT--------------atCTTT-------------
------CTC----AT------tAAT-AAATAAATAAA----a-----tTTTaAAAAAAaA
------------------------------------------------------------
----------------------------------------------------
>input_080.bnk
G---TGGTCTGGGAGGTGGCACAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCAGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCcTCCT--------------ATCTTT-------------
------CTC----AT------taAT-AAATAAATAAA----A-----TTTtAAAAAAAAa
------------------------------------------------------------
----------------------------------------------------
>input_125.bnk
G---TGGTCcGGGAGGTGGtaCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCAGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TTTTAAAAAAAaa
------------------------------------------------------------
----------------------------------------------------
>input_136.bnk
G---TGGTCCGGGAGGTGGCACAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCCGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATg-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----a-----TTTTAAAAAAaaa
------------------------------------------------------------
----------------------------------------------------
>input_068.bnk
G---TGGTCTGGGAGGTGGCgCAGTGG----ATAAAGCACTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCtC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TTTTAAAAAAAAa
------------------------------------------------------------
----------------------------------------------------
>input_127.bnk
G---TGGTCtGGGAGGTGGCGCAGTGG----ATAAAGCAcTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------aTCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----tcTTAAAAAAAAa
------------------------------------------------------------
----------------------------------------------------
>input_129.bnk
G---TGGTCtGGGAGGTGGCaCAGTGG----ATAAAGCAcTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCtGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TTTTAAAAAAAA-
------------------------------------------------------------
----------------------------------------------------
>input_053.bnk
G---TGGTCTGGGAGGTGGCACAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCcTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----a-----TttaAAAAAaAA-
------------------------------------------------------------
----------------------------------------------------
>input_144.bnk
G---TGGTCTGGGAGGTGGCACAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCcAGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------aTCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----a-----TTTAAAaAAAaa-
------------------------------------------------------------
----------------------------------------------------
>input_132.bnk
G---TGGTCcgGGAGGTGGCgCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCaGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------tAAT-AAATAAATAAA----A-----TTTaAAAAAAAaa
------------------------------------------------------------
----------------------------------------------------
>input_078.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----ATAAaGCATTGGACTCTCAA---GCATGA
GGTCCtgAGTTCAATCCCCAGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-Tc-tCCTCCT--------------ATCTTT-------------
------CTC----AT------GAAT-AAATAAATaAa----a-----TTTAAAAAAAAA-
------------------------------------------------------------
----------------------------------------------------
>input_083.bnk
G---TGGTCCGGGAGGTGGTGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCtcct--------------aTcTTT-------------
------CTC----AT------tAAT-AAATAAATAAA----A-----TTTAAAAAAAAAa
------------------------------------------------------------
----------------------------------------------------
>input_152.bnk
G---TGGTCcaGGAGGTGGtgCAGTGG----ATAAAGCATTGGAcTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCtgGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTc---------TCTC-TC-TCcTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TTTAAAAAAAA--
------------------------------------------------------------
----------------------------------------------------
>input_150.bnk
G---TGGTCCaGGAGGTGGCaCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTgAGTTCAATCCCtGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCtCCT--------------aTCTTT-------------
------cTC----AT------tAAT-AAATAAATAAA----A-----tTTaAAAAaaa--
------------------------------------------------------------
----------------------------------------------------
>input_006.bnk
G---TGGTCTGGGAGGTGGCACAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAa
a-----------------------------------------------------------
----------------------------------------------------
>input_013.bnk
G---TGGTCCGGGAGGTGGCACAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_052.bnk
G---TGGTCcGGGAGGTGGCaCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TcTTTAAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_034.bnk
G---TGGTCTGGGAGGTGGCgCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------tAAT-AAATAAATAAA----a-----TCTTTAAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_016.bnk
G---TGGTCCGGGAGGTGGCgCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TTTTTaAAAAAAA
------------------------------------------------------------
----------------------------------------------------
>input_037.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_058.bnk
G---TGGTCcGGGAGGTGGCgCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-Tc-tCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_086.bnk
G---TGGTCCgGGAGGTGGcGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCgGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TcCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>e1-1_CONSENSUS
G---TGGTCCGGGAGGTGGCGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_123.bnk
G---TGGTCCGGGAGGTGGCgCAGTGG----ATAAAGCAcTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTc-tc-TCCTCCT--------------ATCTTT-------------
------CTC----At------taat-AAATAAATAAA----A-----TcTTTAAAAAAAA
Aa----------------------------------------------------------
----------------------------------------------------
>input_038.bnk
G---TGGTCCGGGAGGTGGCACAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TcTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_050.bnk
G---TGGTCcGGGAGGTGGCaCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCtGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
Aa----------------------------------------------------------
----------------------------------------------------
>input_042.bnk
G---TGGTCCAGGAGGTGGCACAGTGG----ATAAAGCAtTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_076.bnk
G---TGGTCtGGGAGGTGGCACAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCtc-tc-TCCTCCT--------------ATCTTT-------------
------CTC----AT------tAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_140.bnk
g---TGGTCTGGGAGGTGGCaCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCtGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCtc-tc-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAAtaAA----A-----TCTTtAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_092.bnk
G---TGGTCCgGGAGGTGGTaCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCtGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-tCcTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TcTTtAAAAAaAA
Aa----------------------------------------------------------
----------------------------------------------------
>input_134.bnk
G---TGGTCCGGGAGGTGGCgCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCaGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TTTTtaAAAAaa-
------------------------------------------------------------
----------------------------------------------------
>input_062.bnk
G---TGGTCcGGGAGGTGGtGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATaAa----a-----TtTTTAAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_138.bnk
G---TGGTCCgGGAGGTGGTGCAGTGG----ATAAAGCaTTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
tTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TaTTtaAAAAAaa
a-----------------------------------------------------------
----------------------------------------------------
>input_073.bnk
G---TGGTCCgGGAGGTGGCGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCgGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------tAAT-AAATAAATAAA----A-----TATtTaaAAAaAA
A-----------------------------------------------------------
----------------------------------------------------
>input_087.bnk
G---TGGTCtGGGAGGTGGCGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TcCtccT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TaTTTAAAAAAaa
a-----------------------------------------------------------
----------------------------------------------------
>input_148.bnk
G---TGGTCtGGGAGGTGGCACAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCaATCCCcGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTc---------TCTC-TC-tccTCCT--------------ATCTtT-------------
------CTC----AT------tAAT-AAATAAATAAA----A-----tATTtAAAAaAa-
------------------------------------------------------------
----------------------------------------------------
>input_017.bnk
G---TGGTCCGGGAGGTGGCACAGTGG----ATAAAGCACTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TTTttaAAAAAAa
------------------------------------------------------------
----------------------------------------------------
>input_077.bnk
G---TGGTCCGGGAGGTGGCaCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCCGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-tc-tcCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAa----A-----TTTTTAAAAAAaa
a-----------------------------------------------------------
----------------------------------------------------
>input_051.bnk
G---TGGTCCgGGAGGTGGCACAGTGG----ATAAAGCACTgGACTCTCAA---GCaTGA
GGTCCTGAGTTCAAtCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------cAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_030.bnk
G---TGGTCCGGGAGGTGGCaCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------gAAT-AAATAAATAAA----A-----TcTTTAAAAAAAa
a-----------------------------------------------------------
----------------------------------------------------
>input_039.bnk
G---TGGTCCGGGAGGTGGCgCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCgGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------tAAT-AAATAAATAAA----A-----TCTTTtAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_028.bnk
G---TGGTCTGGGAGGTGGTGCAGTGG----ATAAAGCAtTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCaGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
------------------------------------------------------------
----------------------------------------------------
>input_082.bnk
G---TGGTCCGGGAGGTGGCACAGTGG----ATAAAGCACTGGACTCTCAA---GCATGA
GGTCCCGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-tc-tcCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TATTTAAAAAAaA
------------------------------------------------------------
----------------------------------------------------
>input_079.bnk
G---TGGTCCaGGAGGTGGCACAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCtGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-tCCTCCT--------------aTCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TATTAaAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_044.bnk
G---TGGTCCGGGAGGTGGcGCAGTGG----CTAAGGCACTAGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TcCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_045.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----cTAAgGCACTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_015.bnk
G---TGGTCTGGGAGGTGGCGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCaGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
Ttc---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------aAAT-AAATAAATAAA----t-----TCTTTAAAAAAAa
a-----------------------------------------------------------
----------------------------------------------------
>input_026.bnk
G---TGGTCCgGGAGGTGGTGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCcGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCTTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TATTTTTAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_088.bnk
G---TGGTCCgGGAGGTGGCaCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATg-TCTGG-TTCT
TTC---------TCTC-TC-TcCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----a-----TaTTTttAAAAAA
aA----------------------------------------------------------
----------------------------------------------------
>input_059.bnk
G---TGGTCCGGGAGGTGGCACAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCAGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-Tc-tcCTCCT--------------ATCTTT-------------
------CTC----AT------gAAT-AAATAAATAAA----A-----TATtTtAAAAAaA
a-----------------------------------------------------------
----------------------------------------------------
>input_081.bnk
G---TGGTCCAGGAGGTGGCGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCgGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTCT-------------
------CTC----AT------TAAT-AAATAAATAaA----T-----TTTAAAAAaAa--
------------------------------------------------------------
----------------------------------------------------
>input_040.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----ATAAAGCGCTgGACTCTCAA---GCGTGA
GGTCCTGAGTTCAAGCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
Ttc---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------CAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_121.bnk
G---TGGTCcgGGAGGTGGCACAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-Tc-TCCTCCT--------------ATCTTT-------------
------CTC----AT------tAAT-AAATAAAAAAa----a-----AAtttAAAAAAa-
------------------------------------------------------------
----------------------------------------------------
>input_066.bnk
G---TGGTCcGGGAGGTGGTGCAGTGG----ATAAAGCATTGGATTCTCAA---CCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTc---------CTCT-Cc-tcCTCCT--------------ATCTTT-------------
------CTC----AT------GAAT-AAATAAATAAA----T-----TCTTtAAAAAAAa
a-----------------------------------------------------------
----------------------------------------------------
>input_067.bnk
G---TGGTCTGGGAGGTGGtGCAGTGG----ATAAAGCATTGGATTCTCAA---CCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTc-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------gAAT-AAATAAATAAA----T-----TCTTTAAAAAAAa
a-----------------------------------------------------------
----------------------------------------------------
>input_010.bnk
G---TGGTCCAGGAGGTGGCACAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-ctCct-----------------atTTT-------------
------CTC----AT------tAAT-AAATAAATAAA----A-----TTTTTtAAAAAAA
------------------------------------------------------------
----------------------------------------------------
>input_057.bnk
G---TGGTCCGGGAGGTGGtgCAGTGG----ATAAAGCAtTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-CTCT
TTC---------TCTC-TC-ctCCT-----------------ATTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTtAAAAAAa
AA----------------------------------------------------------
----------------------------------------------------
>input_046.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----CTAAGGCACTAGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-----TCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_093.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCcGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TcCCT-----------------TCTTT-------------
------CTC----AT------tAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_074.bnk
G---TGGTCCGGGAGGTGGcGCAGTGG----aTAAgGCACTAGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TCTCtcTcCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TcTTtaaAAAAAa
a-----------------------------------------------------------
----------------------------------------------------
>input_142.bnk
G---TGGTCcGGGAGGTGGCaCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TCtTCCtCCT--------------ATCTTT-------------
------CTC----AT------GAAT-AAATAAATAAA----t-----TTTttAAAAaaa-
------------------------------------------------------------
----------------------------------------------------
>input_156.bnk
G---TGGTCcgGGAGGTGGcGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCcgAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
CTC---------TCTCcTC-TCCTCCT--------------ATCTcT-------------
------CTC----AT------TAAT-AAATAAATAAA----a-----ttTTaAAAAaaa-
------------------------------------------------------------
----------------------------------------------------
>input_011.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----ATAAGGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTATC----------------ATTT-------------
------CTC----AT------GAAT-AAATAAATAAA----A-----TCTTAAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_094.bnk
G---TGGTCCgGGAGGTGGtGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCtGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TcCCTAT---------------CaTTT-------------
------CTC----AT------GAAT-AAATAAATAAA----A-----TcTTaAAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_012.bnk
G---TGGTCtGGGAGGTGGtGCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTaAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTatt--------------ATc-TT-------------
------CTC----AT------TAAT-aAATAAATAAA----A-----TCTTTAAAAAAAA
------------------------------------------------------------
----------------------------------------------------
>input_137.bnk
G---TGGTCtGGGAGGTGGcaCAGTGG----ATAAAGCAtTGGACTCTCAA---GCATGA
GGTCCCaAGTTCAATCCCCAGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTc-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------tAAT-AAATAAaAAA-----------tTTTAAAAAAAaA
------------------------------------------------------------
----------------------------------------------------
>input_014.bnk
G---TGGTCCAGGAGGTGGCGCAGTGG----ATAAAGCACTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC--TCTCCT--------------ATCTTT-------------
------CTC----AT-------AAT-AAATAAATAAA----t-----aAaTAAAAAAAaA
Aa----------------------------------------------------------
----------------------------------------------------
>input_158.bnk
g---TGGTCcgGGAGGTGGCaCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAaTCCCCaGC--AGCACA-TGTACCAGAGTG---ATg-TCTGG-TTCT
TTC---------TCTC-Tt-cttct-----------------TcTtT-------------
------cTC----AT------tAAT-AAAtAAattAA-----------------AaAaa-
------------------------------------------------------------
----------------------------------------------------
>input_054.bnk
G---TGGTCTGGGAGGTGGC-CAGTGG----ATAAAGCAtTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCAGC--AGCACA-TGTACCAGAGTG---ATA-TCTGG-TTCT
Ttc---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TaTTTAAAAAAAA
Aa----------------------------------------------------------
----------------------------------------------------
>input_130.bnk
G---TGGTCCgGGAGGTGGC-CAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCtGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------tAAT-AAATAAATAAA----a-----tTAAAAAaa----
------------------------------------------------------------
----------------------------------------------------
>input_157.bnk
G---TGGTCcGGGAGGTGGT-CAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCcgGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTcT
TTcTct------tCTC-TC-TCCTCCT--------------aTCTTT-------------
------CTC----AT------tAAT-AAATAAATAAA----T-----tTTAAAAAAa---
------------------------------------------------------------
----------------------------------------------------
>input_141.bnk
G---TGGTCtgGGAGGTGGC-CAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCcgGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATaaAaATAAAa-a-----TtTTTAAAAAaa-
------------------------------------------------------------
----------------------------------------------------
>input_055.bnk
G---TGGTCtGGGAGGTGGCACAGTGG----ATAAAGtATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC--TctcCT--------------ATCTTT-------------
------CTC----AT---------T-aAATAAATAAA----A-----taTTTTAAAAAAa
a-----------------------------------------------------------
----------------------------------------------------
>input_075.bnk
G---TGGTCCGGGAGGTGGCGCAGTGG----CTAAGGCACTAGACTCTCAA---GCATGA
GGTCCTGAGTTCgATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-gCTGG-TTCT
TTC---------TCTC-t--tccTCCT--------------ATCTTT-------------
------CTC----AT------tAAT-AAATAAATAAA----T-----TTTAAAAAAAAAa
------------------------------------------------------------
----------------------------------------------------
>input_128.bnk
G---TGGTCCAGGAGGTGGCgCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCtGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC-TC-TCTCTCTCTCT----------CTCTCt-------------
------ctt----at------taAT-aAATAAATAAA----A-----TTTAAAAAaaaaa
------------------------------------------------------------
----------------------------------------------------
>input_096.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----GTAAAGCTTTGGACTCTCAA---GCATGA
GGTCCtGAGTTCGATCCCCgGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC----AT------aAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_111.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCCTGAGTTCGATCCCCGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC----AT------AAAT-AAATAAatAAA----A-----TcTTTAAAAAAAa
a-----------------------------------------------------------
----------------------------------------------------
>input_118.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCCtGAGTTCGATCCCCGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTc----TCCTCCT--------------ATCTTT-------------
------CTC----AT------AAAT-AAATAaatAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_101.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCCTGAGTTCGATCCCTGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC----AT------AAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_102.bnk
G---TGGTCCAGGAGGTGGCGCAGTG-----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCCTGAGTTCGATCCCCGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_112.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCCTGAGTTCGATCCCCGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_104.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCCTGAGTTCGATCCCTGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_103.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCCTGAGTTCGATCCCCGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAAT-AAATAAATAAA----A-----TCTTaAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_097.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCCTGAGTTCGATCCCCGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC--------------AT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_108.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----aTAAAGCTTTGGACTCTCAA---GCATGA
GGTCCTGAGTTCGATCCCCGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC--------------AT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_114.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCCTGAGTTCGATCCCCGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC--------------AT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_098.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----GTAAAGCTTTGGACTCTCAA---GCATGA
GGTCCTGAGTTCGATCCCCGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC--------------AT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_099.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----GTAAAGCTTTGGACTCTCAA---GCATGA
GGTCCCGAGTTCGATCCCCGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC--------------AT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_100.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCCCGAGTTCGATCCCCGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------aTCTTT-------------
------CTC--------------AT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_105.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCCCGAGTTCGATCCCCgGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC--------------AT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_107.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCCcGAGTTCGATCCCCGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC--------------AT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_116.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCCCGAGTTCGATCCCCGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC--------------AT-AAATAAATAAA----A-----TCTTTAAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_106.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----GTAAAGCTTTGGACTCTCAA---GCATGA
GGTCCCGAGTTTGATCCCCGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC--------------AT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_109.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCCTGAGTTCGATCCCtGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC--------------AT-AAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_113.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCCcGAGTTCGATCCCcGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC--------------AT-AAATAAATAAA----A-----TCTTTtAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_110.bnk
G---TGGTCCGGGAGGTGGCGCAGTG-----gTAAAGCTTTGGACTCTCAA---GCATGA
GGTCCCAAGTTCGATCCCCGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC--------------AT-AAATAAATAAA----A-----ttTTTTAAAAAAA
AA----------------------------------------------------------
----------------------------------------------------
>input_117.bnk
G---TGGTCCaGGAGGTGGCGCAGTG-----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCCTGAGTTCGATCCCCAGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC----AT-------AAT-AAATAAATAAA----A-----TCTTAAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_119.bnk
G---TGGTCCaGGAGGTGGCgCAGTG-----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCC-GAGTTCGATCCCcGGC--AGCACA-TGTGCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC----AT------aAAT-AAATAAATAAA----A-----TTTTAAAAAAAaa
------------------------------------------------------------
----------------------------------------------------
>input_056.bnk
G---TGGTCCGGGAGGTGGTGCAGTGA----CTAAAGCcTTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCT--tc-tcctcct--------------aTCTTT-------------
------CTC----AT------TAAT-AAATAAATtaA----A-----AATgTTAAAAAAA
a-----------------------------------------------------------
----------------------------------------------------
>input_047.bnk
G---TGGTCCGGGAGGTGGCaCAGTGG----CTAAGGAACTAGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-CTCT
TTC---------TCTC-TC-TCCTCCT--------------ATCTTT-------------
------CTC----AT------TAATaAAATAAATAAA----A-----TCTTTAAAAAAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_115.bnk
G---TGGTCCaGGAGGTGGCgCAGTgG----ATAAAGCTTTGGACTCTCAA---GCATGA
GGTCCTGAGTTCgATCCCCGGC--AGCACA-TGTaCCAGAGTG---ATG-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------ATCTTT-------------
------CTC----AT------AAAT-AAATAAATAAA----T-----AAATAAATAAATA
Aa----------------------------------------------------------
----------------------------------------------------
>input_071.bnk
G---TGGTCTGGGAGGTGGCgCAGTGG----ATAAAGCAtTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTcTcTcC----TCTC-TC-TctTCCT--------------ATCTTT-------------
------CTC----ata---ATAAAT-AAATAAAtAAt----T-----TTTTAAAAAAAa-
------------------------------------------------------------
----------------------------------------------------
>input_131.bnk
G---TGATCCGGGAGGTGGCgCAATGG----ATAAAGCACTGAACTCTCAA---GCATGA
GGTCCCGAGTTCAACCCCCGGC--AGCACA-TGTACCaGTGTG---ATG-TCTGG-TTCT
Ttc---------TCTC-TC-TCCTCCT--------------ATCATT-------------
------CTC----AT------TAAT-AAATAAATAAAtaaAT-----AtTTAAAaAAA--
------------------------------------------------------------
----------------------------------------------------
>input_133.bnk
G---TGGTCcGGGAGGTGGCACAGTaG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCaATCCCCaGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
TTCt--------TCTC-Tc-TcCTcCT--------------ATCTTT-------------
------CTC----AT------A----TAATAAATAAA----A-----TtTTTAAAAAAAa
------------------------------------------------------------
----------------------------------------------------
>input_159.bnk
G---TGGTCcgGGAGGTGGtgCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCAGC--AGCACA-TGTACCAGAGTG---AtT-TCTGG-TTCT
tTT---------CTtc-Tt-tTtCT-----------------TcTct-------------
------cTc----AT-------AaT-aAATAAAtaAt-------------ttaaaaa---
------------------------------------------------------------
----------------------------------------------------
>input_166.bnk
----gtGGTCcGGAGGTGGcACAGTGG----ATAAAGTgTTGGACTCTCAA---GCATGA
GGTCCTGAGTTTGATCCCTGGC--AgcACA-TGTACCAGAGTG---ATg-TCTGg-TTcT
cTc---------TCTC-TC--cCTCCT--------------aTCTcT-------------
------CTC----AT-------AAT-AAATAAAtaAA----a-----TTTtaaaaa----
------------------------------------------------------------
----------------------------------------------------
>input_085.bnk
G---TGGTCTGGGAGGTGTCGCAGTGG----ATAAGGCGTTAGACTCTCAA---GCATGA
GGTCCCAAGTTCGATCCCTGGC--AGCACA-TGTACCAGAAAG---ATA-TCTGG-TTCT
TTC---------TCTC----TCCTCCT--------------cTCTTT-------------
------CTC----AT------TAAT-AAATAAATTAA----A-----ATgTTTAAAAAAA
aa----------------------------------------------------------
----------------------------------------------------
>input_149.bnk
----GTGGTCcGGAGGTGGcaCAGTGG----ATAAAG-ATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGGTtTCT
tTC---------TCTC-TC-TCcTCCT--------------ATCTTT-------------
------CTC----AT------tAAT-AAATAAATAAA----A-----TtTTtAAAaAAaa
a-----------------------------------------------------------
----------------------------------------------------
>input_151.bnk
G---TGGTCcaGGAGGTGGTgCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCcG----CACACA-TGTACCAGAGTG---ATGcTCTGG-TTCT
CTc---------TCTC-Tc-TCttCCT--------------aTCTcT-------------
------CTC----AT------tAAT-AAATAAAtAaa----A-----TTTAAAAAaaaa-
------------------------------------------------------------
----------------------------------------------------
>input_165.bnk
------gGCtgGGAGGTGGTGCAGTGG----ATAAAaTgTTGGACTcTCAA---GCATGA
GGTCCTGAGTTCAATCCCcaGC--A-caCA-TGTgCCAGAGTG---ATGCTCTGG-TTCT
CTC---------TCTC-TC-TCTCtcT--------------CTCTCT-------------
------ctc-----T------TaAT-AAATAAATAAA----a-----tTTTAAAaAaa--
------------------------------------------------------------
----------------------------------------------------
>input_167.bnk
-------tgCgGGAGGTGGtgCAGTGG----ATAAAGC-TTGGACTCTCAA---GCATGA
GGTCCtGAGTTtaATCCCCaGC--A-caCA-TGTGCCAGAgTG---ATGcTCTg--TTCT
CTC---------TCTC-TC-TCTCTCT--------------CTCTCT-------------
---ctcCTC----AT------TAAT-AAATAAATAAA----t-----tTTTaAAAAaAAa
------------------------------------------------------------
----------------------------------------------------
>input_168.bnk
G---TGGtCtgGGAGGTGGcgCAGTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCaGC--AgCACA-TGTACCAGAGTG---ATGTCTtGG-TTCT
cTC---------TCTC-TC-TCTCTCT--------------CTCTCTCTCTCTCTCTCTC
TCttctcTc----AT------tAAT-AAATAAATAAA----T-----TtTTaAAAAAa--
------------------------------------------------------------
----------------------------------------------------
>input_161.bnk
----gTGGcCcGGAGGTGGTGCAGTGG----ATAAAGCATTGGACTCtCAA---GCATGA
GGTCCTGAGTTtgATCCCCaGC--AtcACA-TGTgCCAGAGTG---ATGCTCTGG-TTcT
cTCTCTctTCTCTCTC-TC-TCTcTCT--------------CTCTCT-------------
------CTc----At------TAAt-AAATAAATAAA----a-----tTTaAAAaAa---
------------------------------------------------------------
----------------------------------------------------
>input_181.bnk
----gtggtCcGGAgGTGGG-CAGTGG----aTAAAGcaTTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCaGC--AtcACA-TGTgCCAGAGTG---ATGcTCTGG-TTcT
tTC---------TCTC-tC-TcttTctcT------------ttcTcT-------------
------CTc----at------tAAT-AAATAaAtAAt----t-----att----------
------------------------------------------------------------
----------------------------------------------------
>input_163.bnk
--------gCggGAGGTGGt-CAGTGG----ATAAAGcaTTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCAGC--ATcgCA-TgTGCCAGAGTG---ATGCTCTGG-TTcT
Ctc---------TCTC-tc-tCcCT----------------CttCtT-------------
------CTC----AT------TAAT-AAATAAATAAA----c-----TTTAAAAAAaA--
------------------------------------------------------------
----------------------------------------------------
>input_182.bnk
------tgGCcGGAGGTGGt-CAGTGG----aTAAAGT-TTGGACTttcAA---GCATGA
GGTCCTGAGTTtgATCCCCAGC-----ACA-TGTGCCAGAGTG---ATGtTCTGG-TTCT
cTt---------TCTC-TC-TCtct----------------cTcTCT-------------
------CTC----AT------TAAT-AAATAAATAAA----t-----ttTTAaaAaaa--
------------------------------------------------------------
----------------------------------------------------
>input_178.bnk
----gtggCcgGGAGGTGGc-CAgTGG----ATAAAGCATTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCcgGC--A-CaCA-TaTACCAGAgTG---ATGCTCTgg-TTct
ctt---------TcTT-CT-TCTTC------------------TTCT-------------
------Tct----at------tAat-aAaTAAATAAA----T-----ttTaAaaa-----
------------------------------------------------------------
----------------------------------------------------
>input_160.bnk
------tgCcaGGAGGTGGT-CAGTGG----ATAAAG--TTGGACTCTCAA---GCATGA
GGTCCTGAGTTCAATCCCCAGC--A-tgCA-TGTaCCAGAGTG---ATgcTCTGG-TTCT
CTc---------TCTC-Tc-TCCcTCt--------------CTCTCT-------------
------CTC----TCA-----TAAT-AAATAAATAAA----t-----TtaAaaaaa----
------------------------------------------------------------
----------------------------------------------------
>input_171.bnk
-----tgGtCcGGAGGTGGc-CAGTGG----ATAAAGtgTTGGACTcTCAA---GCATGA
GGTCCcgAGTTcaATCCCtgGC--A--tcA-TaTaCCAGAGTG---ATG-tTCTg-tTCT
CTC---------TCTC-TC-TCTCTCT--------------CTCTCt-------------
------Ctt----a------------aAATAAATAaA----T-----TTTAaAaa-----
------------------------------------------------------------
----------------------------------------------------
>input_177.bnk
------gGCtgGGAGGTGGcgCAGTGg-----TAaAGtgTTGGACTctCAA---GCATGA
GGTCCTGAGTTcgATCCCCAGC--A--cCA-TGTaCCAGAGTG---ATGctcTt--ttTT
cTC---------TCTC-tc-TCtcc------------------tTCT-------------
------CTc----tt------tAAT-AAATAAATAAA----t-----tTAAAaaAaa---
------------------------------------------------------------
----------------------------------------------------
>input_180.bnk
-------tggCGGAGGTGGcacAGTgG----aTAAAGcacTGGACTctCAA---GCATGA
GGTCCTAG--TTcATCCCCaGC--A-CACA-TGTACCAGAGTG---ATG-TCTGG-TTCT
tTc---------TcTc-tC-tCtCc----------------ttcTcT-------------
------cTt----AT------tAAT-AAATAAAtAAA----t-----ttTAAAaAAaa--
------------------------------------------------------------
----------------------------------------------------
>input_162.bnk
g-----tggCgGGAGgTGGtgCAGTgG----ATAAAGCA-TGGACTCTCAA---GCATGA
GGTCC-gAGTTCAATCCCcaGc--A--cCA-TGTaCCAGAGTG---ATGCTCTGGtcTCT
cTC---------TCTC-TC-TCccTCt--------------ctcTCT-------------
------CTC----AT------TAAT-AAATAAATAaaaAatt-----tTTAAAAaa----
------------------------------------------------------------
----------------------------------------------------
>input_164.bnk
------GtCtgGGAGGTgGTgCAGTGG----ATAAAGC-TTGGACTCTcAA---GCATGA
GGTCCtaAGTTt-ATCcCCaGC--ATCACA-TGTGcCAGAGTG---ATGCTCTGG-TTcT
CTC---------TtTC-TC-ctcCtCT---------------TCTCT-------------
------CTC----tC------Tcat-tAATAAAAAAT----C-----TTttAAAAAAaa-
------------------------------------------------------------
----------------------------------------------------
>input_183.bnk
g---TGGtCtGGGAGGTGGTgCAGTGG----ATAAAGcaTTGGACTcTcAA---GCATGA
GGTCCTGAGTTT-ATCCCCAGC--A--cCA-TGTaCCAGAGTg---ATG-TCTGgTttcT
CTC---------TCTC-tC------------------------TTtT-------------
------cTT----ct------tata-aAaTAAATAAA----T-----cTTTAaAAaaa--
------------------------------------------------------------
----------------------------------------------------
>input_170.bnk
--------gcggGAGGTGGcaCAGTGG------TAAGcAtTGGACT-TcAA---GCATGA
GGTCCTGAGTTcgATCCCcaGC--A-caCA-TgTaCCAGAGTG---ATg-TCTGgttTcT
cTC---------TCTC-TC-TCTCTCT--------------CTCTCT-------------
------CTCTCTCTC------TCAT-AAATAAATaAA----A-----ttaaAaa------
------------------------------------------------------------
----------------------------------------------------
>input_172.bnk
-------gccgGGAgGTGGCtCAGtgG-----TAGAGCAtTGGACT-TCAt---GcaTGA
GGTCCtgAGTTCaATCCCCAGC--ACCACA-TGTgCcAGAGTg---aTgCTCTGg-TtTt
tTC---------TCTC-tC-TCTCCCT--------------CTCTCT-------------
------cTCTCttAT------aAAT-AAataAATAAA----T-----cTTTtaaAAa---
------------------------------------------------------------
----------------------------------------------------
>input_184.bnk
--------gcgGGAggTgGctCAGTgG-----TAGAGCActGGACT-TCAa---GCaTGA
GGTCCtAG--TTCATCCCtaGC--ACcACA-TGT-cCAgAGTG---aTGCTCTGG-tTtt
ctc---------tCTC-TC-TCTCccT--------------CTcTct-------------
------cTCtt--ata---aaataa-tAAaAAAtaaa----T-----tTTaAAaAaa---
------------------------------------------------------------
----------------------------------------------------
>input_169.bnk
----gtGgCtGGGAGGTGG--CAGTGG-----TAAAGcATTGGAcTCTCAA---GCATGA
GGTCCTGAGTTCaATCCCCAGC--ATCACA-TGT-CCAGAGTG---ATGCTCTGG-TtCT
CTC---------TCTC-TC-TCTCTCT--------------CTCTCT-------------
------CTCTCTtCtTCccTCTCAT-TAATAAATAAA----T-----aATTTaAAAAaa-
------------------------------------------------------------
----------------------------------------------------
>input_189.bnk
--------gccGGAGgTGgc-cAGtgg-----TAgAGCa-TGGACT-TCA----aGCTGA
GGTcCC-aGTTtgATCCCcgGC--AccaCA-TgTACCAGAGTG---ATGcTCTGg-ttCT
cTc---------TCTC-TC-TCTCTcT--------------CTCTCT-------------
------cTCta---------------aaATAAAtAAA----a-----tttaaaaa-----
------------------------------------------------------------
----------------------------------------------------
>input_193.bnk
------tgGCgGGAGgTgGt-CAGTgG-----TAaAGt-TTGGACTttCAA---GCATGA
GGTCC--AGTTt-ATCCCCAGc--ActaCA-TgTACCAGAGTG---aTGCTCTGG-TTtT
cTC---------TCtC-Tc-tCctttt--------------ctcTAT-------------
--------------------------AAATAAATAAA----T-----TttaAaaaa----
------------------------------------------------------------
----------------------------------------------------
>input_173.bnk
----------GgGAAATgGCTCAACTG----GTAGAGCAtTGGACT-TCAT---GCCTGA
GGTTCC-GGTTcAATCCCCAGC--ACTGCA-TGTACCAGAGTG---GTGCTCTGG-cTTC
TtT---------CTCT-Cc-cCTCTGT---CTCATGTGAA-actTCT-------------
------CTC----ATA---TGTAAT-AAATAAAATAA----A-----TCTTTAAAAAaaa
a-----------------------------------------------------------
----------------------------------------------------
>input_174.bnk
----------gggAaATaGCTCAACTG----GTAGAgCA-tGGACT-TCAT---GCCTGA
GGTTCCTAGTTTgATCCCCAGC--ACTaCA-TGTACCAGAGTG---GTGcTCTGG-CTTc
TtC---------TCTC-TC-TtcTCTCTgtCTCATGTGAAActCTcT-------------
------CTC----ATA---TGTAAT-AAATAAAatAA----a-----TTTtAAAAaa---
------------------------------------------------------------
----------------------------------------------------
>input_175.bnk
g---------GGGAAATaGCTCAACTG----GTAGAGCA-tGGACTTGCAT---GCCTGA
GGTTCCTGGTTCAATCCCtaGC--ACcaCA-TGTACCAGAGTG---GTGCTCTGG-cTTT
cTC---------Tctt-cT-CTCTTCT-----CATGTGAAACTCtTC-------------
------TCa----ATa-----TAAT-AAATAAAATAA----A-----TCTTTAAAAAAAa
a-----------------------------------------------------------
----------------------------------------------------
>input_187.bnk
----------GGgAaATAGCTCAgcTG----gTAGAGcataGGACTTgCAT---GCCTGA
GGTTCC-gGTTCaATCCCCAGc--A-CcCA-TGTACcaGAGTG---GTGCTCTGG-TTcT
cTC---------tcTc-Tt-tTCTGTg-----------AAAcTcTTc--Ta---------
-------------ata---TaaAAT-AAAAAAatAAa----t-----cTTTaAAAAAa--
------------------------------------------------------------
----------------------------------------------------
>input_176.bnk
--------gcgGGAaaTgGCtCAgtGg-----TAGAGCAttgGACT-TCAt---GCcTGA
GGTTCT-AGTTCAAT-CCCaGC--ACCACA-TGTACCAGAGTG---aTGCTcTGGtTTCt
ctc---------tct--tc-tcTCTCT---TCTCaTtgaAactcTCT-------------
------ctc----at------taaT-AAATAAaATAa----a-----tTTTAaaAaa---
------------------------------------------------------------
----------------------------------------------------
>input_186.bnk
----------gGGAggTgc--CAGttG-----TAGAGcattGgAcTTC------AGCTGA
GGTTCC-AGTTcaATCCCtgGC--A-caCA-TGTaCCAGAGTG---aTGCTCTGgTtTct
tTc---------Tttc-tC-tCCTCTC--------------TTCTCT-------------
------cTc----At------aaaT-AAATAAATAAa----a-----ttTTTaAAaaaa-
------------------------------------------------------------
----------------------------------------------------
>input_154.bnk
GTGGTCTGggaGGAGGAGGcAgAGTGG----ATAAAGTACAGGATTCTCAG---GCATGA
GGTCCCAAGTTCAATCCCCAGT--aCCACA-TaTACCAGAGTg---AtG-TctgG-ATCt
CTC---------CCTg-CT-CCT------------------cTCTCT-------------
------CTC----AT------TAAT-GAATAAATAAG----A-----TCTTTAGAAcAAA
A-----------------------------------------------------------
----------------------------------------------------
>input_190.bnk
-------ggcgGGAGgTGGCTCAGtgG-----tAgAGCACaGaCTTCA------TGCTGA
GGtCCTGgGTTC-ATCCCTGGC--ACCACAttgtAcCAGAGtaT--G---CTTgT-cTCT
CTc---------TcTc-tTttctCtcT--------------CTcTtT-------------
------C-------------------aAatAAAtAaA----T-----aatAaaAa-----
------------------------------------------------------------
----------------------------------------------------
>input_191.bnk
-------gGCgGGAGGTGGctCAGTgG-----tAGAGCacaGGAC--TTAt---GCATgA
GGtCCTgAGTT-aATCCCCaGC--ACCaCA-TATgcCAGAGtg----TgCTtttC-TcTT
CTc---------TTtc-Tt-ttCcTtTt--------------------------------
---------------------aaAT-AAaTaAATAAA----T-----tTTaAAAaaaaa-
------------------------------------------------------------
----------------------------------------------------
>input_195.bnk
------tgGCgGGAGgTGgC-CAGTGG-----tAAGaC--TGGACT-tCAa---GCATGA
GGTCCTGAGTTcaATCCCCAGC--A-caCA-TgTgCcAGAGTG---ATc-TCTgg-Ttct
CTc---------tctC-TC-tCTCt-----------------------------------
---------------------TatA-aAAtAaaTaaA----A-----attttAAAAAAAa
a-----------------------------------------------------------
----------------------------------------------------
>input_200.bnk
-----tgGtCgGGAGGTGG--CAGTGG-----TAGAGcA-tgGACT-cCAa---GCaTGA
GGTCCtgAGTTc-ATCCCCAGC--A-tcCA-TgTgCCAGAGTG---ATgCTctgT-cttc
TTC---------tTTt-ct-ttatAtt---------------------------------
---------------------TTaT-aaa------------a------------------
------------------------------------------------------------
----------------------------------------------------
>input_185.bnk
---------------ggAgtgCAgtgg-----TAgAgca-tggAcTttCAt---GCaTGA
GGTTCC-AGTTCaATCCCcAGC--A--ccA-TgTgCcAGAGTG---aT--TCTggTTCtt
tTt---------Tttc-tt-TTcTcTT---------------------------------
---------------------cTAT-aAAaaaaaAAT----A-----TTTTaAAAAaAa-
------------------------------------------------------------
----------------------------------------------------
>input_192.bnk
------ggccGGGAGGTGGCtCAGTGG----gTAGAGt--tGGACTTgcA----GCATGA
GGTCCt-AGTTt-ATCCCCagA----CACA-TaTgCCAGAGTG---ATGCTCTgG--tTT
CTC---------tCTC-Tc-ccTct----------------CTCCct---a---------
--------------------------TAATAAATAaa----a-----tttaaAaa-----
------------------------------------------------------------
----------------------------------------------------
>input_194.bnk
----------ggGAggTGGcCAag--------TAGAGCActgGAcTtC------AGCTGA
GGTCCt-aGTTCaATCCCCaGC--A-cACA-T-TacCAGAGTg----TgtttctT-cTcT
CTc---------TCTC-tc-----------------------------------------
-------------tc------taat-AAAtAAatAaa----t-----tTttAAAAAa---
------------------------------------------------------------
----------------------------------------------------
>input_188.bnk
----------ggGGAGTgGCtCAgtg------TAGAGcactGGACTTgCA----tGCTGA
gGtcCt-AGTTT-ATCCCCAGC--ActgCA-T-TaCCAGAGTgTc-----TcTggtTTTT
CTc---------TCTC-TT-CTtcTTt--------------CTCTTc-------------
---------------------Tata-AAATAAATAaA----t-----ttTttAAAaaa--
------------------------------------------------------------
----------------------------------------------------
>input_179.bnk
-------gctgGgAgGTgG--cAGTGG----ATAAAG---TGAACTTTCAA---GCATGA
GGTCCG-AGTTcaATcCCcgGc-----ACa-tgTacca-AGTa---AT--TcTGGTTTCT
CTC---------TCTt-tT-cTttt----------------tcCTtT-------------
------tTT----At-----------TaaaaAATAAA----t-----AtTttaAAAAa--
------------------------------------------------------------
----------------------------------------------------
>input_196.bnk
tg--------cGgAggTgGc-CAgtGg-----TAGAgca-cGgACT-tcA----gCaTGA
GGcCT--gAGTTAaTCCCtgGC--A-ccCA-TGT-cCAGAgTG---aTC-TctgcTcTCT
CtC---------TtCt-------------------------Ctcttt-------------
------ctt----Aa------taaa-AaATAAAataA----a-----tTtaaAaa-----
------------------------------------------------------------
----------------------------------------------------
>input_147.bnk
G---TGGTCCAGaAGGTtGCGCaGTGGataaATAAAGTATTGGACTTTCAAgacgcAGGA
GGTCCTGAGTTCGACCCCTGGC--AGCACA-TGTACCAGAGTG---ATG-TCTGG-CTCT
TTC---------TCTG-TC-TCCCgTCgT------------ATCTTT-------------
------CTG----CT------TCAG-AAATAAGTACA----A-----TCTTAAATAAAAT
A-----------------------------------------------------------
----------------------------------------------------
>input_197.bnk
----------cGGagGTGgc-CAgtgG-----TaaAgga--------tcAa---gcatAg
GcCc---aGTTcgAtcCC------------------------------------------
------------Cgtcatttttttttt--------ttaAAgATTTTa-------------
------Ttt----at------TTAT-T-ATGAGAAAg----Atag-g---gaGAGAGAAA
GAACCAGACATCACTCTGGcACATGTGCTGCcgGGGATtGAACTCAGGACCTCATGCTTG
AGAGTCCAa-GCTTTAtCCACTGcgCCACCTCCCgGACCActaataaaaaaa
>input_198.bnk
------------ggggtgGc----------agtaagccA---------------tagcaA
ggCCca-gGTTcaAgcCCcgccccatcgtt-agtggTgaatagtCTgtt-cttcT-cTcT
cTc---------Tctc-tcttTtTtTT--------TTtAAgAtTTTA-------------
------TTT----AT------TTAT-T-ATGAGAAAG----ATAGGAGGAGAGAGAGAAA
GAACCAGACATCACTCTGGTACATGTGCTGCCGGGGATTGAACTCAGGACCTCATGCTTG
AGAGTCCAATGCTTTATCCACTGtGCCACCTCCCGGACCAC-----------
>input_199.bnk
------------ggggtgGCAtGgTtAGt-cataacTcA---------------tGctgA
GGaCCtagGTTCaACCCcccaa--gctaca-agTg-tagAGca---gTg-CTtaG-tTcT
cTc---------Ttct-ctcttcttTT--------tttaAaATTTTA-------------
------TTT----AT------TTAT-TAATGAGAAAg----ATAg-----gAGAGAGAAA
GAACCAGACATCACTCTGGTACATGTGCTGCCaGGGATTGAACTCAGGACCTCATGCTTG
AGAGTCCAATGCTTTATCCACTGtgCCACCTCCCAGACCAC-----------
