>input_001.bnk
----cagCttgCTTAA--GATCcGTTAaCAGT----------------------GA-Att
aaa--------------------------tCAtAgCGGCCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGATTCCAGAAGATCCGTGGTTC-GATT-CCCGGTggtGCCGTTG-------
------------------------------------------------------------
TGT--TTTTTTCACTGTTTaCAGATCGCTGAGTTtGACATCCAG
>input_003.bnk
----------------------tcTTAGCAGT----------------------GA-ATT
GA---------------------------GCCTGGT-GGCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGTATCCAGGAGATCCGTGGTTC-GATT-CCCGGTGG--CTGCCGT------
------------------------------------------------------------
TGTGTTTTTTTCACTGTTTACGGATCGCTGAGTTGGACATCCAG
>input_006.bnk
-----------------------gTTAgcAGT----------------------gA-ATT
GA---------------------------GCCTGGT-GGCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGTATCCAGGAGATCCGTGGTTC-GATT-CCCGGTGG--CTGCCGT------
------------------------------------------------------------
TGTGTTTTTTTCACTGTTTACGGATCGCTGAGTTGGACATCCAG
>input_004.bnk
------------------aggtccTTAGCAGT----------------------GA-ATT
GA---------------------------GCCTGGT-GGCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGATTCCAGGAGATCCGTGGTTC-GATT-CCCGGTGG--CTGCCGT------
------------------------------------------------------------
TGTGTTTTTTTCACTGTTTATGGATCGCTGAGTTGGACATCCAG
>input_005.bnk
----------------------tGTtAGCAGT----------------------GA-ATT
GA---------------------------GCCTGGT-GGCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGATTCCAGGAGATCCGTGGTTC-GATT-CCCGGTGG--CTGCCGT------
------------------------------------------------------------
TGTGTTTTTTTCACTGTTTAtGGATCGCTGAGTTGGACATCCAG
>input_007.bnk
---------------------atcgTtACAgT----------------------gA-aTT
gA----------------------------CCTGGT-GGCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGTATCCAGGAGATCCGTGGTTC-GATT-CCCGGTGG--CTGCCGT------
------------------------------------------------------------
TGtTTTTTTTTCACTGTTTACGGATCGCTGAGTTGGACATCCAG
>input_008.bnk
------------------------TTAGcagt---------------------TGA-ATT
gA------------------------------tGGt-GGCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGTATCCAGGAGATCCGTGGTTC-GATT-CCCGGTGG--CTGCCGT------
------------------------------------------------------------
TGTgTTTTTTTCACTGTTTACgGATCGCTGAGTTGGACATCCAG
>input_011.bnk
----------------agGTTCTGTTAGCAGT----------------------GA-ATT
GA---------------------------GCGTGGT-GGCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGTATCCAGAAGATCCGTGGTTC-GATT-CCCGGTGG--CTGCCG-------
------------------------------------------------------------
AGT--TTTTTTCACTGTTTCCAGATCGCTGAGATGGACATCCAG
>input_012.bnk
---------------tagGtTCTGTTAgCAGT----------------------gA-ATT
GA---------------------------GCGTGGT-GGCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGTATCCAGAAGATCCGTGGTTC-GATT-CCCGGTGG--CTGCCG-------
------------------------------------------------------------
AGT--TTTTTTCACTGTTTCCAGATCGCTGAGATGGACATCCAG
>input_013.bnk
---------------taGGaTCTGTTAGCAGT----------------------GA-ATT
GA----------------------------GCTGGT-GGCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGTATCCAGAAGATCCGTGGTTC-GATT-CCCGGTGG--CTGCCG-------
------------------------------------------------------------
AGt-TTTTTTTCACTGTTTCCAGATCGCTGAGATgGACATCCAG
>input_019.bnk
----acactTgCTtaAGgGATCTGTTAGCAGT----------------------GA-ATT
Gt-----------------------------cTaGC-aGCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGATTCCAGAAGATCCGTGGTTC-GATT-CCCGGTGG--CTGCTG-------
------------------------------------------------------------
aGt--TTTTTTCACTGTTTCCAGATCGCTGAGTTTGACATCCAG
>input_009.bnk
actccAGCTTGCTTAAGGGATCTGTTAGCAGT----------------------GA-AtT
GA---------------------------TCgT-GCGGccTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGATTCCAGAAGATCCGTGGTTC-GATT-CCCGGTGG--CTGCtGA------
------------------------------------------------------------
GTtttTTTTTTCACTGTTTCCAGATCGCTGAGTTTGACATCCAG
>input_015.bnk
AcTCCAGCTTGCTTAAGGGATCTGTTAGCAGT----------------------GA-ATT
Gg---------------------------TCgTAGCGGcCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGATTCCAGAAGATCCGTGGTTC-GATT-CCCGGTGGgccTGCTG-------
------------------------------------------------------------
TGTacTTTTTTCACTGTTTCCAGATCGCTGAGTTTGACATCCAG
>input_016.bnk
AcTCCAGCTTGCTTAAGGGATCTGTTAGCAGT----------------------GA-ATT
GG---------------------------TCgTAGCGGCCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGATTCCAGAAGATCCGTGGTTC-GATT-CCCGGTGGG-CTGCTG-------
------------------------------------------------------------
TGTACTTTTTTCACTGTTTCCAGATCGCTGAGTTTGACATCCAG
>input_023.bnk
ACTCCAGCTTGCTTAAGGGATCTGTTAGCAGT----------------------GA-ATT
Gg---------------------------TCGTAGCGGCcTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGATTCCAGAAGATCCGTGGTTC-GATT-CCCGGTGGG-CTGCTG-------
------------------------------------------------------------
TGTACTTTTTTCACTGTTTCCAGATCGCTGAGTTTGACATCCAG
>input_024.bnk
actCCAGCTTGCTTAAGGGATCTGTTAGCAGT----------------------GA-ATT
GG---------------------------TCgTAGCGGCCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGATTCCAGAAGATCCGTGGTTC-GATT-CCCGGTGGG-CTGCTG-------
------------------------------------------------------------
TGTACTTTTTTCACTGTTTCCAGATCGCTGAGTTTGACATCCAG
>input_018.bnk
AcTCCAGCTTGCTTAAGGGATCTGTTAGCAGT----------------------GA-ATT
GG---------------------------TCaTAGCgGCCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGATTCCAGAAGATCCGTGGTTC-GATT-CCCGGTGGG-CTGCTG-------
------------------------------------------------------------
TGTACTTTTTTcACTGTTTCCAGATCGCTGAGTTTGACATCCAG
>input_028.bnk
actcCAGCTTGCTTAAGGgATCTGTTAGCAGT----------------------GA-ATT
Gg---------------------------TcGTAGCGGCCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGATTCCAGAAGATCCGTGGTTC-GATT-CCCGGTGGG-CTGCTG-------
------------------------------------------------------------
TGTAtTTTTTTCACTGTTTCCAGATCGCTGAGTTTGACATCCAG
>input_021.bnk
actCCAGCTTGCTTAAGGgATCTGTTAGCAGT----------------------GA-ATT
GG---------------------------TCgTAGCGGCCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGATTCCAGAAGATCCgTGGTTC-GATT-CCCGGTGGG-CTGCTG-------
------------------------------------------------------------
TGT-ATTTTTTCACTGTTTCCAGATCGCTGAGTTTGACATCCAG
>input_030.bnk
-accCAGCTTGCTTAAGGGATCTGTTAGCAGT----------------------GA-ATT
Gg---------------------------TCGTAGCGGCCTGTGGTGTAGTGGTTAGCAC
gTCTGGCCGGATTCCAGAAGATCCGTGGTTC-GATT-CCCGGTGGG-ctGCTG-------
------------------------------------------------------------
TGT-cTTTTTTCACTGTTTCCAGATCGCTGAGTTTGACATCCAG
>input_017.bnk
---CCAGCTTGCTTAAGGGATCTGTTAGCAGT----------------------GA-ATT
GG---------------------------TCgTAGCgGCCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCAGATTCCAGAAGATCcGTGGTTC-GATT-CCC-GTGGG-CTGCTG-------
------------------------------------------------------------
TGTACTTTTTTCACTGTTTCCAGATcGCTGAGTTTGACATCCAG
>input_029.bnk
---ccAgcTTgcTTAAGgGATCTGTTAGCAGT----------------------GA-ATT
Ga---------------------------TcGTAG-GGCCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGATTCCAGAAGATCCGTGGTTC-GATT-CCCGGTGGG-CTGCTG-------
------------------------------------------------------------
TGTAcTTTTTTCACTGTTTCCAGATCGCTGAGTTTGACATCCAg
>input_022.bnk
-atCCAGCTTGCTTAAGGGATCTGTTAGCAGT----------------------GA-ATT
Gg---------------------------TCaTAGCGGCCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGATTCCAGAAGAT-CGTGGTTC-GATT-CCCGGTGGG-CTGCTG-------
------------------------------------------------------------
TGTACtTTTTTCACTGTTTCCAGATCGCTGAGTTTGACATCCAG
>input_033.bnk
-accCAGCTTGCTTAAGGGATCTGTTAGCAGT----------------------GA-ATT
gg---------------------------TCaTAGcgGCCTGTGGTGTAGTGGTTAGCAC
gTCTGGCc-GATTCCAGAAGATCCgTGGTTC-GATT-CCCGGTGGG-cTGCTG-------
------------------------------------------------------------
TGTAcTTTTTTcACTGTTTCCAGATCgCTGAGTTTGACATCCAG
>input_031.bnk
---ccAgCTTgCTTAAgGGATCTGTTAGCAGT----------------------GA-ATT
GG---------------------------TCaTAGcaGCCTGTGGTGTAGTGGTTAGCAC
ATCTGGCCaGATTCCAGAAGATCCGTGGTTC-GATT-CCCGGTGGG-CTGCTG-------
------------------------------------------------------------
TGTAcTTTTTTCACTGTTTCCAGATC-CTGAGTTTGACATCCAG
>input_032.bnk
-acCCAGCTTGCTTAAGGGATCTGTTAGCAGT----------------------GA-ATT
GA---------------------------TCGTAGCgGCCTGTGGTGTAGTGGTTAGCAC
GTCTGgCCGGATTCCAGAAGATCCGTGGTTC-GATT-CCCGGTGGG-TcGCTG-------
------------------------------------------------------------
TGTatTTtTTTCACTGTTTCCAGATC-CTGAGTTTGACATCCAG
>input_040.bnk
---ccAgCTTGcTTAAGggATCTGTTAGCAGT----------------------GA-ATT
Ga---------------------------TCGTAGCGGCCTGTgGTGTAGTGGTTAGCAC
GTCTGg-CgGATTCCAGAAGATCCGTGGTTC-GATT-CCCgGTGGG-tcgCTG-------
------------------------------------------------------------
TGt--TTTTTTcACTGTTTCCAGATCGCTGAGTTTgAcATcCAg
>input_026.bnk
-acCCAGCTTGCTTAAgGGATCTGTTAGCAGT----------------------GA-ATT
GA---------------------------TCaTAGcgGCCTGTGGTGTAGTGGTTAGCAC
GTCTG--CGGATTCCAGAAGATCCATGGTTC-GATT-CCcGGTGGG-TTGCTG-------
------------------------------------------------------------
TGT-ctTTTTTCACTGTTTCCAGATCgCTGAGTTTGACATCCAG
>input_027.bnk
---cCAGCTTGCTTAAGGGATCTGTTAGCAGT----------------------GA-ATT
GA---------------------------TcGTAGCgGCCTGTGGTGTAGTGGTTAGCAC
GTCTG----CGATTCAGAAGATCCgTGGTTC-GATT-CCCGGTGGG-tTGCTG-------
------------------------------------------------------------
TGT-tTTTTTTCACTGTTTCCAGATCtCTGAGTTTGACATCCAG
>input_039.bnk
---ccAgCTTGCTTAAgggATCTGTTAgCAGT----------------------GA-ATT
Ga---------------------------TC-TAGcGGCCTGTGGTgTAGTGGTTAGCAC
GTCTGGCcGGATTCCAGAAGATCCGTGGTTC-GATT-CCCGGTGGG-TcGCTg-------
------------------------------------------------------------
TGT--TTTTTTCACTGTTTCCAGATCGCTGAGTTTGACATCCAG
>input_025.bnk
---CCAGCTTGCTTAAGGGATCTGTTAGCAGT----------------------GA-ATT
GA---------------------------TCaTAGcgGCCTGTGGTGTAGTGGTTAGCAc
GTCTGCCggGATAGCAGAAGATCCGTGGTTC-GATT-CCCgGTGGG-TcGCTG-------
------------------------------------------------------------
TgT-TtTttTTCACTGTTTCCAGATCTCTGAGTTTGACATCCAG
>input_036.bnk
-----cacTTgcTTAAGgGATCTGTTAGCAgT----------------------GA-ATT
GA---------------------------TCgTAGCGGCCTGTGGTGTAGTGGTTAGCAC
GTCTG-CCcGATAGCAGAAGATCCGTGGTTC-GATT-CCCGGTGGG-TCGCTG-------
------------------------------------------------------------
TGT-TTTTtTTCACTGTTTCCAGATCTCTGAGTTTGACATCCAg
>input_035.bnk
---cCAGCTTGCTTAAGggATCTGTTAGCAGT----------------------GA-ATT
GA---------------------------T-GTAGCGGCCTGTGGTGTAGTGGTTAGCAC
aTCTG-cCCGATagCAGAAGATCCGTGGTTC-GATT-CCCGGTGGG-TCgCTG-------
------------------------------------------------------------
TGTTTTTTtTTCACTGTTTCCAGATCtCTGAGTTTGACATCCAG
>input_038.bnk
---ccagctTgcTtAAgggATCTGTTAGCAGT----------------------GA-ATT
GA---------------------------T-GTAGcgGCCTGTGGTGTAGTGGTTAGCAC
GTCTGGCc-GATTCCAGAAGATCCGTGGTTC-GATT--CCGGTGGG-tcGCTG-------
------------------------------------------------------------
TGtttTTTTTTCACTGTTTCCAGATCgCTGAGTTTGACATCCAG
>input_037.bnk
----cAgcTTgCTTAa-ggATCTgTTAGCAGT----------------------GA-ATT
GA---------------------------TcgTAGc-GcCTGTGGTGTAGTGGTTAGCAC
GTCTGgCCGGATTcCAGAAGATCcgTGGTTC-GATT-CCCGGTGGG-tCGCTG-------
------------------------------------------------------------
TGT-tTTTTTtCACTGTTTCCAGATC-CTGAGTTTGACATCCAg
>input_014.bnk
--accagcttGCTTAAggGaTCTGTTAGCAGT----------------------GA-ATT
GA---------------------------tCaTGG--GGCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCGGATTCCAGAAGATCCGTGGTTC-GATT--CCGGTGG--CTGCTG-------
------------------------------------------------------------
AGT-TTTTTTTCACTGTTTCCAGATCGCTGAGTTTGACATCCAG
>input_034.bnk
-------ccAgttTTaAGGATCTGTTAgCAGT----------------------gA-ATT
g-------------------------------TGtaggcCTGTGGTGTAGTGGTTAGCAC
GTCTGGCCgGATTCCAGAAGATCCgTGGTTC-GATT-CCCGGTGGG-CTGCTG-------
------------------------------------------------------------
tGt-tTTtTTTCACTGTTTCCAGATCgCTGAGTTTGACATCCAg
>input_010.bnk
-------GtcatcTCAGCGATCTGGAAACAGTGAAAAaaacTcgGcagccacgggA-ATc
Gaa-cggacttc-----------------tggatatGggCTgTGGTGTAGTGGTTAGCAc
GTCTGGCCGGTATCCAGAAGATCCGTGGTTC-GATT-CCCGGTGG--CTGCCG-------
------------------------------------------------------------
AGT-TTTTTTTCACTGTTTCCAGATCGCTGAGATgGACATCCAG
>input_020.bnk
-CtgaTGtcaAacTCAGcGATCTGGAAACAGTGAAAaAAactCgGcagCcac-gga-atc
gaaccagacttctggatcgcagacgTGctaccatacGcGCTGTGGTGTAGTGGTTAGCAC
gTCTGGCCGGAtTCCAGAAGATCCgTGGTTC-GATT-CCCgGTGG--CTGCTG-------
------------------------------------------------------------
AGT--TTTtTTCACTGTTTCCAGATCGCTGAGTTTGACATCCAG
>input_160.bnk
--------tatgtTcAGcGATCTGgAAACAGTGAAAAaa----------cac-ggA-Atc
gaAcCagGatctt------------------------cgctgtggTGtaGTaGTTAGCAc
gTCTGGCcGGATTCCAGAAGATCCgTGGTTC-GATT-CCCGGTGG--CTGCtG-------
------------------------------------------------------------
aGT--TTTTTTCACTGTTTCCAGATCGCTGAGTTTGACATCCAg
>input_041.bnk
----------TgcttaAgaATCTGTTAGcagT----------------------gA-ATT
At---------------------------tTa----GgcCTGTGGTGTAGTGGTTAgCA-
GTCTG--CCGATAGCAGAAGATCc-TGGTTC-GATT-CCCgGTGGG-TcGCTG-------
------------------------------------------------------------
TGt-TTTTtTTcAcTgTTTtCAgATCTCTGAGTTTGAcatccag
>input_042.bnk
-----cacTTgCTTAA--GGATTGTTAGCAGT----------------------GA-ATT
GA---------------------------tcgTAGcgGCCTGTGGTGTAGTGGTTAGCAC
gTCTGgC--GATtCCAGAAGATCCgTGGTTC-GATT-CCCGGTGG--gtGCTG-------
------------------------------------------------------------
tGT--tTTTTTCACTGTTTC-AGATC-CTgAGTttgAcatc--a
>input_043.bnk
---ccagCTTgcTtaa---aTCTGTTAGCAGT-----------------------A-ATT
GA------------------------------TaTAGaGCcTgTGTgTAGTGGTTAGCAc
gTCTG---CgGATtCAGAAGATCcgTGGTTC-GATT-CCCGGTGG--GTGCTG-------
------------------------------------------------------------
--t-ttTTTtTCACTGTTTCCAGATc-CTGAGTTtgacAtCcag
>input_044.bnk
-------agctTTTAAGagATcTgtTAgcA-----------------------TgA-ATt
G----------------------------tcaTAGcgGCCTGTGGtgTA-TGGTTAGcA-
gTCTGcCcgA--TgCAGAAGAT-CGTGGTTC-GATT-CccgTgGGt-CtG----------
------------------------------------------------------------
-----gTTTTttactgtTTtCAGATC-cTGAgt-----------
>input_002.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCAcatg-ggctgtGGTGTAG
TGGTTAGCACGTCTGGCCGGTATCCAGGAGATCCGTGGTTCGATTCCCGGTGGCTGCCGT
TGTgTTTTTTTCACTGTTTACGGATCGCTGAGTTGGACATCCAG
>input_045.bnk
CTGGATGTCCAACTCAGCGATCCATAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCAg-------
------------------------------------------------------------
---g----------------------------------------
>input_047.bnk
CTGGATGTCCAACTCAGCGATCCATAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCAG-------
------------------------------------------------------------
---Gctcaata---------------------------------
>input_050.bnk
CTGGATGTCCAACTCAGCGATCCATAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCAG-------
------------------------------------------------------------
---GcTcaattcac------------------------------
>input_051.bnk
CTGGATGTCCAACTCAGCGATCCATAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCAG-------
------------------------------------------------------------
---Gctcaattc--------------------------------
>input_049.bnk
CTGGATGTCCAACTCAGCGATCCATAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCag-------
------------------------------------------------------------
---gcta-------------------------------------
>input_074.bnk
CTGGATGTCCAACTCAGCGATCCATAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCAg-------
------------------------------------------------------------
---gttTcact---------------------------------
>input_048.bnk
CTGGATGTCCAACTCAGCGATCCATAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCAG-------
------------------------------------------------------------
---Gtcaatt----------------------------------
>input_052.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCAg-------
------------------------------------------------------------
---gt---------------------------------------
>input_053.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCAg-------
------------------------------------------------------------
---gctcaatt---------------------------------
>input_059.bnk
CTGGATGTCCAACTCAGCGATCCATAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCAG-------
------------------------------------------------------------
---gtcattca---------------------------------
>input_060.bnk
CTGGATGTCCAACTCAGCGATCCaTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACcac-------
------------------------------------------------------------
--------------------------------------------
>input_061.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATtCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCAG-------
------------------------------------------------------------
---GCTCAATTCactg----------------------------
>input_062.bnk
CTGGATGTCCAACTCAGCGATCGGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATTCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
--------------------------------------------
>input_054.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCAg-------
------------------------------------------------------------
---g----------------------------------------
>input_055.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
--------------------------------------------
>input_056.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCa--------
------------------------------------------------------------
--------------------------------------------
>input_057.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
--------------------------------------------
>input_058.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
--------------------------------------------
>input_064.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCAg-------
------------------------------------------------------------
---Gctaa------------------------------------
>input_066.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
--------------------------------------------
>input_067.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCa--------
------------------------------------------------------------
--------------------------------------------
>input_069.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
--------------------------------------------
>input_070.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCa--------
------------------------------------------------------------
--------------------------------------------
>input_071.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
--------------------------------------------
>input_072.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCAg-------
------------------------------------------------------------
---g----------------------------------------
>input_075.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAAcGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
--------------------------------------------
>input_076.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCag-------
------------------------------------------------------------
---g----------------------------------------
>input_080.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-caCc---------
------------------------------------------------------------
--------------------------------------------
>input_073.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCag-------
------------------------------------------------------------
---gtcaa------------------------------------
>input_063.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CAcCAg-------
------------------------------------------------------------
---a----------------------------------------
>input_104.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATaCCGGCCAGACgTGCTAACC-ACTA-CACCACAGC-CACCAg-------
------------------------------------------------------------
---atcat------------------------------------
>input_065.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCAg-------
------------------------------------------------------------
---t----------------------------------------
>input_068.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAC------------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCAc-------
------------------------------------------------------------
---a----------------------------------------
>input_082.bnk
CTGGATGTCCAACTCAGCGATCCGcAAAtAGT----------------------GA-AAA
AAAC------------------------ACAAcGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CaCcAt-------
------------------------------------------------------------
---t----------------------------------------
>input_081.bnk
CTGGATGTCCAACTCAGCGATCCGcaAACAGT----------------------GA-AAA
AAAC------------------------ACaaGGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CaCCA--------
------------------------------------------------------------
--------------------------------------------
>input_046.bnk
CTGGATGTCCAACTCAGCGATCCATAAACAGT----------------------Ga-AAA
AAAAC-----------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCAG-------
------------------------------------------------------------
---GctCaattcc-------------------------------
>input_077.bnk
CTGGATGTCCAACTCAGCGATCTGTAAACAGT----------------------GA-AAA
AAAAC-----------------------ACAACGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CaCCAa-------
------------------------------------------------------------
--------------------------------------------
>input_100.bnk
CTGGATGTCCAACTCAGCGATCTGTAAACAGT----------------------GA-AAA
AAACA-----------------------CaatcGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CaCcattca----
------------------------------------------------------------
--------------------------------------------
>input_078.bnk
CTGGATGTCCAACACAGCGATCTGTAAACAGT----------------------GA-AAA
AAA-------------------------CACTGGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CGCCA--------
------------------------------------------------------------
--------------------------------------------
>input_086.bnk
CTGGATGTCCATCTCAGCGATCTGTAAACAGT----------------------GA-aAA
AAA-------------------------aACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CGCCA--------
------------------------------------------------------------
--------------------------------------------
>input_099.bnk
CTGGATGTCCATCTCAGCGATCTGTAAACAGT----------------------GA-AAA
AAA-------------------------AACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CgCCat-------
------------------------------------------------------------
--------------------------------------------
>input_094.bnk
CTGGATGTCCATCTCAGCGATCTGTAAACAGT----------------------Ga-AAA
AAA-------------------------CACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTcCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CGCCAc-------
------------------------------------------------------------
--------------------------------------------
>input_089.bnk
CTGGATGTCCATCTCAGCGATCTGGAAACAGT----------------------GA-Aaa
AAA-------------------------AACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACcAta------
------------------------------------------------------------
--------------------------------------------
>input_083.bnk
CTGGATGTCCATCTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAA--------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
--------------------------------------------
>input_091.bnk
CTGGATGTCCATCTCAGCGATCTGGAAACAGT----------------------Ga-AAA
AAA--------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-Cac----------
------------------------------------------------------------
--------------------------------------------
>input_096.bnk
CTGGATGTCCATCTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAA--------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
---cgtcaattcac------------------------------
>input_098.bnk
CTGGATGTCCATCTCAGCGATCTGGAAACAGT----------------------Ga-AAA
AAA--------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
---gcTcAattcactgt---------------------------
>input_101.bnk
CTGGATGTCCATCTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAA--------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
---cgctcata---------------------------------
>input_092.bnk
CTGGATGTCCATCTCAGCGATCTGGAAACAGT----------------------gG-AAA
AAA--------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-cacca--------
------------------------------------------------------------
---a----------------------------------------
>input_112.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAA--------------------------ACTCAGCAG-CCACCGGGAATCGAACCAcGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-cgcat--------
------------------------------------------------------------
---c----------------------------------------
>input_133.bnk
CTGGATGTCAAACTCAGcGATCTGGAAACAGT----------------------GA-AAA
AAa--------------------------aCtCAGCAG-CCACCGGGAATCGAACCACgG
ATCTTCTGGAATCCGGCCAGAcGTGCTAACC-ACTA-CACCACAGc-cgCAc--------
------------------------------------------------------------
---gatCAATTCACTGCTAACAgATcCcttaagaa---------
>input_121.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------Ga-aAA
AAA--------------------------ACTCAGCAG-CCACCgGGAATCGAACCACGG
ATCTTCTGGAATCtGGCCAGACGTGCTAACC-ACTA-CACCACAGC-Caa----------
------------------------------------------------------------
--------------------------------------------
>input_128.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------Ga-aAA
AAA--------------------------ACTCAGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-Ccttt--------
------------------------------------------------------------
---catt-------------------------------------
>input_116.bnk
CTGGATGTCAAACTCAGCAATCTGGAAACAGT----------------------ga-AAA
AAA--------------------------ACTCAGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGAcGTGCTAACC-ACTA-CACCACAGC-cgca---------
------------------------------------------------------------
--------aattactgctaag-----------------------
>input_125.bnk
CTGGATGTCaAACTCAGCGATCTGGAAACAGT----------------------GA-AAa
AAA--------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-cgcat--------
------------------------------------------------------------
---cAat------ctgta--------------------------
>input_132.bnk
CTGGATGTCAAACTCAGcGATCTGGAAACAGT----------------------Ga-AAA
Aaa--------------------------ACaCAGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGAATCcGGCCAGAtGTGCTAACC-ACTA-CACCACAGC-CCAca--------
------------------------------------------------------------
-----ccaattcactgcta-------------------------
>input_084.bnk
CTGGATGTCCATCTCAGCGATCTGGAAACAGT----------------------GA-AAA
AA---------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACcA--------
------------------------------------------------------------
--------------------------------------------
>input_085.bnk
CTGGATGTCCATCTCAGCGATCTGGAAACAGT----------------------GA-AAA
AA---------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CaCCA--------
------------------------------------------------------------
--------------------------------------------
>input_087.bnk
CTGGATGTCCATCTCAGCGATCTGGAAACAGT----------------------GA-AAA
AA---------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
---ta---------------------------------------
>input_088.bnk
CTGGATGTCCATCTCAGCGATCTGGAAACAGT----------------------GA-AAA
AA---------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
--------------------------------------------
>input_095.bnk
CTGGATGTCCATCTCAGCGATCTGGAAACAGT----------------------GA-AAA
AA---------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
--------------------------------------------
>input_114.bnk
CTGGATGTCCATCTCAGCGATCTGGAAACAGT----------------------GA-AAA
AA---------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CAccA--------
------------------------------------------------------------
---t----------------------------------------
>input_093.bnk
CTGGATGTCCATCTCAGCGATCTGGAAACAGT----------------------GA-AAA
AA---------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
---cgtcaatt---------------------------------
>input_097.bnk
CTGGATGTCCATCTCAGCGATCTGGAAACAGT----------------------GA-AAA
AA---------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
---gctcaatt---------------------------------
>input_102.bnk
CTGGATGTCCATCTCAGCGATCTGGAAACAGT----------------------GA-AAA
AA---------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
---GcTcaattca-------------------------------
>input_090.bnk
CTGGATGTCCATCTCAGCGATCTGGAAACAGT----------------------GA-AAA
AA---------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CACCA--------
------------------------------------------------------------
---gctcaatca--------------------------------
>input_113.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
AA---------------------------ACTCgGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CaCCA--------
------------------------------------------------------------
---GcTcaattcactg----------------------------
>input_079.bnk
CTGGATGTCCAACTCAGCGATCTGTAAACAGT----------------------GA-aAA
AAAA------------------------CACTgGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CgCCA--------
------------------------------------------------------------
--------------------------------------------
>input_103.bnk
CTGGATGTCCAACTCAGCGATCCGTAAACAGT----------------------GA-AAA
AAAcaca---------------------aactCGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CCcA---------
------------------------------------------------------------
--------------------------------------------
>input_105.bnk
CTGGATGTCcAACTCAGCGATCT-GAAACAGT----------------------GA-AAA
AAA-------------------------cactCGGCAG-CCACCGGGAATCGAACCACGG
ATCTcCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CaCCAgtatt---
------------------------------------------------------------
--------------------------------------------
>input_115.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------gG-AAA
AA---------------------------ACTCAGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGATGTGCTAACC-ACTA-CACCACAGC-cgCCA--------
------------------------------------------------------------
---gatcAattcatgctaa-------------------------
>input_110.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAa
aAA-------------------------AACTCAGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGAcGTGCTAACC-ACTA-CACCACAGC-tgCctttctgt--
------------------------------------------------------------
--gaa---------------------------------------
>input_117.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------Ga-aAA
AAA-------------------------AACTCAGCAG-CcACCGGGAATCGAACCACGG
ATCTTCTGGAATCCgGCCAGACGTGCTAACC-ACTA-CACCACAGC-CCtAg--------
------------------------------------------------------------
-----acaattca-------------------------------
>input_124.bnk
CTGGATGTC-AACTCAGCGATCTGGAAACAgT----------------------GA-AAA
AA---------------------------ACTCGGCAG-CCACCGGGAATCGAACCACGG
ATCTCCTGGATACCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-cgCca--------
------------------------------------------------------------
----gctaat----------------------------------
>input_154.bnk
CTGGATGTCAAACTCAGcGATCTGGAAACAGT----------------------GA-Aaa
aAAA------------------------AACTCAGcac-CCACCgGGAATCGAACCAcgG
ATCTTCTGGAATCCgGCCAGATGTGCTAACC-ACTA-CACCACAGC-CgCcA--------
------------------------------------------------------------
----gtcaaTTcacta--------------------------ac
>input_107.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAG-------------------------TACACAGCAGCCCACCGGGAATCGAACCACGG
ATCTTCTGGAATCTGGCCAGACGTGCTAACC-ACTA-CACCACAGG-CcgcT--------
------------------------------------------------------------
---agacaattcactgctaacagatcttaaaagt----------
>input_108.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAg-------------------------TAcACAGCAGCCCACCGGGAATCGAACCACgG
ATCTTCTGGAATCTGGCCAGACGTGCTAACC-ACTA-CACCACAGc-caatg--------
------------------------------------------------------------
--------------------------------------------
>input_144.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAg-------------------------TACACAGCAGCCCACCGGGAATCGAACCATGG
ATCTTCTGGAATCCgGCCAGACGTGcTAACC-ACTA-CACcACAGc-ctacg--------
------------------------------------------------------------
-----acAattcactgTaacagattt------------------
>input_137.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAG-------------------------TACACAGCAGCCCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCAcAgt-aaa----------
------------------------------------------------------------
--------atTcacTgtaacaa----------------------
>input_111.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAg-------------------------TACACAGCAGCCcACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGc-gac----------
------------------------------------------------------------
--------aattaaga----------------------------
>input_164.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAg-------------------------TACACAGCAgCCCACCGGGAATCGAACCAcGG
ATCTTCTGGAATCCgGCCAGACGTGCTAACC-ACTA-CACCAcAgC-gCt----------
------------------------------------------------------------
--------Aca---------------------------------
>input_122.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAg-------------------------AACACAGCAGCCCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGAtGTGCTAACC-ACTA-CACCACAGc-catt---------
------------------------------------------------------------
--------actt--------------------------------
>input_118.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-aAA
AAG-------------------------TACACAGCAGCCCACCGGGAATCGAACCACGG
ATCTTCTGGAATCcGGCCAGACGTGCTAACC-ACTA-CACCACAGG-Cccta--------
------------------------------------------------------------
----gaccatt---------------------------------
>input_126.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
Aag-------------------------tACACAGCAGcCCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGg-CgcTA--------
------------------------------------------------------------
----gacAaTtCACTGcTaacaatca------------------
>input_147.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAgT----------------------GA-AAA
aAG-------------------------TACAcAGCAGCCCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGg-CgCTa--------
------------------------------------------------------------
----gacAAtTcactgctaacaata-------------------
>input_120.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAG-------------------------TACACAGCAGCCCACCGGGAATCGAACCAcGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGg-Cgcta--------
------------------------------------------------------------
----accaatt--------ataa---------------------
>input_127.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAG-------------------------TACACAGCAGCCCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGg-CCaaa--------
------------------------------------------------------------
--------attcactctaac------------------------
>input_134.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAG-------------------------TACACAGCAGCCCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGg-CcGCTA-------
------------------------------------------------------------
--tGACCAATTCACTGCTAACAGATCcCTTAAGcAAGCtgg---
>input_146.bnk
cTGgATGTCAAACTCAGcGATCTGGAAACAGT----------------------GA-AAA
AAG-------------------------TACACAGCAGCCCACCGGGAATCGAACCAcGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGG-CcGCTA-------
------------------------------------------------------------
--cGACCAATTCACTGCTAACAattta--------agcagt---
>input_172.bnk
CTGGATGTCAAACTCAGcGATCTGGAAACAGT----------------------GA-AaA
AAG-------------------------TACAcAGCAGCCCACCGGGAATCGAACCAcGG
ATCTTCTGGAATCCGGCCAGACgTGCTAACC-ACTA-CACCACAGG-CCgCTA-------
------------------------------------------------------------
--cgAcCAATTCACTGcTAacAta--------------------
>input_119.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAG-------------------------TACACAGCAGCCCACCGGGAATCGAACCATGG
ATCTTCTGGAATCCGGCCAGACgTGCTAACC-ACTA-CACCACAGg-CcgCt--------
------------------------------------------------------------
---AgacAattcactgcaaatttagca-----------------
>input_167.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------ga-AAA
AAG-------------------------TACACAGCAGCCCACCGGgAATCGAACCACGG
ATCTTCTGGAAT-CGGCCAGACGTGCTAACC-ACTA-CACCACAGG-CCGCTA-------
------------------------------------------------------------
--tgACCAATTCACTGcTAacaattaaaagctgg----------
>input_131.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAg-------------------------tACaCAGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGg-CCaCtA-------
------------------------------------------------------------
--tGatcAATTCACTGCTAACAaccta-----------------
>input_129.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAt--------------------------ACACAGCAGcCCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAG---------------
------------------------------------------------------------
--------catcactgcta-------------------------
>input_145.bnk
CTGGATGTCAAACTCAGcGATCTGGAAACAGT----------------------GA-AAA
AAt--------------------------ACACAGCagCCCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCgGCCAGACGTGCTAACC-ACTA-CACCAct----------------
------------------------------------------------------------
--------------------------------------------
>input_136.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
aat--------------------------ACACAGCAGCCCACCGGGAATCGAACCATGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGG-CgCta--------
------------------------------------------------------------
---cgacAATTCACTgCTAacagatCccttAagcaagctgg---
>input_161.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------gA-AAA
Aat--------------------------AcACAGCggCCCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGAcGTGCTAACC-ACTA-CACCACAGg-c------------
------------------------------------------------------------
------cgattcAcTgtaatca----------------------
>input_130.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------Ga-aAA
AAa--------------------------ACACAGCagCCCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGg-C------------
------------------------------------------------------------
------ccatgctc------------------------------
>input_135.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------Ga-AAA
AAA--------------------------aACCAGCAGcCCACCGGGAATCGAACCAcGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGg-Cctaga-------
------------------------------------------------------------
------tcattcactgtaa-------------------------
>input_155.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAa
AAA--------------------------ACtCAGCAGCCcACggGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGATGTGCTAACC-ACTA-CACCACAGc-CCAta--------
------------------------------------------------------------
------CAATtcacTgctaaacttaaa-----------------
>input_123.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
Aa---------------------------ACACAGCAGCCcACCGGGAATCGAACCACGG
ATCTTCTGGAATCCgGCCAGACGTGCTAACC-ACTA-CACCACAGG-CtGCTA-------
------------------------------------------------------------
--cgAcCAATTCACTGCTAAcagatccttaaaact---------
>input_188.bnk
CTGGATGtCAAACTCaGcGATCTGGAAAcAGT----------------------gA-AAA
AA---------------------------ACaCAGcGaCCCACCGGGAATCGAACCACGG
ATCTTCTGgAATCCGGCCAGAtGTGCTAACC-ACTA-CACcACAgg-CCgCTA-------
------------------------------------------------------------
--TGatCAATTcActgCTAAcAat--------------------
>input_177.bnk
CTGGATGTCAAACTCAGAGATCTGGAAACAGT----------------------GA-AAA
Aa---------------------------ACACAGCgACcCAccgGGAATCGAACCAcGG
ATCTTCTGcaATCCgGgCAGACGTGCTAACC-ACTA-CACCACAGG-CcGCTA-------
------------------------------------------------------------
--cgATcAATTcAcTgcTaaca----------------------
>input_151.bnk
CTGGATGTCAAACTCAGcGATCTGGAAACAGT----------------------GA-AAA
A----------------------------ACACAGCAaCCCACCgGGAATCGAACCACGG
ATCTTCTGGAATCCgGCCAGACGTGCTAACC-ACTA-CACCACAGG-CcGCTA-------
------------------------------------------------------------
--cGAtcAATTCACTGcTAacAatcttaagat------------
>input_109.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
Aa---------------------------ACACAGCAGCCCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGg-CcgCa--------
------------------------------------------------------------
---gatcaaTtcactgctaacagatcttaaa-------------
>input_163.bnk
CTGGATGTCAAACTCAGcGATCTGGAAACAGT----------------------GA-AAA
AA---------------------------ACACAGCAGcCCACcGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGg-cgCta--------
------------------------------------------------------------
----AtcAATTcacTgCTAacagatcccttaaca----------
>input_166.bnk
CTGGATgTCAAACTCAGAGATCTGGAAACAGT----------------------Ga-aAA
AA---------------------------aCACAGcgACCCACCGGGAATCGAACCAcGG
ATCTTCTGCTATCgcGGCAGACGTGCTAACc-AcTA-CACCACAgG-cccta--------
------------------------------------------------------------
----aTcAaTTCAcTgcTaaca----------------------
>input_148.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAa
AA---------------------------ACACAGCAGCCCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-GCtag--------
------------------------------------------------------------
-------aattcAtgctaaa------------------------
>input_150.bnk
CTGGATGTCAAACTCAGcGATCTGGAAACAGT----------------------ga-aAA
AA---------------------------ACACAGCAGcCCACtGGGAATCGAACCACGG
ATCTTCTGGAATCtGGCCAGACgTGCTAACC-ACTA-CACCACAGC-gC-----------
------------------------------------------------------------
---TAgcAaTTCACTgCtaaagact-------------------
>input_158.bnk
CTGGATGTCAAACTCAGcGATCTGGAAACAGT----------------------GA-AAA
AAt--------------------------acaCAGCA-CCCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGg-CgcAg--------
------------------------------------------------------------
----atcAatTcAcTgTaacat----------------------
>input_142.bnk
CTGGATGTCAAACTCAG-GATCTGGAAACAGT----------------------GA-AAA
AAt--------------------------AcACAGCagCCCACCGGGAATCGAACCACGG
ATCTTCTGgAATCcGGCCAGATGTGCTAACC-ACTA-CACCACAGG-CtGCTA-------
------------------------------------------------------------
--tgAtCAATTCACTGCTAACAatctaaaagct-----------
>input_152.bnk
CTGGATGTCAAACTCAG-GATCTGGAAACAGT----------------------GA-AAA
AGt--------------------------ACACAGCAgCCCACCGGGAATTGAACCACGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGG-CcgCTA-------
------------------------------------------------------------
---tGAcAaTTCAcTgCTAaCAgatccttaaa------------
>input_153.bnk
CTGGATGTCAAACTCAG-GATCTGGAAACAGT----------------------GA-AAA
AGt--------------------------ACACAGCAGCCCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCgGCCAGACGTGCTAACC-ACTA-CACCACAGg-ccctaa-------
------------------------------------------------------------
-------aattcactgctaata----------------------
>input_168.bnk
CTGGATGTCAAACTCAGcGATCTGGAAACAGT----------------------GA-AAA
AAa----------------------------acAGCaC-CCACCaGGAATCGAACCAcGG
ATCTTCTGGAATCcGGCCAGACGTGCTAACC-ACTA-CACCACAGg-CcgCTA-------
------------------------------------------------------------
---cgAcAaTTCACTGctaacaa---------------------
>input_140.bnk
CTGGATGTCAAACTCAGAGATCTGGAAACAGT-------------------------AAA
AAA--------------------------ACACAGcGACCCACCGGGAATCGAACCAtGG
ATCTTCTGcTATC-cGgCAGACGTGCTAACc-ACTA-CACCACAGg-CcgCtA-------
------------------------------------------------------------
---gAtcAAtTcact--taa------------------------
>input_165.bnk
CTGGATGTCAAACTCAGAGATCTGGAAACAGT-------------------------gaa
AAA--------------------------ACACAGCgACCCACCGGGAATCGAACCACGG
ATCTTCTGCTATC-cGGCAGACGTGCTAACC-ACTA-CACCACAGG-cgCtac-------
------------------------------------------------------------
---gATCAATTcAcTgCTAAa-----------------------
>input_162.bnk
cTgGATGTCAAACTCAGAGATCTGGAAACAGT----------------------Ga-AaA
AAa--------------------------aCACAGCGACCCACcGGGAATCGAACCACGG
ATCTTCTGCtATC--ggCAGAcGTGCTAACC-ACTA-CACCACAgG-ccaCTA-------
------------------------------------------------------------
--tgATCAATTCAcTGCTAAcAtcctta----------------
>input_181.bnk
CTGGATGTCAAACTCAGAGATCTGGAAACAGt----------------------ga-aAA
aaa--------------------------ACACAGcgaCCCACCGGGAATCGAACCACGG
ATCTTCTGcTATC--GgCAGACGTGCTAACC-AcTA-cACCAcAGG-CcgCTA-------
------------------------------------------------------------
---gatcaATTcacT--taa------------------------
>input_174.bnk
cTGgATGTCAAACTCAGAGATCTGGAAACAGT----------------------GA-aAA
AAa--------------------------ACACAGcGACCCACcGGGAATCGAACCACGG
ATCTTCTGCTATC-gGGCAGACGTGCTAACC-ACTA-CACCACAGg-cccta--------
------------------------------------------------------------
---gatcaatta--------------------------------
>input_175.bnk
CTGGATGTCAAACTCAGAGATCTGGAAACAGT----------------------GA-aaA
AAa--------------------------AcACAGcgACCCACcgGGAATCGAACCAtGG
ATCTTCTGcAATC--GgCAGAcGTGCTAACC-ACTA-CACCACAgG-CgCTa--------
------------------------------------------------------------
-----gcaattcacTgctAacaca--------------------
>input_149.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------GA-AAA
aaa--------------------------AcACAGCgaCCCACcGGGAATCGAACCACGG
ATCTTCTGAATCc-GGcCAGACGTGCTAACC-ACTA-CACCACAGg-CcgctA-------
------------------------------------------------------------
---cAtcAattcactgctAaca----------------------
>input_176.bnk
CTGGATGTCAAACTCAGaGATCTGGAAACAGT----------------------GA-AAA
aaa--------------------------ACACAGCGACCCA-CGGGAATCGAACCACgG
ATCTTCTGcTATC-cGgCAGACgTGCTAACC-ACTA-CACCAcAgG-CcgcTA-------
------------------------------------------------------------
---cAtCAATTCAcTgctAAcaaa--------------------
>input_157.bnk
CTGGATGTCAAACTCAG-GATCTGGAAACAGT----------------------GA-aAA
AAa--------------------------ACACAGCgaCCCACCGGGAATCGAACCACGG
ATCTTCTGgAATC-gGCCAGACGTGCTAACC-ACTA-CACCACAGg-CcgCT--------
------------------------------------------------------------
---AgAcAATTcACTgcTAaca----------------------
>input_173.bnk
cTGGATGTCAAACTCAG-GATCTGGAAACAGT----------------------GA-AAA
AAa--------------------------aCACAGCgaCCCACCGGGAATCGAACCACGG
AtCTTCTGgAATC--gGCAGACGTGCTAACC-ACTA-CACCACAGG-CCGCTA-------
------------------------------------------------------------
--cgAtcAATTCACTGCTAAcAgatcccttAagcaagctg----
>input_170.bnk
CTGGATGTCAAACTCAGaaATCTGGAAACAGT----------------------GA-aAA
AAA--------------------------ACA----GAAcCCACGGGAATCAAACCACgG
ATCTTCTGcAATC--cGCAGAcgTGCTAACC-ACTA-CACCACAgG-CCT----------
------------------------------------------------------------
---AGacAattcACTGCTaAcAgata------------------
>input_178.bnk
CTGGATGTCaAACTCAGCGATCTGgAAACAGT----------------------GA-AAA
AAA--------------------------aca----GAcCCACCGGGAATCGAACCACGG
ATCTTCTGGAaTC--GGCAGAcGTGCTAACC-ACTA-cACCAcAGc-ccat---------
------------------------------------------------------------
--------------------------------------------
>input_139.bnk
CTGGATGTCAAACTCAG-CATCTGGAAACAGT----------------------GA-AAA
AAG-------------------------TACACAGCAGCcCACCgGGAATCGAACCAtGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGG-CCgCA--------
------------------------------------------------------------
---GAtcAaTTcactgctaacaattt------------------
>input_138.bnk
CTGGATGTCAAACTCAGcGATCTGGAAACAgT----------------------gG-AAA
AAG-------------------------TACACAGCAGCCCATtGGGAATtGAACCACAG
ATCTTCTGGAATCCAGCCAGAC-TgcTAACc-ACTA-CAtCACAGG-CCgCTA-------
------------------------------------------------------------
--CGAtCAATTCACTgCTAACAGATCCCTTAAGCAAgCTGG---
>input_141.bnk
CTGGATGTCAAACTCAGAGATCTGGAAACAGT----------------------Ga-AAA
AAA---------------------------CACAGCGACCCACCGGGAATCGAACCAg-G
ATCTTCTGCTATC-gGGCAGACGTGCTAACC-ACTA-CACCACAgG-CgCtAt-------
------------------------------------------------------------
---gATCAATTCAcTgcTaacAactaat----------------
>input_185.bnk
CTGGATGTCAAACTCAGAGATcTGGAAacAGT----------------------GA-AAA
Aaa---------------------------CACAGCGACCCA-CGGGAATCGAACCAc-G
ATCTTCTGcTATC-cGGCAGACgTGCTAACC-ACTA-CACCACAGg-cgCTAc-------
------------------------------------------------------------
---aATCAATTCAcTGCTAAcatta-------------------
>input_182.bnk
cTGGATGTCAAACTCAGAGATCTGgAAACAGT----------------------GA-AAA
AAa---------------------------caCAGCGACCCA-CGGGAATCGAACCAC-G
ATCTTCTGCTATC---GcAGAcGTGCTAACC-ACTA-CACcAcAgg-cct----------
------------------------------------------------------------
---aATCaATTcAcTgcTAa------------------------
>input_169.bnk
CTGGATGTCAAACTCAGaGATCTGGAAACAGT----------------------GA-AAA
AAA---------------------------cACAGCaACCCA-CGGGAATCGAACCAcgG
ATCTTCTGTA---TCggCAGACGTGCTAACC-ACTA-CACCACAGg-Ccgct--------
------------------------------------------------------------
---AAtcaaTtcAcTGctAacatta-------------------
>input_179.bnk
CTGGATGTCAAACTCAGaGATCTGGAAACAGT----------------------gA-AAA
AAa---------------------------cACAGCa--CCCACGGGAATCGAACCAc-G
ATCTTcTGtA---TCGcCAGACGTGCTAACC-ACTA-CACCACAGG-CcgCt--------
------------------------------------------------------------
---aatcaAttcacTgctacat----------------------
>input_106.bnk
CTGGATGTCAAACTCAGCGATCTGGAAACAGT----------------------Ga-aAA
AAA------------------------------AtGgAgCCACCGGGAATCGAACCACGG
ATCTTCTGGATaCCgGCCAGACGTGCTAACC-ACTA-CACCACAGC-cCcag--------
------------------------------------------------------------
------taatTcatgtaaa-------------------------
>input_159.bnk
CTGGATGTCAAACTCAGTGATCTGGAAACAGT----------------------GA-AAA
AAA-------------------------tACACAGcaGCCCA-CGGGAATCGAACCACGG
ATCTTCTGgAATC-gGCCAGAtGTGCTAACC-ACTA-CACcACAgt-tCAcT--------
------------------------------------------------------------
----Gtcagt----------------------------------
>g09_CONSENSUS
CTGGATGTC--ACTCAGCGATCTGGAAACAGT----------------------GA-AAA
AAA--------------------------AAACAGCAG-CCACCGGGAATCGAACCACGG
ATCTTCTGGAATCCGGCCAGACGTGCTAACC-ACTA-CACCACAGC-CGCCA--------
------------------------------------------------------------
---TGTCAATTCACTGCTAACA----------------------
>input_143.bnk
CTGGATGTCAAACTCAGAGATCTGGAAACAGT----------------------gg-AAA
AaA-------------------------aAcACAG-GAcCCACCGGGAATCGAACCACgG
ATCTTCTGtA--TCcGGCAGACGTGCTAACC-ACTA-CACCACAGg-ccgCtA-------
------------------------------------------------------------
------gaatTcactgtaaca-----------------------
>input_156.bnk
CTGGATGTCAAACTCAGAGATCTGGAAACAGT----------------------GA-AAA
aaG---------------------------------CACCCACCAGGAATCGAACCACGG
ATCTTCTGctATC--CGCAGAcgTGCTAACC-ACTA-CACcACAGG-CtGCTA-------
------------------------------------------------------------
--tGATCAATTCACTGCTAACAatccttacaagtg---------
>input_180.bnk
CTGGATGTCAAACTCAGAGATcTGgAAACAGT----------------------Ga-aaa
AaA---------------------------CaCAGCGACCCACCGGGAATCGAACCAG-G
ATCTTCTGTA---TCGgCAGACGTGCTAACC-ATTA-CACCACAGC------g-------
------------------------------------------------------------
--CtaataaTtcacttaaa-------------------------
>input_184.bnk
cTGGATGTCAAACTCAG-GATCTGGAAACAGT----------------------GA-AAA
AaA---------------------------CACAGCgACCCA-CCGGAATCGAACCAc-G
ATCTTCTGaA---TCGgCAGACgTGCTAACC-ACTA-CACCACAgg-cctat--------
------------------------------------------------------------
---------ttcActgta--------------------------
>input_187.bnk
cTGGATgTCAAACTCAG-GATCTGGAAACAGT----------------------GA-aaa
AaA---------------------------CACAGCggCCCA-CGGGAATCGAACCAG-G
ATcTTCTGaA---TcGGcCAGAGTGCTAAcC-ACTA-CACCAcAgg-cCaCTA-------
------------------------------------------------------------
--tgAtcaaTTcactGcTAaca----------------------
>input_189.bnk
cTgGATgtCAAACTCA--gATCTGgAAaaagt----------------------gA-AAA
AAa---------------------------caCAgCgaCCCA-CGGGAATCGAACCAC-G
ATCTTCTGTA---TCGgCAGACGTGCTAACc-ACTA-CAcCACAgg-cccaAa-------
------------------------------------------------------------
---------TTcacTtaa--------------------------
>input_183.bnk
cTGGATGTCaAACTCAgaGATCTGaAAACAGT----------------------GA-AAA
aaa-------------------------------CCAGCACcACGGGAATCGAACCACgG
ATCTTCTGcA---TCGgCAGAcGTGCTAACC-ACTA-CACCAcAgg-CcAtga-------
------------------------------------------------------------
------tcattcactgaaa-------------------------
>input_171.bnk
CTGGATGTCaAACTCAG-GATCTGgAAACAGT----------------------gg-AAA
AAa------------------------------ACCAgACCA-CGGGAATCgAACCACgG
ATCTTCTGgAATCcgGcCAGAcGTGCTAACC-ACTA-CACCACAgg-Ccatt--------
------------------------------------------------------------
----------tcacTgctaa------------------------
>input_190.bnk
cTggATGTCAAAcTcAg-GATCTGGAAACAGt----------------------gA-AAA
AaA-------------------------------acAGCACCCAGGGAATCGAACCACgG
ATCTTCTGcTATC--gGCAGAcGTGCTAACC-ACTA-CACCACAGG-CtgCTA-------
------------------------------------------------------------
---gATcaATTcaTgcTAAa------------------------
>input_186.bnk
cTggATgTCAAAcTCAaAGATCT-GAAACAGT----------------------aA-AAA
Aaa-----------------------------CAGcgACCCA-cGGgAATCgAACCAC-a
ATCTTCTCTA---TCGGCAGACgTGCTAACC-ACTA-CAcCAcAGg-cgCTA--------
------------------------------------------------------------
----aATcATTcAcTgcTAAa-----------------------
>input_196.bnk
cTgGATGTCAAaCTcAGagATCTGAAAaaaAA----------------------AA-Aaa
aa--------------------------------------caCccAGAATCGAACCAc--
ATCTtcTGCTatC--GGCAGACGTGCTAACC-ACta-cacCAcAgg-cgcAc--------
------------------------------------------------------------
---gatcaTatt--------------------------------
>input_197.bnk
cTGgaTGTcAaACTcAGagAtCTggAAa-AgT----------------------GA-AAA
AAA------------------------------accAgcCCCAcgGaAATcGAACCA--g
ATCTTCtgCTATCcggC---AGATGcTAACc-ACTA--ACcacAt---------------
------------------------------------------------------------
--------------------------------------------
>input_198.bnk
cT-GATgtCAA---cTAgGAtcT-gAAacAgt----------------------aa-AAA
AAa--------------------------------cagaCcCacGGgaATCGAACCA--G
ATCTTCtgctaTc-gGgCAGAcgTGCTAAcC-AcTA-cAC-AcAgg-ccgct--------
------------------------------------------------------------
---agatAATTcAcTGTaca------------------------
>input_195.bnk
ctggATgTcAAAcTcAGAgAtCTGAAac---------------------------ATAAA
AaA-------------------------------cCAggACCAcGGGAATCGAACAg--G
ATCtTCgctA----TCgCAGAC-TGCTAACC-ACTA-cACCACAGG-CcgCT--------
------------------------------------------------------------
---AATCaATTCACTgcTAaa-----------------------
>input_193.bnk
----tgatcagAtaCag---------atcAaT----------------------Ga-AAA
AAA-------------------------------AacAtccagctGGAATCGAACCAc--
ATCTTCaGgTAT--GCCCtGAtgT-CTAACC-AtTAACACtgGAca-tgTAAT-------
------------------------------------------------------------
tat-----------------------------------------
>input_194.bnk
------------------tataTcAAatagAtT--------------------TAa-AAA
GAa----------------------------AAAcAGcaccCACaGGAATCGAACCAggt
TTCTgCA-----TccGGCAGAT---cTAACc-ACTA-cACCAAgca-ATtcTgtaa----
------------------------------------------------------------
--------------------------------------------
>input_199.bnk
ct-ggtgtcaaactcagA----ttgAAACAgt----------------------ga-aaa
Aaa-----------------------------------AAcCCAcgGgATcgAAccAgga
ttcttatGaCaga-----------GTCTAAc-AcTa-caccaAaat--------------
------------------------------------------------------------
--------AtTcAtTgT---------------------------
>input_191.bnk
------------------------aaATAAATT------------------------AaA
AAA--------------------------TtAATTtGcGccGCCgGGAaTCGAACaCCGG
ATCTTCTGAaTGG-CCTCAGATGCTTTaACCAGTTA-AGCTACgCA------G-------
------------------------------------------------------------
---CTcCAATTaATTTcTAa------------------------
>input_192.bnk
----------------------aAaAcAtAATT------------------------AAA
AAa--------------------------TAAttaGCCACcGCCtGGAttCGAACCAGGg
TCTTCTaAtTAGA-tCTCAGATGCTTTAACc-GCTA-AGCTACAcA--------------
------------------------------------------------------------
----GCcaATTaatATTcA-------------------------
>input_200.bnk
------------------------gtaagaAtc--------------------tgA-ata
aaa-------------------------AacatAtcAgGAtaacagTCtccttaatggta
gcctT---------------------------AAtA-CTtcatcta--------------
------------------------------------------------------------
--------------------------------------------
