>t4
GTGCGGGTCGGATAAACACCTTGCTGGCGCCGGGGTTCAATCCCGGTCCCGCA-AAATTAATCTGAATTCCAAACCCTTCCTACACCTCTGACAAG-------------ACATCTTGTGAATGTG---GGGAATGCCAGGCCGCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCT
>input_005.bnk
----------------------------------------ctCGGTCCCGGCACAGATTTATCTGATTtCCAAACCCTTCCTTCACCTCTGACAAG-------------ACATCTTGTGAATGTG---GGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_006.bnk
----------------------------------------cTCGGTCCCGGCACAGATTTATCTGATTTCCAAACCCTTCCTTCACCTCTGACAAG-------------ACATCTTGTGAATGTG---GGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GC-
>input_020.bnk
--------------------------------------tcCTCGGTCCCGGCACAGATTTATCTGATTTCCAAACCCTTCCTTCACCTCTGACAAG-------------ACATCTTGTGAATGTG---GGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_017.bnk
-------------------------------------ATCCTCGGTCCCGGCACAGATTTATCTGATTTCCAAACCCTTCCTACACCTCTGACAAG-------------ACATCTTGTGAATGTG---TGGAATGCCAGGCCGCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCG
>input_018.bnk
-----------------------------------taaTCCTCGGTCCCGGCACAGATTTATCTGATTTCCAAACCCTTCCTACACCTCTGACAAG-------------ACATCTTGTGAATGTG---TGGAATGCCAGGCCGCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCG
>input_019.bnk
------------------------------------tatcCTCGGTCCCGGCACAGATTTATCTGATTTCCAAACCCTTCCTACACCTCTGACAAG-------------ACATCTTGTGAATGTG---TGGAATGCCAGGCCGCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCG
>input_023.bnk
---------------------------------------------atcCcgCAcAgATTTATcTGATTaCCAAACCCTTCCTTCACCTCTGACAAG-------------ACATCTTGTGAATGTG---GGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_021.bnk
--------------------------------------TCgtC-------------atttAttTGATTaCCAAACCCTTCCTTCACCTCTGACAAG-------------ACATCTTGTGAATGTG---GGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_024.bnk
-----------------------------------------------ctcggccAAATTTATCTGATTaCCAAACCCTTCCTTCACCTCTGACAAG-------------ACATCTTGTGAATGTG---GGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_007.bnk
-----------------------------------------tCgGTCCCGGCA-AAGATTTATCTGATTCCAAACCCTTCCTTCACCTCTGACAAG-------------ACATCTTGTGAATGTG---GGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_022.bnk
--------------------------------------------------------attttTTattAtTcCAAACCCTTCCTTCACCTCTGACAAG-------------ACATCTTGTGAATGTG---GGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_029.bnk
-----------------------------------------------------ccgccaTTtaTgaTTaccAAACCCTTCCTTCACCTCTGACAAG-------------ACATCTTGTGAATGTG---GGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_025.bnk
---------------------------------------------ctccggca-cAaATtATCtGATttCCAAACCCTTCCTTCACCTCTGACAAG-------------ACATCTTGTGAATGTG---tGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCG
>input_001.bnk
----------------------------------------------ccggcac-AGATTTATCTGATTACCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---GGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_013.bnk
-------------------------------------------------------aaTtTATCTGATTaCCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---GGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_009.bnk
------------------------------------------------------AgATTTATCTGATTGCCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---GGGAATGCCAGGCCTCCACCGTGGTTCGGATCCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GC-
>input_032.bnk
---------------------------------------------------ac-AgATTTATCTGATTGCCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---GGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_034.bnk
------------------------------------------------------cAATTTATCTGATTGCCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---gGGAATGCCAGGCCTCCACCGTGGTTCGGATCCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_002.bnk
----------------------------------------------------c-AgATTTATCTGATTgCCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---TGGAATGCCAGGCCTCCACCGTGGTTCGGATCCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_026.bnk
------------------------------------------------------AgaTTTATCTGATTgCCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---TGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_014.bnk
------------------------------------------------------AaATTTATCTGATTgCCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---tGGAATGCCAGGCCTCCACCGTGGTTCGGATtCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GC-
>input_035.bnk
-------------------------------------------------------aATTTATCTGATTgCCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---TGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GC-
>input_003.bnk
------------------------------------------------------AgATTTATCTGATTaCCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---TGGAATGCCAGGCCTCCACCGTGGTTCGGATCCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GC-
>input_010.bnk
----------------------------------------------------c-AGATTTATCTGATTACCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---TGGAATGCCAGGCCTCCACCGTGGTTCGGATCCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_016.bnk
------------------------------------------------------AgATTTATCTGATTaCCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---TGGAATGCCAGGCCTCCACCGTGGTTCGGATCCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_011.bnk
------------------------------------------------------AaATTTATcTGATTaCCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---TGGAATGCCAGGCCTCCACCGTGGTTCGGATCCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_015.bnk
----------------------------------------------------a-AgATTTATCTGATTGCCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---tGGAATGCCAGGCCTCCACCGTGGTTCGGATCCCACGTTAAACTGTAGGTCCTtCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_033.bnk
-------------------------------------------------------AaATTATcTgATTgCCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---TGGAATGCCAGGCCTCCACCGTGGTTCGGATCCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_004.bnk
--------------------------------------------gTcCCgGCA-AGATTTATCTGATTACCAAACCCTTCCTTCACCTCTGACAAGACgtgtattaatcacATCTTGTGAATGTG---GGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_012.bnk
---------------------------------------------------------aATTATCTgATTCCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---GGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_036.bnk
-------------------------------------------------------aaaATTTatctAttccAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---TGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_042.bnk
--------------------------------------------------------aAatttaTTgAtTcCAAACCCTTcCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---gGGAATGCCAGGCCTCCACCGTGGTTCGGATCCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GC-
>input_037.bnk
-------------------------------------------------gcAA-aTATaTtTcTtAtTaCCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---TGGAATGCCAGGCCTCCACCGTGGTTCGGATCCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCG
>input_043.bnk
--------------------------------------------------------aaAtTtATTATTgCCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---TGGAATGCCAGGCCTCCACCGTGGTTCGGATCCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_008.bnk
-------------------------------------------------------aaATTTATTGATTgCCAAACCCTTCCTTCACCTCTGACAAGACGTGTATTAATCACAACTTGTGAATGTG---gGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTtCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_031.bnk
---------------------------------------------------------aATTTATTgAT-TCcAAACCTTcctTCACCTCTGAcAAGACgTGTATTAATCACAACTTGTGAATGTG---TGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_038.bnk
-----------------------------------------------------------------atTtgatTAAAcCtTcTtCAccTctGacAA---ATGTATTAATcACAACTTGTGAATGTG---TGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_045.bnk
--------------------------------------------------------------aaataTtTtcAAAccCtTCTtcAccTcTa--CAAGAgtgtattaatCACAACTTGTGAATGTG---TGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GC-
>input_044.bnk
-------------------------------------------------------------------------atAAAcTtCaTTaCTcTgACAAgAcgTGTATTAATCA-AACTTGTGAATGTG---TGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GC-
>input_027.bnk
---------------------------------------------------------------cgTTcTAtcAAaaaatAttAcAActTtTTaaataaat-------ataCAtCTTGTGAATGTG---GGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_030.bnk
-----------------------------------------------------------------------atatacttaatTtactct--------------AcAAatAcATCTTGTGAATGTG---GGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_039.bnk
-----------------------------------------------------------------attaAtatActataaccttcCTTataaAttTTaat-------------acAttgaATGTG---gGGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GC-
>input_028.bnk
----------------------------------------------------------------------ttaaAAaTTaataatattcta----------------------aattTTAaTgTG----GGAATGCCAGGCCtCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_041.bnk
---------------------------------------------------------------------aaAAaaccTTacTAC---------------------AatTAtATaatgTgAATGTG----GGAATGCCAGGCCTCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTCCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GCg
>input_040.bnk
-----------------------------------------------ccgTtA-atcctctagTacggTaCAaACCCTTCCTTCACcTCTGACAG--------------ActaCTTGTGAATGTG----GGAATGCCAGGCCtCCACCGTGGTTCGGATTCCACGTTAAACTGTAGGTCCTTCATTTC-------------------------------------------------------------------------------------------------------ATCTCACAATCACCCTACCATTACACATTAGCGTAAGT----GC-
>input_046.bnk
----------------------------------------------TACGGCA-CAATTTATTTATTTTAAAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGACTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT----T--
>input_047.bnk
----------------------------------------------TACGGCA-CAATTTATTTATTTTAAAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGACTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT----T--
>input_048.bnk
----------------------------------------------TACGGCA-CAATTTATTTATTTTAAAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGACTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT----T--
>input_049.bnk
----------------------------------------------TACGGCA-CAATTTATTTATTTTAAAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGACTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT----T--
>input_050.bnk
----------------------------------------------TACGGCA-CAATTTATTTATTTTAAAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGACTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT----T--
>input_051.bnk
----------------------------------------------TACGGCA-CAATTTATTTATTTTAAAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGACTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT----T--
>input_052.bnk
----------------------------------------------TACGGCA-CAATTTATTTATTTTAAAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGACTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT----T--
>input_054.bnk
----------------------------------------------TACGGCA-CAATTTATTTATTTTAAAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGACTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT----T--
>input_055.bnk
----------------------------------------------TACGGCA-CAATTTATTTATTTTAAAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGACTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT----T--
>input_058.bnk
----------------------------------------------TACGGCA-CAATTTATTTATTTTAAAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGACTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT----T--
>input_059.bnk
----------------------------------------------TACGGCA-CAATTTATTTATTTTAAAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGACTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCcACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT----T--
>input_060.bnk
----------------------------------------------TACGGCA-CAATTTATTTATTTTAAAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGACTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT----T--
>input_061.bnk
----------------------------------------------TACGGCA-CAATTTATTTATTTTAAAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGACTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT----T--
>input_062.bnk
----------------------------------------------TACGGCA-CAATTTATTTATTTTAAAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGACTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT----T--
>input_053.bnk
---------------------------------------------ATACGGCA-CAATTTATTTATTTTAAAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGACTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT-------
>input_056.bnk
----------------------------------------------TACGGCA-CAATTTATTTATTTTAAAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGACTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCAACATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT----T--
>input_057.bnk
----------------------------------------------TACGGCA-CAATTTATTTATTTTAAAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGACTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCAACATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT----T--
>input_063.bnk
----------------------------------------------TACGGCA-CAGTTTATTTATTTTCCAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAAGCCTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCTAATCACACTATCACTATACA-AAGCTTAAGT----T--
>input_065.bnk
---------------------------------------------aTACGGCA-CCGTTTATTTATTTTCCAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCATAAATTTA---TAGATTTACAATCCTTCACAATGGTTTGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCTAATCACACTATCAATATACA-AAGCTTAAGT----TCG
>input_066.bnk
----------------------------------------------TACGGCA-CCGTTTATTTATTTTCCAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCATAAATTTA---TAGATTTACAATCCTTCACAATGGTTTGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCTAATCACACTATCAATATACA-AAGCTTAAGT----TCG
>input_067.bnk
---------------------------------------------aTACGGCA-CAGTTTATTTATTTTCCAAAGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTA---TAGATTTACAATCCTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCTAATCACACTATCAATATACA-AAGCTTAAGT----TCg
>input_064.bnk
---------------------------------------------ATACGGCA-CAGTTTATTTATTTTCCAATGAATTCCTTCAACTCTAGCAAGTAGTGTTTTATTCACAACTCGTAAATTTG---TAGATTTACAAGCCTTCACAATGGTTCGGATCCCAGGATAATCTGTAGGTCCACCATTTC-------------------------------------------------------------------------------------------------------ATCTCCAAATCACACTATCACTATACA-AAGCTTAAGT-------
>input_068.bnk
---------------------------------------------------------------------------------tAcGcTAATgTGTAATGGT-------------AGGGTGATTGTGAGATgAAATGAAGgACCTACAGTTTAACGTGGaATCCGAACCACGGTGGaGgccTGGcATTCc-cACaTTCACAAGTagtgtttTaTtCACgtCTTGTcAGAgG-TGTAGgAaGgcaagcttcaccatggTTTGGAAAcaAGgTTAATCTGTaggAcctCCAtttcatctcctaatca-acTatcatTAtAca--agcTTAAGt----gCg
>input_069.bnk
---------------------------------------------------------------------------CGCACTTACGCTAATGTGTAATGGT-------------AGGGTGATTGTGAGATGAAATGAAGGACCTACAGTTTAACGTGGAATCCGAACCACGGTGGAGGCCTGGCATTCCCCACATTCACAAGaTGTgaTtAATACACGTCTTGTCAGAGG-TGAAGGAAG--------------GGTTTGGtAATCAgATAAATctgTg------------------------------ccggGACCgA--GGatTgAAcCccggcc
>input_071.bnk
---------------------------------------------------------------------------cgcactTACGCTAATGTGTAATGGT-------------AGGGTGATTGTGAGATGAAATGGAGGACCTACAGTTTAACGTGGGATCCGAACCACGGTGGAGGCCTGGCATTCCACACATTCACAAGTTGTGATTAATACACGTCTTGTCAGAGG-TGAAGGAAG--------------GGTTTGAATCAGAtAaatcgga---------------------------------------------ggaTtgAac------c
>input_074.bnk
---------------------------------------------------------------------------------TACGCTAATGTGTAATGGT-------------AGGGTGATTGTGAGATGAAATGGAGGACCTACAGTTTAACGTGGAATCCGAACCACGGTGGAGGCCTGGCATTCCaCACATTCACAAGTTGTgAttAATACAcGtCTTGTCAGAGG-TGAAGgAaG--------------GgTTTGgAatcaAtaataacg--------------------------------------------------------------
>input_070.bnk
---------------------------------------------------------------------------------TACGCTAATGTGTAATGGT-------------AGGGTGATTGTGAGATGAAATGAAGGACCTACAGTTTAACGTGGAATCCGAACCACGGTGGAGGCCTGGCATTCCCCACATTCACAAG-------------ATGTCTTGTCAGAGg-TGaAggatt--------------taTtaacagAtattagaa-----------------------------------------taaaca--agttc-----------
>input_072.bnk
------------------------------------------------------------------------------actTACGCTAATGTGTAATGGT-------------AGGGTGATTGTGAGATGAAATGAAGGACCTACAGTTTAACGTGGAATCCGAACCACGGTGGAGGCCTGGCATTCC-CACATTCACAAttC-----------------Tgtaga----tgaAggaAgGTt-----------ttccgGcAcagaAgCcGaAc-----------------------------------ccacgatcCT--atCCta----------
>input_073.bnk
---------------------------------------------------------------------------------TACGCTAATGTGTAATGGT-------------AGGGTGATTGTGAGATGAAATGGAGGACCTACAGTTTAACGTGGAATCCGAACCACGGTGGAGGCCTGGCATTCC-attatatTtaaaAa-----------------taTaaaAaTTTgaTgaAcagta-----------tttt----cagaa----------------------------------------------------------------------
>input_075.bnk
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
