>g1 Consensus of sequences 2-71
GGGCCTCCCCGGTGGCGCAGCGGTTGAG-CGCTGGGTTGCGAAGCTGCCCGCAGCCTCTG
CAGCGCCGGTTCGAT-CCCCGGCTG-----CTCCCCGGCCACCGGAG-GAGGGTCCCACA
TGGCGCAGCAGACCTCTCCTGC--CGCCCGCTGCTCCCCTCAGCAGTGTACTTCGGTCCT
TCTGCCTGCTCTGCTCCCCGCTCTGGCTCTGGTGAATTCTCTCACCCTCCCG-----CGC
TTCTGA-CTGTACCCAGTGCTTGTAT--ATAAAAATAAAAAATCAATCAATAATAAAAAA
TAAATAAAATAAATAAATAAATATAATAAATCTTTAAAA
>g2 Consensus of sequences 3-49
GGGCCTCCCCGGTGGCGCAGCGGTTGAG-CGCTGGGTTGCGAAGCTGCCCGCGGCCTCTG
CGGCGCCGGTTCGAT-CCCCGGCTG-----CTCCCCGGCCACCGGAG-GAGGGTCCCACA
TGGCGC-GCAGACCTCTCCTGC--CGCCCGCTGCTCCCCTCAGCAGTGTACTTCGGTCCT
TCTGCCTGCTCTGCTCCCCGCTCTGGCTCTGGTGAATTCTCTCACCCTCCCG-----CGC
TTCTGA-CTGTACCCAGTGCATGTATAAACAAAAACAAACAAACAAACACAAAAAATAAA
TAAATAAAAAACATGCCTCTATAAAA-------------
>g3 Consensus of sequences 4-102
GG----CCCCGGTGGCGCAGCGGTTGAG-CGCTGGGCTGCGAAGCTGCCCGCAGCCTCTG
CAGCGCCGGTTCGAT-CCTCCCCGGCCGCCCTCCCCGGCCACCGGGC-GAGGGTCCCACA
TGGCGCGACAGACCTCTCCTGCCGCGCCCGCTGCTCCCCTCAGCAGTGTA-TTCGGTCAG
TCTGCCTGTTCTG-TCCCCGCTCTGGCTCTGGTGAATTCTCTCACCCTCCCG-----CGC
TTCTGA-CTGTACCCAGTGCTTGTAT--AAATAAATAAATAAATAAATCTTTAAAA----
---------------------------------------
>g4 Consensus of sequences 5-248
GGGCCTCCCTGGTGGCGCAAGGGGTTAA-GTCCCCACTATGAAGCTATCCGCAGCCACTG
CAGCA-GAGTTCGATCCCCCGGCCG---------GCCGCAGCAGGGGAGCTACCCACAAT
GGCGCA-GCAGACCTCTCCTGTCTCGCCCGCTGCTCCCCTCAGCAGTGTATTTCAGT-CA
TCTGCCTGTTCTG-TCCCCACTCTGTCTCTGGTGAATCCTCTCACCCCCCCCCCCC-CAC
CTCTGGCCTGTACCCCAGTCTTGTAT--GCATAAATAAA-AAATAAAAATAAATCTTTAA
AA-------------------------------------
>g5 Consensus of sequences 6-121
GGGCCTCCCTGGTGGCGCAGGGTTGAGT-CGCAGCGCTGTGAAGCTGTCCGCAGCCTCTG
CAGCG-CGGTTCGAT-CCCCGGCCG---------GCCG----------GAGACCCACATA
TGGCGC-GCAGACCTCTCCTGTCTCGCCCGCTGCTCCCCTCAGCAGTGTATTTCAGT-CG
TCTGCCTGTTCTG-TCCCC-CTCTGTCTCTGGTGAATCCTCTCACCCCCTCC-----CGC
CTCTGGCCTGTACCCCGTTCTTGTAT--ATAAATATAAATAAATAAAAATAAATCTTTAA
AA-------------------------------------
>g6 Consensus of sequences 7-30
GGGCCTCCCTGGTGGCCTAGGGGTTAAGTCTCAGCGCTATACAAGCTTCCGCAGCCACTG
--GCCTGAGTTCGAT-CCCC--------------GCCGCCACGGGAGCTAAACCCACATA
TGGCCA-GCAGACCTCTCCTGTCTCGCCCGCTGCTCCCCTCAGCAGTGTATTTCAGT-AA
TCTGCCTGTTCTGCTCCCCACTCTGTCTCTGGTGAATCCTCTCACCCCCCCCCCCCTCAC
CTCTGGCCTACACCCCAGTTCTTCTA--TGCAAAATAAA-AAATAAATAAAAAATA----
---------------------------------------
