>g1 Consensus of sequences 2-71
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------GGGCCTC----CCCGGTGGCGCAGC-GGTTGAGCGCTGGGTTGCG
AAGCTGCCCG-CAGCCT---CTGCAGCGCCGGTTCGATCC-------CC-GGCTGC----
-TCCCCGGCCACCG------GAGGAG----------------------GGTCCCACATGG
CGCA---------------GCAGACCTCTCCTGC----CGCCCGCTGCTCCCCTCAGCAG
TGTACTTC----GGTCCTT---------CTGCCTGCTCTGCTCCCCGCTCTGGCTCTGGT
GAAT--TCTCTCACC-----CTCCCGCGCTTC-TGAC-TGTA-CCCAGTGCTTGT---AT
ATAAAAAT----------------AAAAAATCAATC-------AAT----------AATA
AAAAATAAATAAAA-----------TAAATAAAT------AAA----TATAATAAATCTT
TAAAA--------------
>g2 Consensus of sequences 3-49
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------GGGCCTC----CCCGGTGGCGCAGC-GGTTGAGCGCTGGGTTGCG
AAGCTGCCCG-CGGCCT---CTGCGGCGCCGGTTCGATCC-------CC-GGCTGC----
-TCCCCGGCCACCG------GAGGAG----------------------GGTCCCACATGG
CGC----------------GCAGACCTCTCCTGC----CGCCCGCTGCTCCCCTCAGCAG
TGTACTTC----GGTCCTT---------CTGCCTGCTCTGCTCCCCGCTCTGGCTCTGGT
GAAT--TCTCTCACC-----CTCCCGCGCTTC-TGAC-TGTA-CCCAGTGCATGT---AT
AAACAAAAAC--------------AAACAAACAAAC-------ACA----------AAAA
ATAAATAAATAAAA------------------------------------AACATGCCTC
TATAAAA------------
>NW023601322.1:79451366-79451739(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------tctggaagaCAGAGCCTTTTTTACTTA-CTGCTTTA
AAACTTCcccaatcagggcctc----cccggtggcgcagc-ggttgagcgctgggttgcg
aagctgcccg-cggcct---ctgaggcgccagttcgatcc-------cc-ggctgc----
-tccccggccaccg------gaggag----------------------ggtcccacatgg
cgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--tctctcacc-----ctcccgcgcttc-ggac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaaccaaa-------aaa----------aaaa
aattaaaaaaaaaa-----------taaataaat------aaa----taaaacttccccA
ATCAATAC-----------
>NW023603184.1:54391201-54391574(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------TAatctcaaaataatcaaaataaaaat-gaatttta
aaaaattcatattgagggcctc----cccggtggcgcagc-ggttgagcgctgggttccg
aagctgcccg-cagcct---ctgcagcgccagttcgatcc-------cc-ggctgc----
-tccccggccaccg------gaggag----------------------ggtcccacatgg
tgc----------------gcagacctctcctgc----cgcccgctgcccccctcagcag
tgtacttt----ggtcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--tctctcacc-----ctcccgcgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatatta-------aag----------aaaa
aaaaagagataaac-----------actTATCTG------TTG----Accttcttgtatt
taaaaaaa-----------
>NW023601754.1:4083848-4084225(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------tatttattaccCTTAAGAGTAAAAatc-atgtgttt
aaaaataaatttacagggcctc----cccggtggcgcagc-agttgagcgctgggttgcg
aagctgcccg-cggcct---ctacagcgccagtttgatcc-------cc-agctgc----
-tccccggccaccg------gaggag----------------------ggtcccacatgg
cgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgcacttc----ggtcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--tctctcccc-----ctcccgcgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaataaatctt---ttaa----------aaaa
taaaaaaatttaaa------------------------aaaaa----ataaatttacatt
tcttgACTAGGAA----AA
>NW023601543.1:43819575-43819948(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------aaaatggaaaaaatcaatgaaacaaaa-agttcttt
aaaaaacagtattcagagcctc----cccgggggcgcagc-cgttgagcgctgggttgcg
aagctgcccg-cagcct---ctgcagtgccggttcgatcc-------cc-ggctgc----
-tccccggccacca------gaggag----------------------ggtcccacatgg
cgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--tctctcacc-----ctcccgcgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatcttt-------aaa----------aaaa
aaaaagaacaatag-----------cattcaggg-------------cctccctggtggc
acaagggttta--------
>NW023601104.1:75543782-75544155(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------CCTAGTACTTTAGAGAAGAGTCATGAA-CACATGTA
AAGAACAGctatccagggcctc----ccgggaggcgcagc-ggttgagcgctgggttgcg
aagctgcccg-cagcct---ctgcagcgccggttcgatcc-------cc-ggctgc----
-tccccggccaccg------gaggag----------------------ggtcccacatgg
cgc----------------gcagacctctcctgc----cgcccactgctcccctcagcag
tgtacctc----ggtcctt---------ctgcctgctctgccccccgctctggctctggt
aaat--tctctcacc-----ctccctcgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatcttt-------aat----------aaat
aaataaataaataa-----------atcttttaa------aaa----aaaaaaaaagaac
agctatcc-----------
>NW023601653.1:6834086-6834461(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ATGTTGGGCATTGTAtaccttcagaaa-ataaaata
aaggctggcagaagtgggcctc----cctggtggcgcagc-ggttgagcactgggttgcg
aagctgcccg-cagcct---ctgcagcgccagttcgatcc-------cc-ggctgc----
-cacccggccatgg------gaggag----------------------ggtcccacatgg
cac----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--tctctcacc-----ctcccgcgcttc-tgac-tgta-cccagtgcttgt---at
aaataaataa--------------aaataaatcttt-------aaa----------aaaa
aaaaaaaaggctgg-----------caGAAGAAA------TAG----AGCTAACAGGTGA
ATAGAGGT-----------
>NW023603184.1:115558621-115558994(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------TGAAAAAGGGACTGGTCAACTCTtctg-aatacatt
aaaaattgaaatatagggcctc----cttggtggcgcagc-agttgagcgctgggttgcg
aagctgcccg-cagcct---ctgcagcgccggtttgatcc-------cc-ggctgc----
-tctccggccaccg------gaggag----------------------ggtcccacatgg
cgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttt----ggtcctt---------ctgcctgctctgctccccactctggctctggt
gaat--tctctcacc-----ctcccgcgtttc-tgat-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatcttt-------aaa----------aaaa
aaaaaagaaatata-----------gactAAGCA------ATA----TCTGTTGAATCTG
ACAGTACA-----------
>NW023601322.1:66901908-66902273(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------TGGCATTTGCCAGACTTGTAGAAGACC-ATGTCTTA
AAATAGGggctcattgggcctc----cccggtgacgcagc-ggttgagcgctgggttgcg
aagctgcccg-cagcct---ctgcagcgccggttcgatac-------cc-ggatgc----
-tccctggccaccg------gaggag----------------------ggtcccacatgg
cgc----------------gcagacctctcttgc----cacccgctgctcccctcagcaa
tgtacttc----ggtcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--tctctcacc-----ctcctgcgcttc-tgac-tgta-cccagtgcttgt---at
aaatgaat----------------gaatgaatgaat-------gaa----------tgaa
tgaatgaataaata-----------aataaatct------taa----aaaaaaagactaa
-------------------
>NW023603184.1:113758423-113758795(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------CAAAGCTATGTATCAGGAACAGTAGAA-TAGTTATA
TAGAAAtaaggaacagggcctc----cccggtggcgcagc-agttgagtgctgggttgca
aagctgcccg-cagcct---ctgcagcaccagttcgatcc-------cc-ggttgc----
-tcccgggccacca------gaggag----------------------ggtcccacatgg
tgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgttctgctccctgttctggctctggt
gaat--tctctcacc-----ctcctgcacttc-tgac-tgta-cccagtgcttgc---at
aaataaat----------------aaataaataagt-------aaa----------taaa
tgaacgaataaata-----------aataaataa------ata----aataaataaataa
ataaata------------
>NW023605083.1:15063894-15064266(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------AATCATGTATAGAATATGAGTACAATT-ATGTGATT
GAAAAATgcatagcagggcctc----cctggtggcgcagc-ggttgagcgcggggttgcc
aagctgcccg-cagcct----tgcagcgccggttcgatcc-------cc-ggctgc----
-tccccggccaccg------gaggag----------------------ggtcccacatgg
cgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctccccgctctggctctggt
ggat--tctctcacc-----ctcccgtgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatcttt-------aaa----------aaaa
aaaaaaaaagaaaa-----------atgcatagc------AAA----AAAAGACTGGATG
GAGGTACA-----------
>NW023605083.1:50859996-50860373(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------GATACtcttgcaaatatattttatgtt-tttttctt
aaaagaataaaatgagggcctt----cccggtggcgcagt-ggttgagcgctgggttgcg
aagccacccg-cagcct---ctgcagtgccggtgtgatcc-------cc-ggctgc----
-tccccagccactg------gaggag----------------------ggtcccacatgg
tgc----------------gcagacctctcctgc----cgccctctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgttctgctccctgctctggctctggt
gaat--tctctcacc-----ctcccgcgcttc-tgac-tgta-cccagtgcttgt---at
aaataaata------------ataaaataaatcttt-------aaa----------aaaa
aaaaaagaataaaac-------------------------gaGTTCTGTGTGTAGGATGT
GTAGAGCATTGC-------
>NW023604972.1:48078252-48078629(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------AGTCTTCCCAATTGGACATAGTACTGA-AATAGTTA
GAAGATGCacgtttagggcctc----cccggtggcgcagc-ggttgagcactgggttgcg
aagctgcccg-cagcct---ctgcagcgctggttcgatcc-------cc-ggctgc----
-tccccggccacct------gaggag----------------------ggtcccacatgg
tgc----------------gcagacctcctctgc----cacccgcagctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctccctgctctggctctggt
gaat--tctctcacc-----ctccctcacttc-tgac-tgta-cccagtgcttat---at
gtataaata------------aataaataaatcttt-------taa----------aaaa
aaaagatataataa-----------aaaaaagaa------cat----gcacgtttaagaa
aatagaat-----------
>NW023602073.1:57076977-57077346(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------CAAAATAGCCACTATATAGATGGAATT-TGGTTTAA
AATACTAttcctctagggcctc----cctggtggcgcagc-agttgagcgctgggttgca
aagctgcccg-cagcct---ctgcagcaccggttcaatcc-------cc-ggctgc----
-tccccggccacca------gaggag----------------------ggtcccacatgg
cac----------------acagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--tcgctcacc-----ctcctgcgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------caataaatttct-------ttt----------ttaa
taaataaataaata-----------aaatactattcc----------TTTAGTGGGGAGG
GAAA---------------
>NW023604861.1:110402289-110402666(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------AATAAATGTCTATCAATAAGAAAaggc-tatttaaa
ataaatctaatgggggggcctc----cctggtggcgcagt-ggttgagcgccgggttgcg
aagctgcccg-cggcca---ctgcagcgccggttcgatcc-------cc-ggctgt----
-tccccggctaccg------gaggag----------------------ggtcccacatgg
cgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--tctctcacc-----ctcctacacgtc-tgac-tgta-cccagtgcttgtataat
aaataaat----------------aaaataaatctt-------aaa----------aaaa
aaaattaattaaat-----------aaaataaat------cta----atgggcctcccca
gtggcgca----------g
>NW026555331.1:69542013-69542386(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------tattctaaaaattaaattttctctaat-attttagt
ttaaaatctattttggggcctc----cccggtggtgcagc-ggttgagcgctgggttgcg
aagctgcccg-cagcct---ctgcagtgcaggttcgatcc-------cc-ggctgc----
-tccctggccacca------gaggag----------------------ggtcccatatgg
ctc----------------ccagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--tctctccca-----ctcctgcgcttc-tgac-tgtt-cccagtgcttgt---at
aaataaat----------------aaataaatcttt-------taa----------aaag
aaataaaataaaat-----------aaaataaaa-------------tctattttgtgtt
ttttttttaag--------
>NW023605194.1:19880822-19881195(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------GAACCTAGCTCTGAGCCAAACCCTCAA-TGCAGATC
AAAACTttgcctctggggcctc----cccggtggcgcagc-agttgagcgctgggttgcg
cagctgcccg-cagcct---ctgcagcgccggttcgatcc-------cc-ggctgc----
-tccccggccactg------gaggag----------------------ggtcccacatgg
cgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgttcctcactctgactcaggt
gaat--tctctcacc-----ctcccacacttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatcttt-------aaa----------aaaa
aaaaactttgcccCT----------GGTGTGGGACT-----------GCAGACAAGGCAC
CCTGTGAG-----------
>NW023601962.1:333228-333600(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------TGTAGTCCAACCTAAACCTGTcttta-aatgaaga
tttaaaaataaaatgtgggcct----cccgttggcacagc-ggttgagcactgggttgcg
aagctgcccg-cagcct---ctgcagcgccagtttgatcc-------cc-ggctgc----
-tccccagccactg------gaggag----------------------ggtcccacatgg
cgc----------------gcagacctctcctgt----ggcccgctgctcccctcagcgg
tgtacttc----ggtcctt---------ctgcctgctctgctacccgctctggctctggt
gagt--tctctcacc-----ctcccgtgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatctta-------aat----------aaat
aaataaataaataa-----------ataaattaa------att----aaaatgcaccACA
TATCTGTT-----------
>NW023605083.1:134187339-134187713(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------AAGGGGTGCAATGGGGAGCACCTGGGTT-GGATTGAA
AGTATGGCACccctgggcctcc----actggtggtgcagc-gattgagcgctgggctgcg
aagctgcccg-cagcct---ctgcagcgccggttcaatcc-------ct-ggcagc----
-tccccggccaccg------gaggag----------------------ggtcccacatgg
cgc----------------acagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctccccactctggctctggt
gaat--cctctcacc-----ctcccgcgcttc-tgac-tgtg-cccagtgcttgt---at
aaataaat----------------aaataaatctta-------aaa----------aaaa
aaaaaaaagaaagt-----------gtggcACCC------TTA----ACCACTaagccag
ccagccag-----------
>NW023605305.1:28435729-28436102(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------TTCCTTGCAAAATAGAGCAAAATAGAG-GAGGAGCA
AGAAATAcatttggtgggcctc----cccggtggcacagc-ggttgagtgctgggttgca
aagctgcccg-cagctt---ctgcagcgccaattcgatcc-------cc-tgctgc----
-gccccagccacca------gaggag----------------------ggtcctacatgg
cgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgttcttc----ggtcctt---------ctgcctgctctgctccctgctctagctctggt
gaat--tctctcacc-----ctcccgcgcttc-tgtc-tgta-cccagtgcttgt---at
aaataaat----------------atataaatctta-------aaa----------aaaa
aaaaaaaaacattt-----------gggacAAGC------ACA----ATTATAAACATTA
AAGTTTCC-----------
>NW026555331.1:35055546-35055919(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------AAGCTAAAATAATAATGTTGGATAAAT-TAAGTTAA
AGAATATtattaggggggcctc----cccagtggcgcagc-ggttgagcactgggttgca
aagctgccca-cagcct---gtgcagcactggttcgatcc-------cc-ggctgc----
-tccccggccaccg------gaggag----------------------ggtcccacatgg
agc----------------acagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctccctgctctggctctggt
gaat--tttcttacc-----ctcccacgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatctta-------aaa----------aaaa
aaaggtgttgcccc-----------cccccaaaa------aaa----ggatattattagg
gcctccct-----------
>NW023605194.1:56121476-56121849(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------taaaaggTGTGCAGAGAAGGTAAATTC-AGAAGATA
AAAGAGCataatatcgggcctc----cccagtggcgcagc-agttgagcgctgggttcca
aagctgcccg-cagcct---ctgcagtgccggttcgatgc-------cc-ggctgc----
-tccccagccacca------gcggag----------------------ggtcccgcatgg
cgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--tatcttacc-----cttccgcgcttc-tgac-tgta-cccagtgtttgt---at
gaataagt----------------aaataaatctta-------aaa----------aaaa
aaaaacacataata-----------tcttgaaga------gaa----aaaaatgatgagt
aaactaaa-----------
>NW023604895.1:29600-29973(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ATGACACTAGCATCCCCCTAGATCTGA-CAATCAAA
AACCCCTtagaggttgggcctc----cctggtggcgcagc-ggttgagcgctgggttgtg
aagctgcccg-cagcct---ctgcagtgccggttcgatcc-------ct-ggctgc----
-tccccggccactg------gaggag----------------------ggtcctgcctgg
agc----------------gcagacctctcctgc----cgtctgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctttctgctctggctctggt
gaat--tctctcacc-----ctcctgcacttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatcttt-------aaa----------aaaa
aaaaaaacccttag-----------atGTTAGCA------GAT----ATCCTCAAGAAGG
GGAGGTAA-----------
>NW023604861.1:70068179-70068543(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------GAAGAACTATCTCTCATtgacatttct-ctctcttt
aaaactCTCAtttgaggacctc----cccggtggcgcagc-agttgagcgccgggttgcg
aagctgccag-cagcct---ctgcagcacccgttcaatcc-------ct-ggctgc----
-tccctggccaccg------gaggaa----------------------ggtcccacatgg
cgt----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctccctgctctgactctggt
gaat--tctctcacc-----ct-ccgcgtttc-tgac-tata-cccagtgcttgt---at
aaataaat----------------aaataaataaat-------aga----------taaa
taaataaataaatc-----------ttaaaaaaa------aaa----aactctcatttGA
-------------------
>NW023605083.1:54273610-54273982(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------GAACTGTTACCCCAAGCACATATttct-tttgcaat
taaaaaaaaacaacagggcctc----cccggtggcgcagc-ggttgagcactgggttgcg
aagatgcccg-cagcct---ctgcaacaccggttcgatcc-------cc-ggcggc----
-tccccggccacca------gaggag----------------------ggtcccacatgg
tgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctccccactctggctctggt
gaat--tctctcacc-----ctcctgcacttc-tgac-tgta-cccagtgcttgt---at
gtatgtat----------------gtatcaatcagt-------caa----------tcaa
tcaataaatcttta-----------aaacaacaa------caa----caacaaatagagt
cctaaaa------------
>NW023601543.1:7494220-7494609(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------cACTGATATTATAACCAAACACTGCCT-CCTCACTT
AAAAAGCtactttatgggcctc----cccagtggcgcagc-agttgagcactgggttgcg
aagctgcccg-cagcct---ctgcagtgccagttcgatcc-------cc-ggctgc----
-tccccggctaccg------gaggag----------------------ggtcccacatgg
cgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----gctcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--tctctcacc-----ctcccgtgcttc-tgac-tgta-ccaagtgcttgt---at
gtatgtatgtatcaatcaatcaataaataaatcttt-------aaa----------aata
aaaataaaaagcta-----------cttTATAAC------AAT----ATACCCATGAGCC
TTATTCCA-----------
>NW023601543.1:76243837-76244205(-)
CT----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------GGGGTTCATCACAGGGGTCCTCTG-TGTCCACA
TATAAAtgtgaaaagagggcct----cccggtggcgcagc-agttgagcgctgggttgcg
aagctgcccg-cagcct---ctgcagcgccggttcgatcc-------cc-ggctgc----
-tccccggccaccg------gaggag----------------------ggtcccacatgg
cgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgttccccgctctggctctggt
gaat--tctctcacc-----ctcccgcgcttc-tgac-tgta-cccagtgcttgt---tt
gtatgtat----------------gtatgtatgtat-------gta----------taaa
tcaataaaaatcaa-----------tcaatcaat------aaa----tcttttaaaaaaa
atgt---------------
>NW023604295.1:15937718-15938095(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------GCCTGAGCAAAAAGACACCACCAGAAA-CTCAAAAT
GGAATAcattttagagggcctc----cccggtggcacagc-ggttgagctctgggttgtg
aagctgccca-cagcct---ctgcagcaccggttcgatcc-------cc-ggctgc----
-tccccagccaccg------gaggag----------------------ggtcccacatgg
cgc----------------acagacctctcctgc----cgcctgctactcccctcagcag
tgtacttc----gttcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--tctctcacc-----ctcctgtgcttc-tgat-tgta-cccaatgcttgt---at
gtataaata------------aataaataaatcttt-------aaa----------aaaa
atggagtacattTT-----------AGGAGTTAC------AGA----Acgagtgttttat
ttttcata-----------
>NW023601433.1:35275871-35276242(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------AGGACTCAATAAAGGCAAACTGAAATA-GTGTCAAA
AGACAATGccgaggagggcctc----cccggtggcgcagc-ggttgagcactgggttgcg
aagctgcccg-ca-cct---ctgcagcaccggctcgatcc-------ct-ggctgc----
-tccccggccacca------gaggag----------------------ggtcccacatgg
cgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctctctgctctggctctggt
gaat--tctctcacc-----ctcccacacttc-tgct-tgta-cccagtccttgt---at
aaataaat----------------aaataaataata-------aaatctttaa--aaaaa
aaaaaaaaggacact-------------------------taA----GCTAAGGGTACAA
CTACAAC------------
>NW023601653.1:48103860-48104231(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ctataaacctaTCACTATCACTATTTG-ATTgataa
aaattactaaattttgggcctc----cccggtggcacagc-ggttgagcgctgggttgca
aagctgccca-cagcct---ctgcagtgccggttcgatcc-------cc-ggctgc----
-tccccggccacc-------gaggag----------------------ggtcccacatgg
cac----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtgcttc----ggtcctt---------ctgcctgctctgctccctgctctggctctggt
gaat--tctctcacc-----ctcccgcgcttc-tgac-tgta-ccctgtgcttgt---at
aaataaat----------------aaataaataaat-------aaatcttttt--taaaa
aattactaaatttt---------------------------------aagaatttataat
GACCATTCTTA--------
>NW023604861.1:22357666-22358046(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------gaatatCCAAGAAAATTAGTGTTGAGT-GTGcgtca
aaaatatataatgtagggtctc----cccagtggcgcagt-ggttgagcgctgggttgcg
aagctgccgg-cagcct---ctgcggcaccggttcgatcc-------cc-ggctgc----
-tccccggacaccg------gaggag----------------------ggtcccacatgg
tgc----------------acagacctctcctgc----cgcccgctgct-ccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctccctgctctggctctggt
gaat--tctctcacc-----ctcccacgcttc-tgac-tgta-cccagtgcttgt---at
gtataaat----------------aaataaataaat-------aaatcttaaa--aaaag
aatatataatatat-----------actatagaT------ACA----TGTTAGCTACAGT
ATAAAGTA-----------
>NW023604972.1:138051291-138051663(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------CAGTTGAACGACTCTGGCCCTGCAGCT-TGGTTTTT
AAAACAAttgcttaagggcctc----cccggtggcgcagc-ggttgagcgctggattgcg
aagctgcccg-cagcct---ctgcagtg-cggctcgatcc-------cc-ggctgc----
-tccccggccaccg------gaggag----------------------ggtcccacatgg
cgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtgcttc----ggtcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--cctctcacc-----ctcccgcgcttc-tgac-tgta-cccagtgcttgt---gt
aaataaat----------------aaatctttttta-------aaa----------aaaa
taaaattggttctg-----------gcctcattt------aaa----aaaaaattgctta
aaatgcat-----------
>NW023604275.1:2135-2506(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------aaaataaattaaagcaaaattattttc-ctagAGGT
AAAAATGACAATATAGGGCCTT----CGcagtggagcagt-ggttgagcgctgggctgcg
aagctgccgg-cagcct---ctgcagcgccggttggatcc-------cc-agctgc----
-tccccggccaccg------gtggag----------------------ggtcgcacatgg
tgc----------------gcagacctctcctgc----cgaccgctgctcccctcagcag
tgtaccgc----ggtcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--tctctcacc-----ctcccgcgcttc-tgac-tgga-cccagtgcttgt---at
aaataaat----------------aaataaatctta-------aat----------ttaa
aaaaaaaaattgac-----------atataaaCA-------------TTCAacttaagaa
gaaaatgta----------
>NW023604861.1:39547120-39547487(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------CTGTGACAGCTTgagagagagtaggga-gaggGAGT
TAGAAAgtaaagggagggcctc----cccggtggcgcagc-tgttgagagctgggttgcg
aagctgcccg-cagcct---ccgcagcgccggttcgatcc-------cc-agctgc----
-tccccggccactg------gaggag----------------------ggtcccgattgg
cgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctcccc------actctggt
gaat--tctgtcacc-----ctcctgcacttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatcttt-------aaa----------aaaa
aaaaaaaaagaaag-----------ggaaattga------GAA----AGAGTAATTGAGT
AAGACTAA-----------
>g3 Consensus of sequences 4-102
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------GG-------------------------------------
---------------------C----CCCGGTGGCGCAGC-GGTTGAGCGCTGGGCTGCG
AAGCTGCCCG-CAGCCT---CTGCAGCGCCGGTTCGATCC-------TC-CCCGGCCGCC
CTCCCCGGCCACCG------GGCGAG----------------------GGTCCCACATGG
CGCG---------------ACAGACCTCTCCTGCC--GCGCCCGCTGCTCCCCTCAGCAG
TGTATTCG-----GTCAGT---------CTGCCTGTTCTG-TCCCCGCTCTGGCTCTGGT
GAAT--TCTCTCACC-----CTCCCGCGCTTC-TGAC-TGTA-CCCAGTGCTTGT---AT
AAATAAAT----------------AAATAAATAAATCTT---TAAA--------------
------------------------------------------------------------
--------A----------
>NW023601322.1:94067375-94067739(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------TGAATTCCAAAATTCCACTCCaagaatt-ttctattt
aaaaaatcatagatgggcctcc----cctggtggtgcagt-ggttgagcgctgggctgca
aagctgcccg-cagcct---ctgcagcaccggttcgattc-------cc-ggcc------
-----------ccc------ggcgag----------------------gatcccacatgg
cgca---------------acagacctctcctgcc--gtgcccactgctcccctcagcag
tgtatttc-----gtcggt---------ctgcctgttctgttccctgctctggctctggt
gaat--tctctcatc-----ctcccgcgcttc-tgac-cgta-cccagtgcttgt---at
aaataaat----------------aaacaaatcttt-------aaa----------aaaa
aatttaaaaattaa-----------ataaaaata------aaa----aataaaaaatcat
agatgggt-----------
>NW023601322.1:88963314-88963678(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------A-TTCTCCATTTACAACCTTAAGAAAATC-TCTAGCAG
AAAAaattattattgggcctcc----cctggtggcgcagc-ggttgagcgctgggctgtg
aagctgcccg-cagcct---ctgcagcaccggttcgaacc-------ct-ggccgc----
-t------------------ggcgag----------------------ggtcccacatgg
cgca---------------gctgacctctcctgct--gcgcccgctgcacccctcagcag
tgtatttc-----ttcggt---------ctgcctgttctgttccccgctctggctctagt
gaat--tctctcacc-----ctcccgtgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatctta-------aaa----------aaaa
aaaagaaaaaaatt-----------attaagtga------AAG----CCAAAACTGTATA
CTAATCTA-----------
>NW023604972.1:127430271-127430636(+)
C-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ACAGGGTTATCAAAATGTAATGAAATC-TACATCAA
GACACAAAgccttcgggcctcc----cctggtggtgcagc-ggttgagcgctgggctgcg
aaactgcccg-cagcct---ctgcagcgccagttcgatcc-------cc-ggctg-----
-----------ccg------ggcgag----------------------ggtcccacatgg
cgc----------------acagacctctcctgct--gcgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgctctgctccccgctctggctctggt
ggat--tctctcacc-----ctcccacgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatcttt-------ata----------aaaa
ttaagaagggagaa-----------aaaagaaaa------caa----aaggaagtactaa
aaaaaaaa-----------
>NW023600993.1:30643065-30643436(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------CTATCAAAGCATGTTTCTGTGTTGTCA-TCTCTAAA
AAATTCTTCataaccgggcctc----cctggtggcgcagc-agttgaacgctgggttgca
aagctgcccg-cagact---ctgcagtgtcggttcgatcc-------cc-agctgc----
-tccctggccacca------gaggag----------------------ggtcccacatgg
cgc----------------acagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc-----atgggt---------ctacctgttctgttccccgctctggctctggt
gaat--tctctcacc-----ctcccgcgcttc-tgac-tgta-cccagtgcttgt---at
aaatgaat----------------aaataaataaat-------aaa----------tctt
aaccataaaaaaaa-----------aatgctctt------taa----aaaaaaaattctt
cataacC------------
>NW023601104.1:73865087-73865456(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------TACAAAGGTTACCACAAATTTACCTAA-GTGTGTAA
AGAATTCCCgaagacgggcctc----cccggtggcgcagc-ggttgagcgctgggctgtg
aagctgcccg-cagcct---ctgcggcaccggttggatcc-------ct-ggctg-----
-----------ccg------aacgag----------------------ggtcccacatgg
cgc----------------acagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc-----gtcact---------ctgcctgttctgctccccgctctggctctggt
gaat--tctctcacc-----ctcccacgcttc-tgac-tgta-cccagtgcttgt---ct
aaataaat----------------aaataaataaat-------aaatctttaa--aaaaa
aaaaaaaagaattc-----------ccgaAGAGT------ATA----AAGAATTAAATTG
CTTTAAGC-----------
>NW023601433.1:16402332-16402675(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------CAAGCTTCCTGGTGAAAAGCCTTACGA-ATGAGTTT
AACACCCAGGCGtcggggcctc----ctcggtggtgcagc-ggttgagcgctggattgcg
aagctgcccg-cagcct---ctgcagcgccagttagatcc-------ct-----------
------ggccactg------ggcgag----------------------ggtcccacacag
tgt----------------gcagacctctc--------------ctgctcccctcagcag
tgtacttc-----atcact---------ctgtctgttctgttccccgctctggctctggt
gaat--tctctcacc-----ctcctgcgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaataaac-------aaa----------caaa
taaataaataaata-----------aataaataa------atc----cttaaaaacaaaa
-------------------
>NW023603184.1:30155280-30155633(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ataacagaattttttaaaaatgacttt-agtAATAA
GAAACGTttattctcgggcctc----cccggtggcgcagc-gtttgagcactgggttgcg
aagctgccca-cagcct---ctgcagtgccagttggatcc-------ct-----------
------ggccaccg------ggcgag----------------------ggtcccacatgg
cgc----------------acagacctctcctgc----tgcccgctgctcccctcagcag
tgtacttc-----gtcagt---------ctgcctgctctgctctctgttctggctctggt
gaat--tatctcacc-----ctcccatgcttc-tgac-tgta-cccagtgcttgt---gt
aaataaat----------------aaataaataaat-------aga----------taaa
taaataaataaata-----------aatatttaa------ata----ttaaaaaaaaaaa
-------------------
>NW023604295.1:87192734-87193094(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------GTTTCTCCAcatagaagagaagaaaaa-accaCTGA
AAAGGTtaagaaattgggcctc----ccaggtggcacagt-ggttgggcgccgggttgcg
aagccaacca-cagcct---ctgcagcaccggtttgatcc-------cc-ggctg-----
-----------ctg------ggtgag----------------------ggtcccacaggg
tgc----------------gcagacctctccagc----cgcctgctgctccccttagcag
tgtacttc-----atcagt---------ctgcctgctctgctctccgctctgtctgtggt
gagt--tctctcatc-----ctcccacacttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaataaat-------aaa----------taaa
taaataaataaata-----------aataaatct------taa----aaaaaaaaaaaaa
aaaggtt------------
>NW023604861.1:118101492-118101855(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------AGAGGGATTATGGACACAACTGGCCCTGCTCAAGAA
CAATGATccacctcgggcctcc----cctggtggcgcagt-ggttgagcgctgggctgtg
aagctgccag-cagcct---ctgcagcgccggttcgatcc-------cc-ggccac----
-c------------------tgtgag----------------------ggtcccacatgg
cgc----------------gcagacctctcctgtc--gcacccgctgctcccctcagcag
tgtatttc-----ctcact---------ctgcctgttctgctccccgctctggctctggt
gaat--tctctcacc-----ctcccgcgcttc-tgac-tgta-cccagtgcttgc---at
aaataaat----------------aaataaatcttt-------aaa----------aaaa
aaaaaaaaaagaga-----------agaacaagt------taa----aaaaataataata
ataatgat-----------
>NW023604295.1:132240055-132240415(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------aaatcctgtattttcttgaaaatagtt-ttgtctat
taaaagaaaacccgtgggcctc----cccggtggcgcagc-ggttgagtgctgggctgca
aagctgcccg-cagcct---ctgcagctccggttcgatcc-------cc-agcc------
-----------cct------ggcgag----------------------ggtcccacatgg
cacg---------------acagacctctcctgc----cgcccactgctcccctcagcag
tgtactta-----gacgct---------ctgcctgttctcttctccactctggctctggt
gaat--tctctcacc-----ctcccgcgcttc-tgac-agta-cccagggcttgt---at
aaataaat----------------aaataaataaat-------aaa----------taaa
taaataaataaata-----------aataaataa------ata----aataaataaatgc
aaaaaat------------
>NW023603184.1:52173533-52173886(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------CTAATGACTATAAATTTAATGAAGATT-GTTCATTA
AAAGTATttatgtgagggcctc----cccggtggcacagt-ggttgagcgctgggctgtg
aggctgtcca-cagcct---ctccagcgcctattggatcc-------cc-ggccgc----
-t------------------gatgag----------------------ggtcccacatgg
cacg---------------acagacctttcctgc----ctcccgctgctcccctcagcag
tgtgtttc-----atcagt---------ctgcctgttctgttccccactctggctctggt
gaat--cctctcccc-----gtcccacacttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------acatacatgcat-------aca----------taca
tgcataaatacata-----------aatacataa------ata----cataattaaatac
-------------------
>NW023603184.1:137551064-137551425(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------AGGCAGTtcttataaaacagaaaacat-aagCATCA
AGAATggaaaattcagggcctc----cccggtggcacagc-ggttgagcactgggtttcg
aagctgcccg-cagcct---ctgcagtgctggttccatcc-------ct-----------
------ggtcaccg------ggcaag----------------------ggtcccacatgg
tgt----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttt-----gtcagt---------ctgcctattctgctccccgctctggctctggt
gaat--tctctcacc-----ctcccacgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatcttt-------aaa----------aaag
gaaaattcaaatta-----------tttgatgat------tat----ctaaaaacaaaac
tctagagg-----------
>NW023601104.1:35161168-35161523(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------CCACCAAATTTTTCAATGCAAATTGAC-CCACATCA
AGAGACATCATtgtcgggcctc----ccaggtggcgcagc-ggttgagtgctgggttgcg
acgctgcctg-cagcct---ctgcagcaccggttggatcc-------cc-----------
------ggccacca------ggtgag----------------------ggtcccacatgg
cac----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc-----gtcagt---------ctgcctgttctgctcccc------gctctggt
gaat--tctctcacc-----ctcctgcgcctc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatcttt-------aaa----------aaaa
aaaaaaaagacatc-----------attgtcaaa------tta----tcaaaaatcaaag
taaaaagt-----------
>NW023605083.1:68074678-68075037(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------Aagacactgtatgatttcacttacgtg-tactataa
agaaacaagaaaacagggccac----cccggtggcgcagc-ggttgagcgctcggttgcg
aagctgcccg-cagcct---ctgcagccccggtttgatcc-------ct-----------
------ggccaccg------agtgcg----------------------ggtcccacatgg
c------------------gcagacctctcctgc----tgcccactgctcccctcagcag
tgtatttt-----gtcact---------ctgcctactctgctctcccctctggctctggt
gaat--tatctcacc-----ctctcatgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatcttt-------taa----------aaaa
gaaaaaaaaaaaaa-----------aaaaagaaa------caa----gaaaacaaataca
agaaaata-----------
>NW023605305.1:64643055-64643409(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------GCTAAGCATGATGCAACATGATCAAAT-TTATACTT
TAGAAATAatctggtgggcctc----cctggtggcgcagc-ggttgagcactgggatgcg
aagctgcctg-cagcct---ctgcagcactggtttgatcc-------cc-ggctg-----
-----------cca------ggtgag----------------------ggtcccacatgg
cgc----------------acagacctctcctgc----cacccactgctcccctcagcag
tgtacttc-----gtcagt---------ctgcctgctctgctctcccctctggctctggt
gaat--tctctcccc-----ccgtcgtgtttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatcgaa-------aga----------aaga
aagaaagaaagaaa-----------gaaagaaag------aaa----gaaagaaagaaag
a------------------
>NW023601322.1:46161000-46161362(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------TCACTTATTGTCCTCACTACTATTTAA-CTTTATGA
AAATAAaccactccagggcctc----cccagtggtgcagc-agttgagcgctgggttgcg
aagctgccca-cagcct---ctgcagagccagttccatGC-------CC-GGCTG-----
-----------CCA------GGctag----------------------tgtcccacatgg
cgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtatttc-----gtcact---------ctgcctgttctgctctccgctctggctcgggt
gaat--tctctcacc-----ctcccgcgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------taaaaaaatctt-------aaa----------aaaa
aaagctaaaaaaaa-----------aattaaaaa------aaa----taaagctttaaaa
aaaaccaaa----------
>NW023601212.1:34817404-34817767(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ACATTTCCCCTATCTCTCGTATTTTTG-CTGAACAG
AATGGTAggttaactgggcctc----cccggtggcacagc-agttgagcgctgggctgca
aagctgcctg-cagcct---ctgcagcactgcttcgatcc-------ct-ggcctc----
-c------------------ggcgag----------------------ggtcccacatgg
cgc----------------acagacctctcctgcc--acaccccctgctcccctcagcag
tgtacttc-----atcagt---------ctgcctgttctgctccctgctctggctctggt
gaattctctctcacc-----ctcccacccttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaataaat-------aaa----------taaa
taaataaataaata-----------aataaatga------ata----aatgaatgaaaag
gaatGGT------------
>NW023605305.1:42190221-42190579(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------agggaaggaaaaaaaacagatcaTATA-TCAGGTTT
AAATGAGaagttggggggcctc----cccggtggcgcagc-agttgagcgctgggttgtg
aagctgccca-cagcct---ctacagtgccggttcgatcc-------cc-ggctgc----
-c------------------agcgag----------------------ggtcccacatgg
tgc----------------acagacctctcctgc----cgcccactggtcccctcagcag
tgtactt------gtcagt---------ctgcctgttctgctcctccctctggctctggt
gaat--cctctcacc-----ctcccgcacttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatcttc-------aaa----------taaa
taaataaataaata-----------aataaatga------gaa----gttGGGGTAAGAT
TAAATTG------------
>NW023601653.1:56171682-56172035(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------AAAGGGTTAGATTAAATCAAACATGAA-ATCTGACT
TTAAAAGtgagactagggcctc----cccggtggcgcagc-tgttgagcgcggggttgtg
aagctgccca-cagcct---ctgcaacgccggttcaatcc-------cc-----------
------ggccaccg------ggtgaa----------------------ggtcccacatgg
cac----------------acagacctctcctgc----tgcccgctgctcccctcagcag
tgtatttt-----gt-------------cagtctgttctgctccctactctggctctggt
gaat--tctctcacc-----ctcccgcgcttc-tgac-tgta-cccagtgcctgt---at
aaataaat--------------------aaatcttt-------aaa----------aata
aataaataaataat-----------aaaataaaa------gtg----agactAATGAGGT
GGAGGGAT-----------
>NW023605194.1:62068652-62069016(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------ACTATTACCAGAtattttcactcatatg-tgaaatat
aaagaaataaagcagggcctcc----cctggtggcacagc-agttgagcactgggctgca
aatctgcctg-cagcct---ctgcagcattggttcaatcc-------ct-ggctc-----
-----------gcc------agcgag----------------------ggtcccacatgg
tgc----------------acagacctctcctgcc--acacctgctgctcccctcagcag
tgtacttc-----gtcatt---------ctgcctgttctgctctccgttctgtctctggt
gaat--tctctcacc-----ctcccatgcttc-tgac-tgta-ctcagtgcttat---at
aaataaat----------------aaataaatcttt-------aaa----------aaaa
aaaaaagaaataaa-----------gcaatctga------caa----acaaaactcaaaa
aaacaact-----------
>NW023605083.1:83352198-83352559(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------GGTATAGTTATTTTTGGTAAACATgta-tagtttat
taaaaataatttttagggcctc----cccggtggcgcagt-ggttgagcgctgggttgca
aagctgcccg-caacct---ctgcagcactggttcgatcc-------cc-----------
------ggccgcca------ggagag----------------------ggtcccacatgg
cgc----------------gcagtcctctcctgc----tgcccgctgctcccctcagcag
tgtacctc-----atcagt---------ctgcctgttctcttctctgctctggctctggt
gaat--tctgtcacc-----ctcccacacttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatattt-------aat----------aata
ataatttttagatc-----------CAGAAAGTA------TGG----TGTAGTACTCAAT
TAGATATT-----------
>NW023601322.1:85465986-85466347(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------AATCCCCTTGGGTGATTGTGGGTAAGT-GTGGAAGA
AATGTACAAgtcatcgggcctc----cctggtggtgcagt-ggttgagggctgggctacg
aagctgcctg-cagcct---ctgcagtgccagttcgatcc-------cc-----------
------ggccacgg------ggcgag----------------------gatcccacatgg
cat----------------gcagacctctcctgc----cactcgctgttcccctcagcag
tgtacttt-----gtcagt---------ctgcctgttctgctcccagctctggctctggt
gaat--tctctcacc-----ctcccgctcttc-tgac-tgta-cccagtgcttgt---at
aaataaaa----------------aaatgaatcttt-------aaa----------aaat
aatgtataagtCAT-----------CTCTATTGC------AGT----AATTGAATTAAGT
TTAATGAA-----------
>NW023600993.1:9146166-9146531(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------cctttttctttttatcttttaagagGT-GGCTGCTT
AAAATGTAagactatgggcctc----cccggtggcgcagt-ggttgagcgctgggctgcg
aggctgcccg-cagcct---ctgcagcgcaggttcaatcc-------cc-----------
------ggcctccg------gaggag----------------------ggtcccacatgg
cgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtccttc----ggtcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--tctctcacc-----ctcccgcgcttc-tgac-tgta-cccagtgcttgt---at
aaataaaa-------------taaaaataaatcttt-------aaa----------aaaa
aaaatgtaagacta-----------CACACAAGG------CTA----ACCTTTGTGGCTG
GGGTCCTG-----------
>NW023601754.1:58875047-58875400(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ATCATGCTATCCTTATGTgagaaaaac-atacattt
aaaaatcttgtcagagggcctc----cgtggtggc------ggttgagcactgggttgcg
aaaccgcccg-cagcct---ctgcagcaccagtttgatcc-------cc-----------
------ggccacca------ggtgag----------------------ggtcccacatgg
cgc----------------gcagacctctcctgc----cgcccactgcttcccccagcag
tgtacttc----ggtcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--tctctcacc-----ctccctcgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat--------------------aaatcttt-------aaa----------aaaa
aaaatcttgtcaga-----------ACTCTTGTT------TCA----TATATGGAGAACT
tgcagtga-----------
>NW023605194.1:16576545-16576908(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------ATGGCATTTCACGTAGAgtatatataat-cattttaa
aactaataattgtagggcctcc----cctggtggtgcagc-ggttgggcactaggctgca
aagctgcccg-cagcct---ctgcagcgccggtttgaacc-------cc-----------
------ggccaccg------ggcaag----------------------ggtcccccatgg
tgt----------------acagacctctcctgc----ctcccgctgctcctctcagcag
tgtacttc----agtcctt---------ctgcctgctctgctccccactctggctctggc
gaat--tctctcacc-----ctcccgcgcttc-tgac-tgta-cccagtgcatgt---at
aaataaat----------------aaataaatcttt-------aaa----------aaaa
tataaatgtagtAC-----------AGTATGAAG------AGA----gtacatatttgaa
ttttatgt-----------
>NW023601653.1:65739327-65739689(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------agacatagAAAAATGTCCATTGGTCAt-tgattaga
agaattaacaatattgggcctc----cccggtggcgcagc-ggttgagcactgggctgca
aagctgtctg-cagtct---ctgcagtgccgattcgatcc-------cc-----------
------cggctgca------ggcgag----------------------ggtcccacattg
cgc----------------acagacatctcctgc----ctcccgctgctcccctcagcag
tgtacttc-----gtcagt---------ctacctattctgttccccgctctggctctggt
gaat--tctctcacc-----ctcccatgcttc-tgac-tgta-cccagtgcttgt---at
aaataaaa---------------taaataaatcttt-------aaa----------aaaa
attattaaaatgac-----------taTTTTGCC------AAA----GGAAATATTCAAA
CATAAACA-----------
>NW023601104.1:89186208-89186566(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ACTATTACCACCAGCAACACCCCTACT-TCCTTTGT
TTAAATTAttaactcgggcctc----cctggtggcgcagc-ggttgagcgctgggttgcg
aagctgcctg-cagcct---ctgcagcgccggttcgatcc-------ct-ggtcg-----
-----------ctg------ggcgag----------------------ggtcccacaagg
cgc----------------gcagacctctcctgc----cacccactgctcccttcagcag
tgtacttc----agtcctt---------ctgcctgttctgctccctgctctagctctagt
gaat--tctctcacc-----ctctcgcgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaat----cttt-------aga----------atta
ttaattaattaact-----------cCTCACACT-------------CACCAtgctattt
cacatttttat--------
>NW023601433.1:42776931-42777304(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------TGaacaccaaaattttaaatgcaataa-tATTTGCA
ATAATCAtttgtggggggcctc----cccggtggcgcagc-agttgagccctgggttgcg
aagctgcccg-cagcct---ctgcagcgccggttcgatcc-------ct-ggctgc----
-tccc-cgccaccg------gaggag----------------------cgtcccacatgg
cac----------------gcagacctctcctac----tgcccgctgctcccctcagcag
tgtatttc--ttcatcagt---------ctgcctgttttgttccccgttctggctctggt
gaat--tctctcacc-----ctcccgcacttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaatgaataaat-------aaatcttttttaaaaaa
taaaaaaataatca-----------tttgtgGGG------GAA----AAGAATATTC---
-------------------
>NW023605083.1:69166709-69167082(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------CCCTTCTCCAGTGTGCCATGGtagttc-ctttgtca
aagattaactgtctagggcctc----cccagtggtgcagc-ggtcaagcgctgggttgcg
aagctgccct-cagcct---ctgcagcaccggttggatct-------ct-ggctgc----
-tcccgggccaccg------gaggag----------------------ggtcccacatgg
cat----------------gcagacctctcctgc----cgcccactgc-cccctcagcag
tgtacttc-----atcagt---------ctgcctgctctgcttgcccctctggttctggt
gaat--tctctcacc-----ctcccgcgcttc-tgac-tgta-cccagagcttgt---at
aaataaataa--------------aaataaatcttt-------aaa----------aaaa
aatagaaaaaatta-----------tttaaaaat------aaa----aataaaaaaagat
taactgTC-----------
>NW023601433.1:42223453-42223824(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------CAAGAGTTTCTTGAGACCAGCGACATT-TTTGGTCA
GAAAGTGctttgtgtgggcctc----cctggtgtcgcagc-ggttgagcgctgggttgcg
aagctgcccg-cagcct---ttgcagcaccggttcattcc-------cc-ggctgc----
-tccgcggccaccg------gaggag----------------------ggtcccacatgg
tgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc--------agt---------ctgcctgctctgctccccgctctggctctggt
gaat--tctgtcacc-----ctcctgcgcttc-tgac-tgta-cccagtgcttgt---at
aaataaataa--------------aaataaatcttt-------aaa----------aaaa
taaaaagtgctttG-----------TGTGGGGGC-------------TGTCCTGTGATTG
TAGGATTTTCA--------
>NW023605083.1:52927972-52928321(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------GCTAGCCCGAATGTGGGGAGAAGCCCTTT-CCCTCTGT
TATAAAAATa----------------ggcggtggcgcagc-ggttgagcgctgggttgtg
aagctgtccg-cagcct---ctgcagcgccggtt-gatcc-------cc-----------
------ggccaccg------ggtgag----------------------ggtcccacttga
cgt----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtactc------gtcagt---------ctgcctgctctgctccccgctctggctctggt
gaat--tctctcacc-----ctcctgtgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatcttt-------aaa----------aaat
aaaaaataaaaata-----------ggtggCAGC------AGG----CATTTCCTGCTTT
CTTCAAAT-----------
>NW023604972.1:18402707-18403086(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------TAGTTTGCTGCAGACAAAACAATATCTGTTTGTAAA
AATGATCTCTTtctgggcctcc----cgtggtggtgcagc-tgttgagcgctgggttgtg
aagctgcccg-aagcct---ctgcagcactggttcgatcc-------cc-ggctgc----
-tccccggccatgg------gaggag----------------------ggtcccacatgg
cgc----------------acagacctctcctgc----cacctgctgcgcccctcagcag
tgtacttt----ggtcctt---------ctgcctgctctgctccctgctctggctctggt
gaat--tcgctcacc-----ctcccgcacttc-tggc-tgta-cccagtgcttgt---at
aaataaataa-----------aataaataaatcttt-------aaa----------aaca
atctcTTTCTATTA-----------CTTTATAGT------CAG----tgctttttatgtt
ttactaTA-----------
>NW023601322.1:93738870-93739235(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------gcactcaaccactgcaccactggggagg-ccctgctt
gaaaaacattttgagggTCTct----tccagtggcgcagc-ggttgagcgttggggtgcg
aagcagcctg-cagcct---ctgtagcaccagttcgattc-------cc-ggctgc----
-t------------------ggcgag----------------------ggtcccacatgt
cgc----------------accgacctctcctgc----cgcccgctgctcccctcagcag
tgtacttc-----ggcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--tctctcacc-----ctcccactcttc-tgac-tgta-cccattgcttgt---at
aaataaat----------------aaataaataaatctt----taa----------aata
aataaataaaaata-----------aaaactttt------tga----tGCATTaccagtt
tttagtttt----------
>NW023604295.1:40249424-40249791(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------AGAGACAAAAATGTATTAAGTCACATAT
AAGAAGCACAAATAGGGCCCCCCCCacccggtgacacagc-ggttgagcgctgggttgcg
aagctgcccg-cagcct---ctgcagcgcaggtttgatcc-------cc-ggctg-----
-----------cag------ggcgag----------------------ggtcccacatgg
cac----------------gcagacctctcctgcctgccgcccgctgctcccctcaatag
tgtactacacttcatcagt---------ctgcctgctctgctctctcctctggctctgct
gaat--tctctcacc-----ctcccgcacttc-tgac-tgta-cccagttcttgt---at
aaataaat----------------aaataaatctta-------aaa----------aaaa
aaaaaaaaaagaaa-----------agaaagaaa------cac----aaataaagGTCAG
TAAGAAGA-----------
>NW023605083.1:29034936-29035296(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------aaaaaacaacagttctACATAATCTAA-AGAGGATT
TAAAATAAGGtagcggggcctc----cccagtggcgcggc-aattgagcactgggttgca
aagctgcccg-cagcct---ctgcagcaccggttccatct-------gt-ggccac----
-c------------------agtgag----------------------ggtcccacatgg
cgc----------------gcagacctctcctgc----cgcccgctggtcccctcagcag
tgtacttt-----gtcagt---------ctgcctgttctgctccctgctctggctctggt
gaat--tctctcacc-----ctcccacgcttc-tgac-tgta-ctcagtgcttgt---at
aaataaat------------------------cttt-------aaa----------aaaa
taaaataaaataag-----------gtagcCTCT----GGCTA----TATTTCTTTAATT
CCATAATACTGCAT-----
>NW026555331.1:135400096-135400459(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------CTTAGAAATCATGTATCCAGATTACACC-ATTTATAA
TCAAggttatttctgggcctcc----cctggtggcgcagt-ggttgagcactgggctgcg
aagctgccca-cagcct---ctgcagcaccggttcgatcc-------cc-ggccgc----
-c------------------ggcgag----------------------tgtcccacatgg
tgc----------------gcagacctctcctgc----cacccactgctcccctcagcag
tgtatttc-----atcggt---------ctacttgttctgttccccgctctggctctgga
gaat--tctctcaccct---ctcccatgcttc-tgac-tgta-cccagtgcgtgt---at
aaataagt----------------aaaaaataaaat-------aaa----------ataa
tcaaggttatttct-----------aagaaaaac------acA----TTGGTTTATATAA
TAAACTTT-----------
>NW023600993.1:69560468-69560834(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ATGCAGAAtatgaaatattacatatta-aatgttta
agaaataagatttctgggcctc----cccagtggcgcagt-ggttgagagctaggttgcg
aagctacccg-tagcct---ctgcaccgcaggttctattc-------cc-agctgc----
-tccccagccactg------gaggag----------------------ggtcccacatgg
c----------------------acctctcctgc----cacccgctgctcccctcagcag
tgtacttc-----gtcagt---------ctgcctattctgctccccactctggctctggt
gaat--tctctcacc-----ctcccgtgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatctta-------aaa----------aaaa
aaatcttactttaa-----------aaaaaaaaa------gta----agatttcttaaaa
ttaacaaG-----------
>NW023605194.1:19503008-19503380(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------gggaccatggtgatattTCACGGGtga-actgagat
gaaaatgcatacattgggcctc----cccggtggcgcagc-gggtgagcgctgggttgcg
aagctgcccgccagcct---ctgcagcaccggttcgatcc-------cc-ggctgc----
-t-cccggccaccg------tgtgag----------------------ggtcccacaggt
ctt----------------gcagacctctcctgc----cgccc---gctcccctcagcag
tgtacctc----ggttctt---------ctgcctgctctgctccacgctctggctctggt
gaat--tctctcacc-----ctcctgcgcttc-tgac-tgta-cccagtgcttgt---at
aaataaataa--------------aaataaatcttt-------aaa----------aaaa
aaaaaatgcataca-----------ttgcacaaa------aat----gaaaaatgatgta
aaaatata-----------
>NW023604972.1:2070905-2071267(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------caatatatttaaatgtaaagattgaagc-ttaaaaat
gttttaaagattttgggcctcc----cctggtggcgcagc-ggttgagcgctgggctgca
aagctgcccg-cagcct---cttcagcaccgctTCGATGGATGC---cc-ggccgc----
-c------------------tgtgag----------------------ggtcccacgtgg
cgc----------------gcagacctctcctgc----cgcccgctgctcccctcagcag
tgtccttc----ggtcctt---------ctgcctgctctgcaacccgctctggctctggt
ggat--tctctcacc-----ctcctgcacttc-tgac-tgta-cccagtgcttgt---at
agataaat----------------aaataaatattt-------ttt----------ataa
aatgttttaaagat-----------tataaGGAG------ACT----ATCTTTATGACTT
GGGG---------------
>NW023605194.1:51384768-51385127(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------atacatctgatgagGGATTGATATCGAA-GATCCTAC
AAAATgcttatacagggcctcc----cctggtggtgcagc-ggttgagcgctgggctgca
aagctgcccg-cagcct---ctacagtgccggttcgatac-------cc-gggc------
-----------ctc------gacgag----------------------ggtcccacatgg
cga----------------acagacctctcctgcc--gcccccgctgctcccttcagcag
tgtctttg-----gtcctt---------ctgcctgttctgctccctgctctgtctctggt
gaat--cctctcacc-----ctcccgcacttc-tgac-tgta-cccagtgcttgt---at
aaataaat--------------------aaatcttt-------aaa----------agaa
aatgcttatacaac-----------tcaataaaa------aca----aaacaaacaaccc
atccaaag-----------
>NW023601433.1:19495575-19495948(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------attgttccTACTGATGTATATCCAGAA-GGTTATTT
CTCACATtctccttagggcctc----cccggtggcgcagc-ggttgagcgctgagttgtg
aagctgcctg-cagcct---ctgcagtgctgtttcgatcc-------cG--GCTCC----
-Tctccagccacag------gaggag----------------------ggtactacatgg
cgt----------------gcagacctctcctgc----cgcacgctgctcccctcagcag
tgtacttc----agtcctt---------ctgcctgctctgctccccgctctgggtctggt
gaat--tctctcacc-----ctcccatgcttc-tgac-tgta-tccaggtcttgt---at
aaataaat----------------aataaattaatt-------taa----------aaaa
aagttctacatccccagggcctgcccctccgtcacccc--aca----gaggggg------
-------------------
>NW023605083.1:26371625-26371980(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ACTCCACTTTCCAACCATAAGAGGTTA-TGATCTTT
AAGAACTtctcttgagggcctc----cctggtggtgcagt-ggttgagcgctgggttgcg
aagctgcccg-cagcct---ctgcagcgccggttcgatcc-------cc-ggctg-----
-----------cca------agcgag----------------------tgtcccacatgg
cat----------------gcagacctctcctgc----tgcccgctgctcccctcagcag
tgtgtttt-----gtcaga---------ctgcctgttctgctctctgccctggctctggt
gaat--tctctcacc-----ctcccctgcttcatgac-tgtaccccagtgcttgt---at
aaatagat------------------------cttt-------aaa----------aaaa
aaaaaaagaactta-----------tctTGAGCAT-----TTA----CCATGCTCAAGCT
TCTCAGC------------
>NW023604295.1:112542346-112542698(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------taaataaaaactaagaatgTTCCATCC-ACATTCAT
CGAAAATCCAATTATgagcctc----cccagtagtgcagc-agttgaacgctgggttgcg
aagctgcccg-cagcct---ctgcagcgccggttcgatcc-------cc-ggctg-----
-----------cag------ggtgag----------------------ggtcccacatgg
cac----------------acagacctttcctgc----cgccagctgctcccctcagcag
tgtacttc-----atcagt---------ctgcctgctctgctcccccctctggctctggt
gaat--tctctcacc-----ctcctgtgctta----------------------------
--ataaat----------------aaagaaatctaa-------aaa----------taaa
taaataaaaataaa-----------atccaatta----tTACAAT--TATTGCATATGCA
TGAACATAATTAGAACATA
>NW023604861.1:29023670-29024028(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------GTGATGAGTTTGTTGTCAGTACTGTCG-GTGGGACA
AAAAATACAggatacgggcctc----cctggtggcacagc-agttgagggctgggttgca
aagctac----caggct---ttgcagcactggttcgatcc-------cc-ggccg-----
-----------ccg------ggcgag----------------------ggtccgacatgg
tgc----------------acagacctcttctgc----cgcccgctgctcccctcagcag
tgtacttc----ggtcctt---------ctgcctgttctgctccctgctctggctctggt
gaat--tctctcacc-----ctcccattcttc-tgac-tgta-cccagtgctcat---at
aaatcaat----------------caatcaatcaatcaatcttaaa----------aaaa
aatatataggctaC-----------TATTGATCAT-----AAG----ATGCTtcttaat-
-------------------
>NW023605194.1:41259461-41259857(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------AGATCTATTTACTTCATTTGCTGTGTT-TGTTGGAT
AAAAAGAtaagcttagggcctc----cccggtggcgcagc-ggttgagcgctgggttgcg
aagctgcccg-cagcct---ctgcagca---gttcgatcc-------cc-ggctgc----
-tccccgtccaccg------gaggagggtcccgcatggcgcgcagaccggtcccgcatgg
cgc----------------gcagacctctcctgc----tgcccgctgctcccctcagcag
tgtactac----ggtcctt---------ctgcctgctctgctccccgctctggctctggt
gaat--tctctcacc-----ctcccacgcttc-tgac-tgta-cccagtgcttatataat
aaataaat---------------aaaataaatctta-------aaa----------aaaa
aaaaaagataagct-----------tatTAATCAAT-----------GATTGCCTGTGTT
AGGAAATCA----------
>NW023604861.1:70429091-70429449(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------actGTTAATCTGTGCTATGTCAACATTA-GACCAGCT
AAAGAAgccagagggggcctcc----cctggtggcccagc-ggttgagctctggcctgcg
aagctgcccg-ca---------gcagggccagttcgatct-------cc-ggccac----
-t------------------gacaag----------------------ggtcccacatgg
cac----------------gcagacctctcctgcc--gtgcccactgctcccctcagcag
tgtacttc----gttcctt---------ctgcttgttctgctccccgctctggctctggt
ggat--tctgtcacc-----ctcctgcgcttc-agac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatctta-------aaa----------aaaa
aaaaaagccagaga-----------gagaaaaag------aaa----ttttccttccCTA
CAACAGTT-----------
>NW023601433.1:22820699-22821066(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------CATAAAAAACTTTGGTGCATGTCTTGT-TCCCTATA
AAAAAGaacactgtagggcctc----cctgatgcttcagt-ggttgagcactgggctgcg
aagctgcccg-cagcctctactgctgcgccaattcgatcc-------ct-ggccgc----
-c------------------ggcaag----------------------ggtcccacatgg
cgca---------------acagacctctcttgca--gagcctgctgctcccctcagcag
tgtacttc----ggtccat---------ctgcctgttctgctccccgctctggctctggt
gaat--tctctcacc-----ctcccgtgcttc-tgac-tgta-cccagtgcttgt---at
aaataaac----------------aaataaatcttt-------aaa----------aaaa
aaaaaaaaagaaaa-----------agaaagaac------act----gtAGAGCTTactt
cattttgg-----------
>NW026555331.1:141004427-141004786(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------TTGGAGAATGTGTTTCTGGCCAGTGCT-CACctata
aaaatgcaataataggggcctc----ccctgtggcacagc-----gggctgcgggctgcg
aagatgcccg-cagcct---ctgcagtgctggttcgatcc-------ct-ggccgc----
-t------------------ggcgaa----------------------ggtcccacatgg
cgca---------------gcagacctctcctgtc--gcacccgctgctcccatcagcag
tgtatttc-----atccgt---------ctgcctgttctgctccccaccctgtctctggt
gaat--tctctcacc-----ctcccgcgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatcttt-------aaa----------aaaa
atgcaataatagTT-----------ACATAACTA------AAG----TTCCTAGTAACCA
CATTAAAA-----------
>NW023602073.1:100008315-100008654(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------GGCAATAAGTAACACCAACGCAACGAAA-Gacattca
agaaaacaaaaatagggtctcc----cctggtggtgcaat-gattgagcactgggctgcg
aagctgcccg-cagcct---ctgcagcgccgggtggatcc-------cc-agccgc----
-c------------------ggcgag----------------------ggtcccacatgg
cgc----------------gcagacctagcctgc----tgcccgctgctcccctcagcag
tg------------------------------------tgttccccgctctggctctggt
gtat--tctctcacc-----ctcccgcgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatctta-------aaa----------aaaa
gaaaaaaaatcaca-----------aattattta------gaa----tttttttaaaaag
attctatt-----------
>NW023601433.1:23665527-23665887(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------ctataaggaaaaaataaattcttact-tCATTGTA
AAAACGTTtactttaagggcct----cccctggtcgcagc-ggttgtgcgctgggctcca
aagctgcccg-cagcct---ctgaagcgctggctCCATCC-------CG-GGctgc----
-c------------------agtgag----------------------agtcccacatgg
cac----------------gcagacctctcctgct--gcgcccactgttcccctcagcag
tgtatttc------ctccc---------ctggctgttctgttccctgctctggctctggt
gaat--tctctcgcc-----ctcccgcacttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatcttt-------taa----------aaaa
tgtttactttaaaa-----------ataatttat------aaa----taataattatcta
tAAAGGCA-----------
>NW023605194.1:66232595-66232944(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------tatccTCATCCAGGAAGCCCAAAGAgc-tccaaaca
aaataataccaagcagggcttc----ccctgtggcgtagc-ggttgagtgct-ggttgcg
aagctgcccg-aagcct---ccgtggcattggttcgatcc-------cc-agctg-----
---------------------------------------------------ctccccagc
cac----------------cgggacctctcctgc----cgcccgctgctcccctcagcag
tgtacttt----ggtcctt---------ctgcctgctctgctccctactctggctctggt
gaat--tctcttacc-----ctcccgtgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaataaatcttt-------taa----------aaaa
aataccaagcaGAC-----------ACATTTTCA------TAA----CGTTTTTAAAAGC
Caatgatg-----------
>NW026555331.1:57935351-57935697(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------TGAGCTCTTCTTGTATTGTTTCACAAAA-CTTTGTTT
CACAAaacttcctagggcctcc----cctggtggcacagc-ggtggagcactgggctgct
gcgaagc-------------------tgccggttcaatcc-------cc-agccg-----
-----------ctg------ggtgag----------------------ggtcccacatgg
cgt----------------gcagacctctcctgc----cacccgctgctcccctcagcag
tgcatttc-----gtcagt---------ccgcctgttctgttctccactctggctctggt
gaat--tctctcacc-----ttcctgcgcttc-tgac-tgta-ctcagtgcttgt---at
aaataaat----------------aaataaataaat-------aaa----------taaa
taaataaatcttta-----------aaaacaaaa-------------caaaacaaaaaaa
aactccctga---------
>NW023605083.1:76265873-76266248(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------TGCATGAGACTCAGAAGGTTGGTGAAAGGTGTGCAA
ATTTCTgttaacatgggcctcc----ccaggtggtgcagc-ggttgagctctgggttgct
aagctgcccg-cagcct---ctgtagcactggttcgatcc-------cc-agcca-----
-----------ccg------gacgag----------------------ggtcccacatgg
cgtgagtgtcccacatggtgcgaggGTCcactgc----cgcctgctgctcccctcagcag
tatacttc-----gtcatt---------ctgcctgctctgctttcccctctgactctggt
gaat--tctctcacc-----ctcccgtgcttc-tgac-tgta-cccagtgcttgt---at
aaataaat----------------aaa---atcttt-------aca----------aaaa
aaaaaaaatttctg-----------ttaacATGA------ACATTT-CACTTTCTAAACA
AAGGC--------------
>g4 Consensus of sequences 5-248
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------GGGCCTC----CCTGGTGGCGCAAG-GGGTTAAGTCCCCACTATG
AAGCTATCCG-CAGCCA---CTGCAGCAGAGTTCGATCCC-------CC-GGCCG-----
-----------GCCGCAGCAGGGGAG---------------------CTACCCACAATGG
CGCA---------------GCAGACCTCTCCTGTC--TCGCCCGCTGCTCCCCTCAGCAG
TGTATTTC-----AGTCAT---------CTGCCTGTTCTG-TCCCCACTCTGTCTCTGGT
GAAT--CCTCTCACCCCC-CCCCCCCCACCTC-TGGCCTGTA-CCCCAGTCTTGT---AT
GCATAAATAAA-------AAATAAAAATAAATCTTT-------AAA--------------
-----------A------------------------------------------------
-------------------
>g5 Consensus of sequences 6-121
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------GGGCCTC----CCTGGTGGCGCAGG-GTTGAGTCGCAGCGCTGTG
AAGCTGTCCG-CAGCCT---CTGCAGCGC-GGTTCGATCC-------CC-GGCCG-----
-----------GCC--------GGAG----------------------ACCCACATATGG
CGC----------------GCAGACCTCTCCTGTC--TCGCCCGCTGCTCCCCTCAGCAG
TGTATTTC-----AGTCGT---------CTGCCTGTTCTGTCCCC--CTCTGTCTCTGGT
GAAT--CCTCTCACC-----CCCTCCCGCCTC-TGGCCTGTA-CCCCGTTCTTGT---AT
ATAAATAT----------------AAATAAAT-----------AAA----------AATA
AATCTTTAAAA-------------------------------------------------
-------------------
>g6 Consensus of sequences 7-30
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------GGGCCTC----CCTGGTGGCCTAGGGGTTAAGTCTCAGCGCTATA
CAAGCTTCCG-CAGCCA---CTG--GCCTGAGTTCGATCC-------CC--GCCG-----
-----------CCAC--GGGAGCTAA----------------------ACCCACATATGG
CCA----------------GCAGACCTCTCCTGTC--TCGCCCGCTGCTCCCCTCAGCAG
TGTATTTC-----AGTAAT---------CTGCCTGTTCTGCTCCCCACTCTGTCTCTGGT
GAAT--CCTCTCACCCCCCCCCCCCTCACCTC-TGGCCTACACCCCAGTTCTTCT---AT
GCAAAATA----------------AAAAATAAAT----------------------AAAA
AATA--------------------------------------------------------
-------------------
>NW023601653.1:38868583-38868947(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------AAAAGTGGAGAATATCAGAAAAGCAAA-GTTTGATT
AAGAATCtgaggggggggcctc----cctggtggcacagcgggttgagcacagcattgtg
ggactgtcca-cagcct---ctgcagtgctggttcgattc-------cc-ggcca-----
-----------gcc-------aggag----------------------aatttcacatgg
caca---------------gaagacctctcctgtc--tcgcccgctgctcccctcagcag
tctatttc----agtcctt---------ctacctgttctgctccctgctctgtctctggt
ggat--tctctcaca-----ctcccacacctc-tggcctgtaccccaatgcttgt---at
aaataaat----------------aaatctattaaa-------aat----------acat
taaaaaaacaaaat-----------ttaaaaaga-------aa----aaaaatactgcta
aAAAGA-------------
>NW023601322.1:45140576-45140940(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ACACTAATATAACATTGATTGACCCCt-ggcttaaa
aaacaaattctcatagggcctc----cccagtggtgcagtggattgagcgcagcactgtg
aagctgtctg-cagcct---ctgcagtctgggTTCTATtc-------gt-ggccg-----
-----------gcc------agggag----------------------atgcccacatgg
caca---------------gcagacctctcctgtc--tcgcccgctgctccccttagcag
tgtatttt----ggtcctt---------cttcctgttctgctgcctgttctgcctctggc
gaat--tctctcgcc-----ctcccgcacctc-tggcttgtacaccagtgcttgt---at
aaataaat----------------acatctta-----------aaa----------aata
aaattaaaaaaaca-----------aattctcat-------------gTTAATTGTATTA
GGCTCAAACCT--------
>NW023604972.1:113099826-113100188(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------TGTCATTGGGCTGTCATATTATAAGAC-AGGGCAAT
CAGAAATAGGTgaggggacctc----cccggtggtgcagcaggttgagcatcgcactgtg
aaactgtctg-cagcct---ctgcagcgtgggtttgattc-------cc-agctc-----
-----------gcc------agggag----------------------aaacccacatga
tgta---------------gcagacctctcctgcc--tcacctgctgctcccctcagcag
tgtctttg-----gtccgt---------ctgcctgttttgctccctgctctgtctttggt
gaat--tctctcacc-----ctcccatgtttc-tgac-tgtaccccagttcttgt---at
aaataaat----------------ctttttttaaaa-------aaa----------agaa
ataagtgagg------------------GCCTGT----TGCTG----AAGGCCTCAACTG
CTATGCCAA----------
>NW023604295.1:117886290-117886660(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ataaataaataaatctttaaaaaaaaa-attatata
tatatatataacacagagcctc----cctggtggtgcagcaggttgagcaccacgctgtg
aaggtgtcca-cagcgt---ctgcagtgcaggtttgattc-------cc-ggctg-----
-----------gcc------agaaag----------------------aaacccccatgg
cgtg---------------gcagacctctcctgcc--ttgcccgctgctcccctcagcag
tgtcttct-----gtccat---------ctgcctgttgtgctccccactctgtctctggt
gaat--tctctcacc-----ttcccatgcctc-tgac-tgtaccccagttcttgt---at
aaataaat----------------ctttaaaatata-------tat----------atat
atatatatagtaca-----------tacaTATAC----TAGGG----TATGGTACAGCCA
TGTGTTCTGA---------
>NW023602073.1:8817991-8818348(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------CATTTCTACTAATTTCTGTTCTGTGTT-ACCAATAA
AAATAGGggactgcagggcctc----cccgatggcgcagc-ggttgagtgcagcactgtg
aagatgtccg-cagcct---ctgcagtgccagttcgattc-------cc-cgctg-----
-----------gcc------agggag----------------------aaccccacatgg
caca---------------gcagacctctcctgcc--tcgcccactgctcccctcagcag
tgtcttca-----gtctgt---------ctgcctgctctgttcccctctctggctctggt
gaat--tctctcacg-----ctcccatgcttc-tgac-tgtaccccagtgcttgt---at
aaataaat----------------ctttaaaa------------------------agaa
aacaggggaCTGCA-----------AATGACTTC----TCATT----GCGTTTTGCATTT
TGCAt--------------
>NW023601653.1:63317108-63317473(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------TTTATATATGTTGATTACTGttataca-aactttta
aaaataatgtatagtgggcctc----cctggttgcacagcgggttgagtgccacgccctg
aagctgtccg-tagcct---ctgcagagctggttcaattc-------cc-agccg-----
-----------gcc------agggag----------------------aaacccacctgg
tgct---------------gcagacctctcctgtt--ccacctgctgcttccctcagcag
agtctttg-----gtctgt---------ctgcctgttctg-tccttgctctgtctctggt
gaat--tttctcgcc-----ctcctgtgcctc-tgac-tgtaccccagttcttgt---at
aaataaaa----------------aaaaaaaacctt-------aaa----------aaaa
agaataataataac-----------aactctatg------gga----gtaatttaaaaaa
aataaaaa-----------
>NW023601322.1:42570589-42571220(+)
CCATTTTATATGAAGAATAGGAAAAATTCCTATCAAAAAGATGctccctggagcctccct
ggtggcgcaggcagttgaacgctgctctgtgaggctatcagcagcctctgcagttcgggt
tcgatcccggccaagaAGATAACCAGatggcatggcagacatctcctgtctcacccactg
ctcccctcaggagcagtgtgttttagttggtctgcctggtctgttccctgttctgtctct
ggtgaatcctctcacccgccctcatgtctggcctgtacctcagttcttgta-tgcatgaa
taaataaatcttaagggcctcc----cctggtagtgcaggcaattgagcgcagcactgtg
aagctgtcctgcagcct---ctgcagtgcctattcaatcc---------cggccg-----
-----------gcc------agcgag----------------------ggtcccacatgg
catg---------------gcagacttctcctgtc--ctgcccgctgctcccctcagcag
tgtatttc-----atcagt---------ctgcctgttctgttccccactctgtctctggt
gaat--cctctcact-----cttccgcacatc-tggcctataccccagtttttgt---at
aaataaat----------------aaataaatcttt-------aaa----------aaaa
taaaaataaaaata-----------aataaatct----taaaa----aaaaatcccatca
tttaaa-------------
>NW023601433.1:70187222-70187585(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ACATTTGCTCACCATCTATCCTACAAG-GGCTCATA
CAAAATgtacaaagagggcctc----cctggtggcgcaggcggttgagcgcagtgttgtg
aagctgtctg-cagcct---ctgcagtgctggttccatcc-------tt--gcca-----
-----------gca------ggcgag----------------------ggtcccacctgg
cact---------------gcagacctctcctgtc--gtacccgctgctcccctcagcag
tgtctttg-----gtccgt---------ctgcctgttcttttccccgctctgtctctggt
gaat--tctctcgcc----ctccccgcacatc-tggcctgtaccccggttcttgt---at
aaataaat----------------aaatcttt-----------aaa---------aaaaa
tacaaaaatgtaca-----------aagaactca-------------tataattcaacaa
aaacgCAATC---------
>NW023605194.1:41766663-41767037(+)
C-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ATTCCATCCCTCTTAAGTCctgctttg-aatatttt
aagaaagtgattgagggcctcc----cctggtggcgcaggcggttgagcgccgtgctgtg
aagctgtcca-cagcct---ctgcagcattggtttgtTCCTGGCTagcc-agccg-----
-----------gcc------ggcaag----------------------ggtcccacactg
tgca---------------gcagacttctcctgtc--acgcctgctgctcccctcagtag
tgtacttc-----ggttgt---------ctgcctgttctgttacccactctgtctctggt
gaat--cctctcacc-----ctcccgcgcatc-tggcctgtacgctggttcttgt---at
agataaat----------------aaaaaatcttaa-------aaa----------aaaa
aaaaagtaagtgat-----------tGAGTTGTT------TTA----TAGCTTTGTGTTT
cttaatt------------
>NW023600993.1:36086172-36086537(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------aaagcttcctggaggaagtaaAACTTG-ACTGGCAA
AGATAAcaagaatttgggcctc----cccagtggcgcagcaggttgagcgctgtgctgtg
aagctgtctg-cagcct---ctgtagcgcaggtttgattt-------ct-ggccg-----
-----------gcc------agggag----------------------aaacccccatgg
cgca---------------gcagtcctctcctgcc--tcgcccactgctccactcagcag
tgtcttcg-----gtccgtccgCCTgtactgcctgttctgctttcggctctg--tctggt
gaat--tctctcacc-----ctcctgcacctc-tgacctgtaccccagttcttgt---at
aaataaat----------------aaatctaa-----------aaa----------aaaa
aagatagcaagaAT------------------------TTGAGT---ATCCGTTTGAGTA
TCCAAAGCC----------
>NW026555331.1:24073421-24073799(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------CAAGTTCCCTGCAGAGAAGGACTGAAG-TCTTTCTG
AAAAGTActgaaatcgggcctc----cctggtggtgcagcgggttgagcgccacactgtg
aagctgtctg-cagtct---ctgcagcatgggtttgattc-------ct-ggtcg-----
-------gccggcc------aggaaa----------------------aaacccacatgg
catg---------------gcagacctctcctgcc--tcacccgctgctcccctcagtag
tgtcttcc-ttcggtccat---------ctgcctgttctgcagccagctctgtctctggt
gaat--cctctcatc-----ctcccgtacctc-tgacctgtaccctagttcttgc---at
aaataaat----------------taaaaaaaaatc-------taa----------aaaa
aagaaaagaaaagt-----------actgAAATC------ACA----TTCAGTCAATACA
AATGCCGACAG--------
>NW023600993.1:25353513-25353872(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ATTCACCTTCTCATTGTAGCTCCGTGA-ACTCATAA
CAAATATCCAGATgcgggcctt----cccagtggcacagcagattgagtgcCACAccgtg
aggctgtcca-cagcct---ctgcagcaagggttcaatcc---------tggcca-----
-----------gcc------aagaag----------------------atatccacatgt
caca---------------gcagacctctcctgtc--acgcccactgctctcttcagcag
t--cttca-----gtctgc---------ctgcctgttctgctccccgctctgtctctggt
gaat--tctctcacc-----ctcccgtgactc-tgac-tgtagcccagttcttgt---at
aaataaat----------------aaatcttt-----------aaa----------aaat
ttaaataaattgca-----------gGCATATAC----AGTAA----Gtgctctttaaaa
acaaaa-------------
>NW023601433.1:32889633-32889998(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------CATATGGTTTGTTGTTATGGTAATATTG-GTCTTATA
AAAAATGTTAGgaagggcctcc----gctggtggcacagg-ggttgagcgctgggttgtg
aagctgcgca-cagcct---cagcagcaccggtttgatcc-------ct-gtccg-----
-----------cca------gaggag----------------------ggtcccacgtgg
tgc----------------acagacctctcctgc----tacccgctgctctcctcagcag
tgtacttc-----gtcact---------ctgcctgttctgccccccgttctggctctggt
gaat--tctctcacc-----ctcctgcgcttt-tgac-tgta-cccagatCTATC-TTAT
AGATAGAT----------------ACCCTCATCTATCT-----TAATT--------ATTT
GAAGTCTTGGTATT-----------ATTTCCTCG------TAA----ATCCATTTGGTCT
TGGAC--------------
>NW023602275.1:10079-10425(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------catGTCTTCCCAAGAGATACAGCCTGG-GACAGGTA
CTTAAATACAACCCGGAGCCTC----TCCGACAGTGCATGGAGTTGagc-----acggtg
aagctgtcca-cggctt---ctgcagtgccaattcgattc-------cc-agctg-----
-----------gcc------agggag----------------------atacccacatgg
caca---------------gcagacctctcctgcc--ttgcccgcttctcccctcagcag
cgccctcg-----gtccat---------ctgcctgttctgctccccactctctctctggt
gaat--cctctcacc-----ctccagccttta-c---------cccagctcttgt---at
aaataaat----------------aaa---atcttt-------ggg----------gaaa
aaaagacaattgga-----------tttaaaaat------ata----tataacccAAATA
GGTT---------------
