>g1 Consensus of sequences 2-71
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------GGGCC
TCCCCGGTGGCGCAGCGGTTGAGCGCTGG-GTTGCGAAGCTGCCCGCAGCCTCTG-CAGC
GCC--------GGTTCGA------------------------------------------
--TCCCCGGCTGC-----TCCCCGGCCACCGGAGGAGGGTCC-CACATGGCGCAGCAGAC
CTCTCCTGC--CGCCCGCTGCTCCCCTCAGCAGTG---TACTTCGGTCCTTCTGCCTGCT
CTGCTCCCCGCTCTG-------------------------GCTCTGGTGAATTCTCTCA-
---CCCTCCCG-----CGCTTCTGA-CTGTACCCAGTGCTTGTATATAA-----------
--AAAT-AAAAAATC-AATCA----ATAATAAAAAAT-----AAAT----------AAAA
TAAATAAATAAATATAATAAATCTTT------AAAA------------------------
--
>NW023601421.1:989-1353(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----ttttgtgtcctttaggtagatggAATAGACTTTTGTTAAGAAggaattaagggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cagc
gcc--------ggttcaa------------------------------------------
--tccccggctgc-----tccccggccactggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgcttccctcagcagtg---tacttcggtccttctgcctgct
ctgctccctgctctg-------------------------gctctggtgaattctctca-
---ccctcctg-----cgcttctga-ctgtacccagtgcatgtataaac-----------
--aaac-aaacaaac-aaaaa----aactaaataaat-----aaaa----------aaaa
aaaa----aaaaaaaaaaga------------aggaatta--------------------
--
>NW023604295.1:19587622-19587986(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----cTTCTCTCTTGGAGaagtttatcttattttaaatataaaaagctgtaggggggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcagcctctg-cagc
acc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccagaggagggtcc-cacatggccc-acagac
ctctcctgt--ggcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--aaacaaaaa
aaaaac-aaccaacc-aacca----aac-aaataaat-----aaat---------aaaaa
catgcctctataa-----------------------------------------------
--
>g2 Consensus of sequences 3-49
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------GGGCC
TCCCCGGTGGCGCAGCGGTTGAGCGCTGG-GTTGCGAAGCTGCCCGCGGCCTCTG-CGGC
GCC--------GGTTCGA------------------------------------------
--TCCCCGGCTGC-----TCCCCGGCCACCGGAGGAGGGTCC-CACATGGCGC-GCAGAC
CTCTCCTGC--CGCCCGCTGCTCCCCTCAGCAGTG---TACTTCGGTCCTTCTGCCTGCT
CTGCTCCCCGCTCTG-------------------------GCTCTGGTGAATTCTCTCA-
---CCCTCCCG-----CGCTTCTGA-CTGTACCCAGTGCATGTATAAAC-AA--------
--AAAC-AAACAAAC-AAACAC---AAA-AAATAAAT-----AAAT--------AAAAAA
CATGCCTCTATAAAA---------------------------------------------
--
>NW023603184.1:48977993-48978353(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----ATACTACTACTCCAGGATAGTGTACTACTTATTATCAAAAAcagcttcttgggcc
tccccggtggcgcagtggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cagt
gcc--------ggtttga------------------------------------------
--tccccggctgc-----tccccggccaccagaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtacatgtataaac--a--------
--aaac-aaacaaac-aaata----aat-aaataaat-----aaat--------aaataa
catgcctctataaaaaaa------------------------------------------
--
>NW023605305.1:115174802-115175162(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----taaataattagacaTTAGTAAAATATAACCCTTAAGAATTTaacatgatagggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----ttcccggccaccggtggaggatcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccactctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cacttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaacaa---aat-aaataaat-aaaaaaaa----------aaaa
catgcctctataaaa---------------------------------------------
--
>NW023604972.1:35390603-35390967(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----ATATGTACAAAATTAAACAATCtaaaattttgagaataaaaaatgttcttgggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaggctgcccgcggcctccg-cggc
gcc--------ggttcga------------------------------------------
--ttcccggcttc-----tccccggccaccgggggagggtcc-cacatggcgc-acagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tgcttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctccca-----tgcttctga-ctgtacccagtgcatgtataaac-aa--------
--aaac-aaacaatc-aaaca----aac-aaataaat-----aaat-------aaataaa
catgcctctataaaaaaaaa----------------------------------------
--
>NW023604972.1:52473653-52474017(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----tttttaaattgaggataTTGGCTTATAATTCTGTAAGATTTAggggtatggggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaggctgcccgcggcctctg-tggc
gct--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cgcatggcga-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------actctggtgaattctctca-
---ccctcccg-----tgcttctga-ctgtacccagtgcatgtataaac-aa--------
--aaac-aaacaaac-aaata----aat--aataaat-----aaat---------aaaaa
catgcctctataaaaaaaaa------------aaa-------------------------
--
>NW023600993.1:83713250-83713614(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----atctctggcctacaccccagttcttctacacacaaaaaattaaaaattaggggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cggc
gcc--------ggttcca------------------------------------------
--tccccggctgc-----tccccggccaccagaggagggtcc-cacatggcga-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacctcggtccttctgcctgtt
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----tgcttctga-ctgtacccagtgcatgtataaac-aa--------
--aaac-aaacaaac-aaaca---------aacaaat-----aa------------aaaa
catgcctctataaaaaaaat------------aaataaata-------------------
--
>NW023601212.1:49289481-49289843(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----TATACTTCAACCAagctgggttgttttttttttttaaatagtggctccttgggcc
tccccggtggcgcagcggttgagtgctgg-gttgcgaagctgcccgcggcctctg-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cgcatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tccttcggtccttctgcctgct
ctgctccctgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--aa-------
--aaacaaaacaaac-aaaca---------aataaaa--ataaata----------aaaa
catgcctctataaaaaaaaat---------------------------------------
--
>NW026555331.1:102922544-102922904(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----GTTGGATACATTCCTGCTGCCTCATTTCTGGTTTACAAAATAtcatgggggggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccacctgaggagggtcc-cacatagcac-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tgcttcggtctttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaaca----aat-aaataaat-----aaat------------aa
aatgcctctattaaaaaaaa------------aa--------------------------
--
>NW023604972.1:130326409-130326769(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----agaaattgttttcttaatgtcAAAGTTTAGTTCTAAAAATTtcagttccagggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cacatggcgt-gcagac
ctctcctgc--tgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccactctg-------------------------gctctggtgaattctctca-
---ccctcccg-----tgcttctga-ctgtacctagtgcatgtataaac--a--------
--aaac-aaacaaac-aaacc----agc-aaacaaat-----aaat----------aaag
catgcctctataaaaaaaaa----------------------------------------
--
>NW023603184.1:83889702-83890062(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----gactgtcaccTTCAGCCTGGTAGGTGAAGATAAAGAATGGGAgataagctgggcc
tccccggtggcgcagaggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccagccaccagaggagggtcc-cacatggcgt-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaacc----agc-aaacaaat-----aaat----------aaag
catgcctctatataaaaaaa----------------------------------------
--
>NW023603184.1:115915418-115915778(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----gtttgtgatttcttttctgaCCCATTAGTTATTTAAAGTATTgtttctttgggcc
tccccggtggcgcagcggttgagcactgg-gttgcgaagctgcccgaggcctctg-cggc
gcc--------ggttcga------------------------------------------
--tcccgggctgc-----tccctggccaccggaggagggtcc-cacatggtgc-gcagac
ctctcctgc--ggcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaacc----agc-aaacaaat-----aaat----------aaag
catgcctctattaaaaaaaa----------------------------------------
--
>NW023601104.1:3357339-3357699(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----taaaggggacTTTTCTCTGCCCTATAAAGCATTATAGAACTaccattattgggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcgcgcggcctctg-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccacctgaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctcg-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaag-aaacc----agc-aaacaaat-----aaat----------aaag
catgcctctataaaaaaaaa----------------------------------------
--
>NW023602073.1:42952032-42952392(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----aaaaaaaaaaaaaaaagaaagaaaaatagcttaGAATACTAGttgtctctgggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cggt
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cacatggcac-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctcctccccgctctg-------------------------gctctggtgaattctccca-
---ccctcccg-----tgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaaca----aat-aaataaat-----aaat----------aaag
catgcctttattaaaaaaaa----------------------------------------
--
>NW023601754.1:8142298-8142658(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----ACGTCTCTCTGTTGAGCAGGAAGGGATTTGTTCCTTTAAAACCtatagatgggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcgcgcggcctctg-cggc
gcc--------ggttcgt------------------------------------------
--tccccggctgc-----tccccggccaccagaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tgcttcggtccctctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctcg-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaacc----agc-aaacaaat-----aaat----------aaag
catgcctctataaaaaaaaa----------------------------------------
--
>NW023602073.1:34894-35254(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----AATGTGGTAATTATGTTtagaaattatttgcttttaaactcttgcattgtgggcc
tccccggtggcgcagcggttgagcactgg-gttgcgaagctgcccgcagcctctg-tggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccactggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaata---------aataaat-----aaat----------aaag
catgcctctataaaaaaaaa------------ataa------------------------
--
>NW023604972.1:105077400-105077760(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----AATGCCTACGAGTACATGTTAAAATTAATATGATAAAGATCTccatggtggggcc
tccccggtggcgcagcggttgagcactgg-gttgcgaagctgcccgcagcctctg-tggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccactggaggagggtcc-cacatggcgc-gcagtc
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaata---------aataaat-----aaat----------aaag
catgcctctataaaaaaaaa------------aaaa------------------------
--
>NW023605194.1:49576772-49577132(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----TTTGTGATCTTGGGCATGACACAATTACTGCAATAGAATACAtgcttgctgggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaatctgcccgcgccctctg-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccctggccaccggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacctcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaaca---------aataaat-----aaat----------aaaa
catgcctctatttaaaaaaa------------aaaa------------------------
--
>NW023605194.1:44969081-44969441(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CTCCCACCAGACAGCCCTTCACAGATGTTTCTCTTCTAGAATaaatctctgggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcagcctctg-cagc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggctaccagaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacgaac-aaata---------aataaat-----aaat----------aaaa
catgcctctataaaaagaaa------------aaat------------------------
--
>NW023602073.1:14476238-14476598(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CTTTCACTCAATGAAATATAGTTCAAAATGTCATTAAGACTcctaaactagggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cggc
gcc--------ggttcga------------------------------------------
--tccccgggtgc-----tccccggccaccggaggcgggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcagtccttctgcctgct
ctgctccccgatctg-------------------------gctctggtgaattctctca-
---ccctcccg-----tgcttctga-ctttacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaaca---------aataaat-----aaat----------aaaa
catgcctctattaaaaaaaa------------aaaa------------------------
--
>NW023605305.1:38066058-38066418(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CAAGTCAAGAATTTGCATGGAAATTCTTCTCACCCAAACAATaactgagagggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-tggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccctggccaccggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcagtccttctgcctgct
ctgctccccactctg-------------------------gctctggtgaattctttca-
---ccctcctg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaata---------aataaat-----aaat----------aaa-
-atgcctctattaaaaaaaa------------aaaaaa----------------------
--
>NW023601212.1:77948444-77949027(-)
---acagtgagatttCACTTCACACCTAGTAGGATGGCTACTCTTGAAAataggggcctc
gctggtggccaaggggttaagtctcagcaccattacggcaggagttcgatcc---ccagc
cagggagctacccacatggcgcagcagacctctcctgtcttgcctgctgctcccctcagc
agtgtgtttcagtagatctgcctgttttgctccccac-tctgcctctggt----------
-----gaatcctctcatcccccacacctctggtctatatcccagttctatgtatagggcc
tccccggtggcgcagcagttgagcgctgg-gttgcgaagctgcccgcggcctctg-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cacatggcgc-acagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccctgctctg-------------------------gctctggtgaattctctca-
---ccctccca-----tgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaaca---------aataaat-----aaat-----------aaa
catgcctctattaaaaaaaa------------aaaaa-----------------------
--
>NW023605305.1:112295031-112295391(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CACATCCACAGAAAATAAAGAGGTcaaattttcagtgaaaatagcagcatgggcc
tccccggtggcgcagcggttgagcgctgg-gttgtgaagctgcccgcggcctctg-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccggcggaggatcc-cacatggtgc-gcagac
ctctcctgc--cacccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----tgcttctga-ctgtacccagtgcttgtataaac--a--------
--aaac-aaacaaac-aaacaa-------aaataaat-----aaat----------aaaa
catgcctctataaaataaaa------------ta--------------------------
--
>NW023604972.1:21389561-21389917(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----agcacaatcccttccagcaccatccatgttgctgcaaatgacatgacttcgggcc
tccccagtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcagtctctg-cggc
gcc--------ggtttga------------------------------------------
--tccccggctgc-----cccccggccaccagaggagggtcc-cacatggtgc-gcagac
ctctcctgc--cacccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctcg-
---ccctcccg-----cgcttctga-ctgtacccagtgcttgtataaac--a--------
--aaac-gaacaaac-aaata---------aataaat-----aaat----------aaaa
catgcctctatttaaaaaaa----------------------------------------
--
>NW023605194.1:16597055-16597415(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CAGCAACCTTTTTGTAGTGACTGtgcaacaaatataaaaatgaagatagagggcc
tccccggtggcgcagctgtagagtgctgg-gttgcgaagctgcccgcggcctctg-aggc
gcc--------ggttcaa------------------------------------------
--tccccggctgc-----tccccggccacaggaggagggtcc-cacatggcgc-gcagac
ccctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aagca----aac-aaataaat-----aaag---------aaaaa
catgcctctattaaaaaaa-----------------------------------------
--
>NW023600993.1:14849123-14849483(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----TTTAATTTTGGATGTTTTCCTTAAactaatagttaaaaaaaatcagatcagggcc
tccccggtggcgcagtggtagagcgctgg-gttgcgaagctgcccgcggcctctg-cagc
gcc--------ggttcaa------------------------------------------
--tccccggctgc-----tccccggccactggaggagggtcc-cacatggtgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttctgtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctcg-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aagca----aac-aaataaat-----aaag---------aaaaa
catgcctctattaaaaaaa-----------------------------------------
--
>NW023601104.1:94144478-94144838(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CAACATTTGGAGTCTAGCCaacctttaatgaaaaaaaaaaaaaaaaaatcgggcc
tccccggtggcgcagcggttgtgcactgg-gttgcgaagctgcccgcggcctctg-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cacatggcac-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccctgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaata----aat-aaatcata---aataaa----------aata
catgcctctttaaaataa------------------------------------------
--
>NW026555331.1:49875592-49875947(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----tcctgaaaaagaaaaaaaatcacattagctCCTCAAATAAGaggtttttagggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggccattg-tggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccctgctctg-------------------------gctctggtgaattctctcg-
---ccctcccg-----cacttctga-ctgtacccagtgcatgtgtagac--A--------
--AGAC-GAacgaac-aaatg----aat-aaataaat-----aaat-----------aaa
catgcctctattaaaa--------------------------------------------
--
>NW023604861.1:74678189-74678549(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CACTGAGCagtatttttagttttagaaCTACTTCAAAAACtggtaaaacagggcc
tccccggtggcgcagcggtagagcgctgg-gttgcgaagctgcccgcggcctctg-tggt
gcc--------ggttcga------------------------------------------
--tccctggctgc-----tccccggccaccggaggagggtcc-cgcatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctatacccagtgcatgtataaac--a--------
--aaac-aaacaagc-aaaca---------aataaag------------------aaaaa
catgcctctattaaaaaaaa------------aaaaaaa---------------------
--
>NW023601653.1:27763366-27763727(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----ATTCTAACCATTTTTTCGGATGGGGTTGCAAGGCAAAAATTGGTTAAggtgggca
tccccggtggcgcagcggttgagcgctgg-attgcaaagctgcccgcagcctctg-cagc
gcc--------ggttcga------------------------------------------
--ttcccggctgc-----tcccgggccaccagaggagggtcc-cacatggtgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcgcg-----cgcttctga-ctgtacccagtgcatgtataaac--g--------
--aaac-aaacgaac-aaac---------aaataaat-----aaat----------aaaa
catgcctctataaaaaaaga------------aaaaa-----------------------
--
>NW023601212.1:59208226-59208585(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----GAATGCTTATCTTTCTTTGAAAGTGCAGCAGTTATTTAAATGGTGtgattgggct
tccctggtggcgcagcggttgagcgctgg-gttgcgaagctgctcgcggcctctg-cggc
gcc--------agttcga------------------------------------------
--tccctggctgc-----tccccggccaccggaggagggtcc-cgcatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----tgcttctga-ctgtacccagtgcatgtataaac--a--------
--aa---aaacaaac-aaaca----aat-aaataaat------------------aaaaa
catgcctctataaaataaat------------aaat------------------------
--
>NW023605083.1:82829919-82830279(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----tctttaaacaaagaaataaatagttTGTATTAAAAACATTAGTCAAATCAGGggc
tcccaggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cggc
act--------ggttcaa------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-catatggcac-gcagac
ctctcctgc--cgcctgctgctcccctcagcagtg---tactttggtccttctgcctgct
ctgctccccactctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaacaaacaaac-aaataaat-----aaat----------aaaa
catgcctctattaaaa--------------------------------------------
--
>NW023604861.1:44928963-44929323(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----AAACTATTATCACACCACTAActacctaaaagaatgaaaattggggtctagggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcagcctctg-cagc
gcc--------ggtttga------------------------------------------
--ttcccggctgc-----tccccggccacaggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tgcttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaatgaac-aaacaaacaaac-aaacaaat-----aaat----------aaat
aatgcctctattaaaa--------------------------------------------
--
>NW023601322.1:68869477-68869836(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----tgtatctctagttttataatgaaaatagtttaataaagaatatacattcagggcc
tccccagtggcacagcggttgagcgctgg-gttgcgaagctgcccatggcctctg-cgac
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccctggccaccggaggagggtcc-tgcatggcgc-gcagac
ctctcctgc--cgtctgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaaa-acaaaaac-aaacaaacaaat-aaacaaat-----aaat----------aaaa
catgcctctataaaa---------------------------------------------
--
>NW023601104.1:61740610-61740974(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----TTCACAGCCTTCTGTACTTTGCATATTTTAGTCATAAGACtgcatttcttgggcc
tccctggtggcacagcggttgagcgctgg-gttgagaagctgcccgcagcctctg-ctgc
gcc--------agttcga------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tatttcggtccttctgcctgct
ctgctccctgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaaa--aaaa-----
--acaa-aaacaaac-aaaca----aat-aaataaat-----aaaa----------aaaa
catgcctctaaaaaaaaaaaa---------------------------------------
--
>NW026555331.1:125268594-125268954(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----Atccaagtcaaaaccacagtgtcacacctcacacacaaaaagaatagcttgggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cggc
gcc--------agttcga------------------------------------------
--tccccggccgc-----tccccggccaccggaggagggtcc-cacatggtgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctccca-----cacttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaaca----aac-aaaaaaac-----aaataaata-aataaaag
catgcctcctc-------------------------------------------------
--
>NW026555331.1:139854340-139854700(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----aaatattaaacccaaatgatttaatatattttttaaagatttatttatttgggcc
tccctggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cggc
gcc--------ggttcaa------------------------------------------
--tccccggctgc-----tccccggccaccagaggagggtcc-catatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttgggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaaca----aac-aaacaaat-----aaat-----------aaa
tatttatttatttatgcata-----------c----------------------------
--
>NW023601653.1:57819289-57819648(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----ACAAGAGGCAAAACTCTAATATGACTTCCTGTTCAAGAAAAAgaaggggtgggcc
tccccagtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cggt
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggtcactggaggagggtcc-cacatggtgc-gcagac
ctctcctgc--tgcccgctgctcccctcagcagtg---tacttcagtccttctgcctgct
ctgctccctgctctg-------------------------gctctggtgaattctctca-
---ccctccca-----tgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaaaacaacaaac-aaaca----aat-aaataaaa-----------------caaaaa
catgcgtctattaaaagaaa----------------------------------------
--
>NW023601543.1:47640223-47640587(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----GGGGAAATGAGATGATAggagaaaattctttttctaaatctaaagacaaggggcc
tccccagtggcgcagcggttgagcactgg-gttgcgaagctgcccgcggcctctg-cggc
gct--------ggttcga------------------------------------------
--tccccagctgc-----tccccggccacctgaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tactttggtccttctgcctgtt
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctccca-----cgcttctga-ctgtacccagtgcatgtataaac-----------
--aaac-aaacaaac-aaaca----aat-aaataaat------------------aaaaa
catgcctctattaaaaaaaa-tgttt------aaa-------------------------
--
>NW023605194.1:27829612-27829972(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----atccaGTGTGCTATGTTCtgaaaacaaacctttaaaactTTCCccagggggggcc
tccccggtggcgcagcggttgagtgctgg-gttgcgaagctgctcgcggcctctg-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cacatgtcgc-acagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctccctgtt
ctgctccccgctctg-------------------------gctctggtgaattctctcg-
---ccctcccg-----tgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaata----aag-aaagaaag-----aaag----------aaaa
catgcctctctaaaaaaaaa----------------------------------------
--
>NW023603184.1:65654090-65654454(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----TGATGCCCCCTGACACAAGTTGGGGAAATCTGCTTAAGAGCcaagctaaagggcc
tccccggtggtgcagcggttgagcactgg-gttgcgaagctccccacggcctctg-cggt
gcc--------ggttcga------------------------------------------
--tccccggcttc-----tccccggccaccagaggagggtcc-cgcatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtgtgaac-----------
--aaac-aaacaaac-aaaca----aac-aaataaat-----aaat----------aata
cgtgcctcttttaaaaaaaa------------aaaaa-----------------------
--
>NW026555331.1:131786521-131786885(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----AGGTACAATCAAGCTTTAACAAGATAATCTTTAAGAATTGCACAataagcgggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgtggcctctg-cggc
gcc--------ggtttga------------------------------------------
--tcctcggctgc-----tccccggttcccagaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccactgctcccctcagcagtg---tacttcagtccttctgcctgct
ctgctcctcactctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtgtaaac-----------
--aaac-aaacaaac-aaaca----agt-aaataaat-----aaat----------aaaa
catgcctctatttaaaaaaa------------aaaaa-----------------------
--
>NW026555331.1:94721042-94721406(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----TTTgaccatttctttgttttctagttggagatttaaaaaattttaaggtagggcc
tccccggtggcgcagaggttgagcattgg-gttgtgaagctgcccgcggcctctg-cgga
gcc--------ggttcaa------------------------------------------
--accccggctgc-----tccccggccactggaggagggtcc-cgcatggtgc-gcagac
ctctcctgc--cgcccgctgctctcctcagcagtg---tacttcagtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac-----------
--aaac-aaacaaac-aaaca----aac-aaacaaat-----aaat----------aata
catgcctcttaaaaaaaaat------------cttta-----------------------
--
>NW023601212.1:27360478-27360842(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----aTAAAGGGGGAGATTCTTTgaatttaaagtggaaaaaaaacaatatttcagggcc
tccctggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcagcctctg-cgac
gcc--------ggttcga------------------------------------------
--tccctggctgc-----tccccggccacaggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------actctggtgaattctctca-
---ccctccca-----cgcttctga-ctatacccagtgcatgtgtaaac--gaac-----
--aaac-aaacaaac-aaata----aat-aaataaat-----aaat----a-aaaaaaaa
catgcctcttaaaaaa--------------------------------------------
--
>NW026555331.1:44343500-44343859(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----aaaagataatatatagtATGGTAGGTGCTATTAAAAGCTAtctaaaaattgggcc
tccctggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccagaggagggtcc-cacatggtgc-gcagac
ctctcctgc--cgcctgctgctcccctcagcagtg---tacttccgtccttctgcctgtt
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---gcctcccg-----cgcttctga-ctgtatccagtgcatgtataaaacaaaaa-----
caaaac-aaacaaac-aaat---------aaataaat-----aaat-----------aaa
catgcctctattaaaaa-------------------------------------------
--
>NW023601653.1:45426925-45427289(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----caatcgtgtaaaatatatatagaaataaatactttaaaaactttccttcagggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cggt
gca--------ggttcga------------------------------------------
--tccccggctgc-----ttcccggccaccagaggagggtct-cgcatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tgcttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtaaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac-----------
-------aaacaaac--------------aaagaaag-----aaag----------aaaa
catgcctctataaaaaaaaa------------aaaaccaaaaaaaaact-----------
--
>NW023604861.1:120226409-120226769(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----ctaaagaaaatgaaatggagttTCTTgggtatcaaaaaaaaaaatcaggagggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cgac
gcc--------ggttcga------------------------------------------
--tcccgggctgc-----tccccggccaccggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tgcttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgctcctga-ctgtacccagtgcttgtataaac--a--------
--aagc-aaag------------------aaagaaag-----aaat----------aaaa
catacctctataaaaaaaaa------------aaaatcaggagt----------------
--
>NW023601104.1:51925677-51926058(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----AGAGACTGTCAAGAATGATCtcaataaaattcttttaaagtaggaggatagggcc
tccccggtggcgcagtggttgagcgctgg-gttgcgaagctgcccgcggcctctg-aggc
gcc--------ggtttga------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cacatggcac-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcagtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----tgcttctga-ctgtacccagtgcatgtataaac-----------
--aaac-catcaaac--------------aaataaat-----aaat----------aaaa
catgcctctataaaaaaaaa------------ataaattaaaaaaataaagtaggaggAT
AA
>NW023605305.1:116298976-116299336(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CCTTCCTTTCTAATTCTATTAGTTATTTTGCACTAAGAGTATCCTTggccgggcc
tcccgggtggcgcagtggttgaacgctgg-gttgtgaagctgcccgcagcctctg-cagc
gcc--------agttcaa------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cccatggcgc-gcagac
ctcccctgc--cgcccgctgctcccctcagcagtg---tccttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcttgtataaac--a--------
--aaac-aaacaaac-aaat----------aataaat-----aaat----------aaaa
catgcctctattaaaaaaaa------------aaagt-----------------------
--
>NW023604861.1:110084982-110085342(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----tttttcttttcctatacaTTTAAGTTGCAAGATGTTAAAAACtgctttgtgggcc
tccccagtggcgcagcggttgagcgctgg-gttgtgaagctgccggcgacctctg-cggc
gac--------ggttcta------------------------------------------
--tccccggctgc-----tccccggccacctgaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tgcttcggtctttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac--------------aaataaat-----aaat----------aaaa
catgcctctattaaaaaaaa------------aaaaaaac--------------------
--
>NW023601212.1:73849531-73849903(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CTAAAGGTTAAAatgtgtgatttctttttttttaagaattatttatgcttgggcc
tccccggcggcgcagcagttgagcgctgg-gttgtgaagctgcccgcggcctctg-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccgaccaccggaggagggtcc-cccatggcgc-gcagac
ctctcctgc--cacccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgcttcccgctctg-------------------------gctctggtgaattctctca-
---ccctccca-----cgcttctga-ctgtacccagtgcatgtataaac-----------
--aaac-aaacaaac--------------aaataaat-----aaat----------aaaa
catgcctctaaaaaaaaaaa------------aaaagaattatttatgcttac-------
--
>NW023604861.1:125362990-125363362(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----gatatATGATTCACATACAGTACAATctacccatttaaagtgtactgacagggcc
tccccggtggcgcagcggttgagcactgg-gttgcgaagctgcccgcggcctctg-cggc
acc--------ggttcaa------------------------------------------
--tcccctgctgc-----tccccggccaccggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccctggtctg-------------------------gctccggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcttgtataaac-----------
--aaac-aaac------------------aaataaat-----aaat----------aaaa
catacctctattaaaaaaaa------------aataaagtgtactgacagggaacct---
--
>NW023604972.1:39011262-39011861(+)
gaaaaagaaaaactagaaaagaaacaaCTTTGAGTCCCCCCCCATAACAAcacaggttga
gcgcagtgctgtgaagctg---tccgtagcctctgcagtgtgggtttgattccggctggc
caaggagattcccacatggcgca-cagacctctcctgtctcgcccgctgctcccctcagc
agtgtatttcggttg-tctgcctgttctgttccccctacctgtctctagtgaattctctc
accttcccgcgcctctggtctgtagcccagctcttgtataaaaataatcttttaagggcc
tccccagtggcgcagcggttgagcgctgg-gttgcaaagctgcccgcggcctctg-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgttcttcgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaaacaa--------
-------aaacaaac--------------aaagaaag-----aaag----------aaaa
tatgcctctatataaaaaaa------------aaaaattaa-------------------
--
>NW023605083.1:69636424-69636788(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----TGACCTCTCTGGGAATGGAGTTTAAAGCCTTTGTCCAAAATAgtagttaagggcc
tccccggtggtgcagcggttgagcgctgg-gttgcaaagctgcccgcggcctctg-cgac
gct--------ggttcga------------------------------------------
--tccctggctgc-----tccccggccaccggaggagggtcc-cacatggcgt-gcagaa
ctctcttgc--cgcccgctgctcccctctgcagtg---tgcttcagtccttctgcctgct
ccgctcccctctctg-------------------------gctctggtgagttttctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--aa-------
--aaac-aaacaaac-aaat---------aaataaat-----aaat----------aaaa
catgcctctattaaaaaaaa------------aaaaaaa---------------------
--
>NW023605194.1:19595003-19595362(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----AAGAATTTAGGCAACTGATAACTTCTGATTAAaggttaaaaacaacaacagggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcgcgcggcctctg-aggc
gcc--------ggttcga------------------------------------------
--tccccggctg------ttcccggccaccggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctcccagctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-cagc---------aaacaaat-----aaat----------aaag
catgcctctataaaaaaaaa------------aaaa------------------------
--
>NW023604861.1:85392512-85392871(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CTTTCCCTATGCTCCTTTGCTTCATGAGCTGTTgaaaagaagggggtggggggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-tggc
gcc--------ggttcga------------------------------------------
--tccctggctgc-----tccccggccgccgg-cgagggtcc-cacatggtgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcagtccttctgcctgct
ctgctccccactctg-------------------------gctctggtgaattctctca-
---ccctccca-----cacttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaacc----agcaaaacaaat-----aaat----------aaag
catgcctctataaaaaaaa-----------------------------------------
--
>NW023600993.1:36093562-36093921(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----GGAAAGTGTTACCTGGAGAAAGCTACTCCTGATTTAAGATTtttgaaatggggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccgtccgccgg-cgagggtcc-cacatggtgc-gcagac
ctctcctgc--cgcccgctgctccccttagcagtg---tacctcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaacc----agcaaaacaaat-----aaat----------aaag
catgcctctataaaaaaaa-----------------------------------------
--
>NW023601322.1:68146508-68146872(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----TCTTAAGGTAATTAAGGCAGTGTAAAATTGGAACAAGAATAAacagattggggcc
tccccggtggcacagcggttgagcgctgg-gttgcaaagctgcccgcggcctctg-cgac
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccagaggagggtcc-cacatggcgc-gcagac
ctctcctgc--ctcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
----cctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--c--------
--aaac-aaacaaac-aaacc----agc-aaacaaat-----aaat----------aaag
catgcctctaaaaaaaaaaa------------aaaaa-----------------------
--
>NW023601754.1:38135221-38135580(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CCTGACTTTGTGCTTTcacatattacatatttattaaaaaaaaggaatatgggcc
tccccggtggcgcagcggtagagcgctgg-gttgcgaagctgcccacggcctcta-cggc
gac--------ggttcaa------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cacatggcgt-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggagaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaaa-acaaaaca-aaaaagcaaaac-aaataaat----aaaga----------aaaa
catgcctctataaa----------------------------------------------
--
>NW023605194.1:15824294-15824667(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----GTGTGGACAGAGGGTGCGGAGCAGGCAAAAGAAATGGGGATTaagagtttgggcc
tccccagaggcacagtggttgagcgctgg-gttgtgaagctgcccgcagcctctg-cggc
acc--------agttcga------------------------------------------
--tccccggctgc-----tcccaggccaccggaggagggttc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcagtccttctgcctgct
ctgctcccctctctg-------------------------gctctggtgcattctctca-
---ccctccca-----cgcttctga-ctgtacccagtgcatgtataaac-----------
--aaac-aaacaaac-aaataaaaaaac-aaataaat-----aaat-------aaaaata
catgcctcttaaaaaaaaaa------------aaaaaaa---------------------
--
>NW023605180.1:8742-9116(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----gatttAGATGAGTGTTAAGGAGTAAgtatactaaagaaaaaaataactcagggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cagc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccctggtcactgggggagggtcc-cacatggcac-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccgtccct-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaat-aaaaa----aaa-aaaaaaaaaaaaaaaaa----------aaaa
aataactcagtaTTCCTggc------------ttcattcat-------------------
--
>NW023605083.1:13207820-13208194(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----AGGTAGAGAAAAGATCTTATATAAACTGCCATCAAAAGTAAtttagttttgggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-cagc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tctccggccaccggaggagaatcc-cacatggcgt-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--aa-------
--aaac-aaacaaat-aaata----aattaattaaaa-----aaaa----------aaag
taatttagttTTTAGTATTCTCACTGCTGACC----------------------------
--
>NW023601322.1:44660843-44661203(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----TTCactatctagtttttttttttttttttttttaaagatttatttattttgggcc
tcctcggtggcgcagctgttgagcgctgg-gtttcgaagctgccggcgacctctg-tggc
gcc--------ggtttga------------------------------------------
--tccccggctgc-----tccacggccaccggaggagggtcc-cacatggcgc-atagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccactctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaccaaaccaaac-aaac---------aaacaaac-----aaa-----------aaaa
aatgcctctattaaaaaaaa------------aaag------------------------
--
>NW023600993.1:50258506-50258866(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----AAACTAGAAATACTGTGTTTTatattctcatcacaagaaaatgaaattgtgggcc
tccccggtggcgcagcggttgagcgctgt-gttgcgaagctgcccgcggcctcag-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccgcggccagcagaggagggtcc-cacatggcgc-tcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttccgtccttcagcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--c--------
--aacc-aaccaacc-aacc---------aaataaat-----aaat----------aaaa
catgcctctattaaaaaaaa------------aaaa------------------------
--
>NW023601104.1:4025578-4025942(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CTATTTCCTCTCCCAGGACCACCCTCCAAGTGTGGTCAAAAcccacatcagggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaaactgcccgcagcctctg-cagc
gct--------ggtttga------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cacatggcg--gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctccca-----cgcttctga-ctgtacccagtgcatgtataaac--c--------
--aaac-aaacaaac-aaat-----aat-aaataaat-----aaat----------aaga
catgcctctagaaaaaaaat------------atatat----------------------
--
>NW023600993.1:23363431-23363803(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----AATTATCCCTTTTCGTTCATTCTGCTATTCCTTTAAAAGCCCcatcactggggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcctgcagcctctg-ca--
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccatcggaggagggtcc-cacatggcgt-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgacttctctca-
---ccctccca-----cgcttctga-ttgtacccagtgcatgtataaac--c--------
--aaac-aaacaaat-aata-----aat-aaataaat-----aaat----------aaga
catgcctctagaaaaattaa------------aaaaaaaaaaaaaaa-------------
--
>NW023603184.1:67216444-67216807(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----GccttaaataaagtttttttttttttcttcccttaagaGCAAggactctagggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcctgcagcctctg-ca--
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccagaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctccca-----cacttctga-ctgtacccagtgcatgtatcaaa--c--------
--aaac-aaacaaac-aaac-----aat-aaataaat-----aaat----------aaga
catgcctctagaaaattaaa------------aaaaaa----------------------
--
>NW023604972.1:136356410-136356773(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----ggggaggcccttttttttctattcttgtcctccatcaaaatggccatggggggcc
tccctggttgcgcagcggttgagcgctgg-gttgcgaagctgcccgcagcctctg-ca--
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cacttctga-ctgtacccagtgcttgtataaac--c--------
--aaac-aaacaaac-aaac-----aat-aaataaat-----aaat----------aaga
catgcctctagaaaatttaa------------aaaaaa----------------------
--
>NW023603184.1:100839267-100839630(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----agaattagtagtAATGAAAATTGGAAACTACATATATAAAAccaagaatagggcc
tccccggtggtgcagcggttgagcgctgg-gttgcgaagctgcctgcagcctctg-ca--
gcc--------ggttcga------------------------------------------
--tccctggctgc-----tccccggccacaggaggagggtcc-cacatggtga-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tccttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--c--------
--aaac-aaacaaac-aaat-----aat-aaataaat-----aaat----------aaga
catgcctctagaaaattaaa------------aaaaaa----------------------
--
>NW023601754.1:51009677-51010046(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----tagcacagataaatttttttaaaaaacaacatagAATGAGGATggtcctagggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-tagc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccggaggag---cc-cacatggcgc-gcagac
ccctcctgc--cgcccgctgctcccctcagcagtg---tccttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----tgcttctga-ctgtacccagtgcatgtataaac-----------
--aaac-aaacaaac--------------aaataaat-----aaat----------aaag
catgcctctataaaaaaaaa------------aagcttattaaaaaaaaaaaa-------
--
>NW023602073.1:71971372-71971743(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------CCTAAGCTGTCATTAAAACTACTATTCaaaactcaaaaattattttctcaggcc
tccccagtggcgcagcggttgagcactgg-gttgcgaagctccccgcggcctctg-tggc
gct--------ggttcga------------------------------------------
--tccccggctgc-----tcccaggccaccggaggagggtcc-cgcatggcgc-gcagac
ctctcctgc--tgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac-----------
--aaac-aaacaaat--------------aaataaat-----aa------------aata
cgtgcctctttaaaaaaaaa------------ttgttaaaaaaaaaaaattcttt-----
--
>NW023601653.1:71730768-71731140(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----AGTTGGACATGATCCTTGCCCTTGGGGGTCGACTTTAAGAGGTGGTACTTGGGCC
ttcccggtgacgcagcggttgagcgttgg-gttgcgaagctgcccgcggcctctg-tggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cacatggcac-gcagac
ctcttctgc--tgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccctgctctg-------------------------gctctggtgaattctctca-
---ccctcctg-----cgcttctga-ctgtacccagtacacgtataaac-----------
--aaac-aaacaaac--------------aaataaat-----aa------------aaaa
catgcctctataaaaaaaaa------------aagaggtggtacttttaggggcc-----
--
>NW023605305.1:57790334-57790699(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----TCAATTTCTGAGTCATGGGTGAGGAAgctctttttaaaacacaaaggatagggcc
tccccggtggcgcagcggttgagcgctgg-gttacgaagctccctgcggcctctg-cagc
gcc--------ggttcca------------------------------------------
--tccctggctgc-----tccccggccaccggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccactctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac-----------
--aaac-aaacaaat-----------------------------------------aaaa
tatgtgcctcttaaaaaaaa------------aaataaaacacaaaggatATTTACAA--
--
>NW023604861.1:29441486-29441860(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----attttcttttaaattccagTGTAACAGTTTGCATTAACAACTagatacatgggcc
tccccggtggcacagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-tggc
gtc--------ggttcga------------------------------------------
--tccccggctgc-----tccgtggccaccggaggagggtcc-cacatggcgc-gcagat
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----ctcttctga-ctgtacccaatgcatgtataaac--a--------
--aaac-aaacaaat---------------------------aaat----------aaaa
catgcctctataaaaaaaaa------------aaaaaacaaactagataCATAGTTAaca
ta
>NW023605083.1:102043254-102043611(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CAATTCAATTtgaccaaattctttttttttaaagatttatttatacaagagggcc
tcccaggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgtgg---ctg-cagc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccagaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccactgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccctgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaaccaaata----aat-aaataaat-----aaataaataaatgaaaaa
catgcctct---------------------------------------------------
--
>NW023602073.1:92986837-92987194(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----ATGGGCACTtaaattcacttttcattttcattataaatgaaaattttcaggggcc
tccccagtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcgg---ctg-cagc
gcc--------agttcga------------------------------------------
--tccctggctgc-----tccccggccacccgaggagggtcc-cacatggcgc-gcagac
ctctcctgc--tgcccgctgctcccctcagcagtg---tacttcggttcttctgcctgct
ctgctccccgctctg-------------------------actctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtgcccagtgcatgtataaac--a--------
--aaac-aaacaaac-taactaactaactaactaaat-----aaat--------aaaaaa
catgcctctgtta-----------------------------------------------
--
>NW023604972.1:117537304-117537665(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----ctcccagtcggtggggtttgaagctagtttattttaaaacataagccatcgggcc
tccctggtggtgcagcggttgaacgctgg-gttgcgaagctgcccgcagcctctg-cggc
gcc-------cggttcga------------------------------------------
--tccctggctgc-----tccccggccaccggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcctgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgatctg-------------------------gctctggtgaattctctcg-
---acctcccg-----tggttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaacaaaacaaataaat-aaataaat-----aaat----------aaaa
catgcctctataaaa---------------------------------------------
--
>NW023603184.1:53943003-53943381(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----tgcaccatcagAGGCCCCtaaaactgttatttaaaaacattgggcatatagggcc
tccccggtggcacagcggttgtgcactgg-gttgcaaagctgcctacggcttctg-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccctggccaccggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cacttctga-ctgtgcccagtgcttatataaac--a--------
--aaac-aaataaat--------------aaaacaat------------------aaaaa
catgcatctataaaaaaaaa------------agctaaaaaaaaaacaaacattgggcat
a-
>NW026555331.1:117710443-117710806(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----TGTGCTATAATAATTCAAGGTaacattattcttaaaaatattaacttctagggcc
tccctggtggcacagcggttgagcgctgg-gttgtgaagctgcccgcggcctctg-cggc
gcc---------atttga------------------------------------------
--tccctggctgc-----tccctggccaccggaggaggatcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagctgtg---tacttcagtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcttgtataaac--aa-------
--aaac-aaacaaac--------------aaacaaat-----aaat----------aaaa
catgcctctaaaataaaaat------------attaactgctA-----------------
--
>NW023601104.1:33627201-33627580(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----AGTTTCATATTCCCGAGGGTATCCAAATCAGATCAAAAGTATtggaactggggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctatgccggc
gcc--------ggttcga------------------------------------------
--tcccaggctgc-----tccccggccactggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tatttcggtccttctgcctgct
ctgctccctgctctg-------------------------gctctggtgaattctctca-
---ccctccca-----cgcttctga-ctgtacccagtgtatgtataaac--a--------
--aaac-aaac------------------aaataaat-----aaat----------aaaa
catgcctctattaaaaaaaa------------attaaaaaaaaaaaaaagtattggaaCT
CC
>NW023601433.1:86058778-86059139(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----ATTCCTTTAAGAATTAATCCCATTTCAAAGGCTGAATCAAAacttttagagggcc
tccccggtggcacagcggttgagcgttgg-gttgcgaagctacccgca---ccCG-Agac
tcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cacatggtgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacgtcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----tgcttctga-ctgtacccagtgcatgtataaac--aa-------
--aaac-aaacaaac--------------aaataaat-----aaat----------aaag
catgcctctattaaaaaaaa------------aaattaaaaaa-----------------
--
>NW023600993.1:71822632-71822997(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----ttgcaccaccagggaggtcccagagttctgttttaaaaaaagaagggggtgggcc
tccccggtggcgcagtggttgagctctgg-gttgcgaagctgc---------ctg-cggc
acc--------ggtttga------------------------------------------
--tccccggctgc-----tccccggccaccagaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctccca-----cgcttctga-ctgtacccagtgcttgtataaac--a--------
--aaac-aaacaaac-aaata---aaat-aaataaat-----aaat----------aaag
catgcctctaagaaagaaag------------aaagaaagaaaga---------------
--
>NW023604861.1:38637272-38637631(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----AGCATTtgacttcattttcaaaattctcatctaaagaaaaataatttcccgggcc
tccccagtggcgcagcggttgagcgctgg-gttgcgaacctgcccgcagcctctg-cggc
acc--------ggttcga------------------------------------------
--tccccggctgc-----tccccagccgccagaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tccttcggtccttctgcctgct
ctgctcccctctctg-------------------------gctctggtgaattctctca-
---ccct-ccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aagcaaaataaata----aat-acataaat-----aaat-----------aaa
catgcctctataaaaaaatt----------------------------------------
--
>NW023601322.1:57078523-57078885(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------TCTTAAAATCTAGATATTTTctgatagactgatgaaataagaga
aatggagtggcgcagcggttgagcgctgg-gttgcgaacctgcccgcagcctctg-cggc
tcc--------agttcga------------------------------------------
--tcccaggctgc-----tccccagccaccggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcagtccttctgcctgct
ctgctccctgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----tgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac-aatt---------aaataaat-----aaat-----------aaa
tatgcctctataaaattaaa------------aaaaaaaaaatcagtcaa----------
--
>NW023604972.1:59214247-59214621(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CGTGGTCATTATGTTTCCACATGAAGAATCTGAAGTCAAGAGATTAAATAGGGTC
ttcgtggtggcgcagcggtggagcgctgg-gttgcgaagctgcccgcagcctctg-cagc
gcc--------tgctcaa------------------------------------------
--tcccaggctgc-----tccccgggcaccagaggagggtcc-cacatggcgc-acagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
gtgctccccgctttt-------------------------gctctggtgaattctctca-
---ccctctcg-----tgcttctga-ctgtacccagtgcatatataaac--a--------
--aacc-aaacaaac-agata---aaat-aaataaat-----aaat----------aaaa
catgcctctataaaataaaa------------aaaaagaagaaaa---------------
--
>NW023601322.1:12258087-12258436(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----tggagagagagaagttctgaactttaaaaagtgaaaaaaattccacaactgggcc
tccctggtagcgcagcggttgagcgctgg-gttgcgaagctgcctgcagcctctg-cagt
gcc--------ggttcga------------------------------------------
------------------tccccggtcgctggacgaaggtcc-cacatggcgt-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaac--------------aaataaat-----aaat----------aaaa
catgcctcttaaaaaaaaaa------------aatatatg--------------------
--
>NW023604295.1:30244880-30245243(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----accaaaaaaggaaagcaggTGTACCAAAAAAGTAAAGCAGGTGCggaggcgggcc
tccccggtggcacagcggttgagcactgg-gttgcgaagctgcctgtagcctctg-cagc
acc--------ggttcga------------------------------------------
--tccctggctgc-----tccccggccacaggaggagagtcc-cacgtggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tg-tttggtccttctgcctgct
ctgctccccgctttg-------------------------gctctggtgaattctctca-
---ccctcccc-----tgcttctga-ctgtacccagtgcgtgtataaac-----------
--aaac-aaacaaac-aaaca----aac-aaataaat-----aaat----------aaaa
catgcctctattaaaaaaaa------------aattt-----------------------
--
>NW023604972.1:31087010-31087363(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CTCTTTTGGTACTTAAttatagctatttatttatttataaaagctttttagggcc
tccccagtggcacagcggttgagtgctgg-gttgctaagctgcccgcggcctctg-cggc
gcc--------ggtttga------------------------------------------
------------------tccccggccaccggaggagggtcg-cacatggcgc-gcagac
ctctcctgc--cgcctgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcctg-----tgcctctga-ctgtacccagtgcttgtataaac--aa-------
--aaac-aaacaaac--------------aaataaat-----aaat-----------aaa
catgcctctattaaaaaaaa------------aaaaaaaaaaaa----------------
--
>NW023604861.1:61382961-61383326(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----gttgtACATATTTTCTCTTGCTTATCTCTAAATGATAGAAAGtgattgtagggcc
tccccggtagcgcagcggttcagcgctgg-gttgccaagctacccgcggcctctg-cagc
gcg--------ggttcga------------------------------------------
--tccccagctgc----gtccccggccaccggaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---cacttcggtccttctgcctgct
ctgttccccgctctg-------------------------gctctggtgaattctctca-
---ccctcctg-----cgcttctga-ctgtacccagtgcacatataaat-----------
--aaac-aaacaaac-aaaca----aat-aaataaat-----aaat-------aaaaata
catgcctctttaaaaaaaaa------------ag--------------------------
--
>NW023605194.1:18936564-18936928(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----GAATATACTGGCATACATTAGGGTAAactgagataaaaaaaattattatcgggcc
tacccagtggcgcagcggttgagcgctgg-attgcgaagctgcccgcggcctctg-cagc
gct--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccactagaggagggtcc-cacatggcgc-gcagac
ctcttctgc--cgccagctgctcccctcagcagtg---tactttggtccttctgcctact
ccgctccccgctctg-------------------------gctctggtgaattctctca-
---ccttcccg-----tgcttctga-ctgtacccagtggttgtataaat-----------
--aatt-aaacaaac-aaac---------aaataaat-----aaat----------aaa-
------tctttaaaaaaaat------------tattatcatttgtttt------------
--
>g3 Consensus of sequences 4-102
GG----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-CCCCGGTGGCGCAGCGGTTGAGCGCTGG-GCTGCGAAGCTGCCCGCAGCCTCTG-CAGC
GCC--------GGTTCGA------------------------------------------
--TCCTCCCCGGCCGCCCTCCCCGGCCACCGGGCGAGGGTCC-CACATGGCGCGACAGAC
CTCTCCTGCCGCGCCCGCTGCTCCCCTCAGCAGTG---TA-TTCGGTCAGTCTGCCTGTT
CTG-TCCCCGCTCTG-------------------------GCTCTGGTGAATTCTCTCA-
---CCCTCCCG-----CGCTTCTGA-CTGTACCCAGTGCTTGTATAAAT-----------
--AAAT-AAATAAAT--------------AAATCTTT-----AAAA--------------
------------------------------------------------------------
--
>NW023600993.1:43004574-43004949(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CAATAGCCAACTAAGCCTTGGctctaaatttattaaaaatgtagcctttggggcc
tccccagtggcgcagtggttgagcgctgg-gttgcaaagctgcccacagcctctg-cagc
gccggttcaatggttcaa------------------------------------------
--tccccggctgc-----tccccggccaccggaggagggtcc-cacatggcac-gcagac
ctctcctgc--cacccgctgctcccctcagcagtgtgctgctttggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctccag-----cgcttctga-ctgtacccagtgcttgtataaac-----------
--aaac-aaacaaac--------------aaacaaat-----aaat----------aaa-
--------tcttaaaaaaaa------------atgtagcttttCTTTTCTGCTA------
--
>NW023600993.1:61868735-61869099(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----TACTTTGGGAGTAAAATGACAAGTGATGGTAGCCATTAAAATGAAAgatgggacc
tccccggtggcgcagtggttgagcgctgg-gttgcgaagctgcccacggcctgtG-CGGC
Aca--------gtttcga------------------------------------------
--tccctggctgc-----tcctcagccactggaggagggtcc-cacatggtgc-gcaga-
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----tgcttctga-ctgtacccagtgcatgaataaac--a--------
--aaat-aaacaaac-aaaca----aac-aaacaaat-----aaat----------aaa-
------taaataaataaata------------aataaataacat----------------
--
>NW023601322.1:68485416-68485788(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----GTAAGAATGGTGACTGTATATACACACTCCTTTTAAACCATttgaattttgggcc
tccccagtggtgcagcggttgagcgctga-gttgcgaagctgcctgcggcctctg-cggc
gcc--------ggttcta------------------------------------------
--tccccggctgc-----tctccggccactggaggagggtcc-cacatggcgc-gcggac
ctctcctgc--cgccccctgctcccctcaactgtg---tacttcagt-cttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcttgtataaac-----------
--aaac-aaacaaat--------------aaata----------------------aaaa
catgcctctattaaaaaaga------------aaaaaataataataaaccatttgaattt
t-
>NW023604295.1:99174831-99175190(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----AGACTTTATATGttaagaacatattttaaaataaaaagcaaacaactgctgggcc
tccccggtggcgcagtgg--------------tgcgaagctgcctgcagcctctg-cggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccgcccaccggaggagggtcc-cacatggcga-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtacaaac-----------
--aaac-aaacaaac--------------aaataaat-----aaa-----------aata
catgcctctttaaaaaaaaa------------aaaaagcaaacaactgctcatc------
--
>NW023604295.1:11536682-11537100(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----GCTGGCTAAATATTAGAGTTTAGAGAagtcaatagaaataaaatcaaatagggcc
tccccggtggcgcagcggttgagtgctgg-gttgcgaagctgcctgtggcctctg-ctgc
gcc--------ggttcgatccccggctgctcccaggctgctccccggctgctccccggct
gctccccggctgc-----tccccggccaccggaggagggtcc-cacatggcgc-gcagac
ctgtcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaacaaat-aa-----------aaaaaaaa-----aata----------aaaa
catgcctctattaaaaaaaa------------aaaaagaaataaaatcaaat--------
--
>NW023601543.1:23828247-23828643(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----aAGTTATATATGTTGTGGTGTTAGTTATCACATAAAACACTAtgtagctggggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctacccgcgacctctg-aggc
gcc--------ggttcga---------------------------------tccccggct
gctccccggctgc-----tccccggccaccggaggagggtcc-cacatggcgc-gcagac
ctgtcctgc--cgcccgctgctcccctcagcagtg---tacttcggtccctctgcctgct
ctgctccccgctctggctctggtgaattctctcaccctccgctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagtgcttgtataaac--a--------
--aaac-aaacaaac-aaac---------aaataaat-----aaat----------aaaa
catgcctctataaaaaataa------------ataa------------------------
--
>NW023601754.1:9114954-9115317(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----TCAAATTTTGATAGACTGTGATGTAAGTGcacataaaaatacttaaaacagggcc
tccccagttgtgcagcggttgagcgctgg-gttgtgaagctgcccgcggcctctg-cggc
gct--------ggttcga------------------------------------------
--tccccggctgc-----tccccggccaccagaggagggtcc-cacatggcgc-acagac
ttctcctgc--cgccc---gcttccctcagcagtg---tgcttcggtccttctgcctgct
ctgctccgc-------------------------------gctctggtgaattctctca-
---ccctcccg-----cgcttctga-ctgtacccagggcatgtataaac-----------
--aaac-aaacaaac--------------aaataaat-----aaat----------aaaa
catgcctctattaaaaaaat------------aaataaataaaaaataaaaat-------
--
>NW023601754.1:6798595-6798943(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----ctgaaatacactgctgaggggagcagcgggcgggtcagaagtggtctcctgggcc
tccccggtggcgcagcggttgagcgctgg-gttgtgaagctgcccgcggcctctg-cggc
gcc--------agttcaa------------------------------------------
--tccccggctgc-----tccccggc-----gaggagggtcc-cacatggcgc-gcagac
ctctcctgc--cgcccgctgctcccctcagcagtg---tgcttcagtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtg-----------
----cctccca-----ggcttctga-ctgtacccagtgcatgtataaac-----------
--aaac-aaacaaac--------------aaacaaat--------------------aaa
catgcctctataaatttaaa------------aaaaaaaaaaaagaagaa----------
--
>NW023601754.1:6283071-6283434(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----CCATATTTGCCACATATGTATCTACATATAACTATAAGACAAtattgatggggcc
tccccggtggcgcagcggttgagcgctgg-gttgcgaagctgcccgcggcctctg-----
----------cggttcaa------------------------------------------
--tccccggctgc-----tccccggccaccagaggaaggtcc-cacatggcgc-acagac
ctctcctgc--cacccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ttgctccccgctctg-------------------------gctct-gtgaattctctcac
cctccctcccg-----cgcttccga-ctgtacccagtgcatgtataaac--a--------
--aaac-aaataaat-----------------------------------------aaaa
catgcctctaaaaaaaaaaa------------aaaagacaatattgaTGTTTTGATAC--
--
>NW023603184.1:29047708-29048061(-)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----GTCAAAAACAAATATGTGTTTCCTGAAATTGTTTTAAATCTcctcttccagggcc
tccccggtggcgcagcggttgagcgct-g-gttgcgaagctgcccgcagcctctg-tggc
gcc--------ggttcga------------------------------------------
--tccccggctgc-----tccccgg-caccagaggagggtcc-cacatggcgc-gcaga-
ctctcctgc----gccgctgctcccctcagcagtg---tacttcggtccttctgcctgct
ctgctccccgctctg-------------------------gctctggtgaattctctca-
---ccct-ccg-----cgcttctga-ctgta-ccagtgcatgtataaac--a--------
--aaac-aaacaaac-aaacc----agc-aaacaaat-----aaat----------aaag
catgcctctataaaaaaaaa----------------------------------------
--
>g4 Consensus of sequences 5-248
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------GGGCC
TCCCTGGTGGCGCAAGGGGTTAAGTCCCC-ACTATGAAGCTATCCGCAGCCACTG-CAGC
AG---------AGTTCGA------------------------------------------
-TCCCCCGGCCGG---------CCGCAGCAGGGGAGCTACCC-ACAATGGCGCAGCAGAC
CTCTCCTGTCTCGCCCGCTGCTCCCCTCAGCAGTG---TATTTCAGT-CATCTGCCTGTT
CTG-TCCCCACTCTG-------------------------TCTCTGGTGAATCCTCTCA-
---CCCCCCCCCCCC-CACCTCTGGCCTGTACCCCAGTCTTGTATGCAT-----------
--AAATAAAAAATAA--------------AAATAAAT-----CTTT----------AAAA
------------------------------------------------------------
--
>g5 Consensus of sequences 6-121
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------GGGCC
TCCCTGGTGGCGCAGGGTTGAGTCGCAGC-GCTGTGAAGCTGTCCGCAGCCTCTG-CAGC
GC---------GGTTCGA------------------------------------------
--TCCCCGGCCGG-----CC-------------GGAGACCCA-CATATGGCGC-GCAGAC
CTCTCCTGTCTCGCCCGCTGCTCCCCTCAGCAGTG---TATTTCAGT-CGTCTGCCTGTT
CTGTCCCC--CTCTG-------------------------TCTCTGGTGAATCCTCTCA-
---CCCCCTCC-----CGCCTCTGGCCTGTACCCCGTTCTTGTATATAA-----------
--ATAT-AAATAAAT-AA-----------AAATAAAT-----CTTT----------AAAA
------------------------------------------------------------
--
>g6 Consensus of sequences 7-30
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------GGGCC
TCCCTGGTGGCCTAGGGGTTAAGTCTCAGCGCTATACAAGCTTCCGCAGCCACTG---GC
CTG--------AGTTCGA------------------------------------------
--TCCCCG--------------CCGCCACGGGAGCTAAACCCACATATGGCCA-GCAGAC
CTCTCCTGTCTCGCCCGCTGCTCCCCTCAGCAGTG---TATTTCAGT-AATCTGCCTGTT
CTGCTCCCCACTCTG-------------------------TCTCTGGTGAATCCTCTCA-
---CCCCCCCCCCCCTCACCTCTGGCCTACACCCCA-GTTCTTCTATGC-----------
--AAAA-TAAAAAAT--------------AAATAAAA-------------------AATA
------------------------------------------------------------
--
