>g1 Consensus of sequences 2-71
------------------------------------------------------------
-----GGGCCTC---CCCGGT-----GGCGC-----A-GCGGTTGAGCGCTG---GGTTG
CGAAGCTG-CCCGCAGCCTCTGCAGCGCC---GGTTCGA----------------TC---
-C----CCGGCTGCTCCCCGGCCACCGGAGGAGGG-----TCCCACATGGC-GCAGCAGA
CCTCTCCTGC----CGCCC---GCTGCTCCCCTCAGCAGTGTAC---TTCGGTC-CTTCT
GCCTGCT-CTGCTCC---------CCGCTCTGG--CTCTGGTGAATTCTCT-CACCCTCC
CGC-----GCTTCTGA-CTGTACCC-AGTGCTTGT-----ATATAA---AAAT-AAAA--
-------AATCAAT--------------------CAATAATAA---AAAATAAAT-----
---AAAATAAATAA--ATAAATATAATAAATCTTTAAAA---------
>g2 Consensus of sequences 3-49
------------------------------------------------------------
-----GGGCCTC---CCCGGT-----GGCGC-----A-GCGGTTGAGCGCTG---GGTTG
CGAAGCTG-CCCGCGGCCTCTGCGGCGCC---GGTTCGA----------------TC---
-C----CCGGCTGCTCCCCGGCCACCGGAGGAGGG-----TCCCACATGGC-GC-GCAGA
CCTCTCCTGC----CGCCC---GCTGCTCCCCTCAGCAGTGTAC---TTCGGTC-CTTCT
GCCTGCT-CTGCTCC---------CCGCTCTGG--CTCTGGTGAATTCTCT-CACCCTCC
CGC-----GCTTCTGA-CTGTACCC-AGTGCATGT-----ATAAACAA-AAAC-AAAC--
-------AAACAAA--------------------CACAAAAAA---TAAATAAAT-----
---AAAAAACATGC--CTCTATAAAA----------------------
>g3 Consensus of sequences 4-102
------------------------------------------------------------
---GG------C---CCCGGT-----GGCGC-----A-GCGGTTGAGCGCTG---GGCTG
CGAAGCTG-CCCGCAGCCTCTGCAGCGCC---GGTTCGATCCTCCCCGGCCGCCCTC---
-C----CCGGCCA-----------CCGGGCGAGGG-----TCCCACATGGC-GCGACAGA
CCTCTCCTGCCG--CGCCC---GCTGCTCCCCTCAGCAGTGTAT---TCG-GTC-AGTCT
GCCTGTT-CTG-TCC---------CCGCTCTGG--CTCTGGTGAATTCTCT-CACCCTCC
CGC-----GCTTCTGA-CTGTACCC-AGTGCTTGT-----ATAAAT---AAAT-AAATA-
----AATAAATCTT--------------------TAAAA---------------------
------------------------------------------------
>NW023601653.1:65697582-65697947(-)
-------------TACAAGGGCTATAAG-GAGGAATAGCAGCacattaataaaaggaaac
atgagggcctcc---cctggt-----ggcgc-----a-gcggttgagcgctg---ggctg
cgaagcta-cccgcagcctctgcagtgct---gatttga----------------tc---
-c----ccagcca-----------ctgggcgaggg-----tcccacatggc-gcaacaga
cctctcctgatg--cgccc---gctgctcccctcagcagtgtat---ttc-atc-agtct
gcctgtt-ctgttgc---------ccgctctgg--ctctggtgaattctct-caccctcc
cat-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------aaaaaaaaa---aataaaagg-----
---agacaagaaca--gtcttttcaacagaaaacaaaaattt------
>NW023604295.1:75344865-75345231(-)
-------------TATCTCATCTCCTCT-GAGTGCTGTCCAAGGGCCATCAAGACttcat
atcagggcctcc---cctggt-----ggcac-----a-gaggttgagcgctg---ggctg
caaagctg-cccacagcctctgcagtgct---agttcaa----------------tc---
-c----ctggcca-----------cc-cgtgaggg-----tcccacatggt-gcgacaga
cctctcctgcca--cgccc---gctgctcccctcagcagtgtat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ccgctctgg--ctctggtgaattctct-caccctcc
cgc-----gcttctga-ctgcaccc-agtgcttat-----ataaat---aaat-aaat--
-------aaatatt--------------------tttaaaaaa---aaaaaagac-----
---ttcatatcact--acacacaatttttttaattgttttattt----
>NW023605194.1:21078861-21079225(-)
-------------AAAGGATTTCCAAAT-ATGCATCTCACAACTGTGGTTAAAAATCacg
aatagggcctcc---cctggt-----ggtgc-----a-gtggttgagcgctg---ggctg
caaagctg-cccgcagcctctgcagcgcc---agttcaa----------------tc---
-c----ccggcca-----------cc-agcaaggg-----tcccacatggt-gcgacaga
cctctcctgcct--cgccc---actgctcccctcagcagtgtat---ttt-gtc-agtct
gcctgtt-ctgttcc---------ctgctctgg--ctctggtgaattctct-caccctcc
tgt-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------taaaaaaaa---aatcacaaa-----
---caaaaaCTCAT--CCATAATATTGGAGCAAGATGAGATG------
>NW023601543.1:65794485-65794851(-)
-------------GGTCCTGCTTTCTAG-AAGCTAGTATTTAGGGagttgaaaacacaca
cacagggcctcc---cctggt-----ggcgc-----a-gcggttgagcgctg---ggctg
caaagctg-cccgcagcctctgcagtgct---ggttcga----------------tc---
-c----ccggcca-----------ccaggcgaggg-----tcccacatggc-gctacaga
cctctcctcccg--cgcct---gctgctcccctcagcagtgtat---ttc-atc-agtct
g-ttaat-ctgttcc---------ccgctctggctctctggtgaattctct-caccctcc
cgt-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------tataaagaa---aaagaaaac-----
---acatacacaca--ccacacacacacacaatgggaaggct------
>NW023601322.1:76811552-76811918(+)
-------------TGACATttggagaat-aaataaatatttaagtacataAAATACaagg
tggtgggcctcc---cctggt-----ggcgc-----a-gcagttgagcactg---ggctg
cgaagctg-cccacagcctctgcagcgct---ggttcga----------------tc---
-c----ccagccat-------------ggcgaggg-----tcctacatggc-gt-gcaga
cctttcctgcca--cgccc---gctgctcccctcagcagtgtat---ttt-gtc-tgtct
gcctgtt-ctgttcc---------ccgctctgc--ctctggtgaattctct-caccctcc
tgc-----acttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaata-
----aataaatctt--------------------taaaaaaaa---aaatacaag-----
---gtggTGTTTAT--GGCCATGTGcttatgtaataaaaata------
>NW023604861.1:78403548-78403912(+)
--------------TGTCCCCCTCTAGA-CTAATAACTGTATGAATTCAAGAATTAtttc
ctttggggcctc---cctggt-----ggcgc-----a-gtggtcgagcactg---ggctg
cgaagctg-cccacagcctctgcagtgcc---ggttcga----------------tc---
-c----ccggccg-----------cc-tgcgaggg-----tcccacatggt-gcgacaga
tctctcctgctg--cgcct---gctgctcccctcaacagtgtac---ttc-gtc-agtct
gcctgtt-ctgctcc---------ccgctctgg--ctctggtgaattctct-caccctcc
cat-----gcttctga-ctgtaccc-agtgcttgt-----ataaata--aaat-aaat--
-------acatctt--------------------taaaaaaaa---aagaattat-----
---ttccttttctt--tgttcaaCAGTACCTTCTCAACACct------
>NW023604295.1:108204143-108204507(-)
-------------attaTGACAAATTCT-AAGGAGGGCATTTGGTTATTAAAAGATagct
gggagggcctcc---cctgat-----ggcac-----a-gcagttgagcgctg---ggctg
cgaagctg-cctgcaacctctgcagcact---ggtttga----------------tc---
-c----ctggcca-----------cc-ggcgaggg-----tcccacatggc-acgacaaa
cctctcctgccg--tgcct---gctgctccactcagcagtgtat---ttc-gtc-actct
gcctgtt-ctgtttc---------ccgctctgg--ctctggtgaattctct-caccctcc
cgc-----gcttctga-ctataccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------taaaaataa---aaaaaagat-----
---agctgGGAATG--ATTTATCTTAAATTATTGTAAAGGAT------
>NW023604295.1:49473553-49473920(+)
-------------TATTACTCCAGaatc-ttaaaaaatgagttaaaaaaaaaaaaaaact
agaagggcctcc---cctggt-----ggcac-----a-gtggttgagcactg---ggctg
tgaagctg-cctgcagcctctgcagcacc---ggttcga----------------tc---
-c----ccggcca-----------cc-ggcgaggg-----tcccacatggt-gcgacaga
cctctcctgcta--cgcccgctgctgctcccatcagcagtgtat---ttc-atc-actct
gcctgtt-ctgttcc---------ctgctctgg--ctctggtgaattctct-catcctcc
cgc-----gcttctga-ccgtaccc-agaacttgt-----ataaat---aaat-aaac--
-------aaatctt--------------------taaaaaaaa---aacctagat-----
---aaTACAATAtc--atttgtgacttttttctaTTGTCTTC------
>NW023605305.1:84391616-84391979(-)
-------------TAtccagttgttaaa-tattttgatctTGTATCAAAATATATctcat
ctctgggcctcc---cctggt-----ggcgc-----a-gtggttgagcactg---ggctg
cgaagctg-cctgcagcctctgcagcgcc---agttcga----------------tc---
-c----ccggcca-----------cc-agggaggg-----tcccacatggc-gc-acaga
cctctcctgccg--tgcct---gctgctcccctcagcagtgtat---ttc-atc-agtct
gcctgtt-ctgttcc---------ccgctctgg--ctctggtgaattctct-caccctcc
tgt-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------ttaaatata---tatatatct-----
---catctCTGACA--TTCGTGAGTAAACctaaaaaattctt------
>NW023601433.1:29113804-29114167(+)
-------------aaatcCCAAGAACTG-CCCACatcgtgtgtgtgtatataacatatat
gtatgggcctcc---cctggt-----ggcgc-----a-gcggttgagcgctg---ggctg
caaagctg-cccacagcctctgcagcacc---ggttcga----------------tc---
-c----ccggcca-----------cc-ggcgaggg-----tcccacatggc-ac-gcaga
cctctcctgcca--cgccc---gttgctcccttcagcagtgaat---ttt-gtc-agtct
gcctgtt-ctgttcc---------ctgcactgt--ctctggtgaattctct-caccctcc
cat-----gcttctga-ctgtaccc-agtgcttgt-----atacat---aaat-aaat--
-------aaatctt--------------------taaaaaaat---atatatgta-----
---ttatgttgGAT--GCACACAAAAAATATGCAcactttta------
>NW023604861.1:58662931-58663292(+)
-------------ctgtaccccggttct-tgtatgcataaataaataaatcttaaaaaaa
aagagggcctct---cctggt-----ggcgc-----a-gcaattgagtgctg---ggctg
cgaagctg-cccacagcctctgcagcgcc---agttgga----------------tc---
-c----ccggccg-----------cc-ggcaagag-----tcccacatggc----gcaga
cctctcctgctg--cgccc---gcttctcccctcagcagtatat---ttc-att-ggtct
gcctgtt-ctgttcc---------ccgctctgg--ctctggtgaattctct-caccctcc
cac-----acttctga-ctgtaccc-agtgcttgc-----ataaat---aaat-aaat--
-------aaatctt--------------------taaaaaaaa---aaaaaaaga-----
---aagaggaagga--gcagTAGATAGATGAAGTCAGAGATG------
>NW026555331.1:71407306-71407670(+)
-------------atacccctgttcttg-tataaataaaaataaatctttaaaaaaaaaa
aagagggtctct---cttggt-----ggcac-----a-gcagttgagcgctg---ggctg
tgaagctg-ccctcagcctctgtagcacc---ggtttga----------------tc---
-c----ctggcct-----------cc-ggcgaagg-----tcccacatggt-gc-tcaga
cctctcctgccc--tgacc---gctgctcccctcagcagtgtat---ttc-atc-agtct
gcctgtt-ctgtccc---------ctgctctgg--ctctggtgaattctct-caccctcc
tat-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaataaaat--
-------aaatctt--------------------taaaaaaat---aaaaaaatt-----
---aaaaaaagata--ccagTAAAGGTCTAAGTCCTTGGAAG------
>NW023605305.1:62262796-62263159(-)
-------------GTCCACCTGTGAACC-TGAACAGGTAAGTGACttggaaaatgaagga
aggagggcctcc---cctggt-----ggcac-----a-gcggttgagcgctg---ggctg
cgaagctg-cctgcagcctctgcagcgcc---ggttcga----------------tc---
-c----ccagccg-----------cc-ggcgaggg-----tcccacatggc-ac-gcaga
catctcctgcca--tgccc---actgctcccctcagcagtgtat---ttc-atc-agtct
gcctgtt-ctgttcc---------ccgctctga--ctctggtgaatcctct-caccctcc
cgc-----aagtctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------gaatgtt--------------------taaaaaaaa---gagagagag-----
---agaaggaagga--aaagctaCAAATGAGTTTAATATTAG------
>NW023601322.1:82207668-82208031(-)
-------------AATACAGTCCAAACA-ATGCTCAACTGGTAGTTCTAGAAATAtacaa
aggtgggcctcc---cctggt-----ggcgc-----a-gcggttgagctctg---ggctg
cgaagctg-cccgcagcctctgaagtgcc---ggttcga----------------tc---
-t----ccggcca-----------cc-agcgaggg-----tcccacatggc-gc-acaga
cctttcctgcag--cgccc---actgctcccctcagcagtgtat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ctgctctgg--ctctggtgaatcctct-caccctcc
ggc-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------taaaagaaa---aaaagaaat-----
---atacaaaggTA--TCTGAACACCCTCTGTTAAGCACATG------
>NW023605305.1:81969714-81970077(+)
-------------ccccagctcttgtat-gcataaataaataaatatttaaaaaaaaacc
tcctgggcctac---ccttgt-----ggcgc-----a-gcggttgagtgctg---ggctg
caaagctg-cccgcagcgtctgcagtacc---agtttga----------------tc---
-c----ccagcca-----------cc-agtgaggg-----tcccacatggc-tc-acaga
cctctcctacca--tgccc---actgctcccctcagcagtgtat---ttc-atc-ggtct
gcctgtt-ctgttcc---------ctgctctgg--ctctggtgaattctct-caccctcc
tgt-----gcttctga-ctgtaccc-aatgcttgt-----ataaat---aaat-aaat--
-------aaatcta--------------------aaacaaaaa---aaaaccctc-----
---ctaattttgct--ttttcctaaTGATTTTCTGGATTTGG------
>NW023605305.1:84675238-84675601(-)
-------------TCTCAATGGGAATCA-AGGCCCCACTTCTCACTGCAAAAGTCTgtcc
tgttgggcctcc---cctggt-----ggtgc-----a-gtggttgagcgctg---ggctg
caaagctg-cccgcagcctctgcagcacc---agttcga----------------tc---
-c----ccggccg-----------cc-ggtgaggg-----tcttgcatggc-ac-tcaga
cctctcctgcca--tgccc---gccgctcccctcagcagtatat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ccgctctgg--ctctggtgaattctct-caccctcc
tgc-----ccttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------tgaaaaaaa---aaaagtctg-----
---tcctGTTGTGG--GTAGGGAGGGACACATTTTCTAGGCT------
>NW023601322.1:35620894-35621257(-)
--------------aagtttgaaaCTTC-CCCTTAGAAAAATGCACATAAAGAATTAaca
aaatcgggcctc---cccagt-----ggcgc-----a-gcggttgaacgctg---ggcta
cgaagcca-cccacagtctctgcagcgcc---ggttcga----------------tc---
-c----ccggcca-----------ccgggcgagag-----tcccacatggt-gc-acaga
cctctcctgcca--cgacc---actgctcccctcagcagtgtgt---ttt-gtc-agtct
gcctgtt-ctgctcc---------ctgctctgg--ctctggtgaattctct-catcctcc
cat-----gcttctga-ctgtactc-agtgcttgt-----acaaat---aaat-aaat--
-------aaatctt--------------------taaaaaaaa---atgaacaaa-----
---atcctCTGAAG--TTCATACATGAATTTATTTGGATTCC------
>NW023601653.1:23501807-23502174(-)
--------------AATCCTTTAATAGT-GTTACAGTATAAAAAATTAGGTTTAAAGaaa
ggtcagggcctc---cccagt-----ggcac-----a-gcagttgagcgctg---ggctg
aaaagctg-cccgcagtctttgcagtgct---ggttcaa----------------tc---
-cccggccggcca-----------cc-ggcgaggg-----tcccacatggc-gcgacaga
tctctcctgcca--tgccc---gctgcttcccttagcagtgtat---ttt-gtt-agtct
gcctgtt-ctgctcc---------ctgctctgg--ctctggtaaattctct-caccctcc
cac-----acttctga-ctgtaccc-aatgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------taaaaaaaa---aacaaaaac-----
---aagaagtcaga--agacttcatttaaaaaaataaataaa------
>NW023602073.1:8887163-8887524(-)
--------------caaaatgGCAATGC-ACAGATTCTTGAGCAACTTGAAAAAGGacat
gtgtggggcctc---cctggt-----ggcgc-----a-gcagttgagcgctg---ggctg
cgaagctc-cctgcagcctctgcagcgca---ggctcga----------------tc---
-c----ccggcca-----------cc-ggcgaggg-----tcccacatggc-acgacaga
cctctcctgc----ctccc---actgctcccctcagcagtgtat---ttc-atc-agtct
gcctctt-ctgttcc---------ccgctctgg--ctctggtgaattttct-caccctcc
cgt-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------taaaaaaaa---ggaaaagaa-----
---aaagggcatGT--GTGTAATGTACCTGTTCTCAACTAAA------
>NW023604861.1:64983671-64984034(-)
-------------ACAGGACGTTAGCtc-acatgtggctatttacattaaaaactcctga
aagagggcctcc---cctggt-----ggcgc-----a-gtggttgagcgctg---ggctg
caaaactg-cccacagcctctgcagcgcc---ggtttga----------------tc---
-c----ctggccg-----------cc-agtgaggg-----tcccacatggc-gcgacaga
cctctcctgtct--cgccc---gctgcttccctcagcactgtat---ttc-atc-agtct
gtctgtt-ctgttcc---------ctgctctgg--ctctggtgaattctct-caccctcc
cat-----gcttctgg-ctgtaccc-agtgcttgc-----ataaac---aaat-aaat--
-------aacttct--------------------GAAAGAAAA---TACACTAAT-----
---ATGTTAAGCTT--GGTATTTTGGGGtgctcttaaattt-------
>NW023601212.1:45274783-45275147(+)
-------------aCCAAatcgccctgt-aatactcccattctctccattGAAAAGCccg
acaggggcctcc---cctggt-----ggcgc-----a-gcggttgagcactg---ggctg
caaaggtg-tctgcagcctctacagcacc---agttcga----------------tc---
-c----ccagcca-----------ca-ggcgaggg-----tcccacatggc-gcgacaga
cctctcctgccg--cgcct---gctgctcccttcagcagtgtat---ttc-gtt-actct
tcctgtt-ctgttcc---------ccgctctgg--ctctggtgaattctct-caccctcc
tgt-----gcatctga-ctgtaccc-agtgctcgt-----ataaat---aaac-aaat--
-------aaatctt--------------------aaaaaaaaa---aaacccgaa-----
---ggTTCTTACCG--CCTAGTTCAAGACCTTTGCCTCATCA------
>NW026555331.1:93852749-93853105(+)
-------------GTAGATGACTCTCAA-AAACTAAATCAGTTCTTGTTAAAAGTAccca
tactgggcctcc---cctggt-----ggcgc-----a-gcggttgagcgctg---gtctg
caaagctg-cccgcagcctctgcagcact---ggttcga----------------tc---
-c----ccagcca-----------cc-tgcgagcg-----TCCCGCATGgt-gcggaaga
cctctcctgcca--tgccc---gctgctcccctcagcagtgtat---ttc-atc-cgtct
gcctgtt-ctgttcc---------ccgctctgg--ctctggtgaattctct-cacactcc
cgc-----gcttctga-ctgtaccc-agtgcttgc-----ataaat---aaat-aaat--
-------taa------------------------taaaaaagt---acCCATACTACACT
T---------------GTCCTTTGTgactaaatacatttttt---a--
>NW023601212.1:46233778-46234137(-)
-------------cccgaagcaatgtcc-agtgttttaagtcctaaacaaaatgcatcta
agatgggcctcc---ccaggt-----ggcgc-----a-gcggttgagcgctg---ggctg
cgaagctg-cccgcagcctctgcagcgcc---ggttcca----------------tc---
-c----ccggcca-----------tc-ggcgaggg-----tcccacatggt-gg-gcaga
cctctcctgccg--cgccc---actgctcccctcagcagtgtat---ttt-gtc-agtct
gcccgat-ctgttcc---------ctgctctgg--ttctggtgaattctct-caccctcc
cac-----acatctga-ctgtacct-agtgcttgt-----ataaat---aaat-------
-------aaatctt--------------------taaaaaaaa---aaaatacat-----
---ctaagatggtg--tcttcccaccactaAGAACGCAGACC------
>NW023605194.1:90331401-90331759(+)
-------------tacttttttaatgta-gaaagaTAAAATTGCTAATTAAAAGTTCCTa
atcagggcttcc---cctggt-----ggcgc-----a-gcagttgagcgctg---ggctg
tgaagctg-cccgcagcctctgcagtgcc---tgttcga----------------tc---
------ccggcca-----------cc-agcgaggg-----tctcacatgtc-gc-gcaga
cctctcctgcca--caccc---gctgctcccctcagcagtgtat---ttc-atc-agtct
gcctgtt-ctgttcc---------ctgctctgg--ctctggtgaattctct-caccctcc
cac-----gcttctga-ctgtaccc-agtggttgt-----ataaat---aaat-------
-------aaatctt--------------------taaaaaaaa---ataagttcc-----
---taATCATGCAA--AACGTAAACACCAGGATTTTAAGTTT------
>NW023605083.1:17900191-17900554(-)
-------------GGTTTTAATACTTTT-AGCTTCTGTGACTGTAAATGGAAAACCAATT
gactggacctcc---cctggt-----ggtgc-----a-gcggttgaacgctg---ggctg
tgaagctg-cccgcagtgtcagcagcgcc---ggttcaa----------------tc---
-c----ccaacca-----------ct-ggcaaggg-----ttccacatggc-ac-acaga
tctctcctgccg--tgccc---gctgctcccctcagcagtgtgt---ttc-atc-agtct
gcctgtt-ctgttcc---------ccactctgg--ctctggtgaattctct-caccctcc
tgt-----gcttctga-ctgtaccc-agcacttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------aaaaaaaaa---aaaaagaaa-----
---accaactgaCT--GATTACAATCAGACAGCTAATTATGT------
>NW023603184.1:65620205-65620568(+)
-------------CCCCAAGTAGAGTAT-GACTGATATCTTCATAAAAAGAAAGTCacat
gatggggcctcc---cctggt-----ggcgc-----a-gccgttgagtgctg---ggcta
tgatgctg-cccgcagcctctgcagagcc---agttgga----------------tc---
-c----ccagccg-----------cc-ggcgaggg-----tcccacatggt-gc-gcaga
cctctcctgctg--tgtcc---gctgctcctctcagcagtgtgt---ttc-atc-agtat
gcctgtt-ctgttct---------ccactttgg--ctctggtgaattctct-caccctcc
cac-----gtttctga-ctgtaccc-agtgctcgt-----ataaat---aaat-aaat--
-------atatctt--------------------aaaaaaaaa---gtctcatga-----
---AAAGACAAACA--CAAGAACAATGCCACATAGACAGGGC------
>NW023605305.1:97102768-97103131(+)
-------------GCACCAGTAAAGAAA-TCTATAGAAATATTTCAGTCAAAAATGcaca
aaaggggcctcc---ctaggt-----ggtgc-----a-gtggttgagcgccg---ggctg
cgaagctg-ctcatagcctctgcagcgcc---ggttcaa----------------tc---
-c----cctgcct-----------cc-ggtgaggg-----tcccacatggc-ac-acaga
cctctcctgccg--tgcct---gctgctcccctcagcagtgtac---ttc-gtc-agtct
gcctgtt-ctgttcc---------ctgctctgg--ctctgatgaattctct-caccctcc
tgc-----acttctga-ctgtaccc-agtgcttat-----ataaat---aaat-aaat--
-------aaatctt--------------------taaaaaaat---gcacaaaag-----
---tcAAACTACAA--TGAAAAGGACTAGATTATCATCATCA------
>NW023605194.1:15293797-15294159(-)
---------------TCCCCTTTaccta-atctttaaaaaaatttctttaaaaaaaaaat
aatgaagtctct---cctggt-----ggtgc-----a-gcggttgaacgctg---ggcta
cgaagctg-cccgcagcctctgcagcacc---agtttga----------------tc---
-c----ctggccg-----------cc-agcgaggg-----tcccacatggc-acaacaga
cctctcctgcca--tgccc---gttgctctcctcaggagtgtat---ttc-gtc-agtct
gcctgtt-ctattcc---------ctgctctgg--ctctggtgaatgctga-caccctcc
cgc-----gcttctga-ctgtacac-agtgcttgt-----ataaat---aagt-aaat--
-------aaatctt--------------------taaaaaaaa---aataatgga-----
---ggggcctccct--agtggtgcaaggagttaagacacagc------
>NW023605305.1:95245189-95245536(-)
----------gct----------------gcaccaccggggaggcccgaaagaaaaatct
taaaagcaaata---GAGAgg-----ggtgc-----a-gcagttgagtgctg---ggctg
caaagctg-cctgcagcctctgcagtgcc---agttcaa----------------tc---
-c----ctggcct-----------ct-ggcgaggg-----tcccacatggc-ac-acaaa
cctctcctgcca--cgccc---gctgctccccttagcagtgtat---gtt-gtc-agtct
gcctgtt-ctgttcc---------ccactctgg--ctctggtgaattctct-caccctcc
cgc-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--tttttttttt--------caaaaaaaa---gtttcacaT-----
---AGGGAAGAGTA--TCCAAAAGAAGA--------------------
>NW023601433.1:32255430-32255787(+)
-------------aattctcaggataga-aggaacatacctaaacatgataaaagccata
tacagggcctcc---cctggt-----ggcgc-----a-gcagttgagtgctg---ggctg
caaagctg-cccgcagcctctgcagcacc---agtttga----------------tt---
-c----ccagaca-----------ct-ggcgaggg-----tcccacatggc-ac-acaga
tctcttctgc----cgccc---gctgctcccctcagcagtgtat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ccactctgg--ctctggtgaattctct-caccctcc
cgc-----acttctga-ctataccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--tttttttttt--------tttaaaagc---catatacaa-----
----caaacccatggccaacattattc---------------------
>NW026555331.1:77695384-77695744(+)
--------------AAAAGCTTATTTCT-GTTGATTTATAATTTCCACCAAAATTTTTTT
GTCCTGGGCCTC---ctcgat-----ggcgc-----a-gcagttgagtgctg---ggttg
cgaagctg-cccgcagcctctacagcgcc---agttcaa----------------tc---
-c----ccagcca-----------ccgggcaagga-----tcccacatggc-gc-acaga
cctctcctgccg--tgcct---gctgctcccctcagcagtgtac---atc-gtc-agtct
gcctgtt-ctgctct---------ccactctgg--ctctggtgaattctct-caccctcc
cgc-----acttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-gaat--
-------aaatcttaattttttttgtcc------tAAGAAACT-----------------
----------------TCTCTATATACTTAGTCTTCCAAATTat---c
>NW023603184.1:150179155-150179511(-)
-------------GGccggggcagggag-agagggccGCTCCATCGGACAAAAGACttag
gtgtgggcctcc---ct--------gggcgc-----a-gtggttgagcgctg---ggctg
tgaagctg-cctgcagcccctgcagcgcg---ggttcga----------------tc---
-c----cggctgg-----------ct-ggcaaggg-----tcccacatggt-gc-gcaga
cctctcctgcag--cgccc---gctgctcccctcagcagtgtat---ttt-gtc-agtct
gcctgct-ctgctcc---------ccgctctgg--ctccggtgaattctct-caccctcc
cgc-----gctgctga-ctgtaccc-agtgcttgt-----gtaaat---aaat-caat--
-------aaatctttttttttttttttttttttttaaaaaaaa---gacttaggt-----
---GTGAGTCCTGAAA--------------------------------
>NW023602073.1:80036954-80037315(+)
--------------agtaATTTGTGGAA-TGTAGAGTAACTAAACTAAGATTAAAAAcaa
gcttagggcctc---cccagt-----ggcgc-----a-gcggttgagcgctg---ggcta
caaagctg-ccagcagcctctgcagcact---ggtttga----------------tc---
-c----ccagcca-----------cc-tgcgaggg-----tcccacatggc-gc-acaga
cctttcctgctg--cacct---gctgctcccctcagcagtgtat---ttc-ctc-agtct
gcctgtt-ctgtt-c---------ccgctctgt--ctctggtgaatcctct-caccctcc
tgc-----acttctga-ctttaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------taaaaaata---ataaaaaat-----
---aaaaacaagct--taaaaattaacccttgaaaaCTAACT------
>NW023604295.1:64293808-64294169(-)
-------------caattccactacgag-ggatctacccaaaggacacaaaaacagtgat
tcaagggcctcc---cctggt-----ggcac-----a-gcggttgagcgctg---ggctg
caaagctg-ccggtagcctctgcagcacc---ggttcga----------------tc---
-c----ctggccg-----------cc-ggtgaggg-----tcccacatggc-acgacaga
actctcctgg----cgctc---gttgctcccctcagcagtgtat---ttc-gtc-agtct
gcctatt-ctg-tcc---------ccactctgg--cactggtgaattctct-caccctcc
cgc-----acttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------aaaaaaaaa---aacaacagt-----
---gattcaaaaga--acacctatacacctatgtttgttgca------
>NW023604861.1:7104691-7105056(+)
-------------tatgcataaataaat-aaaataagccttaaaaaaaaaaaaaaaaaaa
aacagggcctcc---cctggg-----ggcgc-----a-gcggttaagctctg---ggttg
ccaagctg-cccacagcctctgcagcacc---agttcaa----------------tc---
-c----ctggcca-----------cc-agtgaggg-----tcccacatggc-tcgacaga
cctctcctgtct--cgccc---actgctcccctcagcagtgtat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ccactctgg--ctctggtgaattctct-taccctcc
tgc-----gcttctga-ctgta-tc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatatt--------------------tttaaaaaa---taaaacaaa-----
---taaaagacaag--GGTTTTATCTCGAGAGGCTGGTCATATT----
>NW023601653.1:28856009-28856368(-)
--------------GAGGagataatgaa-caaaatatattctatgtGGCCAAAATTGGAG
AGACAGGGCCTC---CAaagt-----ggcac-----a-gcggtttagcgctg---ggctg
caaaactg-cccacagcctcggcagcact---ggtttaa----------------tc---
-c----ctggcca-----------ct-ggagagag-----tcccacatggc-acgacaga
cctctcctgcca--tgcct---gctgctcccctcagcagtgtat---ttc-atc-agtct
gcctgtt-ctgctcc---------ctgctctgg--ctctggtggattctct-caccctcc
cgc-----acttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-------
-------aaatctt--------------------taaaaaaaa---aaattggag-----
---agacAGCATAT--GATTATCTTACCTTAGGaagtaaata------
>NW023603184.1:70577320-70577682(-)
-------------GAAGTGGCAATGGTA-GACTGTATGATTTCATGATTAAACAGTgtct
tggagggcctcc---cctggt-----ggcgc-----a-gcggttgtgcgctg---ggctg
tgaagctg-cccacagcctctgcagctcc---ggttcga----------------ac---
-c----ctggctg-----------cc-ggtgagag-----tcccacatggc-ac-gcaga
cctctcctgccg--cgccc---gctgctcccctcagcagtgtat---ttc-atc-agtct
gcctgtt-ctgttgc---------ctgctctgg--ctctggtgaattctct-caccctcc
cat-----gcttctga-ctgta-ct-ggcgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------taaaaaaaa---aagtgtctt-----
---ggAAAACTAAG--AGATGTGAGTTTGAATCTCATATCTG------
>NW023601754.1:22093248-22093610(-)
-------------TCGCCAGTCCCAAGG-GAAGGACTGGAGGCCACACTAAAGTGtttga
acttgggcctcc---cttggt-----ggcac-----a-gcggttgagcgctg---ggctg
cgaagctg-cccgcagcctctgcagcgct---ggttcaa----------------tc---
-c----ctagctg-----------cc-agcgaggg-----tcccacatggc-at-tctga
cctctcctgcca--cgccc---gctgctcctctcagcagtgtat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ctgctctgg--ctctggtgaattttct-cgccctct
cac-----acttctga-ct-taccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------aaaaaaaaa---tagtttgaa-----
---ctGTACCCTAA--ATTAGACACTGAAGGGTTTAAACAGG------
>NW023601322.1:35183224-35183592(-)
-------------AATACTCTTTTAGAG-TTCaatctaatttatttaaaaaatgaccttT
CGGTGGGCCTCC---CCAGTTCGGTGGGCGC-----A-GCAGTttagcactg---ggttg
tgaagatg-tccacagcctctgcagcgcc---agttcaa----------------tc---
-c----ccagccg-----------cc-agcgaggg-----tcccaaatggc-at-gcaga
cctctcctgcca--cgccc---gctgctcccctcagcagtgtac---ttc-atc-agtct
gcctgtt-ctgttcc---------ccgctctgg--cttttgtgaattctct-caccctcc
cgt-----gcttctga-ctgtaccc-agtgctttt-----ataaat---aaat-aaat--
-------aaatctt--------------------taaaaaaaa---aaatggcct-----
---ttcaggcctcc--cctattggggcaggcagttgagcacc------
>NW023604861.1:26473659-26474023(-)
-------------AAGTTGACTCAAAAT-CTCCAGCTCATTAACCTATAAAAGTAAatga
tgctgggcctcc---cctggt-----ggcgc-----aggtggttgagcactg---ggctg
tgaagctg-cctgcagcctctgcagcgct---gattcca----------------TC---
-C----ctagccg-----------cc-ggcaaggg-----tcccacatggt-gc-acaga
cctctcctgctg--tgcca---gctgctcccctcagcagtgtat---ttt-gtc-agtct
tcctgtt-ctgctcc---------ctgctctgt--ctctgatgaattctct-caccctcc
cac-----acttctga-ctgtaccc-agtgcttgc-----ataaat---aaat-aaat--
-------aaatctc--------------------aaaaaaaaa---aaagtaaat-----
---gatgcTGCCAC--TACAAATGTCACAATTAACTAACATA------
>NW023604972.1:92552658-92553021(-)
-------------GATTGGCTGATGAAT-CACTTCTTACAATTCTTCAAAAATTctaatc
tttagggcctcc---cttggt-----ggtgc-----a-gcggttgagcgttg---ggctg
caaggctg-cccgcagcctctgcagcact---ggttcca----------------cc---
-c----ccggcca-----------cc-agtgaggg-----tcccatatggt-gt-gcaga
cctctcctgttg--cgccc---gctgctcccctcagcagtgtat---ttt-gtc-agtct
gcctgtt-ctgttac---------ccgctctgg--tgctgttgatttctct-caccctcc
cgt-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------acatttt--------------------taaaaaatt---tctaatcCT-----
---TAAATTGTTAG--AAAAAGTGCTCTGATTGGGATAAATA------
>NW023601543.1:15815451-15815813(+)
-------------agggaaggacagaga-aacattttgaaaatatattaaaaatagcaga
attagggcctcc---cctggt-----ggcgc-----a-gaggttgagcgctg---ggctg
caaagctg-cccgcagcctctgcagtacc---ggttcga----------------tc---
-c----ccggccg-----------at-ggcgagag-----tcccacatggc-ac-gcagt
cctctccggctg--tgccc---gctgct-ccctcagcagtgtat---ttc-atc-agtct
gcctgtt-ctgttcc---------ctgctctgt--ttctgatgatttctct-caccctcc
cgt-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------ttaaaaaat---agcagaatT-----
---AACTACATGTG--AATCAACCCAAAACCAGTTTACTAGG------
>NW023603184.1:129434317-129434680(+)
-------------AAAAGCTCTATTCAT-AAAATACAGCAATGTCTATATAAAAATCCAG
TGTAgggccttc---cctagt-----ggcac-----a-gcggttgagtgctg---ggcta
tgaagctg-ctcgcagcctctgcagcacc---ggttcca----------------tc---
-t----ccggctg-----------cc-agcgaggg-----tcccacatggt-gcgacaga
cttctcctgcct--ggccc---gctgctcccctcagcagtgtat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ccg--------ctctggtgaattctct-caccctcc
tgc-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaataaa-------atct---------taaaaaaaa---aaaaaatcc-----
---agcgtATTACC--CTAAAATCCGTTAAGACTATAATTTTT-----
>NW023601543.1:66763294-66763642(-)
--------------tttcagAGATGATG-TCTATAGGCTTTTGGAATTTTATTCTACAGa
atgaaggcctcc---cctggt-----ggcgc-----a-gcgattgagtactg---ggctg
cgaagctg-cccgcagcttctgcagcgcc---ggttcga----------------tc---
-c----ctggccg-----------cc-agcgaggg-----tcccacatggc-ataacaga
ccactcctgtct--tgcct---gctgctcccctcagcagtgtat---ttc-atc-agtct
gcctgtt-ctgttcc---------ccg--------ctctggtgaattctct-caccctcc
cgt-----gcttctga-ctgtacac-agtgcttgt-----ataaat---aaat-taatt-
----------------------------------taaaaaaat-gtacctaTAAT-----
---GATGCTATGTT--AGCTATATCAATTAAATGTAA-----------
>NW023604972.1:21578021-21578375(+)
-------------ttttatttttagaaa-gcactttgtagttcttttaaaaatcttcctg
gactgggcctcc---cctggt-----ggcgc-----a-gcaattgagcgctg---ggctg
tgaagctg-cccgcagcctctgcagtact---ggtttga----------------tc---
-c----ctggcct-----------cc-agcaaggg-----tcccacatggc-gc-gcaga
cctctcctgccg--cgcct---gctgctcccctcagcagtgtat---ttc-atcaagtct
gcctgtt-ctgttcc---------ctg--------ctctggtgaattctct-caccctcc
cgt-----gcttctga-ctataccc-agtgcttgt-----ataaat---aaat-------
-------aaatctt--------------------taaaaaaaa---attttaaaa-----
---aaatcttcctg--gACTTgaaaaaggggtgggggtgttt------
>NW023603184.1:94058173-94058535(-)
-------------gaaaactgaaaagga-gggTACATTTCACcaccattaaagaaaaatt
tcctgggcttcc---cctggt-----ggcac-----a-gcagtagagtactg---ggctg
cgaagctg-cccacagtctctgcaacgct---ggttcga----------------tc---
-c----ccagcca-----------cc-cgggaggg-----tcccacctggc-acgacaga
cctctcctggca--caccc---gctgctcccctcagcagtgtat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ccactctgg--ctctggtgaattctct-caccctcc
cat-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aatc-ttaa--
-------aaaaaat--ttttttttcc-------ttagaaatta---aaatagaac-----
---tactcaatgat--ccagcaatcccac-------------------
>NW023601212.1:63804589-63804931(-)
-----------gtt---------------ACCTGGTTTTCACattctgacttatatcact
tagAATAATTAC---CTCAgg-----ggcgc-----a-gtagttgagcgctg---ggctg
cgaagctg-cctgcagcctctgcagcacc---ggtt-ga----------------tc---
-c----ccggctg-----------cc-agcaaggg-----tcccacatggc-tcgacaga
cctctcctgccc--tgccc---gctgctcccctcagcagtgtat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ctgctctgg--ctctggtgaattctct-caccctcc
cgc-----gcttctga-ccgtaccc-agtgcttgt-----ataaat---taaa-aaaa--
-------aaaaaaa--------------------aaaggaata---atcacctca-----
---aggtccatcta--ttttgccccaaaaggca---------------
>NW023604861.1:65982646-65983008(-)
--------------CCTTCCTTCCTAAG-CAGTGACCCTGAAATTTAGCAAAATTGTgat
gacaagggcctc---cccggt-----ggcac-----a-gcggttgagtgctg---ggctg
caaaactg-cctgcagcccctgcagcgct---ggttca-----------------tt---
-c----ccggctg-----------cc-ggggaggg-----tcccacaaggc-ac-gcaga
cctctcctgccg--tgccc---actgctcccctcagcagtgtat---ttt-gtc-agtct
gtctgtt-ctgctcc---------ccgctctgg--ctctggtgaattctct-caccttcc
tgc-----gcttctga-ctgtaccc-agtgcttat-----ataaata--aaat-aaat--
-------aaatctt--------------------taaaataaa---aattgtgat-----
---gaCTAATTAGA--GCAGTTTGTGTTAGAAGGTGGGGAAG------
>NW023602073.1:7019382-7019743(-)
-------------GAGACATGTGGAGGC-CAGTGTGACTGCACAGGAGTTAGAATGTAAG
Atgaggtcctcc---cctggt-----ggcgc-----a-acggttgagcgctg---ggctg
cgaagctg-cccgcagcctctgcagtgcc---ggttcga----------------tc---
-c----ccggcca-----------cc-agcgaggg-----tcccatatggc-gctacaga
cctctccagc----tgccc---gctgctcccctcagcagtgtat---ttc-gtc-agtct
gcgtgtt-ctgttcc---------cctctctgg--ctctggtgaattctct-caccctcc
tgc-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---caat-caat--
-------caatcaatcaatcaatctt--------taaaaaaaa---tgtgaagat-----
---gaGGTCAGGGA---------------GATAGGTAATGTC------
>NW023602073.1:35972260-35972625(+)
--------------agtttatcatcatg-tgctgtcagaaaaatgccaattcaaaccaca
atgaaggcctcc---cctggt-----ggcgc-----a-gcgggtgagcactg---ggctg
cgaagctg-ccagcagcctctgcaa-gcc---agtttga----------------tc---
-c----ccggccg-----------ca-ggcgaggg-----tcccacatggt-gcaacaga
cctcacctgcct--ctcct---gctgctcccctcagcagtgtatttcttc-gtc-agcct
gcctgtt-ctgttcc---------ctgctctgg--ctctggtgaattctct-caccctcc
tgc-----gcttctta-ctgtaccc-agtgcttgt-----atgaat---aaat-aaat--
-------aaatctt--------------------taaaaaata---aataaaacc-----
---acagtgagttc--ccacctcacatctgtgagaatgaccc------
>NW023604295.1:66730920-66731288(-)
-------------AATTTCACAgctaaa-aaacccaaaaaacttcAGTTAATAAGttaag
aacagggcctcc---cctggt-----ggcgc-----a-gcagttgagcgctg---ggctg
cgaagctg-ccggcagcctctgcagcgcc---agctcgc----------------tC---
-C----CAGGCCC-----------CC-CGGAGAGG-----TCCCCCATGgctgaggcaga
cctctcctgctg--cgccc---gctgctcccctcagcagtgtatttcttc-gtc-agtct
gccagtt-ctgttcc---------ccactctgg--ctctggtgaattctct-caccctcc
tgc-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------taaaaaaaa---attaagaac-----
---aaccTGATTTT--AGAATTCTGTCAGTTTCAACTTAAAC------
>NW023601322.1:65102384-65102749(-)
-------------CTTATAAAAGGTATT-AAAATAATCACTTGCCTAATAAAGAAtgtgt
ttcagggcctcc---cctggt-----ggcgc-----a-gcggttgagcactg---ggttg
caaagctg-cccgctgcctctgcagcgcc---ggttcga----------------ac---
-c----caggcgg-----------ctgggtgaggg-----tcccgcatggc-atgactga
cctctcctgtct--ctccc---gctgctcccctcagcagtgtat---ttc-gtt-ggtct
gcctgtt-ctgttcc---------cagctctga--cactagtgaattctct-caccctcc
tgc-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatttt--------------------aaaaagaat---gtgtttCAA-----
---TGGAGCActtt--ttggttggtttttattttctaatgac------
>NW023601433.1:56951846-56952203(-)
-------------GATACTGatttggaa-tcagaaaaaaagaggCTTGATTTAAAGtggt
tatggggcctcc---cctggt-----ggtgc-----g-gcggttgagcactg---ggct-
caaagctg-cccgcagcctttgcagcgcc---ggttcga----------------tc---
-c----ccggcca-----------cc-ggcaaggg-----tcccacatggc-gtgacaga
cctctcctgg----cgccc---gctgctcccctcagcagtgtat---ttt-gtc-actct
gcctatt-ctgttcc---------ccgctctgg--ctctggtgaattctct-caccctcc
cgc-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------ctttttt-------tttt---------tttatagag---gcatgtttt-----
---atttatttatt--ttatttgtttgttttttt--------------
>NW023601433.1:30415907-30416274(+)
-------------ACATATGCATTTGTT-GTAAACAttggtaaatatataaataatctat
tttagggcctcc---cctggt-----agcgc-----a-gcggttgagcactg---ggctg
caaagctg-cccgcagcctctgcagcgct---gattcta----------------tc---
-c----ccggcca-----------cc-ggcaaggg-----tcccacatggc-ac-acaca
cctctcccgcca--cgcct---gctgctccccttagcagtgcac---ttc-atc-agtct
gcctgtt-ctgttcc---------ccgctcggg--ctctggtgaattctct-taccctcc
tgt-----gcttctga-ctgtaccctggttctttt-----ataaataataaat-aaat--
-------aaatctt--------------------taaaaaaat---ctattttat-----
---tgttgtctaat--attttctcaaatgGGCATATCCAGTT------
>NW023602073.1:51574937-51575299(+)
--------------gctcttgtatgcat-acttaaataaaaataaatctttaaaaaaaat
ctgacggcctcc---cccagt-----ggcgc-----a-gaggttgagcgctg---ggatg
caaagctg-cctgcagcctctgcagcacc---ggttcaa----------------tc---
-c----ccggcca-----------cc-agcgaggg-----tcccaaatggc-ac-gcaga
cctctcctgctg--cgcct---gctgctcccctcagcagtgtat---ttt-gtc-agtct
gcctgtt-ctgctcc---------ctgctctgt--ctctggtgaattctct-----ctcc
cgt-----gcttctga-cactaccc-agtgcttgt-----ataaat---aagt-aaata-
----aataaatctt--------------------taaaaaaat---aaaataaat-----
---ctgagtactat--ttcattatgtgtatgtgtatgtatac------
>NW023601543.1:48553808-48554176(+)
-------------tcctaaatgtatggg-atgcagcaaaagcagttataagaggaaaata
tatagggccttc---cctggt-----ggcgc-----a-gtggttgagcgctg---ggctg
tgaagctg-cccacagcctctgcagcacc---acttcaa----------------ac---
-c----ccggcca-----------ccaggctaggg-----tcccacatgtc-gt-gcaga
cctctcctgctg--tgcct---actgctcccctcagcagtgtgt---ttt-gtc-ggact
gcctgtt-ctgttcc---------cccctctgg--ctctggtgaattctct-catcctgc
cgt-----gcttctga-ctgtacct-agtaattgt-----ataaat---aaat-gaata-
----aataaatctt--------------------taaaaaaat---gactagaat-----
---cccaatattaa--aaaaaagaaaaaagaggaaatatata------
>NW023602073.1:95620256-95620610(-)
-------------ccagctcttgaatgc-ataaataaataaatcttttttaaaaaagtaa
ctgtgggcctcc---cctggt-----ggcac-----a-gtggttgagcactg---ggctg
tgaagctg-cccgcagcctctgcagcacc---agttcta----------------tc---
-c----ccagcca-----------cc-agcgaggg-----tcccacatggt-gcgacaga
cctctcctgccg--caccc---gctgctcccctcagcagtgtatttcttc-gtc-agtct
gcctgtt-ctgttcc---------ccgctctgg--ctctggtgaattctca---------
----------ccctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctg--------------------aaaaaaatt---tttaaaaaa-----
---aagtaactgca--CTGTACACAGGAGCACCTGCATCCAA------
>NW023605083.1:92643552-92643913(-)
--------------TCCAAGATCCTGGA-AGGATAGGCAAGGTGGTCATGAATAGCccta
ttttggggcctc---cctggt-----ggcac-----a-gcggttgagcgct----ggcta
cgaagctg-cccgcagcctctgcagcacc---tgttcga----------------tc---
-c----ctggcca-----------cc-ggcgaggg-----tcccacataga-gc-gcaga
cctctcctgccg--tgccc---gctgctcccctcagcagtgtgt---ttt-gta-agtct
gtctgtt-ctgctcc---------ccgctctgg--ctttggtgaattctct-caccctcc
cgc-----acttctga-ctatagcc-agtgcttgc-----ataaat---aaat-aaat--
-------aaatctt--------------------ttaaaaagc---ccTATTTTT-----
---CTCATGATTCA--ACTGTTACTAtcgcaattaaaaataa------
>NW023601212.1:2428637-2429001(-)
--------------atattttatttttg-ctgtcacTATACCTTAAGTTAAAATTGcaca
tactggggcctc---cccgat-----ggcac-----a-gcggttgagcgctg---ggttg
caaagctg-cctgcagcctctgcagcgcc---agttcga----------------tc---
-c----caggcca-----------ctgggcgaggg-----tcccacatggc-gc-gcaga
cctctcctgccg--cacct---gctgcttccctcagaagtgtat---ttc-atc-agtct
gcctgct-ctgctct---------cccctctgg--ctctggtgaattttctggGCTCCcc
cgt-----acttctga-ctataccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatatt--------------------taaaaaatt---gcacaTACT-----
---gtcaaaattaa--actttttgtgtAGTTTAATGAGGTGT------
>NW023603184.1:75359521-75359873(-)
-------------TTTCATGTAGGGAGC-ACAGAGTTGagtgttcttttaaaat------
-ctacttggtcc---cctggt-----gacgc-----a-gtggttgggcactg---ggctg
caaagcta-cccgcagcctctgcagcgct---ggttcaa----------------tc---
-t----ccagctg-----------cc-cgtgaggg-----tcccacatggc-gc-gcaga
cctctcctgctg--tgctt---gctgctccccttagcagtgtat---ttt-gtc-agtct
gcttggt-CTGCcac---------ccgcactgg--ctctggtgaattctct-gaccctcc
tgt-----gcttctga-ctgtaccc-agtgcttat-----ataaat---agat-------
-------aaatctt--------------------taaaaaata---aataaaatc-----
---cacttGGTAAT--ATTAGTATTAATTagtatatttatta------
>NW023604861.1:121289148-121289513(+)
-------------ttgtatctattggacctccctggtgctacaggggttaaagtctcagc
actgggcCTTCC---TCCCGT-----GACGC-----A-GCAATTGGGCATTg---agcta
caaagctg-cccgcagcctctgctgcacc---ggttcaa----------------tc---
-c----ccagcag-----------cc-agcgagtg-----tcccacatggc-gt-acaga
cctctcctgcca--cgcct---gctgctcccctcagcagagtat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ctgctctgg--ctctggtgaattctct-caccctcc
cac-----acttctta-ctgtaccc-actgcttgt-----ataaat---aaataaaat--
-------aaatctt--------------------taaaaaata---aataaagtc-----
---tcagcactatc--aagctattgccagccactgtggcatg------
>NW023605083.1:81352974-81353332(-)
-------------ggttcttgtatgaat-aaataaataaatctttaaaaaaaaaaaaaaa
gtatgggcctcc---cctggt-----ggcgc-----aggcagttgaatgctg---ggcag
tgaagctg-cctgcagcctctgcagtgct---ggttcga----------------tc---
------ccggcag-----------cc-ggcaaggg-----tcccacatggc-gcgacaga
cctctcctgcca--tgccc---actgctcccctcagcagtgtat---ttc-gtc-agtct
gcctgtt-ctggtcc---------ccg--------ctctggtgaattctct-caccatcc
cac-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------taaaaaaaa---agtacaaca-----
---tTCATGGGACA--AGGTCGTCAAGTGGTTAAGGCGATGG------
>NW023602073.1:83732231-83732582(+)
--------------gttacctccgtaaa-aagttataaaattaaaaaagaaaaaagataa
aactagagcctc---cctggt-----ggcgc-----a-gcag-tgagcactg---ggctg
tgaagctg-cccacagcctctgcagcact---gattgga----------------tc---
-c----ccagcct-----------cc-agcaaagg-----tcccacatggc-ac-gcaga
cctctcttccca--caccc---gctgctcccctaagcagtgtac---ttc-atc-agtct
gcatgtt-ctgttcc---------ccg--------ctctggtggattctct-caccttcc
cac-----gcttctga-ttgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------tttttaaaa---aagataaaa-----
---cctgcAATACC--TGGAATCCAATAAAAAAAGTAT----------
>NW023605194.1:38353028-38353391(-)
-------------TCACGCATCAGATTG-GCAAAAATCAAAAAGCATGATAAGACCCTAC
ATTGGGGcgtcc---cctgat-----ggcgc-----aggcagttgagcgctg---ggctg
cgaagctg-ccctcagcctcggcagcgcc---agttcga----------------tc---
-c----ccggcag-----------ct-ggcgaggg-----tcccacatggc-gc-gcaga
cctctcctgtct--caccc---gctgctcccctcaacagtgtat---ttt-gtc-agtct
gcctgtt-ctgttcc---------ctgctctgg--ctctgg-aaattctct-cacccgcc
cgt-----acttctga-ctctaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------aaaaaaaaa---aaaagaccc-----
---tacATTACAGA--GGATTTGGGGAAAAGGTCCTCCCTTG------
>NW023601543.1:53314993-53315352(+)
-------------GAAGACTTCACATGT-AAATtgtaccaaaccttcaaagatgaactaa
tatcGGGCCTTT---Tttagt-----ggtgc-----a-gcagtttagagctg---ggctg
cagagctg-cccacagcctctgcagcacc---agtttta----------------tc---
-c----ccagcca-----------cc-agtgaggg-----tcccacatgga-gt-gcaga
cctctcctgctg--tgccc---gctgctcccctcagcagactat---ttc-att-ggtct
gcctgtt-atgttcc---------acactcttg--ctctggtgaattctat-cactctac
tgt-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------caatcat-------tccc---------caaaaaaga---tgaattaat-----
---atcTATCCTGC--CAAGACActttcaaaaaa--------------
>g4 Consensus of sequences 5-248
------------------------------------------------------------
-----GGGCCTC---CCTGGT-----GGCGC-----A-AGGGGTTAAGTCCC---CACTA
TGAAGCTA-TCCGCAGCCACTGCAGCAGA---GTTCGAT----------------CC---
-C----CCGGCCGGCC--------GC-AGCAGGGGAGCTACCCACAATGGC-GCAGCAGA
CCTCTCCTGTCT--CGCCC---GCTGCTCCCCTCAGCAGTGTAT---TTC-AGT-CATCT
GCCTGTT-CTG-TCC---------CCACTCTGT--CTCTGGTGAATCCTCT-CACCCCCC
CCCCCCCACCTCTGGC-CTGTACCC-CAGTCTTGT-----ATGCAT---AAAT-AAAAAA
TAAAAATAAATCTT--------------------TAAAA---------------------
------------------------------------------------
>g5 Consensus of sequences 6-121
------------------------------------------------------------
-----GGGCCTC---CCTGGT-----GGCGC-----A-GGGTTGAGTCGCAG---CGCTG
TGAAGCTG-TCCGCAGCCTCTGCAGCGC----GGTTCGA----------------TC---
-C----CCGGCCG-----------GC-CG-GAGAC-----CCACATATGGC-GC-GCAGA
CCTCTCCTGTCT--CGCCC---GCTGCTCCCCTCAGCAGTGTAT---TTC-AGT-CGTCT
GCCTGTT-CTGTCCC---------C--CTCTGT--CTCTGGTGAATCCTCT-CACCCCCT
CCC-----GCCTCTGGCCTGTACCC-CGTTCTTGT-----ATATAA---ATAT-AAAT--
-------AAATAAA--------------------AATAAATCT---TTAAAA--------
------------------------------------------------
>g6 Consensus of sequences 7-30
------------------------------------------------------------
-----GGGCCTC---CCTGGT-----GGCCT-----A-GGGGTTAAGTCTCAG--CGCTA
TACAAGCT-TCCGCAGCCACTG--GCCTG---AGTTCGA----------------TC---
-C----CCGCCGCC-------ACGGG-AGCTAAAC-----CCACATATGGC-CA-GCAGA
CCTCTCCTGTCT--CGCCC---GCTGCTCCCCTCAGCAGTGTAT---TTC-AGT-AATCT
GCCTGTT-CTGCTCC---------CCACTCTGT--CTCTGGTGAATCCTCT-CACCCCCC
CCCCCCTCACCTCTGGCCTACACCCCAGTTCTTCT-----ATG---C--AAAA-TAAA--
-------AAATAAA--------------------TAAAAAATA-----------------
------------------------------------------------
>NW023604295.1:95627436-95627806(-)
--------------GTAGAGTGAGGTTT-TTAGGGTTATATTAGAAATACATTATAGTTT
GTCAgggggctc---cccagt-----ggtgc-----a-gcggttgagcgctg---ggctg
caaagctg-cccgcagcctctgcagcacg---ggttcga----------------tc---
-c----ctggccac-------------ggcgaggg-----tcccacatggt-gc-gtaga
tctctcctgcca--caccc---gctgctcctctcagcagtgtac---ttc-att-agtct
gcctgtt-ctgccccccacccccgccgctctgg--ctctggtggattctct-caccctcc
cac-----gcttctga-ctgtaccc-agtgcttgt-----atgaat---aaat-aaat--
-------aaatctt--------------------taaaaaaaa---aaagaaata-----
---cattatagTTT--GTCAAAGTGAAAGTTAGCAGATCAGC------
>NW023604972.1:94486383-94486748(+)
-------------GCCCCATAAAGAGCT-GCAGGGagaaatttttgcttaaaaaatgttt
tgtagggcctcc---ccctga-----ggtgc-----a-gcagttgagcacta---gactg
cgaagctg-cccgcagcctctgcagtgccggtggttcaa----------------tc---
-c----ccggcca-----------cc-agcgaggg-----tcccacatggc-gc-gcaga
cctctcctgc----cgcct---gctgctcccctcagcagtgtat---ttcagtc-agtct
gcctttt-ctgttcc---------atgctctgg--ctctggtgaatcctct-caccctcc
cac-----gcttctga-ctgtaccc-agtgcttgt-----acaaat---aaat-aaat--
-------aaatctt--------------------taaaaaaaa---atgttttat-----
---aaccAAAGGCA--TGGTGTGTTCAAGGTCATGATCATAG------
>NW023603184.1:69104083-69104451(+)
-------------GACTACATGCTCTCT-TCCCGCAGCACTTTCATAAAAACAGCtatgg
tatagggcctccccgcctggt-----ggcgc-----a-atggttgagcactg---agcag
caaagctg-cccgcagcctctgcagcgtc---ggttcga----------------tc---
------ccggccg-----------ac-ggcgaggg-----tcccacatggt-gc-acaga
cctctcctgctg--agccc---actgctcccctcagcaatgtatttcttt-gtc-agtct
gcctgtt-ctgcaac---------ccgctctgg--ctctggtgaattctct-caccctcc
cgt-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------taaaaaaac---gaGATTAAA-----
---AAAACAGCTAT--GGTATATTGGGTTATATTAATTTACA------
>NW023605083.1:96164795-96165162(+)
-------------tatggaaagctgtct-ggaggttcctcagtctactaaaaatagagct
accagggcctcc---cctggt-----ggcac-----a-gcggttgaacact----gactg
caaagctg-cccgcagcctctgcagcgct---ggttctttcc----------ctttc---
-c----ccggcca-----------ct-ggcgaggg-----tcccacatggc-ac-acaga
catcttctgtct--caccc---gctgctcccctcagcagtgtat---ttc-gtc-agtct
gcctgtt-ctgtt-c---------ccactctgg--ctctggtgaattctct-caccctcc
cgc-----ccttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------aaaaaaaaa---tggagctac-----
---cgtgcaacctg--gcaattccactactagggatctaccc------
>NW023604861.1:31707929-31708293(+)
------------TATATTCATTTTTGAT-GGTTTTGTTCACtgcacagaaactttttagt
ctggggccttcc---cctggt-----ggtgc-----a-gcagttgaacgctg---ggctg
tgaagctg-cccgcatcctctgcagcacc---ggttcca----------------tc---
-a----tCGGCCA-----------CC-Agcttggg-----tcccacatggt-gt-gcaga
cctctcctgccg--cgtcc---gctgct-ccctcagcagtgtat---ttc-atc-agtct
gcctgtt-ctgttcc---------ccgcgctgt--ttctggtgaattttct-ctccctcc
cgc-----acttttga-ctgtaccc-agtgcttgt-----ataactg--aaat-aaat--
-------aaatcct--------------------taaaaaaat---ttaaaaaat-----
---taaaaaaaaga--aacattttagtcTGATCTAATTCtgc------
>NW023605305.1:76862440-76862794(-)
-------------AAACAGATGTGAGCG-AGAGctccatggggaggttaacaatgaaAGT
Gtttgggcatcc---cctggt-----ggctc-----a-gtggttgagcgctg---ggctg
cgaagctg-cccgcagcctctgcagcacg---ggttcgg----------------tT---
-C----CCggcaa-----------cc-agcgaggg-----tcccacatggc---ggcaga
cctctcctgtcg--cttct---gcagctcccctcagcagtgtat---ttc-gtc-agtct
gcctgttcctgttct---------ccactctgg--ctctggtgaattctct-cacgctcc
cgc-----gcttctga-ctataccc-agtgcttgt-----attaaa---aaaa-aaaa--
-------aaaagga--------------------------------agtgtttat-----
---cttaattttga--ttttgctcctttccttccagactcgt------
>NW023601212.1:70156590-70156957(-)
-------------GAGAGGTTCTTAGAA-AGAGAGCcatttttaaagcttaaaaatcatt
tcaagggcctcc---catggt-----ggcgc-----a-gcagttgagccctg---ggttg
cgaagctg-cccacagcctctgcagcgcc---agtttga----------------tt---
-c----ccagtcg----------cCC-GGCAAGTG-----TCCCGCatggc-g--acaga
cctctcctgccg--ggcct---gctgctcccctcagcagtgtat---ttc-gtc-agtct
gcctgtt-ctattcc---------ccactctgg--ctctggtgaattctct-cacactcc
cgt-----gcttctga-ctgtaccc-agtgcttgatt--aataaata--aaat-aaat--
-------aaatctt--------------------taaaaaaaa---aaatcattt-----
---caaaattattc--ttcTAGTtatactaccaaaaaaaaaa------
>NW023605083.1:103533752-103534121(-)
-------------GTTATCCAAGAAATG-TAAAACtgtttcaacattaaaaaaatcaata
aatggggcctcc---cctggt-----ggccccattga-gccgttgagtgctg---ggatg
cgaagctg-ccggcagcctctgcagcgcc---agtttga----------------tc---
-c----ccggccg-----------cc-ggtgaagg-----tcccacatggt-gcaacaga
gctctcctgttg--caccc---gccgcacccctcaacagtgtgt---ttc-gtc-agtct
gcctgtt-ctgttct---------ccattctag--ctctggtgaattccct-catcctcc
tgt-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-gaat--
-------aaatctt--------------------tttaaaaaa---tcaataaat-----
---gcacccctatg--tttatagcagcactgtttacaatagc------
>NW023605194.1:58900551-58900897(+)
-------------TAATTGATGCAGAAC-AGgacattttcatgtttttaaagaatctccc
tatagggcctcc---cctggt-----ggcgc-----a-gtggctgaaccctg---ggctg
caaaactg-cttgcagcctctgcagcg---------------------------------
------cggccga-----------tg-ggcgaggg-----tcccacatggt-gc-accta
CCTCTcc-gccg--tgccc---gctgctcccctcagcagtgtat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ctgctctgg--ccctggtgacttctct-caccctcc
cgc-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-------
-------aaatctt--------------------taaaaaaaa---aaaaagaat-----
---ctctctATAGA--CAGCCTTTTACTagtaaggggaaaaa------
>NW023605083.1:52455316-52455671(+)
-------------aaagaaaaaaaatca-ccaaagaaACAATATGCCTATAAAATGgatc
atcagggcctcc---cctgat-----ggcac-----a-gcggttgagcgctg---ggctg
caaagctg-ccctcagcctctgcagcgcc---ggttcga----------------tc---
-c----ccggcca-----------ctgggcaaggg-----tcccacatggc-gtgacaga
cctctcctgc----cgccc---gctgctcccctcagcagggtatt------gtc-agtct
gcctgta-ctgtttc---------catctctgg--ctctggtgaattctct-caccctcc
cac-----gcttctgt-ctATACCc-agt-----------ataagt---aaat-aaat--
-------caatctt--------------------taaaaaaaa---aaaaaaaag-----
---attatcagaCA--CTGAGATGGAACAGCTCCTCATTCCT------
>NW023604295.1:135333825-135334178(+)
---------------tATGTTTAACAAT-GTTTCTTGTGAATATAGCCATAAGAATAATA
GTgcttggcctc---cccggt-----ggcac-----a-gcggttgagcactg---ggttg
caaagctg-cccacagcctctgcagtgcc---ggtttga----------------tc---
-c----ccagcct-----------ctgggcgaggg-----tcccacatggt-gcgacaga
tctctcctgc----tgcct---gctgcttccctcagcagtgtac---ttt-gtt-agtcT
AC----------------------CTGCTCTca--ctgtggtgaattctct-cactctcc
cgc-----tcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaata-
----aataaatctt--------------------aaaaaaaaa---tagtgcttg-----
---TGGAATTTGAA--GACTTTACCCTTTGTTAAGAATAGAT------
>NW023605305.1:73673811-73674180(+)
--------------AATTTTAGTAGTGT-TTCAGAGAGGTAAATGtgtataaaatttaag
attttgggcctc---cccagt-----ggcgc-----aggcggttaagcgctg---cgctg
tgatgctg-tctgcagcctctgcagcgcc---ggttgga----------------tc---
-c----cggccag-----------tg-ggcttggg-----tcccacatggc-gcagcaga
cctctcctgtgg--tgctc---gctgctcccctcaacagtgtat---ttc-atc-agtct
gcctgtt-gtgttcc---------ccactctgt--ctctggtgaatcttct-caccctcc
cac-----gtatctggcctataccccggttcttgt-----ataaataaaacat-aaat--
-------aaatctt--------------------taaaaaaaa---ttaagatag-----
---atTTCAGTAGT--GTGACTGGCTCTTGCAATGCAATGAT------
>NW026555331.1:136720392-136720751(+)
-------------CTTCCCTTACATTAT-TATTGGTAAATTGCTGGCAAAGATAgacatt
tttagggcctcc---cctggt-----ggcgc-----aggtggtcgaccacca---cactg
taaagctg-cccacagcctctgcagcgcc---agttcga----------------tc---
-c----tggcagg-----------cc-agcgaggg-----tcccacatggc-acagcaga
cctctcctgtct--cgccc---gctgctcccctcagcagtgtat---ttt-gtc-agtct
gcctgtt-ctgttcc---------ccactctgt--ctctggtgaatcctct-caccttcc
cac-----gcatctggcctataccccagttcttgt-----ataaat---aaat-aaata-
----tataaatctt--------------------ttttaaaaa---aaaagatag-----
-acactTTTAGAAA--TAACAGAGGCAA--------------------
>NW023604295.1:131503669-131504036(+)
--------------GGCAATGTTTCACC-TTCATGTATAATCTTTTAAGAGAAGAGATAC
ttgagggccctc---cctggt-----ggcgc-----aggcgattgagctcca---cactg
tgaagctg-tctgcagcctctgcagcgct---ggctgga----------------tc---
-c----cggctgg-----------cc-agtgaggg-----tcccacatggc-acggcaga
cctctcctgtca--caccc---actgctcccctcagcagtgtat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ccgctgtag--ctctggtgaatcctct-caccttcc
tgc-----gcatctggcctatacccctgttcttgt-----ataaat---gaat-aaata-
-------aaatctt--------------------taaaaaaaa---aaaaaagag-----
---agtagagATAC--TTGAAAGTGTTAGCCAGTAGCCACCC------
>NW023601104.1:11346379-11346741(-)
-------------catataaattttgga-atttcaagtttttcacataaaaagctatcaa
tattgggcctcc---cctggt-----ggcac-----aggtggttgagcacca---tgctg
tgaagtgg-tccacagcctctgcagagcc---agttca-----------------tc---
-t----caaccgg-----------cc-ggcaaggg-----tcccacatggt-gcggcaga
cctctcctgtct--cgccc---gctgctcccctcagcaatgtat---ttt-gtc-agtct
gcctgtg-ctattcc---------ccactctgt--ctctggtgaatcctct-caccctcc
cgc-----acatctggcctgtaccccagttcttgt-----ataaat---aaat-aaat--
-------aaatctt--------------------tttttaaaa---aagctatca-----
---------------aTATTTTGGTTAGAACTAAAATGAAATGATGgg
>NW023603184.1:4512069-4512437(+)
-------------AGCATATTTGAAAGG-AGAACTTCCTCCTCAACAGAATAGtcagaaa
aagagggcctcc---cctggt-----ggtgc-----aggcagttgagcgctg---tgctg
tgaagctg-cccacagcctctgcagcacc---ggttcga----------------tc---
-c----cggccgg-----------ct-ggcgaggg-----tcccacatggc-gtggcgga
cctctcctgtct--cgtcc---cctgctcccctcagcagtgtat---ttc-atc-agtct
gcatgtt-ctgttcc---------ccgctctgt--ctttggtgaatcctct-cactctgc
tgt-----gcatctggcctgtaccccggttctcgt-----ataaat---aaat-aaatt-
-------aaatctt--------------------taaaaaaaa---aaaaagaat-----
---agtcagaaaaa--gaaagtggaCAGTTACACTCACTGAA------
>NW026555331.1:87128452-87128820(+)
-------------AAGTGTTAGAATATA-AAAGAACAATCCTCTGTTCAAAAAATAgaca
actggggcctcc---cctggt-----ggcgc-----aggtggttgagcgccg---cgctg
tgaagctg-tctgcagcctctgcaccgcc---agttcga----------------tc---
-c----cagccag-----------cc-ggcgagga-----taccacatggc-gtggcaga
cctctcttgtct--ctccc---actgctcccctcagcagtgtat---ttc-gtc-agtct
gcttgtt-cggctcc---------ccgctctgt--ctctggtgaatactct-caccctcc
cgc-----gtccctggcctgtaccccggttcttgt-----ataaaat--aaat-aaat--
-------gaatctt--------------------taaaaaaaa---ttgacaact-----
---gGTTCTAGACA--TAAATTCATTCAATAATCAATCCATT------
>NW023604861.1:62643555-62643931(+)
-------------tactctaataccaaa-actggataaagaaaagacataaaGCGAAAAC
TAtagggccttc---tctggt-----ggcac-----aggaggttgagcactg---tgctg
tgaagctg-acagcagcctctgcagtact---ggtttga----------------tcctg
gc----tggctgg-----------ct-ggcgaggg-----tcccacatggc-gcagcaga
cctctcctgtct--tgcct---gctgctcccctcagcagtacat---ttc-gtc-agcct
gcctgtt-ctgcttc---------ccactctgt--ctctggtgaatcctct-caccctcc
tgt-----gcatctggcctgtaccccggttcctgtatgaaataaat---aaat-aaat--
-------aaatctt--------------------ttaaaaaat---gaaaactat-----
---aaaccaataat--ttctctgatgaacataaatgtaaaaa------
>NW023604295.1:99779749-99780116(+)
-------------TCATAAAACTGTTAA-ACAttccacatggaaaaaaaaagtatataga
ttTTGGGCCTac---catggt-----ggcac-----aggcggttcagcactg---cgctg
tgaagctg-cctgcagcctctctagcatc---tgttcga----------------tc---
-c----tggccag-----------ct-ggcaagag-----tcccacatggc-gaggcaga
cctctcctgtcg--cgccc---actgctcccctcagcagtgtat---ttc-atc-agtct
gcctgtt-ctgttcc---------ccactctgt--ctctggtgaatcctct-caccctcc
tgc-----acatctggcctgtaccctggttctggt-----ataaat---aaat-aaat--
-------aaatctt--------------------aaaaaaaag---tatatagat-----
---tTAAGTGAAAG--TTTCCAGCTTAGAAAGAGATGTATAG------
>NW023601433.1:53074635-53075001(+)
-------------AAAGTAAGGTAAACC-CAATCATATATAAATTGGCATAAAAATTTCT
gattgggcctcc---tctggt-----ggcac-----aggtggttgagcgctg---cgctg
tgaagctg-tctgcagcctctgcagcacc---ggttcca----------------tc---
-c----cagccta-----------cc-ggtgaggg-----tcccacacgga-gcggcaga
cctctcctgtct--cgcct---gctgctcccctgagcagtgtat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ccgctctgt--ctctggtgaatcgtct-caccctcc
cgc-----atatttggcctgtacccaggttcttgt-----ataaat---aaaa-aaa---
-------aaatctt--------------------taaaaaaaa---tccctgatt-----
---gggcctccccg--gtggcgcagcggttgagcgctgggtt------
>NW023602073.1:59749462-59749828(-)
-------------GTCAAGAGTCAAACA-GGGATAAAATGTGCAAATCAAAATTTCCCCT
Tcagggtcctcc---cctggt-----ggtgc-----aggcggttgagcacag---cgctg
tgaagctg-tccgcagtttctgcagtgcc---agttcga----------------tc---
-c----tggccag-----------cc-ggtgaggg-----tcccacatggt-gcggcaga
cctctcctgtca--caccc---gctgctcccctcagcagtgtat---ttt-gtc-agtct
gcctgtt-ttgttcc---------ccgcactgt--ctctggtgaatcctct-cacgctcc
cgc-----acatctggtctgtatcccggttcttgt-----ataaat---aaa--aaat--
-------aaatctt--------------------taaaaaaaa---aatttcccc-----
---ttcaGTTTCAC--TCTCCAGGCAGAACCGCTGTGACCTT------
>NW023604829.1:28368-28736(+)
--------------AAATACCCTACCAG-CTGGGATTTTATTGCTATTTAAGTTTGAGCA
GTttaggccttc---cctggt-----ggcac-----aggcagttgagcatca---cgctg
tgaagctgtcccgcagcctctgcagtgcc---ggttcga----------------tt---
-c----tggccag-----------cc-agcgaggg-----tcccacatggc-atgacaga
cctctcctgtca--cgccc---gctgctcccctcagcagtgcat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ccgttctgt--ctctggtgaatcctct-cacccttc
cgc-----gcatctgacctgtaccccagttcttgt-----ataaaa---taaa-aataa-
-------aaatctt--------------------aaaaaaaat---aataaaagt-----
---tagagCAGTTT--AAACACTTGGCACGTACGCATCagac------
>NW026555331.1:87506850-87507212(+)
-------------gggaggccctggaaa-cttGAGGGTCTTTGACCTCAGAATCTCCTGA
GTTCGgacctcc---cccggt-----ggtgc-----aggcggttaagcgcca---tgctg
tgaagctg-tcagcagcctctgcagtgtg---ggttcga----------------tc---
-c----tggctgg-----------cc-agggaggg-----tcccacatggc-acagcaga
cctctcctgtct--cacct---gctgctcccctcagcagtgtat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ccgctctgt--ctctggtgaattctct-------cc
cac-----acatctggcctttaccctggttcttgt-----ataact---aaat-aaat--
-------aaaatct--------------------taaaaaaaa---aaaaaaaaa-----
---gaatctcctgA--TTCTGTATTTTGCCCTGAATCTGGAAT-----
>NW023601543.1:29624612-29624966(+)
-------------GAATACAAAATGTTA-AAGCATCAATAATAGTCCAAACAAAAGTCat
agtcgggcctcc---cctggt-----ggcgc-----aggcagttgagc------------
----gctg-tccacagcctctgcaggtcc---agttcga----------------tc---
-c----tggccgg-----------ct-ggcgaggg-----tgccacatggc-aaggcaga
cctatcctgtct--ctccc---gctgctcccctcagcagtgtat---ttc-gtc-aatct
gcctgtt-ctgttcc---------cctctctgt--ctctggtgaatcctct-cactctcc
ctc-----gcatctggcctgtaccccagttcttgt-----ataaat---aaat-aaag--
-------aaatctt--------------------taaaaaaag---tcatagtCA-----
---TCCTTCATCAG--TTCATTCAATACTACATAATTAATCG------
>NW023604861.1:86454691-86455053(-)
-------------tgTCTACAATTGAAT-ACTGCTCAGCTgcctattaaaaaagatgaag
tcttgggcctcc---cctggt-----ggcac-----aggcggttgaacgcca---cactg
tgaagctg-tccacagcctcagcagcgcc---agtttga----------------tc---
-c----tggcagg----------ccc-agcaaggg-----tcccacaag------gcaga
cctctcccgtct--cacct---gctgctcccctcagcagtatat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ctgctctgt--ctccgatgaatcctct-caccctcc
cat-----gtgtctggcctgtaccctggttcttgt-----ataaat---aaa--aaat--
-------aaatctt--------------------taaaaaaaa---aataaaaga-----
---tgaagtcttgc--cttttggggcaacatggatggaactt------
>NW023602073.1:41593650-41594011(-)
--------------tatatctcagtcag-ctcctgacattagatagaagcttaagaagtt
tgagaggactcc---cctgat-----ggcgc-----agatggCAAAGCGCCG---CTCTG
TGAGTctc-tccgaggcctctgcagtgcc---ggttcca----------------tg---
-c----cgcccgg-----------cc-agcgaggg-----tcccacatggc-acagca-a
cctctcctgcct--cgccc---gctactcccttcagcagtgtat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ccactctgt--ctctagtgaatcctct-caccctcc
cac-----gtatctggcctggaccccggttctagt-----gtaaat---gaat-aaat--
-------aaatcttttttttttttt---------ttaaagaagcctgaggactgtcctca
aacccctatccagg----------------------------------
>NW023605083.1:53477556-53477915(-)
-------------ATGCCCTTGTCAACA-CTACACATAATCACATCTTAAAAATCTTTGc
ttacgggcctcc---cctggt-----ggtgc-----a-gcggttgagcactg---ggctg
tgaagctg-ccggcaacctctgcagcacc---gattcta----------------tc---
-c----ccggcca-----------cc-ggcgaggg-----tcccacctggc-tggacaga
cctttcctgtct--cgccc---gttgctcccctcagcagtgtgt---ttc-gtc-agt--
--ctgtt-ctgttcc---------ccgctctgt--ctctggtgaattctct-caccctcc
cac-----acatctggcctgtaccccggttctcgt-----ata------aaat-aaat--
-------aaatctt--------------------aaaaaaaaa---aaatctttg-----
---cttacCTGcta--ggtttaaaaaaagaattgtttttgtt------
>NW023604972.1:77336706-77337074(+)
--------------ttatacaactcaac-ataaagaaaacaaacaacccaatcaaaaaat
aggcagggcctc---tctggt-----ggtgc-----a-gcagttgagccctgggtggcag
caaagctg-cccgcagcctctgcagcgct---ggttcga----------------tc---
-c----ctggctggc------cagcc-agcaaggg-----tccaacgtggc----gcgga
cctctcctgtct--tgcct---gctgctcccctcagcagtgtat---ttc-gtc-agtct
gcgtgtt-ctgttcc---------ctgctctgg--ctctggtgaattctct-caccctcc
cac-----gcttctga-ctgtaccc-agtacttgt-----ataaat---aaat-aaat--
-------taattta--------------------aaaaaatgg---gcagaagaa-----
---ccaaatggaca--cttctccaaagaacatgcagatggcc------
>NW023601754.1:43668576-43668937(-)
-------------ataaatctttaaaaa-aaaaaacaaacaaaaaaacccaaaaagctcA
CAAAGGGCCTAC---CCTaga-----ggcgc-----a-gtggttgagtgatt---aa--a
aaaatctg-cccgcagcccctgcagggcc---agttcga----------------tc---
-c----ctggcca-----------cc-agcgaggg-----tcccacatggt-gcgaaaga
cctctcctgctg--cgccc---actgctcccctcagcagtgtat---ttc--tt-tgtct
gtctgtt-ctgttcc---------ccgctctgg--ctctggtgaaatctct-caccctcc
cac-----acttctga-ctgtaccc-agtgctttt-----ataaat---aaat-aaat--
-------aaatctt--------------------aaaaaaaaa---aaaaaaaaa-----
---agctcacaaag--cctggaatcatatagtatggaAGTTT------
>NW026555331.1:121230024-121230381(+)
---------------catacacatatat-gaattatatatttaaataaaaatatacatgg
gTGGTTggtctc---ccctgt-----ggcgc-----a-gtggttgagccctg---ggttg
tgaagctg-cctgcagtctctgcagt------ggttcga----------------tc---
-c----ccggctg-----------cc-agcgaggg-----tcccacatggt-accacaga
cgtctcctgccg--caccc---gctgctcccttcagcagtgtac---ttc-gtc-agtct
gcctatt-ctgttcc---------cccctctag--ctctggtgaattctct-caccctcc
cgt-----gcttctga-ctctaccc-agt-cttgt-----atgaat---aaat-aaat--
-------atctttt--------------------aaaatatat---atatacatg-----
---ggCAGCTTTAG--GCTATTAACTAGCTCAAATGGCCTA-------
>NW023601653.1:19254402-19254742(+)
-------------GCTCAGTGTGTTTGT-GTACTTATGGAAGTGGGTGAAAAAATTGGTt
ctgcgggcctcc---cctggt-----ggcgc-----a-gcggttgagcgctg---ggctg
cgaagctg-cctgcagcctctgcagcacg---ggttcaa----------------tc---
-c----------------------cc-gacgAGGG-----CCCCATATGGC-ATGACATA
cccctcctgctg--cgccc---actgctc---------gtgtat---ttc-gtc-agtct
gcctgtt-ctgttcc---------ccgctctgg--ctctggtgaattctct-caccctcc
cgc-----gctactga-ctgtaccc-agtgcttgt-----ataaat--------------
-------aaatctt--------------------taaaaaaaa---attggttct-----
---gAATCTTGGGC--TGAATCAAAACAGAGTTGAGAAAAAA------
>NW023604295.1:130706313-130706671(-)
--------------Cccttcattttaca-aaagcacgaatacataatttaaaaatcaacc
aaactgggcctc---cccagt-----ggtgc-----a-gcggttgagcactg---ggctg
cgaggctg-cctgc-------ccTGCGct---gtttcaa----------------tc---
-c----ccggctg-----------ccgggcgaggg-----tcctacatggt-gcagcaga
cctctcctgccg--cgccc---gctgctcccctcagcagtgtat-----c-gtc-aggct
gcctgtt-ctgttcc---------cc-ctctgg--ctctggtgaattctct-caccctcc
cgc-----gcttctga-ctgtaccc-agtgcttgt-----ataaat---aaat-aaaaa-
----aataaatctt--------------------taaaaaaaa---atcaaccaa-----
---actGATGCTAT--TTATACTAATTTGGTAAGTTAATATA------
>NW023605194.1:103329279-103329628(-)
-------------aaaaaatgtctattt-tttttaagaaaacagctataaaaacatgtat
ttgggggcctcc---cctggt-----ggtgc-----a-gtggttggggtgtg---ggctg
tgaag------------ctctgcagcgtt---ggttcga----------------tc---
-c----ctggcca-----------cc-agtgaggg-----tcccacatggt-gcgacaga
cctctcctgctg--ctccc---gctgctcccctcagcagtgtat---ttc-atc-agtct
gcctgtt-gcgttcc---------ctgctccgg--ctctggtgaattctct-caccct-c
agc-----acttctga-ctgtaccc-agtgctggt-----ataaat---aaaa-------
------taaataat--------------------taaaaaatg---tatttggaa-----
---cTGCAATTGAA--ACTACAAGCAAGTAACAACAGACGTC------
>NW023601322.1:45639550-45639919(+)
--------------ACTCCCTCAGGTCA-CATTTCctcaggactctgaggagaaaataca
actggggacccc---cctggt-----ggagc-----aggtggttgagcacca---cgctg
tgaggctg-tccgcagcctct-cagcacc---ggttgga----------------tc---
-c----tggccctggc-----cagcc-ggtgaggg-----tcccacatgt--ggggcaga
cctctcctgtcg--caccc---gctgctcccctcagcagtgtat---ttc-gtc-agtgt
acCTGAT-CAGTTca---------ccg--ctgt--ctctggtgaatcctct-caccctcc
tgc-----gcaactggcctgtaccccagttcgtgt-----ataaaat--aaat-agat--
-------aaatctt--------------------taaaaagaa---aacacaact-----
---gaCCGTTCAAG--TCACACACCTTGACATCATCTGTGGC------
>NW023601754.1:50690247-50690617(+)
CTCTGGCGTCTGT----------------GAAGGTCTTGGCAGGGCGGGCCTCAGCTCCT
GCGCGAGGTCCT---CCGGGC-----CGGGC-----T-GAGTGTACCCGGTG---GGCTT
TCCACACG-CTTTCCTCGCGGTCGGCCCT---GGCTCTGGACAG-----------CC---
-C----GGGACTC-----------AC-AGGGCGGC-----CTCCGCACC---CGaccaga
cctctcccgccgcccgccc---gctgc-cccctcagcagtgtcc---tcg-gtc-cccct
gcctgct-ctgcgcc---------ccgctctgg--ctctgggggatcctct-ccccctcc
cgc-----gcttctga-ctgtaccc-cgtgcttgt-----agaaac---aaat-aaata-
----aataaatctt--------------------aaaaaaaaa---atggactag-----
---gCAGGAGGCCC--GCCGGTCCGCCTCCATTGCTGCGTCT------
