>g1 Consensus of sequences 2-71
----------------------------------------------------GGGCCTCC
CCG--GTG-----GCGCA-GCGGTTGA-------G-CGCTGGG-TTGCGAAG----CTGC
CCGC----AGCCTCTGCAGCGC-CGGTTCGATCCCC-GGC-TG-----CTCCCCGGCC--
ACCGGAG---GAGGG--TCCCAC-A-TGGC--GCAGCAGA----CCTCTCCTGC------
------------------------------CGC------------CCGCTGCTCCCC-TC
AGCA------GTGTACTTCGGTCCTTCTGCCTG----------------------CTCTG
CTCCCCGCTCTGGCTCTGGTGAATTCTCTCA-------------------CCCTCCCGCG
CTTCTGAC---TGTA--------------CCCAGTGCTTGTAT--ATAAAAA---TAAAA
A---------ATCAATCAATAA--TAAAAAATA-AATAAAATAAAT-AAATAAATATAAT
AAATCTTTAAAA------------
>g2 Consensus of sequences 3-49
----------------------------------------------------GGGCCTCC
CCG--GTG-----GCGCA-GCGGTTGA-------G-CGCTGGG-TTGCGAAG----CTGC
CCGC----GGCCTCTGCGGCGC-CGGTTCGATCCCC-GGC-TG-----CTCCCCGGCC--
ACCGGAG---GAGGG--TCCCAC-A-TGGC--GC-GCAGA----CCTCTCCTGC------
------------------------------CGC------------CCGCTGCTCCCC-TC
AGCA------GTGTACTTCGGTCCTTCTGCCTG----------------------CTCTG
CTCCCCGCTCTGGCTCTGGTGAATTCTCTCA-------------------CCCTCCCGCG
CTTCTGAC---TGTA--------------CCCAGTGCATGTATAAACAAAAA---CAAAC
A---------AACAAACACAAA--AAATAAATA-AATAAAAAACAT-GCCTCTATAAAA-
------------------------
>g3 Consensus of sequences 4-102
--------------------------------------------------------GGCC
CCG--GTG-----GCGCA-GCGGTTGA-------G-CGCTGGG-CTGCGAAG----CTGC
CCGC----AGCCTCTGCAGCGC-CGGTTCGATCCTC-CCC-GGCCGCCCTCCCCGGCC--
ACCGGGC---GAGGG--TCCCAC-A-TGGC--GCGACAGA----CCTCTCCTGCCG----
------------------------------CGC------------CCGCTGCTCCCC-TC
AGCA------GTGTA-TTCGGTCAGTCTGCCTG----------------------TTCTG
-TCCCCGCTCTGGCTCTGGTGAATTCTCTCA-------------------CCCTCCCGCG
CTTCTGAC---TGTA--------------CCCAGTGCTTGTAT--AAATAAA---TAAAT
A---------AATAAATCTTTA--AAA---------------------------------
------------------------
>NW023604295.1:92937815-92938177(-)
--GGGTGAGGTGTTAAGTTATTGTGGCTTTTCCCTTATAAAAGTGATgaacagggactcc
ctg--gtg-----gcacagcggtttga-------g-tgcagca-ctatgaag----ctgt
ccac----agtctctgaaTCAC-AGGTTCaatctca--gc-t------------------
ggccagg---gagat--acccac-a-tggc--gcagcaga----cctctcctgtct----
------------------------------cgc------------ccgctgctcccc-tc
agca------gtgt-tttcggtctgtctgcctg----------------------ttctg
ctccccagtctgtctctggtgaattctctcac------------------cctcctgcac
ttctggcc---tgtac-------------cccagttcttgtat--aaataaa---taaat
c-------------ttaaaaaa--aagtgatga-acattttcctCA-TGTGTCTGTAGGC
CATTgagtattttct---------
>g4 Consensus of sequences 5-248
----------------------------------------------------GGGCCTCC
CTG--GTG-----GCGCAAGGGGTTAA-------GTCCC--CA-CTATGAAG----CTAT
CCGC----AGCCACTGCAGCAG-AGTTCGATCCCCC-GGC-CG------------GCCGC
AGCAGGG---GAGCT--ACCCACAA-TGGC--GCAGCAGA----CCTCTCCTGTCT----
------------------------------CGC------------CCGCTGCTCCCC-TC
AGCA------GTGTATTTCAGTC-ATCTGCCTG----------------------TTCTG
-TCCCCACTCTGTCTCTGGTGAATCCTCTCACCCCC--------------CCCCCCCCAC
CTCTGGCC---TGTAC-------------CCCAG-TCTTGTAT--GCATAAA---TAAAA
AATAAAAATAAATCTTTAAAA---------------------------------------
------------------------
>g5 Consensus of sequences 6-121
----------------------------------------------------GGGCCTCC
CTG--GTG-----GCGCA--GGGTTGA-------GTCGCAGCG-CTGTGAAG----CTGT
CCGC----AGCCTCTGCAGCGC--GGTTCGATCCCC-GGC-C------------------
GGCCGGAG---------ACCCACATATGGC--GC-GCAGA----CCTCTCCTGTCT----
------------------------------CGC------------CCGCTGCTCCCC-TC
AGCA------GTGTATTTCAGTC-GTCTGCCTG----------------------TTCTG
TCCCC--CTCTGTCTCTGGTGAATCCTCTCAC------------------CCCCTCCCGC
CTCTGGCC---TGTAC-------------CCC-GTTCTTGTAT--ATAAATA---TAAAT
A---------AATAAAAATAAA--TCTTTAAAA---------------------------
------------------------
>NW023601212.1:37785569-37785936(+)
--AGAAGAAAAGGGGATGTTGGAatcctgtcatttaaaaaatatgtcactttgggcctcc
ctg--gtg-----gcacaaagtgttaa-------g-cactgca-ctatgaag----caat
ccgc----agcctctgcagcat-gagttcaatccct-ggc-t------------------
ggccaga---aagca--acccac-a-tggc--gcagcaga----cctctcctgtct----
------------------------------ttc------------cggctgctcccc-tc
agca------gtgtatttcagtcagtctgcctg----------------------ttctg
ctccccactctgtctctggtgtatcctttcacaccc--------------ccccccacat
ctctgttc---tgtac-------------cccagctc-tatat--gcataaa---taaat
g-------------tttaaaaa--ataaaaaat-atctcacttatt-tctgggcctccct
ggtggtgcaggggtt---------
>NW023601754.1:10625947-10626313(-)
--GACTCCATGTAAACTTTCCAAAAACACAatttccttaaaacatttttagagggcctcc
ctg--gtg-----gcgcaaggggctaa-------g-cccagca-ctatgaag----ctat
ccgc----agcctttaCAGCAG-GAGAtggatcccg-ggc-c------------------
agcca-----gagct--acccac-a-tggc--acagcaga----cctctcctgtct----
------------------------------agc------------cctctgctccccttc
agta------gtgtatttcagtcattctgcctg----------------------ttctg
ctccccactctgtctctggtgaatcctctcacccc---------------acccccgtac
ctctggcc---tgtac-------------cccagttcttgtat--gcataaa---taaat
c-------------tttaaaac--aattttttt-tagaattccaag-gattttattttta
ggaaaatctAACCAA---------
>NW023605194.1:45705628-45706006(-)
--ttattaacagatcattaaaaaaaaaaaagacttaaaagcatgaaagaacagggcctcc
ctg--cta-----gtacaaggggttga-------gtctcagcg-ctatgaag----ctat
ttcc----agtcattgcagcac-gagttcaattcac-----t------------------
ggccagg---gaggtg-acccac-a-tggc--acagcaga----cctctcctgtct----
------------------------------tgc------------ctgctgctccct-tc
agca------gtgtatttcagtagatctgcctg----------------------ttcta
gtccccactctatctctggtgaatcctctcacccagcctt------ctctgcccctgcac
ctctgacc---tacac-------------cccagctcttgtat--gcataaa---taaat
a---------aatctttaaaga--aaaagggcA-CATGAAAGAGCG-GTGTGTTAGTTCA
CTAGGGCAACTATA----------
>NW023605305.1:74602873-74603238(-)
--ccaagtatcttctctgaccataaaggtatcaaactagaaatcaactacaagggcctcc
ctg--gtg-----gtgcaagcagttaa-------gatgcagca-taatgaag----ctat
ctgc----tgccactgcagcat-gaatccgatccca------------------------
ggccagg---gaggtg-acccac-a-tggc--acagcaga----cctctcctgtct----
------------------------------ccc------------ccgctgctcctc-ta
agca------gtgtattttagtagatttgtctg----------------------ttctg
ctccccactctgtttctggtgaatcctctca-------------------ccccccgcat
ctctgacc---tacat-------------cccagctcttatat--gcataaa---taaat
a---------aatctttaaaaa--aaaaaaaaa-gaaaggaacccC-CCCATTACATGGA
GACTAAataacacac---------
>NW023601212.1:95948798-95949167(+)
--agatttagtggACACTCACCTTATCGATAAGGTAGGAATAGCcattgcaggggcctcc
ctg--gtg-----gcgcaagtggctaa-------gccgcagca-ctatgaag----ctat
ccac----cgccagtgcagcac-gagttcgatccca------------------------
tgccagg---gaggtg-acccac-a-tggc--gcagcagatctctctctcctgact----
------------------------------tgc------------ctactgctcccc-tc
agca------gtgtatttcagtacatctgcctg----------------------ttctg
ctccccactctttctctggggaatcctctca-------------------ccctccacat
ctctggcc---tatac-------------cccagctcttgtat--gcataaa---taaat
a---------aatctttaaaaa--aaaaaaaga-aatagccattGC-AAGGATTATAATG
GATCCGATACAGCCA---------
>NW023603184.1:138831584-138831949(+)
--GGCAGAGCCCTTGTGAATAAGAtgagtgcccttataaaagagggcccccagggcttcc
ctg--gtg-----acagaaggggttgg-------gtctcagca-ctgtgaag----ctat
ccgc----agccactgcagcaa-gagttcaatccct------------------------
gatcagg---gaggtg-acccat-a-tggc--gcagcaga----cctctcctgtct----
------------------------------tgc------------ctgctgctcccc-tc
aaca------gtgtatttcaataaatctgcctg----------------------ttctg
ctccccaccctgtctctggtgaatcctctta-------------------ctccctgcac
ctctggca---ttcac-------------cccagttcttgtat--gcataaa---cacgt
a---------aatcttaaaaaa--aataaaaat-aaaaaaggcccC-CAAGTGCTCTCAT
ATACCTCTTGCCATG---------
>NW023605083.1:123859881-123860247(+)
--CACTGTTGCAAAGGATTTGTTTGTATGTTACTGACCAGAAATaaacagtagggcctcc
ctg--gtg-----gctcaaggggttaa-------gacgcagta-ctatgaag----ctat
ctgc----agccactgcagcac-gagttcgatcctg------------------------
ggccagg---aaggtg-acccac-a-tggc--acggcaga----cctctcctggct----
------------------------------tgc------------ctgctgctcccc-tc
agca------gtgtatttcaatcaatctgcctg----------------------ttctt
ctccccactcta--tctggtgaatcctctcaccc----------------cccaccaaac
ctctggcc---tttac-------------accagttcttgtat--gcataaa---taaat
a---------aatcttaaaaaa--aaaaaaaga-aaagaaaaacag-tagaaGCACATGC
TGTATAGCAGGGCCA---------
>NW023601322.1:73006763-73007131(-)
--AATAGTTGCAAACCAGCTCCTGTACAGTCtcagataaaaataacaaaatggggccttc
ctg--gtg-----gtgcaaggggttaa-------atctcagca-ctatgaag----ctat
cctc----agacactgcagcat-gaatttgatcccc------------------------
ggccagc---gaggtg-acccac-a-tggc--gcagtaga----cctctcctgtct----
------------------------------cac------------ccgctgctcccc-tc
agca------gtgtatttcagtagatctgccta----------------------ttctg
ttccccactctgtctttggtgaatcctctcaccc----------------ccccccacac
ctctggcc---tgtac-------------cccagttcttgtat--gcataaa---taaat
a---------aatctttaaaaa--agataacaa-aatgcTCATGTA-CATGGAAAagaaa
gtctggaaagaaaag---------
>NW023604861.1:25871308-25871679(-)
--GTGTAAGCTGAATACTTCTTTAGTTACAAGACACAGAAATTCAAattgaggggccttc
ctg--gtg-----gcacaaggggttaa-------gtcacagca-ctgagaag----ctat
ctgc----aaacaatgcagcat-gagtttgatcccc-agc-c------------------
acccagg---gagcg--acccac-a-tggc--acagcaga----cctctcctgtct----
------------------------------cat------------tccctgttcccc-tc
agca------atgtacttcagtagatctgcctg----------------------ttctg
ttccctactctgtctctggtgaatcctctcatct----------------cctcccacac
ctctggcc---tatac-------------cccagttctcatat--gcataaa---taaat
a---------aatctttaaaaa--aaaaaccaa-cttgaAATAGAT-TAAGCAAAGTAAT
ATTTCTAAAGGGAGG---------
>NW023604972.1:91988912-91989277(-)
--AATCAGTCTCCAGCAGTTTGCTTCCAAGTTGAGCTCTGTTTAagagtcaggggcctcc
ctg--gtg-----gcgcaaggggttaa-------gacacagca-ctatgaag----ctat
cccc----agccactgcagcac-aagttcgatcccc------------------------
agccagg---gaggtg-acccac-a-tggc--gcagcaga----cctctcctgatt----
------------------------------cac------------ccactgctcccc-tc
agca------gtgtacttcagtcaatccaccta----------------------ttctg
ttccccactctttttctggtgaatcctctta-------------------ccccccacac
ctctggcc---tgtac-------------ccctattcttatat--gcataaa---tgaat
a---------aatattaaaaaa--aaagtcaat-cccCTGCTTTCT-GGTCTCAAGTATG
TGACCAGAAAGGCCA---------
>NW023604972.1:53790674-53791046(-)
--ATTCCCAAAGCACACTTCCATTGATTAATTTACAGAAAAGTGgtaggttagggcctcc
ctg--gtg-----gcacaaggggttaa-------gtcccagca-ctgtgaag----ctat
ctgc----agccactacagctcagagttccatccca------------------------
ggccagg---gagcta-acccac-a-tggt--gtagcaga----cctctcctgtct----
------------------------------cgc------------ccgctgctcccc-tc
agca------gtgtatttcggtcactctgtctg----------------------ttctg
ttccccactctgtctctggtgaatcctctcacccac-------------tctcctcccac
ctctgccc---tttac-------------catagctcttgtat--gcataaa---taaat
a---------aatctttaaaat--aaagaaatg-actgaataaatt-tTCTCATAATAAA
AAGCTGAGTAAGAAC---------
>g6 Consensus of sequences 7-30
----------------------------------------------------GGGCCTCC
CTG--GTG-----GCCTAGGGGTTAAGT--------CTCAGCG-CTATACAA----GCTT
CCGC----AGCCACTG--GCCT-GAGTTCGATCCCC-GCCGC------------------
CACGGGA---GCTAA--ACCCAC-ATATGG--CCAGCAGA----CCTCTCCTGTCT----
------------------------------CGC------------CCGCTGCTCCCC-TC
AGCA------GTGTATTTCAGT-AATCTGCCTG----------------------TTCTG
CTCCCCACTCTGTCTCTGGTGAATCCTCTCACCCCC-------------CCCCCCCTCAC
CTCTGGCC---TACAC-------------CCCAGTTCTTCTAT--GCAAAAT---AAAAA
A---------TAAATAAAAAAT--------------------------------------
-----------------------A
>NW023604972.1:88181713-88182081(-)
--TTATTATTAGTTTCAATAATGCtgtgacttcattttttaaagagcaggtagggcctcc
ctg--gtg-----gcacaaggagttaa-------gtctcagca-caatgaag----ctat
ccac----agccactgcagcat-gagtttgatcccc------------------------
ggccagg---gagatg-acccat-a-tggc--ccagcaga----cctctcctgact----
------------------------------cgc------------ccgctgctcccc-tc
agga------gtatatttcagacaatccacctg----------------------ttctg
ttccccactctgtctct-gtgaatcctctcaccc----------------cctctcacat
ctctggcc---agtac-------------cccagttcttggat--gcataaa---taaag
t---------aaaacttaaaaa--ttttttttt-aaaagtgggcaaagaagagaaagcaa
aaccaCCAAATCTGA---------
>NW023604972.1:68143990-68144351(-)
--aaaaacagacacacagacaaatggaatttaatagaaaaccccaaaatatggggccttc
ctg--gtg-----gcacaaggagttaa-------gatgcagc--ctatgaag----ctat
ctgc----agccactacagcat-aagttcaatccct------------------------
ggcctgg---gagct--actcac-a-tggc--gcagcaga----cctcttctggct----
------------------------------cac------------ccgctgctcccc-tc
agca------gtgtatctcaatcaatctgcctg----------------------ttctg
ttccccagtctgtctctggtgaatattctca--------------------ctcccatac
ctctggcc---tgtac-------------ctcagttcct-cag--gcataaa---taata
a---------atctattaaaaa--agaaaactc-caaaataAAGCC-ACTTATGTATGGG
CAAttaatccttgac---------
>NW023601754.1:43974120-43974483(-)
--CCTGACTTAGGAACTTTTTAGCTCTCATGATGGGACAAAACACAGGCtgcgagcctcc
ctg--gtg-----gtgca-ggggttaa-------gacgaaac--ccatgaag----ctgt
ccgc----agccactgcagcat-gagtttgatcccc------------------------
agccagg---gagca--acccac-a-tggc--gcagcaga----cctctcctgtct----
------------------------------c-c------------ccgctgctcccc-tc
agca------gtgtacttcggtcaatctgcctg----------------------ttctg
ctccccgccctgtctctggtgaatcctctca-------------------ccctccgtac
ctctggtc---tgtgc-------------cccagctcttgtat--gcataaa---taaaa
a-------taaatctctaaaaa--acattaaaa-ataaataaaaaa-taaaaaccatggg
CTGTCCTCCTGGGAC---------
>NW023605083.1:132219461-132219830(-)
--TGAGCCCCGAAGCAAAAGCAATGAGCAGAGAGGTAAAGATTCCGccaggcgggcctcc
ctg--gtg-----gcgta-ggggttaa-------gtctcag---ctatgaag----ctat
cacc----aaccaccgcagcat-gagttcgatcccc------------------------
ggccagg---gagct--gcccac-a-tggc--acagcaga----cccctcctgtct----
------------------------------c-c------------ccgctgctcccc-tc
agca------gtgtatctcagtcaacccaccta----------------------ttctg
ctccccactctgtctctggtgaatcttctca-------------------ccccccacac
ctctggcc---tgtac-------------cccagttcttgtat--gcacaaa---taaat
aataaaaataaatcttaaaaaa--aaaaaaaaa-aagattccgcAG-GGAGTTCTAAAGC
CGCCCTGAACTACAG---------
>NW023600993.1:5229835-5230197(-)
--ataaatgaaaaaaataactccaGCCCactcattttaaaaggacaaataaggggcctcc
ctg--gtg-----gcaca-ggggttag-------gacccaac--ctatgaag----ctgt
ccgc----agcctctgcagcag-gagttcgattcca------------------------
ggccagg---gagca--acccac-a-tggc--gcagcaga----cctctcctgact----
------------------------------cgc------------ctgctgctcccc-tc
agca------gtgtgtttcagtcagtctgcctg----------------------ttctg
ttcccagctctgtctctggtgaatcctctca-------------------cctcccacac
ctctgacg---tgtac-------------cccagctcttgtat--gcataaa---taaat
a---------aatctaaaaaaa--aaaggacaa-ataaaatgATCT-TCACACATTAGAT
GATGGTGACAGGAAA---------
>NW023604295.1:30685934-30686297(-)
--TAGAGTAGAGctaagaggaaggagaaaaggttTTTCAAAGTgctactacagggcctcc
ctg--gtg-----gcgcaaggggttaa-------gacacaac--ctatgaag----ctgt
ccgc----agtcactgtagcac-aagttcgatcccc------------------------
ggacagg---gagca--acccac-a-tggc--gcagcaga----cctctcctgact----
------------------------------cac------------ccactgctcccc-tc
agca------gtatacttcagtcaatctgcctg----------------------ttctg
ttccccaccctgtctctggtgactcctctca-------------------ccccctgcac
ctctagcc---tgaat-------------cccagttcttgtat--gcataaa---taaat
a---------aatgtaaaaaaa--aaaaaaaag-tcctactaCAGA-GACAACCAATATT
AACTTTTGATACAGC---------
>NW023604972.1:125977849-125978209(+)
--TGCACATAGTCCTTGGACAATGTTTTCTGTCTACATTAAAGAGTACAggggggtgtcc
ctg--gtg-----gtgcaaggggttaa-------gacgtaac--ctatgaag----ctat
cctc----agccactgcaacac-gagtttgatcact------------------------
ggcaaat---gagct--acccac-a-tggc--acagcaga----cctctcctgact----
------------------------------cgc------------ccactgctcccc-tc
agca------gtgtatttccgtcaatctgcctg----------------------ttctg
ttccccactctgtctctggtgaatcctctca-------------------ccttccacac
ctctggcc---tggat-------------cccagttcttgtat--gcataaa---taaat
a---------aatcttaattta--aaaaaaaaa-agagtacaggGA-TCTAGAATTAAGT
GCTTTCAATCAC------------
>NW023601433.1:8470145-8470507(+)
--ATAAATGTAAAACCACAGCAGATAATCCAGAGTTAAATTACTatcatgaggggcctcc
ctg--gtg-----gcacagagggttaa-------gatgcagc--ctatgaag----ctgt
ccac----agccactgcagcac-cagtttgatcccc------------------------
ggccagg---gagct--acccac-a-tggt--gcagcaga----cctctcctgtct----
------------------------------c-c------------ccgctgcttccc-tc
agct------gtgtacttcagtcaatctgcctg----------------------ttttg
ctccccagtctgtctctggtgaatcctctca-------------------ccccccacac
ctctggcc---tgtac-------------cccagttcttgtat--gcataaa---taaat
c---------ttttttaaaaaa--attactatc-gTGAATAGATGG-AGTTACCAACTCG
ATTTTTATACCAACA---------
>NW023604972.1:29735020-29735378(+)
--GGTGAAATTTAACAGGAAAAGTGAGTGTGGTTTAAAACATCAAGTgcagtgggccttc
ctg--gtg-----gcgcaaggggttag-------gacgcagc--ctgtgggg----ctgt
ccgc----agccactgcagcac-gagttcaatcccc------------------------
ggccagg---gagct--acccac-a-tggc--gcagcaga----cctctcctgacg----
------------------------------tgc------------ccactgct-ccc-tc
agca------gtgtatttcactcagtctgcctg----------------------ttctg
ttccccactctgtctctggtgaatcctctca-------------------ctccccacgc
ctctggcc---tgtac-------------cccagctcttgtat--gcataaa---taaat
c-------------ttcaaaaa--aaaaagtca-agtgtgGTAACA-GATTAGATTGACC
AAACCTTGATTCATC---------
>NW023605305.1:8902212-8902578(-)
--GCTCCCTCAAGAACTAAGGTCTCAGGAAGCAGAGAAGAAATAGGTccggcgggcctcc
ctg--gtg-----gtgcaagaggttag-------gacgcaac--cgatgaag----ctgt
ccac----agcctctgcaacac-aagttcgatctcc------------------------
cgccagg---gagct--acccac-a-tggc--gcagcaga----cctctcctgact----
------------------------------cgc------------ccgctgctcccc-tc
agca------gtgtatttcagttggtcttccta----------------------ttctg
ttccccactctgtctctggtgaatcctctcacca----------------ccacccccac
ctctggcc---tgtac-------------cccagttcttgtgt--gcaaaaa---taaat
a---------aatcttaaaaaa--aaaaaaaag-aaataggtccAT-GGTTGGAAGAAAG
GAGGCGTCCCAGGTA---------
>NW023602073.1:140889560-140889932(-)
--CTCATGTAAGCACTGTGGCCCCAAGTAATTGACAAAGAATTTcgtgtgttgggcctcc
ctg--gtg-----gcgcaagtggttaa-------gacacaaa--ctatgaag----ctgt
ctgc----agcctctgcagcac-gagtttgatcccccagc-a------------------
ggccagg---gagcg--acacac-a-tggc--gcagcaga----cctctcctgatt----
------------------------------cgc------------cctctgctcccc-tc
agca------gtgtactttgctcaatctgcctg----------------------ttctg
ttccccactctgtctctggtgaatcctctcaccac---------------ccccccatat
ctctggcc---tatac-------------cccaactcttgtat--gcataaa---taaat
a---------aatcttaaaaaa--atagaattg-tgtgtgtcttcc-ttttcttatagTT
TGTAATATGCAGTCT---------
>NW023601212.1:9629537-9629895(-)
--GAACACCCCGTGTAGAAATagtggaatttaaaataaaaatttaagaaacagggcctcc
ctg--gag-----gcgcaaggggttaa-------gatgcaac--ccgtgaag----ctat
ccgc----agctactacagcac-gagttcgatcccc------------------------
agccagg---gtgct--acccac-a-tggc--gcgggaga----cctctcctgtct----
------------------------------cgc------------ccgctgctcccc-tc
agca------gtgtattttgctccatctgcctg----------------------ttctg
ctccccactctgtctctggtgaatcctctca-------------------ccccccgcgt
ctctggcc---tgtac-------------cccagctctcgcat--gcataatc-------
----------aatctttaaaaa--aaattaaaa-cacagaaaaaca-gcaGGAAAGCAAA
ACACGTCGGGGCCAC---------
>NW023601433.1:44139032-44139388(+)
--ataaattatatgTGCATTTAGATAGAAAAGtcatataagaaataaaatcagggcttcc
ctg--gtg-----gcgca---ggttac-------aacgctac--ctatgaag----ctga
cagc----agccgctgcagcac-aagttcgatcccc------------------------
ggccagg---gagct--acacac-a-tggt--gcagcaga----cctctcctgact----
------------------------------cac------------ccactgctcccc-tc
agca------ttgaatttcagtcaatccgcctg----------------------ctctg
ctccccactctgtctttggtgaatcctctca-------------------tcccccacac
ctctggcc---tatac-------------cccagttcttgtat--gcataaa---taaat
a---------aatcttttttta--aaaagaaat-aaaatcataagt-ctaagatacattg
aaaaaaatgtc-------------
>NW023604972.1:30894041-30894426(+)
--TAGCTCATTAACACTCAACCCTCCATGTaccattaaaaattacaaaagaagtgcctcc
ctg--gtg-----gcacaaggggttaa-------gacgcaac--ctaagaag----ctat
ctgc----agccactgcagcac-gagttcgatcccc------------------------
agccagg---gagct--acccac-a-tggc--acagcaga----cctctcctgtct----
------------------------------cac------------ctgctgctcccc-tc
agca------gtgtatttcggtcagtctgcctgtgtatttcagtagatcccactgttctg
ctccccactctgcctctggtgagtcctctta-------------------gcccctacgc
ctctggcc---tgtac-------------cccagctcttgtat--aaataaa---taaat
a---------aatctaaaaaaa--aattacaaa-agagcATGGGCA-TCTACTGTCAAAA
GCAGCAGTGATCAAA---------
>NW023604861.1:93609615-93609969(-)
--ACTGAAACAGCTTTCTGCCATTGGAGATGGAAGTTAAAAACttgggaaaggggcctcc
ctg--gtg-----gcacaaggggttaa-------gatgcaag--ctatgaag----ctat
ctgc----agccactgcagcac-gagttccatcccc------------------------
gaccagg---gagct--acccac-a-cggc--gcagcaga----tctctcctcacT----
------------------------------CGC------------CTGCTGATTacc--t
agca------gtgtacttc----aatctgcctg----------------------ctctg
ttccccactctgtctctggtgaatcctctca-------------------cccatcacac
ctctggct---tgtac-------------cccggttcttgtat--gcataaa---taaat
c-------------tttaaaaa--aaaaaaaac-aacttgtgaAAG-GAAGTGAGAAGTG
ATGCACTGTTTTGAG---------
>NW023605083.1:64586800-64587150(+)
AATagagaaaatttctcttttggctcaaaaaaaaaaaaaatgctcaatgtTGGGGACTCC
ATG--Gta-----gcg----------------------caac--ctatgaag----ctat
ctgc----agccactgcagcat-gagtttgatccct-ggc-a------------------
ggccagg---gagca--acccac-a-tggc--gcagcaga----cgtctcctgact----
------------------------------tgc------------ccgttgctcccc-tc
agca------gtgtatttcagtcaatctgcctg----------------------ttctg
ctccccactctgtctctggtgaatcctctca-------------------cctcccgcac
ctctgacc---tgtat-------------gccagttcttgtat--gcataaa---caaat
c-------------ttaaaaaa--aaaaataac-aggaataaagaa-actaatttttata
tttaaaaaaatgctc---------
>NW023600993.1:63533573-63533939(+)
--TGACCAAGTAGAAATTCCTGGCAAGACGTTTGCTTAAAAAAgcaaagtgagggcctcc
ctg--gtg-----gctcaaggggttaa-------aacacaac--ctatgaag----ctat
ccat----agccactgcaacat-gagttccatccct-ggc-c------------------
agccaag---aaaca--acccac-a-tggt--gcattaga----cctctcctgact----
------------------------------cgc------------ccgctgctcccc-tc
agca------gtgaatttcagtcattctgcctg----------------------ctctg
tggcccactctgtttctggtgaatcctttca-------------------tcccccacac
ttctggcc---tgtac-------------cccagttcttgtat--gcataaa---taaat
a---------aatcttaaaaga--agtaaaaac-caAGATGTGGAA-TTCAAAGACTTTG
TATAATAAGATACA----------
>NW023605305.1:18009188-18009550(-)
--ATTGTCTAAAACTGTTTTCACACTATCTCAGAATTAAACAATCCctggccgggcctcc
ctg--gtg-----gcgcaaagggtaaa-------gacgcaac--ctaagaag----cttg
ctgc----agccactgcagcac-aagtttgattccc------------------------
agccagg---gagct--acccac-a-tggc--gcagcaga----cctctcctgact----
------------------------------tac------------ccgctgctcccc-tc
agca------gtgtatttcagtcaatccgcctg----------------------ttctg
ttccccactctgactctggtgaatcctctca-------------------cccccc-caa
ctctggcc---tgtac-------------ccccattcttatat--gtatata---taaat
a---------catctttaaaaa--taaataaat-aaataaacaatc-ctTGGCCCTTTGC
AGAAAGTTAGCCAAC---------
>NW023601543.1:5040990-5041351(-)
--GAAAACTAGACTTTAGTTTGACAACTACAAGGAACTAAATTCTGTcaataggggctcc
ctg--gtg-----gcgtaaggggttaa-------gaggcaac--ctatggag----ctca
ctgc----agccactgcagcac-gagttccatcccc------------------------
agccagg---gagct--gcccac-a-tggc--acagcaga----cctttcctgtct----
------------------------------cgc------------ccgctgct-ccc-tc
agca------gtgtactttggtcaatctgcctg----------------------ttcta
ttccctgttctgtctctggtgaatcctgaca--------------------cccccacac
ctctagtc---tgtac-------------cccagctcttgtat--gcataaa---taaat
a---------aatcttttaaaa--ataaataaa-taaattctgtca-atagaaagaatga
aattgggAGCCAACT---------
>NW023605083.1:90184263-90184622(-)
--aaaaagtttggaaaaaaaagatctgagttaaactaaaaaaaaaaaatccagggcctcc
ctg--gtg-----gtgcaaggggttaa-------gatgcaac--ctatgaag----ctat
ctat----agccactgcagaac-gagtttgatACCC------------------------
gcccaga---gagct--acccac-a-tggc--gcagtaga----cctctcctgact----
------------------------------tgc------------ccgctgcttccc-tc
agca------gtatatttcagtcagtctgcctg----------------------ttctg
ttccacactctgtctttggtgaatcctctca----------------------ctcacac
cgctggcc---tggac-------------cccagtt-ttgtat--gcataaa---taagt
a---------aatctttaaaaa--aatcaataa-aatgaatggGAA-TAAAACAATGCAG
AAGTTAAGACACTTA---------
>NW023600993.1:85361686-85362060(+)
--AAGGACAAAAAGTAGACAAAAGAATTTTACTATAAAAAAGAGCACaaaaggggtctcc
ctggagtg-----gtgcaaggggttga-------g-cacagtg-ctatgaag----ctat
ctgc----agcctctgcagcac-aagttcaatcccg--gc-c------------------
ggccagg---gagca--acccac-a-tggc--gcagcaga----cctctcttgcct----
------------------------------cgt------------tcattgctcccc-tc
agca------gtgtgtttcagtcggtctgcctg----------------------ttcta
ttccccactttgtctctggtgaatcctctcaccccg-------------ccactccacac
ctctggcc---tactc-------------cccattttttgtat--gcataaa---taaat
a---------aatctttaaaaa--aatgttaaa-aaaaaaaaaaag-gacaaaaggagAT
AATTGCCCTGTGAGA---------
>NW023605083.1:18318810-18319171(+)
--TTCCCAGAAGCAGATGAATTAAGGTATTTCTCATCAATCAGGCTTCAagggagcctct
ctg--gtg-----gtacaaggggttaa-------g-cacagca-ctgtgaag----ctat
ccac----agcctctgcagtac-aaatTCAATCCCT-AGC-C------------------
TACCAGG---GAGac---accac-a-tggt--gcagcaga----cctctcctgtct----
------------------------------cgc------------ctgctgctcccc-tc
agca------gtgtatttcagttaatctgcctg----------------------ttctg
ttccccactttgtctctggtgaatcctctca-------------------ccccccacat
ctctggcc---tgtac-------------ccca-ttcttatat--gtataaa---tagat
c-------------tttaaaaa--aaagcaatg-aggCTAAAgaac-agctctttaaaaa
aattcgaCTTAAAAT---------
>NW023605083.1:50452561-50452931(-)
--GGTATGAATTTGAGGATGATGAGCTTTTAAGACTTCTTAAGAAAtcattgggacctcc
ctg--gtg-----gcacaaggggttga-------g-caccgta-ctatgaag----caat
ccac----agcctctgcagcac-gagttcgatccct-ggc-t------------------
ggccagg---gagca--acccag-a-tggt--gcagcaga----cctctcctgaat----
------------------------------c-c------------ctgctgctcccc-tc
agca------gtgtatttcagtcagtctgcctt----------------------ttctg
ttccccactctgtctctggtgaatcctctca-------------------ccccccacat
ctctggcc---tgtac-------------cccagctcttgtat--gcataaa---taaat
g---------aatgtgtcttta--aaataaaag-acttgtTAAGAA-ATcataagttttt
ttaatatataattataatt-----
>NW023603184.1:124877598-124877969(-)
--aaataaataaataaataaataaacatgcctctatcaAAGATttaagcatagggcctcc
ctg--gtg-----gcgcaaggggttaa-------g-caccaca-ctatgaag----caat
ccga----agcctctgcagcat-gagttcaatccct-ggc-c------------------
ggccaga---cagca--acccac-a-tggt--gaagcaga----cctctcctgtct----
------------------------------cgc------------ccgctgctcccc-tc
agca------gtgtgtctcggtccgtctgcctg----------------------ttctg
ttccccacgctgtctctggtgaatcctctca-------------------ccgcccgcat
ctctggcc---tgcac-------------cccagctcttgtat--gcataaa---taagt
a---------aatcaatcttaa--aaaaaaaaa-ataatttatgta-tacaagagctggg
gtgtaggccagagcttgag-----
>NW023603741.1:21737-22103(+)
--AAGTTTGAAAGTTATttaggattcattcattcattcaaaacccaaaaagtgggcctcc
ctg--atg-----gtgcaagggtttaa-------g-cactgca-ctatgaag----caat
ccac----agcctttgcagcac-gagctcgatcccc-agc-c------------------
ggccagg---gagca--acccac-a-aggt--gcagcaga----cctctcctgact----
------------------------------tgc------------ccgctgttcccc-tc
agca------gtgtacttcggtcaatctgccgg----------------------ttctg
ttccccactctgtctctggtaaatcctctca-------------------ctccccgcat
ttctggcc---tgtac-------------cccagctcttgcat--tcataaa---taaat
a---------aatcttaaaaga--aacaaaaag-tttttCTACAGG-ATTGGAAAAGTTC
TTTCTCATAAGAAT----------
>NW023603184.1:79971544-79971911(-)
--GAATAGGatgtaaatgatatttttggatgctattgaaaatgttattttttgggtctcc
ctg--gtg-----gtgcaaggggttaa-------g-caccaca-ctttgtag----caat
ccac----agcctctgtggcac-aagttcgatccct-ggc-c------------------
tgccagg---gagct--acccac-a-tgat--gaagcaga----cctcccctgtct----
------------------------------cac------------ctgctgctcccc-tc
agca------gtgtgtttcagtcggtctgcctg----------------------ttctg
ttccccactctgtctctggtgaattctatca-------------------ccccctgtat
ctctggcc---tgtac-------------cccagctcttgtat--gcatgaa---taaat
a---------aatcttaaaaaa--aagaaaatg-ttatgttatttt-tttaaaaataaaa
ttaaaaatgatcatt---------
>NW023604295.1:42084732-42085100(-)
ACCAGCATTCACTTATAAGGGAAAAAGTGTACCTAAGAATGTCCTTGAAGGGGCCTcccc
ctg--gta-----gcacaaggggttaa-------g-caccgca-ctatgaag----caat
gcac----agcctctgaagcac-aagttagatcccc-ggc-c------------------
agccagg---gagaa--acccac-a-cggc--gaggcaga----cctctcct-cct----
------------------------------tgc------------ccgctgctccct-tc
agca------gtgtatttcagtcagtctgcctg----------------------ttctg
ttccccactctgtctctggtgaatcctctca-------------------cctcccacat
ctctggcc---tgtac-------------cccagctcttgtat--gcataaa---taaat
a---------aatcttaaaaaa--aaaaaaaaa-aaaagaatgtcc-ttgagggcctccc
cagtagtgcagcagg---------
>NW023600993.1:53862410-53862776(-)
--GCTATAATTTTGTAACAACAGAATAACTGTCACTTTACAAATGTAtcgaagggcctcc
ctg--gtg-----gcacaaagggttta-------g-cacagca-ctgtgaag----ctat
ctgc----aacctctgcagcac-aagttcaatcccc-agt-c------------------
agccagg---gcgct--accc-c-a-tggc--acagcaga----cctctcctgtct----
------------------------------cat------------ccgctgctccct-tc
agca------gtgtatttcagtcgatctgcctg----------------------ttctg
ctcccctctctgtctctggtgaatcctctca-------------------caccccacac
atctggac---tgtac-------------cccagttcttgtat--gcataaa---taaat
a---------aaccttaaaaaa--aaaaaaaca-acaaaacccccc-TTTAAAAACCATG
AGGCTAGGGATGTGT---------
>NW023601433.1:80756055-80756427(-)
--TAAAAACATGTTAACATGTTAAAAACATGTTAGAAAACAtgttaaaaacagggcctcc
ctg--gtg-----gtgcaagggattaa-------gtcgcaac--ctttgaag----ctgt
ccac----agccactgcagtac-aagttcgatcccc-agc-t------------------
ggccagg---tagct--acccac-a-tggc--gaggcaga----cctctcctgtct----
------------------------------cac------------cctctgctcccc-tc
agca------gtgtacttcggtccatctgcctg----------------------ttctg
ctcccttctctgtctctggtgaatcttcttatcccc----------ccccgcccccgcac
ctctggcc---tgtac-------------cccagctcttgtat--gcataaa---taaat
a---------aatcttttttaa--aaaaagaaa-acatgtcaaAAA-CAAACATGGTATG
ATGTTCCCTTT-------------
>NW023604972.1:45855755-45856126(+)
-----CTGtggaaaattcaaaatttgagcTCTTATATAAAACAAGAATATTGGaacctcc
cgg--gtg-----gcgcaaggggttgg-------g-cgccgca-ctatgaag----cagt
ccac----agcctctgcagcac-gagttcgatcccc-agc-c------------------
ggccagg---gagag--acctac-a-tggc--gcagtgga----cctctcctgtct----
------------------------------cgc------------ccgctgctccca-tg
agca------gtgtatttcagttagtctgcctg----------------------ttctg
ttccccg--ctgtctctggtggatcctctcaaccca--------------ccccctgcat
ctctggcc---tgtac-------------cccagctcttgtat--gcataaa---taaat
a-----aataaatcttaaaaaa--aaaacaaaa-caagaacattaT-AAATGATCACCAG
Tgtgctttaaaacaa---------
>NW023604861.1:7247293-7247664(-)
--CTCCTGCCACTGTACCTTCCCTCCAAGGGTGGCATCAAGAAccaagagctgggcctcc
ctg--gtg-----gcgcaaggggttaa-------g-caaagca-ctatgagg----caat
ccgc----ggcctctgcagcac-aagttcaatcccccggc-c------------------
ggcca-----gagca--ACCCAC-actggc--gaagcaga----cctctcctggct----
------------------------------cac------------ccgctgctcccc-tc
agca------gtgtacttcagtcaatctgcctg----------------------ttctg
ttccccgctctgtctctggtgaatcctctca-------------------ccccccgcat
ctctggcc---tgtac-------------cccagctcttatat--gcataaa---tacat
a---------aatattttttaa--aaaaagaac-caagaacTGAAA-AAAGTGATCTGAG
GCCCTGTCAACACTCCAAT-----
>NW023605083.1:45489389-45489748(+)
--TTGTGAACACAAACCCAATCACATCACTCACCTATTTAAAAttccccacagggcctcc
ctg--atg-----gcacaaggggttaa-------g-caccgca-ctatgaag----ctat
ctgc----agccactgcagcac-gagttcaatccca------------------------
ggccagg---gagct--acccac-a-aggc--acagcaga----tctctcctggct----
------------------------------cgc------------ctgctgctcccc-tc
agca------gtgtatttc----aatctgcctg----------------------ttcag
ctccccactctatctctgatgaatcctctca-------------------gcccccgcat
ctctggcc---tgtac-------------tccagctcttgtat--gcataaa---tacac
a---------aatctttaaaaa--aataaagta-aaattcccCACA-GCTCCCCACTTTC
TATATGATGAGACAG---------
>NW023604861.1:120421841-120422207(+)
---taaaaatgccattggtttggaaagtaaataaaatctgatGATACCCTTgaggtttcc
ctg--gtg-----gtgcaagggattaa-------g-cacagca-ctgtgaag----ctat
ccta----aGCCTCCaccgcat-gagtttgatccct-ggc-c------------------
agccagg---gagct--acccac-a-tggg--gcaggcga----cttctcctgtct----
------------------------------ctc------------ccactgctccac-tc
agca------gtgtatttcagtagatctatctg----------------------ttctg
ttccccaatctatctctggtgaatcctctca-------------------ccccctgcac
ttctggcc---tacac-------------cccagctcttgtat--gcataaa---taaac
a---------aatctttaaaaa--atttgatga-TACCCAACTTCT-CTAACAGTTGTAC
AAATTTCTATCTAAC---------
>NW023604295.1:92858364-92858738(+)
--CATAAAATTATTCATCTTTGGCCACTTGTTTGTTTAAACTAAACTgttatgggcctcc
ttg--gtg-----gcacaaggggttaa-------a-catcaca-ctatgaag----caat
ccgc----agcctctgcagcat-gagttcaatcccc-ggc-t------------------
ggccaga---gagaa--acacac-a-tggc--gaagcaga----cctctcctgtct----
------------------------------cgc------------ctgctgctccccttc
agca------gtgtgtctcagttagtctgcctg----------------------ttctg
ttccccactctgtctctggtgaatcctctcaccccc-------------ccacctcaact
ctctggcc---tgtac-------------tctagctcttgtat--gcataaa---taaat
a---------aatctttaaaaa--aaatacagt-gttgtTTCAGTC-ACATTATATACTG
TCACCTATTGGATCG---------
>NW023603184.1:12832783-12833144(-)
--CCACTGCATACTGAAACACTTCACTTgggagcctttaaaaaaataccagtgggtctcc
ctg--gta-----gcacaaggggttaa-------g-caccaca-ctatgaag----caat
ctgc----agcctctgcagcac-gagttcgatcccc-gac-a------------------
ggccaga---gagaa--atcctc-c-tggt--gcagcaga----cctctcctgact----
------------------------------cgc------------ctgctgctcccc-tc
agca------gtgtatttcagtcattccgcctg----------------------ttctg
ttc------ttgaCTCTGGTAgcgcctctca-------------------ccccccacat
ctctggcc---tgtac-------------cccagctcttatat--gcataaa---taaat
a---------aatatttaaaag--aaaatacca-gtTCCCAGGTCT-CACCCTAGATCAA
TGAAATCAGAAGCTC---------
>NW023605083.1:106765423-106765808(+)
--ataaataaataaataaaatctttaaaataaaataaaataaaagggttactgggcctcc
ctg--gtg-----gtgcaag-ggttaa-------g-cactgca-ctatgaag----caat
tctc----agcctctgcagcat-gagttcgatcccc-ggc-t------------------
ggccagg---gagaa--acccac-a-tggc--gcagcaga----cctctcctgact----
------------------------------tgc------------ccactgctcccc-tc
agca------gtgtgtttcagtcagtccacctg----------------------ttctg
ttccccactctgtctgaggtggatcctctcacccggcccctgcccgccccccacaggcat
ctctggcc---tgtgc-------------cccagctcttgtat--gcataaa---taaat
a---------aatctttaaaaa--atataaaat-aaaatgtggttg-cTAGGAAATTTTA
ACTAACAATGCTGTC---------
>NW023604861.1:94420522-94420891(+)
----TATTCTGGCATTCTGAAACTGATAGTTCAGTCAGAAAACAGGGTGATCatgcctct
gtg--gtg-----gtgcaagagattaa-------g-cacagca-ctgtgaaa----ctat
ccgc----caccactgcagcat-gaattcgatccct-ggc-t------------------
ggccaca---gagct--accaac-a-tggc--gcagcaga----cctctcctgtct----
------------------------------cgc------------ctgcttctcctt-tc
agca------gtctatttcagtcaatctgcctg----------------------ttctg
ttccccactctgtttctggtggatcctctcacccc---------------caccccacac
ctgtggcc---tacac-------------cccagctcttgtat--gcataaa---taaat
a---------aatcttttaaaa--aaaaaaaga-aaatagtcatcA-AATAATCCCACAT
GATATAGAATAGCAA---------
>NW023605194.1:89808164-89808522(-)
--CCTCTGAATCCCTCTCAGCTCTTCAAATCGTGGCTATAGAAACCTCtttggagtctcc
ctg--gtg-----gtgcaaggggttaa-------gacgcaac--caatgaag----ctat
aggc----agcctcagcagcac-cagttcgatcccc------------------------
agccag----gagca--acccac-a-tggc--acagcaga----ccgctcctgact----
------------------------------cac------------ccactgctcccc-tc
agca------gtgtatttcagtagatctgcccg----------------------ttctg
ctccccactctgtccctggtgaatcctctca-------------------cccactgcat
ctctggct---tgtac-------------cccagttcttctat--gcataaa---taaat
c-------------tttaaaaa--aaaaaaacc-tctttgatGGTT-GGTTGAGAATAGA
AGAACACTCCGTGGG---------
>NW023601212.1:35989110-35989468(+)
--TGATATAGTTCACATATGATAAAGCCCAACCATTTAAAATGCATgatttagggccttc
ctg--gtg-----gtgcaaggggttaa-------gacacaac--ttgtgaag----ctgt
ctgc----agcctctgcagcac-aagttcaatcccc-agc-c------------------
agccaag---gagca--acccac-a-tggt--gcagcaga----cctctcctgact----
------------------------------tgc------------ccactgctccct-tc
agca------gtgtacttcaatca----accta----------------------ttctg
ttccccacttagtcttctgtgaatcctctca--------------------cccccacat
ctctggcc---tgtac-------------cccagctcttgtat--gcataaa---taaat
c-------------tttaaaaa--aataaaata-aaatgtatgttt-tagtggggatttt
ttgtatatttacaga---------
>NW023603184.1:28775885-28776249(+)
--AGAACTTACagggatgaataggagtttgcaggcaaaatagaagggaaagtgggcctcc
ctg--gtg-----gtgcaggggttaaa-------gacgcaGCA-CTATTAat----ctat
tgcc----agtcactgcagcac-gagttcaacccct-ggc-c------------------
tgccagg---gcgca--acccac-a-cggc--gcagcaga----cctctcctgttt----
------------------------------tgc------------ccactgctctcc-tc
agca------gtgtatttcagtcaatctgcctg----------------------ttctg
ctccccactctgtctctggtggttcctctca-------------------cccgccacac
ctctggcc---tgtac-------------cccagttcttgtat--gcataaa---taaat
c-------------tttaaaaa--gagagagag-agagaaaggaaa-gaacattAAAGAG
CAGATGGTAGCACAA---------
>NW023604861.1:43817961-43818327(+)
--TAAACCTGACAAACTGATATTTACTACTCACTGCCATTAAAAGTagagaggggcctcc
ttg--gtg-----gtgcagggggttaa-------catgcaac--ctatgaag----ctgt
cctc----agccactgcagcac-gagttcgatcacc-agc-c------------------
tgccagggaggagtt--acccat-a-tggt--gcagcagg----cctctcctgact----
------------------------------cgc------------ccactgctcccc-tc
atca------gtgtatttcagtcaat-tgcctg----------------------ttctg
cttcccactgtgtctccggtaaatcttctcac------------------ccccccacac
ctctggcc---tgtac-------------cccagttcttgtat--gcatata---taaat
c-------------ttaaaaaa--aaaaaaaaa-cagtagagaggt-aaaaaatagataa
attgggtTTTTCTGA---------
>NW023601754.1:39822403-39822779(-)
--CAGAATTACCCTAATATGAAAGCCAGAAAAAGAGATAATgtaaaaaaagagggcctcc
ctg--gtg-----gcacaag-ggttaa-------gacacaac--ctatgaag----caat
ctgc----agcctctgaggcac-gagttcaattccc-atc-c------------------
ggccagg---gagca--acctac-a-tggg--gcagcaga----tctctcctgtct----
------------------------------cgg------------ccgctgctcccc-tc
agca------gtgtacttctgtcaatctgcctg----------------------ttctg
ttccccactccgtctctggtgattcctctcaccaccgccc-----cccccccacacacac
ctctggcc---tgtac-------------cccagctcttgtat--gtataaa---taaat
c-------------ttaaaaaa--aaaaaagac-taccaaCATGAC-Tcattaatataca
taaaaatcatcaaca---------
>NW023601104.1:55343962-55344318(-)
--tatgGGAAATTGGccactgattattttattttataaagaaaataatgacagggacttc
ctg--gtg-----gtgcaaggggttaa-------gacgcaac--ctatgaag----ctat
cagc----agccaaagcagcaa-gagttcaatcccc------------------------
cgccagg---gagct--acccac-a-tggt--gcagcaga----cctctcctgtct----
------------------------------cac------------cagctgctcccc-tc
agca------gtgtatttcagtcaatctgcctg----------------------ttcta
ttcccca--ctgtctctggtgaatcctctca-------------------cacccc-cct
ctctggtc---tgtac-------------cccagttctcatat--gcataaa---tattt
t-------------tttaaaaa--aagaaaata-atggcaaTTGGT-TTGGGTGTGATGA
TATTAGAGTATATTT---------
>NW023601543.1:71156377-71156748(+)
--TACAAGAAATTCCCCTGTGCATGAGtctgcattttaagaaaaaggccgcagggcctcc
ctg--gtg-----gtgcaaggggttaa-------gacccaac--ctatgaag----ctat
ctacagctatccactgcagcac-gagtt-aatcccc------------------------
agctagg---gagct--acccac-a-tggt--gtagcaga----cctctcctgtct----
------------------------------cac------------cccctgctctcc-tc
agca------gtgtatttccatcgatctgcctg----------------------ttctg
ttccccaatctgtctctggtgaatcctctcaccccc--------------caccccccac
ccccagcc---tgtac-------------tccagttcttatat--gcataaa---taaat
a---------aatcttaaaaag--aaaaaaagg-ccacAGATAAAA-AAGCCCTCAAGCC
GGGCAACCTCATCCT---------
>NW023605194.1:24694624-24694978(-)
--GATGGTGACTTAGTAGAGAGGTGGAAGTTGTCATCTAAATGtcagaagaggggcctcc
ctg--gtg-----gcgcaagaggttaa-------gacacagc--ctatgaag----ctgt
cccc----agcctctgcagcac-gagttcgatcctg-ggc-c------------------
agccagg---gggca--acccac-a-tggt--gcagcaga----cctctccttact----
------------------------------cac------------ccgctgctcccc-tc
agca------gtgtacttccatcgatctgcctg----------------------ttctg
ttccctcgtctgtctctggtgaatcctctca----------------------------c
ctctggcc---tgtac-------------ccctgctcttatat--gcataaa---taaat
a---------aatctttttttt--tttttaatg-tcagaagAGACA-TATATAAAGATGT
CATTTGTATCC-------------
>NW023605194.1:68691430-68691793(+)
--TTATTACATAGGGGTTatgccaatattttcttttaaaatatttactctttgggcctcc
ctg--gtg-----gcacaaggggctaa-------gatgcagca-ctgtgaag----ctat
ccgc----agccgctgcaacat-gggtttgatcccc------------------------
ggccagg---gagct--acccac-a-cggc--acggcaga----cctctcctgtctt---
--------------------------------c------------ctgctgctcccc-tc
agca------gtggatttcagtggatccacctc----------------------ttctg
ttccacactatgtctctgctgaatcctctca-------------------tgtcctgcac
ctctggcc---tgaac-------------cccagttcttgtat--gcatgaa---taaat
a---------aatctttaaaaa--aataaaact-tttttactcttt-aattttctctctc
ttattttaaagattt---------
>NW023602073.1:115008567-115008916(-)
--ACTGGCTTATTTTGGTGctattatatttccttatttaaattttgttttctggacctcc
ctt--gtg-----gcataAGGAGTAAG-------A-TGCAac--gtatgaag----ctgt
ctgc----agctacagtggcat-gggttctatccct------------------------
ggccagg---gagct--acccac-a-tggt--gcagcaga----cctctcctggct----
------------------------------cgc------------ccgctgctcccc-tc
agca------gtgtatttcagttagtctgcctg----------------------ttctg
ctccccattctgtctctggtgaatcctctca----------------------------c
ctctggcc---tgtac-------------cccagttcttgtat--gcataag---taaat
c-------------tttaaaaa--actaaattt-tgttttctcttc-tcattGGAAAGAG
GAAGCTGTTTGGGCA---------
>NW026555331.1:137389696-137390067(+)
---TCAGTCCTCATCAGCCAAGGTGATTGGTCTTGTAAATAGGCCttaactcaggcctcc
ctg--gtg-----gtgcaaggggttaa-------gttgcagca-ctatgaag----ctat
gtgc----agccactgcagcat-gagttcagtcct-------------------------
gttcagg---gagct--acccac-a-tggt--gcagcaga----tcccacctgtct----
------------------------------cac------------ccgctgttcccc-tc
agca------gtatatttcattcagtctgcctg----------------------ctctg
ttccccattctgtctctggtgaatcctctcaccctg----------ccccccccccacac
ctctggcc---tgtac-------------cccagttcttgtat--gcatcaa---taagt
a---------aatctttaaaaa--aaataggcc-ttAACTCTTCTT-ACTTGGACTTCCC
AAGAGGTACTAGGAG---------
>NW023605194.1:62114977-62115347(+)
--agagacagagaaagagaagaaaggatttcaaacaACAGACTCCTGGATCAgggcttcc
ctt--gtg-----gtgcaaggggttaa-------gtctcagca-atgtcaag----ctat
cgcc----agccactgtaacat-gagtttgatcccc-aacgc------------------
ggccagg---gagcta-acccac-a-tggt--gcatcaga----cctcccctgtct----
------------------------------cgc------------cctctgctcccc-tc
agca------gtgtatttcagtcgatgcacctg----------------------ttctg
cgccctactctgtctctggtgaatcctctca-------------------ccccctatac
ctctggcc---tacac-------------cccaatttttgtat--gcataaa---tgaat
a---------aaaattttaaaa--gtctgtaaa-aaaatatatact-agacTCCTGgatc
aaatttcaaaaatca---------
>NW023601104.1:26563374-26563738(+)
-------GGGTTTACAGGTCAGAGAATGGGGAGTTAAGGAATAACTGGGGTCGGTtattc
ctg--gtg-----gtgcaaggggttaa-------gtctcagca-ctatgaag----ctac
cagt----aGCCACTttagcaa-gagttcaatccct-agc-c------------------
ggccagg---gagcta-acccac-a-tggc--acagcaga----cctctcctgtct----
------------------------------cgc------------cggctgttcccc-tc
agca------gtgtgtttcagtcaatccacctg----------------------ttctg
ttcccccctccgtctctggtgaatcctctca-------------------tccctaacat
ctctggct---tacac-------------cccagctcttgtat--gcataaa---taaat
a---------aatacataaaat--cttaaaaaa-agggaataaCTC-GGGTCAAGAAGGG
GCAGAGGCTATAGGA---------
>NW023605305.1:84570497-84570866(-)
---GGCACAAAGTAGATGCTCAGTCACTATGTGGTCAAAAGACAACtaattcaggcctcc
ctg--gtg-----gcacaggggttaaa-------gtctcag---ctatcaag----ctat
tgcc----agccactgaagcat-gagttcaatcccc------------------------
aggtaag---gagcta-acccac-a-tggc--gcagcaga----cctctcctgtct----
------------------------------cgc------------ctgttgctcccc-tc
agca------gtgtatttcagtagattaacctg----------------------ttctg
ctccccactttgtctctggtgaatcctctcacc-----------------taccctgcac
ctctagcc---tacac-------------cccaattcttgtac--gcataaa---taaat
a---aaaagcaatcttaaaata--aaaagaaaa-ccaattcactaa-acaaacaaccaaa
aaaagacaaaagaa----------
>NW023605083.1:78531991-78532352(-)
---gtttgctttatcctctcaggtgtagtccccgtaaaattccagccaccagaggcctcc
ctg--atg-----gtgcaagggtttaa-------ggctcagcc-ctatgaag----ctat
cggc----agccattggggcat-gagtttgatcccc------------------------
caccaga---gagctG-GCAtgc-a-tggc--acagtgga----cctctcctgcct----
------------------------------cac------------ctactgctcccc-tc
agca------gtgtatttcagtcaacacaccta----------------------ttctg
ctccccattctgtctctggtgaatcctctcac------------------ctccctgtac
ctctggcc---tacac-------------cacagttcttgtgt--gcataaa---taaat
c-------------ttaaaaaa--aaaaaaata-ccaccaattcac-ctgtgcaccatca
ccatagtcccttgtg---------
>NW023604972.1:64014772-64015136(-)
--TATCAAAGTGGTATTTATGATGCATGATTGAGTACTATTATAAAGGGTcggtgccttc
ctg--gtg-----gtgaaaggggttaa-------ctctcaaca-ctgggaag----ctat
ccac----agtcactgtggcag-gagttcaatccc-------------------------
agccagg---gaacta-acctac-a-tggc--atagcaga----cctctcctgcct----
------------------------------cac------------ccactgctcccc-tc
agca------gtgtctttcactCAATAcacgtg----------------------ttctg
ttccccactctgtctctggtgaatcctctcg-------------------ccccctgcaa
tTCTAGGT---tgtag-------------cctggttcttgtat--tcataaa---tgaat
a---------aatcattaaaat--aaggTAGAA-GATGATCTTGGG-TAACAATATGCat
gcaaaagaaaaggaa---------
>NW023602073.1:128162473-128162838(+)
--TCCAGGAATCTCAACCATCTTTGCAATCCTCATTTACAATGCTgcagctagggcctcc
ctgg---------gcacaaggcgttaa-------gacccaaca-ctatgaag----ctat
ctgc----agccactgcagcag-gagttccatcccc------------------------
atcccgg---gagctg-acccac-a-aggc--ccagcaga----cctctcctgtct----
------------------------------ctc------------tggctactcccc-tc
agca------gtgtatttcagtcaatccacctg----------------------ttctg
ctccccactctgtctctggtgaatcctctcacc-----------------cacccagcag
gtctggcc---tgtac-------------cccagctcttgtat--acataaa---taagt
a---------aatctttttaat--aaagaaata-gaatgttCCAGC-TAATACACATATC
CTTAAAAACGTTATT---------
>NW023601543.1:16472309-16472684(+)
---ATAGCATCATTTCACTAAACAAtaccatattttaaattaaaaaaaagagaggactCC
CTA--agg-----gtgcaaggagttaagcacagcattgcagca-ctgtgaag----ctgt
ccga----agcctctgcagcac-gggtctgatcccc------------------------
agccagg---gagca--acccac-g-tggccagcagcaga----cctctcctgtct----
------------------------------cat------------cagctgctcccc-tc
agca------gtgtatttcagtcagtctgcctg----------------------ttctg
tttcccactctgtctctggtgaatcctctcacgc----------------cccccccaat
ctctggcc---tgcac-------------cctagctcttgtat--gcataaa---tagat
a---------aatctttaaaaa--aattgaaag-attatCTCAGAG-ATCTGAACTAGTA
TCCAGACTACTCAAG---------
>NW023605083.1:123470244-123470605(-)
--ACATAGGCACAATTCATTTACATGCTTCCACCCCATAAGAATtgtactttgggcctcc
ctg--gtg-----gcgcaagaggttaa-------g--tcagca-ctatggag----ctat
aggc----agccactgcagcat-gagttcaatcccc------------------------
ggctagg---gagctg-acccac-a-tggt--gcagcata----cctctcctctct----
------------------------------cgc------------ctgctgctccct-tc
agca------gtgc-tttcagtcaatctgccta----------------------ttctg
ctccccactctgtctctggggaatccactca--------------------ccccagcac
ctctggcc---ttcac-------------cccagctcttgtat--atataaa---taaat
c---------tttatttaaaaa--aagaattgt-atttcAACACAT-CTCAAGACTATTT
AGTAGTACTTCATAA---------
>NW023605083.1:76706840-76707208(-)
--GTATAATAACTTGATAATATCTCTTTTTCCCCTGTTTAAATTGCAGTTTGGAGTCTTC
CTG--GTG-----ATGCAatgggttaa-------g-catcaca-ctgtgaag----ctat
ccac----agcctctgcagtat-gagtttgatcccc-agc-c------------------
agccagg---gagct--acccaggagaggt--gcagcaga----cctctcctgtct----
------------------------------cgc------------ctgctgctcccc-tc
agca------gtgt-tttcagtcactctgcctg----------------------ttctg
ttccccactctgtctctggtgaatcctctca-------------------ccccctgcac
ctctggcc---tgtgc-------------cccagttcttgtat--gcataaa---taaat
c---------tttttttaaaaa--aagatttat-ttatacaagcac-tgggtatagtcag
aagcatgggagggtg---------
>NW023604295.1:17366837-17367198(-)
---CTGTCTTCCATGACAGCATATACCATAAACTAAGTTAAAACTgcaagccaggcctcc
ctg--gtg-----gcgcaagggggtta-------g-cacagca-ctgtgaag----ctac
gctc----agcctctgcagcat-gacttagatcctc------------------------
ggccagg---gagct--acccac-a-tggc--gcgacaga----cctctcctgtct----
------------------------------cat------------ctgcaactcccc-tc
atta------gtgtatttcagtcagtctgcctg----------------------ttctg
tggcccactctgtctctggtgaatcctctta-------------------ccccctgcac
ctttggcc---tgtac-------------cccagttc-tgtat--ccataaa---tatat
a---------aatctttaaaaa--aaaaaaaaa-agaaactgcaag-cCAACCCAAGCTA
TTATTTCATGTGGTG---------
>NW023601543.1:18031090-18031441(+)
--ATACAATTCAATGATATATCTTAAGTGACTAGTATTTAAAACtgagttaggggcctcc
ctg--gtg-----gcgcaaggggttaa-------g-cacagca-ctgtgaag----ctat
ctgc----agc--------cac-gagttccatcccc------------------------
ggcccgg---gaaaa--acccac-a-tggc--gcagcaga----cctctcctgtct----
------------------------------cac------------cagctgctcccc-tc
agca------gtgtatttcagtcagtctgcctg----------------------ttctg
ttccccactctgtctccagtgaatcctctca-------------------ccccctacac
ctttggcc---tgtac-------------ctcagttccttttt-tttaaaga---tttat
t---------tatttatgcata--caagaactg-gggtgcagacca-gaggtgggggggg
ggtgagagga--------------
>NW023600993.1:16466375-16466744(+)
--TTCTGATACACATTCCTGATGAATATATTCAAAGCATAAAAcaagctacagggcctcc
ctg--gtg-----gctcaaggggttaa-------g-cacaacacttatgaag----caac
ccgc----agcctctgcagcac-gagttccatccct-ggc-t------------------
gtcCAAGG--GAGCAA-CCctac-a-tggt--gcatcaga----cctctcctgcct----
------------------------------cac------------ccactgctcccc-tc
agca------gtgtatttcagtagatctgcatg----------------------ttctg
ctccccactctgtctctggtgaatcctctca-------------------ctccctgcac
ctctggct---tgta--------------cccagctcttgtat--gcataaa---tatat
a---------aatcttaaaaaa--aaaaaagct-acaaagaCAAAT-GGCACAATAAGTA
TTTATGTCTAGGATT---------
>NW023604295.1:93882871-93883233(-)
c------cactagcgccacgaggggaggccctggttaattattttaaatcttaactctcc
ctg--gag-----gtgcaaggggttaa-------g-cacagaa-ctgttaag----ctaa
ccac----agcctctgcagcac-atgttagatcccc-tgc-t------------------
ggccagg---gagtt--acctac-c-tggc--tcaacaga----cctctcttgcct----
------------------------------ctc------------ctGCTGTTtccc-ac
agca------gtatatttcagtcagtctgcctg----------------------tt-tg
ctccccattctgtctctgatgaatcttctca-------------------ccacctgcac
ctctggcc---cgtat-------------cccagttcttgcat--gcataag---taaat
a---------aatcttttaaaa--gaattttta-aatctttattta-tttaaaataatac
agaggAAATAATATG---------
>NW023601543.1:50442491-50442862(-)
--ATAGTGGGAGATAAAACCAGTGACATGCTTTGGAAAGATGAAattacacagggcctcc
ctg--gtg-----gtgcaaggtgttaa-------g-cacagca-ctgtgaagttatctat
ccgc----accctctgcagcat-gagttcaatccct-ggc-ca-----------------
ggacagg---gagct--acccac-a-tggc--agagcaga----cctctcctgtct----
------------------------------tgc------------ctgctgctcccc-tc
acca------gtgtatttcagtcagtctgcctg----------------------ttctg
ttccacactctgtctctggtgaatcctctca-------------------ccacccacac
ctctggcc---tgtac-------------ctcagttcttatat--gcataaa---taaat
a---------aataaataaata--tttttctta-agattaagattt-tttaagttcttaa
aaaaagatttattt----------
>NW023604295.1:139612210-139612574(-)
--GTCAATATTTTCTCTCTAGTGGTGAGGATGGTATGAAAATATCTGTAGAGGGTCCTCC
CCA--ATG-----GTGCAATgtgttag-------gacacaac--ctatgaaa----caat
ccgt----agccactgcagcac-gaattcgatcccccagc-c------------------
agccagg---gagca--acgcac-a-tggt--tcagcaga----cctctcctgtct----
------------------------------ccc------------ccgctgctcccc-tc
agca------gtgtatttc----aatctgcctg----------------------ttctg
ttccccactctgtctctggtgaatcctctca-------------------ccatccacac
ctgtggcc---tgtac-------------cccagttcttgtat--gcataaa---caaat
t---------tttttttttaaa--agaaaatat-ctgtagAGGTTT-GCATCTATAAAGC
ATAAAGCAAACATCA---------
>NW023604972.1:64403407-64403755(-)
--CAATGTGATAAACCAAATGttatcccaatttaaaaaaaaaatgaatttgtggacctcc
ctg--gtg-----gcacaaggtgttaa-------g-cacagca-ctgggaag----ctat
ccac----agcctctgtagcac-aagtttgatccct-ggc--------------------
--------------------------tggc--acagcaga----cctcccctgtct----
------------------------------tgc------------ctgctgctcctt-tc
agca------gtgtatttcagtctgtctccctg----------------------ttctg
ttctccgctctgcttctggtgaatcctctcacaccc--------------tgccccatac
ctctggcc---tgtat-------------cccaattcttgtat--gcataaa---taaat
c-------------tttaaaaa--aatggattt-gcaACAAGAACT-CTAAACAGAATGT
CCACCTGCCACCAAT---------
>NW023604295.1:52791561-52791931(-)
--CTACTCTTTGGGGGAATTTCTTCaactttataataaatatgatcttcacagggcctcc
ctg--gtg-----ttgcaaaggGTTAgt--------cacagcc-ctatgaag----ctac
tggc----agccactgcagcac-gagtttgatcccc------------------------
aaccagg---gaggtg-acccac-a-tggt--gcagctga----cctttcctgact----
------------------------------cgc------------ccactgctcccc-tc
agca------gtgtatttcagttaatcctcctG--------------------GTttcag
tttcccactctgtctctggtgaatcctttcacccc---------------taccccacac
ctctgacc---tgtac-------------cctagttcttgtat--gcataaa---taaat
a---------aatcttaaaaaa--tatttaaat-ttgatatGCACA-GACATGGTAGGGG
TATGCTGGATGATAA---------
>NW023605083.1:128934194-128934557(+)
--AGGAAAGGTAGACCAAGAGTtcaagaaagcaaattaaaacaatcatgatagggcctcc
ctg--gtt-----gcacaaggggttaa-----acgaTGCAGCA-ccatgaaa----ctat
ctgc----agccactgcagcat-gagttggatcctg------------------------
ggccagg---gaggtg-acccac-a-tagt--atGGCAGA----Caactcctgtcg----
------------------------------cgc------------ccgctgctcccc-tc
agca------gtgtatttcagtcagtctgcctg----------------------ttctt
ctccccacactgtctctgttgagtcctctcac------------------ctccctgcac
ctctgact---tgtac-------------cccagttcttgtat--gcataaa---taaat
c-------------tttaaaga--aaaccaATC-ATGATAGTtaga-actgttacagggc
aacccaatgtgaaa----------
>NW023605194.1:98684141-98684500(-)
--taaaagtgtTGTTATTTTCCCTGacttatttctaaaatgcattgtcctaggggccttc
ctg--gtg-----gagcaagcagttaa-------gatgcagca-ctatgaag----ctat
gtgc----agccactgcagcac-aagtttgatcccc------------------------
ggccagg---gaggtgaccccac-a-tggc--tcagcaga----cctct--tgtct----
------------------------------tgc------------ccactgctccct-tc
agca------gtatatttcagtcaatccacctg----------------------ttctg
ctccccactctgtctctggtgaatactcac--------------------tttcccacac
ctctggcc---tatat-------------cccagttcttgtat--gcataaa---taaat
a---------aatcttttttta--aaaaatgta-tttccctaGAAA-AACCTATCTGAAT
TTATTCTTTGC-------------
>NW023605194.1:70515508-70515911(-)
--CCTGGGTGATCCAGCTTcctgctcttggttgatttgaaaggcaacttgcggagcttcc
ctg--gtg-----gtgcaagggattaa-------gacacagca-ctatgaag----ctat
ccgc----agccactgcagcac-aagttccatcccc------------------------
ggccagg---gagctgacccccc-a-CGTC--ACAGCAAA----CCTCTCCGAGCCCCAA
CCTTGGCCTATAAACTCCCACCCCAAAGAGCAg------------gtcctgctcccc-tc
agca------gtggatttcagtagatccgcctg----------------------ttctg
ctccccactctgtctctggtgaatcctctca--------------------cccccgcac
ctatggcc---tacaa-------------cccagctcttgtat--acataaa---taaat
a---------atttttttttta--aaaagaaag-gcatgTTGTGAG-GTTTGGCTCTGAC
TGaatgactgggcagttct-----
>NW023603184.1:108022088-108022443(+)
--AATTTAGAGTTTTACTAGTGTTTATCCTTTGCAAAAAGTTTCCTATTACTGGgacccc
ctg--gtg-----gtgcaaggggttaa-------g---tagca-ctatgaag----ctgt
ccgc----agtcactgcaacat-gagtttaatcccc------------------------
atccagg---aaggtg-acccat---tggt--gtagcaga----cctctcctgtct----
------------------------------cac------------ccactgcttccc-tc
agca------gtgtacttcag----tctgcctg----------------------ttctg
ttccccactctgtctccggtgaatcttctca-------------------ccccctgcat
ctctggcc---tgtgc-------------cccacttcttgtat--gtataaa---taaat
g-------------tttttaaa--aagtttcct-atTACTTAAGAAATTAAACATGAAGT
AACTGTTTTGACATAT--------
>NW023605305.1:56612115-56612486(-)
--GCTTTATTCTTTCAACATAAAAAATAAGCAGGTCATTAATAAtaagagaagggcctcc
ctg--gtg-----gtgcaagtgtttaa-------a-aacagca-ctgtgaag----ctat
ccgc----aacctctgcagcat-gagttagatcctgcAGGCCG------------GGTGG
GGGTAGG---GTGTg--gcccac-a-tggc--ctggcaga----tctctcttgtct----
------------------------------cat------------ccacttctcccc-tc
agca------gtgtatttcacttagtctgcctg----------------------ttctc
ttccccactctgtctctggtgagtcttctca-------------------acctcagcac
ctctggcc---tgtac-------------cccagttcttgtgt--gcataaa---taaat
c-------------ttaaaaaa--aaaaataag-aataagaggATG-AATGAAGAAGTTT
GAAGAGGTCTCAGCT---------
>NW023605083.1:132221173-132221538(+)
--GCCCTGTAATTTGGACTAGCGTCTGTCGCTTAAGAAAACCAccgaaacaggggcctcc
ctg--gtg-----gcgcaagaggttaa-------ggcgcaac--ctatgaag----ctgt
ccgt----agt--ctgcagcac-gagttccatcccc-ggccc------------------
gaccagg---gagct--acccac-a-tgga--gcagcaga----cctct-aggtct----
------------------------------cgc------------tcactgctcccc-tc
agca------gtgtacttccgccaatctgcctg----------------------ttctg
ctccccactttgtctctggtgaatcctctca-------------------ccccccacac
ctctggcc---tgtac-------------ccctgctcttgtat--gcataca---taaat
c---------aatctgaaaaaa--gaaaaagaa-aactgcccAAAC-CGTCTGGAGCGCT
CAGCGTGGCCCCCCA---------
>NW023604295.1:36864322-36864690(-)
--ACCACTAACTTTTCTATCAGTAGTATAGGAAAGTTAGAAATcataaatttgggcctcc
ctg--gtg-----gcacaaggggttaa-------gtctcaggt-cTATGAAG----CTAG
AGGC----AACCagtgtagcac-gagttcaatcccc------------------------
agccagg---ctgctg-atccac-a-tgga--gcagcata----cctttcctgtct----
------------------------------cac------------ccgctgctcccc-tc
agta------gtgtatttcagtatatccaccta----------------------ttctg
ctctgcgctctg--tctggtgaatcatcttctcctc-------------ttccccaacac
ctctggcc---tatac-------------cccagctcttgtat--gcataaa---taaat
a---------aatcttaaaaga--gatCATAAC-TTTTTACTTGGT-cataatgaaaaag
agaaatgctgAATA----------
>NW023601653.1:22759931-22760308(+)
--GATAATAGCAATGAAAATgccctatattttccttttaaatggcttttcagggacctcc
ctg--gtg-----gcacaaggggttaa-------gatacaac--ctatgaag----cgat
gcac----agccactgcagcat-gaatttgatgcct------------------------
ggcaagg---gagct--acacac-a-tggc--acagcaga----cctctcctgact----
------------------------------cac------------ccactgctcccc-tc
agca------gtgtatttcagtcaatctgtcta----------------------tgCTG
TTCCcca--ccatctctggtgaatcctctcacccacccccat---cccctacacacacac
ttctggcc---tgtac-------------accagttcttgaat--gcataaa---taaat
a---------aatctttaaaat--aaataaatg-gcttttCATATG-TGACCAAACTAGG
TGTTTTCTACAGGAA---------
>NW023600993.1:74049320-74049658(+)
--TAGAATGGACGATTAAGATTAACCTTTCTTGCAATTGTTAAAtttgacaagggcctcc
ctg--gtg-----gcacaaggggttaa-------gacacaac--ctatggag----atat
ctgt----agccactgcagcac-gagtttgatccct------------------------
ggccagg---gagca--acccac-a-tggc--gcagcaga----cctctcctgact----
------------------------------cac------------ctgctgctcccc-tc
agca------gtgtatttc----aatctgtctt----------------------ttcta
ttcccca--ctgtctctggtgaa-------------------------------------
-tttggcc---tgtac-------------tccagttcttgtat--gcataaa---aaaat
a---------aaccttaaaaaa--ataaagttg-tcaatatatgaa-ttattttttttct
ttttatcccttgttc---------
>NW023604972.1:13519338-13519709(-)
--TGGTGGTGGcggagaatttttttctttccttcttaagaGTTTGAattgctgggtctcc
ctg--gtg-----gtgcaagtg--taa-------gatgcaac--ctatgaag----ctaa
ctgc----agccactgtagcag-gagttcgatcccc------------------------
ggccagg---gagca--acccac-a-tagc--acagcaga----cctctcctgact----
------------------------------cac------------cggctactcccc-tc
agca------gtgtatttcagttaatctgcctg----------------------ttttt
ttccccactctggtactggtgaatcctctcaccccc------------tcccccgacCCT
GCATGGCC---Taaat-------------cccagcttttgtat--gcataaaaataaaat
a---------aatcttaaaaaa--aaaaaaaag-agtttgaattAC-TGTGCAATCTTGG
ATTTTCTAGTGACCT---------
>NW023600993.1:85190618-85190979(-)
--TGGTAAGTGGTGAGGAGAAAAAGCAGGAATGGGTATAAAAATTAGttcctgggccacc
ctg--gtg-----gcctaagggggtga-------g-cacagca-ctgtgaag----ctgt
ccgc----agcctctgcggcgc-gagttcgatccct-ggc-c------------------
ggacagt---cagct--acccac-a-tggc--gcagcaga----cctctcctgtct----
------------------------------cgc------------tggctgctcccc-tg
ggca------gtggaCTTCAGTCAGCCGgacag----------------------ttctg
ctccctg------ctctggtgaatcctctcactca---------------ccctgcacac
ctctggcc---tgtac-------------cccagctcttgtat--gcataaa---taaat
c-------------cttaaaaa--aattaattc-aaagtacCATTT-TAGTTACTCTTCT
CGGAAAGAACAAGAG---------
>NW023603184.1:87227195-87227565(-)
--CCATTAGATATTTCATAGCTGATTTATCAACTATAAAAATAACTTGgcccgggtctcc
ctg--gtg-----gtgcaaggagttaa-------g-caccgca-ctatgaag----caat
ccac----agcctttacaccac-aagttcaataccc-agc-c------------------
ggccagg---aagga--acccac-a-aggc--acagcaga----cctctcctgtct----
------------------------------cgc------------ccactgctcccc-tc
agca------gtgtatttcagccagtccgcctg----------------------ttctg
ttcccca--ctgtctctggtgaatcctctcaccc----------------cccaaaaaaa
ctccagcc---tgtac-------------cccagttcttgtat--gcataaa--------
------------tctttttaaa--aaataacttgtccCTACTTACA-TATTGAAAGgaat
tcatatatacatatatatttacat
>NW023604861.1:79099999-79100360(-)
--tcttctatgcataaataaataaaaaataaatctttagaaaaaaagaaagagggcctcc
ctg--gtg-----gcacaaggggttaa-------gacacaac--ctatgaag----ctat
ctgc----a--cactgcagcat-gagttctaattcc-----c------------------
agccagg---gtgct--acccac-a-tggt--acagcaga--cctctctcctgtct----
------------------------------ctc------------ccgctgctccca-tc
agca------gtgtatttcagtcagtctgactg----------------------ttctg
ttcccca------ctctggtgaattctcccactgcc------------ccccacacatac
ctttggtc---tgtac-------------cccagttcttgtat--gcataaa---taaat
a---------tatattttttta--gatttattt-atttatttatac-aagcactgggtat
attcagaagtg-------------
>NW023605194.1:34620437-34620809(-)
--CCTGTGTAGGAAAGGGTctagaaaattttcctttaagagATTTCCTTAAAGGGCCatg
ctg--gtg-----gtgca-gggcttaa-------a-gccagtg-ctatcaag----ctat
cccc----agcgactgcagcaa-gagttcaatcccctggc-t------------------
ggccagg---aagca--acccac-a-tggg--gcagcaga----cctcacctgcct----
------------------------------cac------------ccgctgctcccc-tc
agca------atatatttcagtagatctgcctg----------------------ttctg
ctccccactc--tctctggtgaatcctctcaccccc------------tttccCCAGTGT
CTCtaact---tacac-------------cccagttcttgtat--gcataaa---taaat
a---------aatcttaaaaaa--agagatttc-ctTAAAGCCAAG-GTATATAAGATAT
AAAGAAGTAGTCATA---------
>NW023603184.1:104950544-104950909(+)
--TTAAACCTTACAAATGTACAAGTTGTCTTGCTACAATAAAACTAAAtaaggggcctgc
ctg--gtg-----gcccaagta--taa-------a-gacagct-ctatcaag----atAC
TGCCAgctagccactacagcac-gagtttgatccct-ggc-t------------------
ggccagg---gagca--accgat-A-TGGT--ACAataga----cctctcctttct----
------------------------------tac------------tggctgctcccc-tt
agca------gtgtatttcagtcgatctgagtg----------------------ttctg
ctccctactc--tctctggtgattcctccca-------------------ccccc--cac
cccagtct---tacac-------------cccagttcttgtat--gcataaa---taaat
a---------aatctttaaaaa--aaaaaaaaa-cctaaatatata-cacatcaaaaaat
aaataaaaatagtac---------
>NW023601212.1:74986910-74987269(+)
--TAGGTCCTCCACCGAGGGAGCCACCTTGTCTCTGAACAATggaaaatcctgggcctcc
ctg--gtg-----gtgcaggggttaaa---------gacagtg-atatgaag----ctat
tgcc----agccactacagcac-gagtttgatccct-ggc-c------------------
ggccagg---gagct--acccat-g-tggc--acagcaga----cctcttctgcct----
------------------------------tgc------------ccgctgctcccc-tc
agca------gtgtatttcaggagatctg-------------------------------
---cccactccgtctttggtgaatcctctta-------------------ccccctggac
ctctggccttttatac-------------cccagttcttgtat--gcacaaa---taaat
a---------attgtttttaaa--aaataatgg-aaaatccTCCCT-TATTGCTCTCAGT
TTTGGGACCAAAACC-------AG
>NW023601322.1:10281618-10281973(+)
--TACTGTTATAATTATTGAGAAGAAAGATTGCTTAATAATATggtcctttagggcctcc
ctg--gtg-----gcgcaaggggttaa-------g-tattgca-ctatgaag----caat
-------------cagcagcac-aagtttgatcccc-ggc-c------------------
ggccagg---gagca--acccac-a-ttgt--gcagcaga----actctcatgtct----
------------------------------cgc---------------ctgctcctc-tc
agca------gtgtatttcagtcagtctgcctg----------------------ttcgg
ttccccactctgtctctggtgaatcctttca-------------------cccctgtgTC
TCCCGGCT---TATAC-------------CCCAggtattgtat--gcataaa---taaat
a---------aatctttaaaaa--aaataatat-ggtcCTTTAGTA-AGGCTCAGCAGGA
GTATGTGGGCTATGA---------
>NW026555331.1:46832520-46832881(+)
--aaaatttagaaatactcTCTTTATAAATGTTCTTCAAGATTTCCATTTAcgcgcctcc
ctg--gt------------ggggttaa-------g-cactgca-ctatgaga----caat
ccgc----agcctctgcagcac-aagctcgatcccc-ggc-c------------------
tgccagg---gagaa--acccac-a-tggc--gaggcaga----ct-------gct----
------------------------------cgc------------ctgctgctcccc-tc
agca------gtgaatttcagtcagtctgcctg----------------------ttctg
ttccccactctgtctctggtggaaccTCTCACACCc-----------cctacccctgcat
ctctggcc---tgtgc-------------cccagctcttgtat--gcataaa---taaat
a---------aatctttgaaaa--aaaaagatt-tccgtTTATTAA-TTAGAATCTCAGC
CTTTAAGTGACTTAC---------
>NW023602073.1:15564269-15564634(-)
--TATGGGAAAATCCCTGCAGAAGCAACCTAAATAGAAAATAGatgactcctgggcctcc
ctc--ggg-----gcacaaggggttaa-------g-cacagca-ctgtgaag----ctat
cctc----agcctctgcagcat-gagttccatttgT-GGC-T------------------
GGCCCGA---AAGCCA-ACTTAC-A-TGGC--ACAGTA------CCTCGCCTATAT----
------------------------------TGC------------CCGCTa-ttccc-tg
agca------gtgtattccagtcagtctgcctg----------------------tgctg
ttccccattcagtctcaggtgaatcctttcaccgtc--------------cgcccaacac
ctctggcc---tgttt-------------ccTAGCTCtagt---tgcataaa---taaat
c-------------tttaaaaa--aataaatgg-tgggATAAAATA-CATACTTAAAATG
GCAGCACACCAGTGC---------
>NW023603184.1:137018572-137018918(-)
TATCCCAGGTTTCTTATTCTCATACTGAATACTCAGAATAA-------------------
-----GAgt----acacaaggggttaa-------g-cacagca-ctatgaaa----c--t
ccgc----agcttctgcagcac-aagtttgatcccc------------------------
agtcagg---acact--acccac-a-tggc--gcagcaga----gctctcttgtct----
------------------------------tgt------------ctgctgctcccc-tc
agca------gtgtatttcagtcagtctgcctg----------------------ttctg
ttccccactctgtctctggtgaatcctctcaccccac---------ccacacacacacac
acacacac---tgtacacacacacccctggccagttcttgtat-------------aaat
a---------cctttttttaaa--aaaaaaaaa-gatttatttatt-tatttatacaagc
actg--------------------
>NW023602073.1:41895570-41895955(-)
----CTGACGGaacagggaaacaaaataaatatggaaaaagatGATTGAACTCAGCCTCC
CTG--ATGGTTTTGTGCAAGGGTTACGT--------cccagcg-ctatgaag----ctat
cccc----agtcagtgcagcag-gagttcaagccCA------------------------
GGCCAAG---GAAcg--aaccac-a-tggt--gcagtaga----tctctcctgtct----
------------------------------cacccatctCGAGcaccgctgcttccc-tc
agca------gtgtattttagtagatttgcctg----------------------ttctg
ctccccactctgtctctcgtgattcttctcac------------------caccccgcac
ttctgact--taacac-------------cccagctcttgtat--gcataaa---taaat
a----aaataaatctttaaaaa--aaaaaaaat-tgacccatAAGA-TGAACCACCTTGA
TGTAATGTCCATGTA---------
>NW023605083.1:133054435-133054779(-)
--TCACATGCATTAAACATCGATGTCAACAAGCATTGATGAAAGtacaacctgggcctcc
ctg--gtg-----gcgcaaggggttaa-------gacgcagca-ctatgaag----ctat
ccac----agccactgcagcac-aagttcaaacccc------------------------
aggcagg---gaactg-acccac-a-tggc--gcagcaga----cctctcctgtct----
------------------------------c-c------------ccgctgctcctc---
-----------------tcagtcaCGCCACctc----------------------ttcta
ctccccactctgtctctggtgcatcctctca--------------------cccccacac
ctctggcc---tgcac-------------cccagttctttaaa--aaaaaaa---aagta
c---------aacctCCACCAATT---TACCTG-GTGCGTTCCTGT-CACCCAACGAAGT
CTCCTCATGC--------------
>NW023605083.1:10744821-10745178(+)
--ctctTCAAGGAATGTTAAGACTGTTcgggcaatttaaaaaaaaataccaggggCCTCT
GTA--GTAG----GCGCTTGgtggtaa-------gtctcagca-ctgtgaag----ctat
-------------ctgcagcac-cagttccattcac------------------------
agccagg---gagcta-acccac-a-gggc--gcagcaga----cctctcctatct----
------------------------------tgc------------tcgcag-acccc-tc
agcagtgcatgtgcatttcagtagatcctcctg----------------------ttc--
-tccccattctgtctctggtgaatcctctcaccccc------------caccccccacac
ctatggcc---tgtac-------------cccaactcttgtat--gcataaa---aaaaa
a---------aaagaacagaat--acagTGGTT--------CAAAC-TTATCAGTTGTTA
AGATTTGGTCATT-----------
