>g1 Consensus of sequences 2-71
---------------------------------------------------GGGCCTCCC
C------GGTGGCGCAG-CG--GTTG----------AGCGCTGGGTTGCGAA--------
------GCTGCCC-GCAGCCTCTG---CAGCGC-CGGTTCGATCCCCGGCTG-----CTC
CCCGGCCACCG------GAGGAG----GGTC-----CCAC-ATGGCGCAGCAGACCTCTC
CTGC----CGCC----------CGCTGCT-------------CCCCTCAGCAGTGTACTT
CGGTCCT------------TCTGCCTG-CTCTGCTCCCC-------------GCTCTGG-
CTCTGGTGAATTC-TCTCA-----CC--------CTC------CCGCGCTTCTG-AC-TG
TACCC--AGTGCTTGT------ATATAAAAAT--------AAAAAAT----------CAA
TCAATAATAAAAAATAAATAAAATAAATAA-ATAAATATAATA---------AATCTTTA
AAA---------------
>g2 Consensus of sequences 3-49
---------------------------------------------------GGGCCTCCC
C------GGTGGCGCAG-CG--GTTG----------AGCGCTGGGTTGCGAA--------
------GCTGCCC-GCGGCCTCTG---CGGCGC-CGGTTCGATCCCCGGCTG-----CTC
CCCGGCCACCG------GAGGAG----GGTC-----CCAC-ATGGCGC-GCAGACCTCTC
CTGC----CGCC----------CGCTGCT-------------CCCCTCAGCAGTGTACTT
CGGTCCT------------TCTGCCTG-CTCTGCTCCCC-------------GCTCTGG-
CTCTGGTGAATTC-TCTCA-----CC--------CTC------CCGCGCTTCTG-AC-TG
TACCC--AGTGCATGT------ATAAACAAAA------ACAAACAAA----------CAA
ACACAAAAAATAAATAAATAAAAAACATGC-CTCTATAAAA-------------------
------------------
>g3 Consensus of sequences 4-102
-------------------------------------------------------GGCCC
C------GGTGGCGCAG-CG--GTTG----------AGCGCTGGGCTGCGAA--------
------GCTGCCC-GCAGCCTCTG---CAGCGC-CGGTTCGATCCTCCCCGGCCGCCCTC
CCCGGCCACCG------GGCGAG----GGTC-----CCAC-ATGGCGCGACAGACCTCTC
CTGC--CGCGCC----------CGCTGCT-------------CCCCTCAGCAGTGTATTC
GG-TCAG------------TCTGCCTG-TTCTG-TCCCC-------------GCTCTGG-
CTCTGGTGAATTC-TCTCA-----CC--------CTC------CCGCGCTTCTG-AC-TG
TACCC--AGTGCTTGT------ATAAATAAAT--------AAATAAATAAA------TCT
TTAAAA------------------------------------------------------
------------------
>NW026555331.1:111934911-111935278(-)
TCTGAGCATCAGCATAGTCTTGCTCTGttccataaaatttttttttttgagggcctcccc
t------ggtggcacaggtg--tttg----------agcgctgcactgtgaa--------
------gctgtta-gcaacctctg---cagggc-cggttcga-----------------t
ccctgtcggcc------ggcgag----ggtc-----ccac-atggcgcggcagacctctt
ctgt--ctctcc----------cgctgct-------------cccctcagcagtgtattt
ca-tcag------------tctgcctg-ttctgttcccc-------------cctctgt-
gtttggtgaatcc-tctca-----cc--------ctc------ccacgcatctg-gtctg
tacctg-ggttcttgt------ataaataaat--------aaataaa----------tct
taaaaaaattttttttgaaagaaaggatAT-TGTTGACAGGTG------ATGTAGGGGTC
GTT---------------
>g4 Consensus of sequences 5-248
---------------------------------------------------GGGCCTCCC
T------GGTGGCGCAAGGG--GTTA----------AGT-CCCCACTATGAA--------
------GCTATCC-GCAGCCACTG---CAGCAG-AGTTCGAT----------------CC
CCCGGCCGGCCGCAGCAGGGGAG----CTAC-----CCACAATGGCGCAGCAGACCTCTC
CTGT--CTCGCC----------CGCTGCT-------------CCCCTCAGCAGTGTATTT
CA-GTCA------------TCTGCCTG-TTCTG-TCCCC-------------ACTCTGT-
CTCTGGTGAATCC-TCTCACCCC-CC--------CCC------CCCCACCTCTG-GCCTG
TACCCC-AG-TCTTGT------ATGCATAAAT------------AAA----------AAA
TAAAAATAAATCTTTAAAA-----------------------------------------
------------------
>g5 Consensus of sequences 6-121
---------------------------------------------------GGGCCTCCC
T------GGTGGCGCAGGG---TTGA----------GTCGCAGCGCTGTGAA--------
------GCTGTCC-GCAGCCTCTG---CAGCGC-GGTTCGAT-----------------C
CCCGGCCGGCC--------GGAG----ACCC-----ACAT-ATGGCGC-GCAGACCTCTC
CTGT--CTCGCC----------CGCTGCT-------------CCCCTCAGCAGTGTATTT
CA-GTCG------------TCTGCCTG-TTCTGTCCCCC---------------TCTGT-
CTCTGGTGAATCC-TCTCA-----CC--------CCC------TCCCGCCTCTG-GCCTG
TACCCC--GTTCTTGT------ATATAAATAT--------AAATAAA-------------
-TAAAAATAAATCTTTAAAA----------------------------------------
------------------
>NW023601322.1:74786826-74787198(+)
-CAGGTGAATGTGGTTCATGTACAAACTATAAATAAGAAACCtggaggagggggcctccc
c------ggtggcgcagcgg--gttg----------agcgcagcgctgtgaa--------
------gctgtcc-gcagcctctg---cagtgt-gggttcaa----------------tt
cccggccggcc------ggggag----attc-----ccac-atggcg-ggcagacctctc
ctgc--ctcgcc----------cgctgct-------------cccctcagcagtgctttt
gg-tctg------------tctgcctg-ttctggtcccc-------------attctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccgcacctctg-gcctg
tattcc-agctcttgt------ataaatttaa--aaaaaaaaaaaaa----------act
taaaaaaaaaaagaagaaaccaggaGAACT-AGTGTGAACGAG------ATGACCACTCT
GCC---------------
>NW023604295.1:99075468-99075833(+)
-CAGTGTTTCcctaataaaaaaatcatttatagaTTCAAGAATTAAAgcttgtgcctccc
t------ggtggcgcagtgg--gtcg----------agcacagcgctgtaaa--------
------gctgtcc-gcagcctctg---cagcgt-gggttcga----------------tt
cctggccagcc------agggag----attc-----ccac-atggcatggcagacttctc
ctgt--tgcgac----------cgctgct-------------cccctcagcagtactctc
ag-tcca------------tctgcctg-ttctgctcccc-------------attttgt-
ctctagtgaatcc-tctca-----cc--------ctc------ctgcgcctctg-gcctg
tacccc-agctattgt------attaaaaaaa----------aaaaa----------tct
taaaaaaaaaaaattgaagcttgATAAACT-ATGAATTTGAAA------ACAGTGCAACA
AAA---------------
>NW023604861.1:28827379-28827741(+)
----gaaatttggggttttttcaatgtaataaataaataaataaaagtatagcaccaccc
t------ggtggtgcagatg--gttg----------agcgctgcactgtgaa--------
------gctgtcc-acagcctctg---caacgc-agttttga-----------------t
tctggccggcc------ggggag----atac-----ccac-atggcacagcagacctctc
ttgt--cttgcc----------cactgct-------------cccctcagcagtgtattt
ctgccag------------tatgcctg-ttctgttccct-------------gctctgt-
ctctggtgaatct-gctca-----tc--------ctc------ccgcacatctg-gcctg
taccct-ggttcatgt------atatataaaa----------ataaa----------tct
ttaaaaaaaataaaaataaaagttggctCT-Tctagaagataa------acaaaatgaat
taa---------------
>NW023601265.1:3435-3801(+)
-TAATTGAGGTTGTTAtactttcagaaaacaaaaataaataatgaaatttggggccttcc
c------ggtggtgcagcgg--gttg----------agtgcagcactgtgaa--------
------gctgtcc-acagcctcta---caatgt-gggtttga----------------tt
cccagccagcc------agggag----attc-----ccac-atggcgcagcagacctctc
ctgt--cttgcc----------cactgct-------------cccctcagcagtgtattt
ccgtcag------------tctgcctg-ttctgctccct-------------gctctgt-
ctctggtgaatcc-tctta-----cc--------ctc------ccacaactctg-gcctg
tacccc-agctcttgt------ataaa--aat--------aaataaa----------tct
taaaaaaataataataataatgaaatttaa-cCTTATCCTCTT------ATAGGATATGT
GAT---------------
>NW023601212.1:46209453-46209819(+)
-AGATAGAGATAAATGTAGTGATAGAGATTTGaataaagacatggatataagggcctccc
c------ggtggcacaggga--gttg----------agcgcagctctgtgaa--------
------gctgtct-gcagcctctg---cagcgt-gggttcga----------------tt
tccggccagcc------agggag----caac-----ccac-atggcgcagcagacctctc
cagt--ctcgcc----------tgctgct-------------cccctcagcagtgtattt
cagtccg------------tctgcctg-ttccgttcccc-------------actctgt-
ctctggtgaatcc-tctca-----cc--------ctc------cagcacctctg-ccctg
tacccc-agctcttgt------ataaa--aat--------aaataaa----------tct
ttaataaaaaaaagacatgaagggcctccc-cggtggcacagc------ggttgagcgct
gcg---------------
>NW023604295.1:80832931-80833295(+)
-cccagtgcttatataaataaataagtcttttaaaaaatatatatacttgggggcctccc
c------tgtggtgtaGCGG--cctg----------agtgcagtgctgtgaa--------
------gctgtcc-aaagcctctg---cagcac-aggtttga----------------tt
cctggccagcc------agagag----atat-----ccac-atggtgtgacagacctctc
ctgt--ctcacc----------tgctgct-------------cccctcagcagtgtattt
cagtcag------------tctgcctg-ttctgctcccc-------------actctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccatgcctctg-gtctg
tacccc-agctcttgt------ataaataaat------------aaa----------tct
ttaaaaaaataaaataaaatgtacttgggc-ctccctggtagc------tcaaggggtta
agc---------------
>NW023601212.1:28644988-28645355(-)
--CAGGCTACCCATTTCATATTGcagttgccctgtaacagttagactaggtagggcctcc
c------ggtggcacagtga--gttg----------agcgcagcgctgtgaa--------
------gctgtcc-acagcctctg---cagcgt-gggttcaa----------------tt
cccagccggcc------agggag----attc-----ccac-gtggcgtggcagacctctc
ctgt--ctcacc----------cattgct-------------cccctcagtagtgtattt
cagtcag------------tctgcctg-ttctgctcccc-------------gctctgtc
ctctggtgaatcc-tctca-----cc--------ctc------ccgcacctctg-gcctg
tacccc-agctcttat------ataaa--aat--------aaataaa----------tct
tctaaaaaaattaaaaaaaaaaaaccagtt-agACTAGGCATG------TACTAAAAAGT
TTTA--------------
>NW026555331.1:81859691-81860056(+)
-ttgagataccaccttacaccagtaagaatggcatatataaacaagcaacagggcctccc
t------gggggcacagcca--gttg----------agcacaacgctatgaa--------
------gctgtc--gtagcctctg---cagtgc-gggttcaa----------------tt
cccggctggcc------agggag----attc-----ccac-atggtgcagcagacctctc
ctgt--catgcc----------cgctgct-------------cccctcagcaatgtattt
tggtcct------------tctgcctg-ttctgctccct-------------tctctat-
ttctggtgaatcc-tctca-----cc--------ctc------ccatgcctctg-gccta
tacccc-agctcttgt------ataaa--aat--------aaataaa----------tct
ttaaaataaaaaagcaacaacaaatgtggg-caaggatgtggt------gacaaaggaac
tct---------------
>NW026555331.1:59288628-59288992(+)
-taatttaaaaaaatcctagaaaaaaattaataaaaataatgttgattttagggcttccc
t------ggtggcgcaggcg--gttg----------aacaccgCACCGTGac--------
------gctgtcc-gaagcctctg---cagcgt-gagttcaa-----------------t
ccctgccggcc------ggcaag----aatc-----tcac-atggtgcaacagacctctc
ctgt--cccgcc----------tgctgct-------------cccctcagcagtgtattt
ca-gtcg------------tctgcctg-ttctgctcccc-------------atactgt-
ctctggtgaatcc-tctta-----cc--------ctc------ctgcacatccg-gcctg
tacccc-agctcttgt------ataaa--aat--------aaataaa----------tct
tttaaaaataataataataatgtagaTTTT-AATAACCTAGAA------CCACTTCATAC
TTT---------------
>NW023602073.1:83945899-83946262(-)
-tcaggggaaaaagtaattataataaattaaaaatgaaaatcatgggacctgggcctccc
t------ggtggtacaggtg--gttg----------agtgctgc-ctgtgaa--------
------gctgtct-gaagcctctg---caatgc-aggttcga-----------------t
cctggccagcc------ggtgag----aagc-----ccac-atggtgtggctgacctctc
ctgt--catgcc----------tgctgct-------------cccctcagcagtgtattt
ca-tcag------------tctgcctg-ttctgttcccc-------------gctctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccacacctctg-ccctg
tacccc-aattcttgt------ataaa--aat--------aaataaa----------tct
tttaaaaaaaaagaaaatcaataggcaact-ataaatcagaag------cattctgtagg
gga---------------
>NW023601433.1:33892281-33892648(+)
catatgcaaaaatattcaGAATTGTTTAGTcattatagaaatagaaattagggcctcctc
t------ggtggcacaggca--gttg----------agcgtagcactgtgaa--------
------gctgtcc-gcagcctctg---cagtga-cggttcaa-----------------t
cccggcaggcc------agcaag----ggtc-----ccac-atggcacagcagacctctc
ctgt--ctcgcc----------agctgct-------------ccactcagcagtgtattt
cg-tcag------------tctgtctg-ttctgttcccc-------------tctctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccgcgcatctg-gccta
tacccc-ggttcttgt------ataaataaat--------aaataaa----------tct
ttaaaaaaaaaagaaagaaatagaaattaa-aagcacaaaaga------TTTGGCCATAG
TAT---------------
>NW023604972.1:112489484-112489851(-)
TTCTACAGGGCATgagtgtacgtgtgtgtgtattagaagagggagaaagagggcctcccc
t------ggtggcacaggag--gttg----------agtgcagcgctgtgaa--------
------gctgtcc-acagcctctg---cagcac-cagttcga-----------------t
ccaggctggcc------attgag----aatc-----ccac-atggggcggcagacctctc
ctgt--ctcacc----------cgctgct-------------cccctcagcagtgtattt
cg-tgag------------tctgcctg-ttctgttcccc-------------acactgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccgcgcatctg-gcctg
tacccc-ggttcttgt------ataaataaat--------aaataaa----------tct
ttaaaaaaaaaaaaaaaaaaaagaaaagaa-gagggagaaaga------gaccaaaactt
tag---------------
>NW023604972.1:77134661-77135028(+)
ATTGAGATACACCAGACAATCAAAGGGCTATTTCAAGAAACtaagcaagagggcctcccc
t------gttggcgcaggcg--gttg----------agcacagtgctgtaaa--------
------gctgtcc-gcagcctctg---cagcat-cggttcaa-----------------t
cccagccggcc------ggtgag----ggtc-----ccac-atggcacagcagacctctc
ctgt--cacgca----------tgctgct-------------cccctcagcagtgtattt
ca-tcag------------tctgcctg-ttctgttcccc-------------actctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ctgcgcatctg-gcctg
taccct-ggttcttgt------ataaataaat--------atataaa----------tct
taaaaaaaaaaagagtagtatcttaaaaaa-aaaaaaaacctg------agcaaAAACAC
AGT---------------
>NW023605305.1:82358133-82358492(-)
TCCTGCTAGGCAAACCCAGTGTTGCTGatggggaaaaagaagagaaataagggcctcccc
t------ggtggcacagaca--gttg----------agcgcagtgctgtgag--------
------gctgtcc-acagcctctg---cagcac-cagttcga-----------------t
cccggccggct------ggcgag----ggtc-----ccac-atggcatggcacacctctc
ctgt--ctcgcc----------cgctgct-------------cccctccgcagtgtattt
cactcag------------tctgcctg-ttctgttcccc-------------actctgt-
ctctggtgagtcc-tctca-----cc--------ctt------ccatgaatctg-gcctg
tacccc-ggttcttgt------gtaaataaat--------aaaaaaa-------------
-aaaaaaaagagagagagaaacaacagGTG-AGCAAGAATAGC-----------------
-------ATTCATTGT--
>NW023604295.1:43545154-43545521(+)
GAATGTCTCACTGCTGCATGGATCTTTTCTCTCTATAAAGTgcagatccagggcctcccc
t------ggtggcgcaggta--gttg----------agcacagtgctgtgaa--------
------gctgtcc-gcagcctctg---cagctt-tggttcga-----------------t
cccggccggct------ggcaag----agtc-----ccac-atggcacggcagacctctc
ctac--cacgcc----------cgctgct-------------cccctcagcagtgtattt
tg-tcag------------tctgcctg-ttctgttccct-------------actctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccgcgaatctg-gcctc
tacccc-ggttcttgt------ataaataaat--------aaatacc----------tct
ttaaaaaaaaataaagtgcagatCCAGGTC-TCTTGACTTTCT------TATTGATCAAG
ATC---------------
>NW023600993.1:77934166-77934529(-)
-taaaaatatgaagaatgtaaattttttttaaaaaaaatcaataaaagggagggcctccc
t------gatggcacaggca--gttg----------agcaccgcactgtgaa--------
------gctgtcc-acagcctctg---cagcgc-aggttcaa-----------------t
cccagccaggc------agcgag----ggtc-----ccac-atggcacagcagacctctc
ctgt--cttgcc----------cgctgct-------------cccctcagcagtgtattc
ca-tcag------------tctgcctg-ttctgttcccc-------------gctctgt-
ctctggtgaatcc-tct-a-----cc--------ctc------ccgtgcatctg-gcctg
tacccc-ggttcttgt------ataaataaat----------aaaaa----------tct
ttaaaacaaaataataaaaggaaaaaaaaa-aaccttcaaact------TCTAACTCTAA
ATT---------------
>NW023601543.1:8425378-8425742(-)
-GGTGCTGACAACTGTGAAAGAACATCCTCGtgaaaaatgacttaaatatggggcctccc
t------ggtggcacaggtg--gttg----------agcgccgcactgtgaa--------
------gctgtcc-gcagcctctg---cagtgc-aggttcga-----------------t
cccagcaggcc------agcgag----aatc-----ccac-atggcaaagcagttctctc
ctgt--ctcacc----------cgctgct-------------cccctcagcagtgtattt
ca-tcag------------tctgcctg-ttctgttcccc-------------actctgt-
ctctggtgaatcc-tctca-----cc--------ttc------ctgcacatctg-gcctg
tacccc-ggttcttga------ataaa--aat--------aaataaa----------tct
ttaaaaaaaatgactgaaataataGTGGTT-GGGGAATCGAGC------ATAATCATGTT
CTC---------------
>NW023604861.1:122176805-122177169(-)
-GATTATCCAAAAGAAGACACAATGTCAAAACTAAAAGTGTGtgaacttcagggcctccc
t------ggtgacgcaggcg--gttg----------agcaccgcactgtgaa--------
------gctgttc-acagcatcgg---cagcgc-ggattcga-----------------t
cccagctggct------ggtgag----aatc-----ccac-atggtgcagcagacctctc
ctgt--ctcgcc----------cgctgct-------------cccctcagcaatgtattt
cg-ttag------------tctgcctg-ttttgttcccc-------------gctctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ctgtgcatctg-gtttg
tacccc-agctcttgt------ataaataaaa----------taaaa----------tct
ttaaaaaaaaaaaaaagcgtgtGAACTTCA-TTCTGGGTCAGT------ACAGCAAGCAC
ACA---------------
>NW023601104.1:88117036-88117399(-)
TGAAAATTAtatgttacttcaacaaaaattatttaaaaacagaaaaaatagggcctcccc
c------gatggtgcaggca--gttg----------agcgcactgctgtgaa--------
------gctgtcc-acagcctctg---cagtgt-aggttcga-----------------t
cccagccagcc------ggtgag----atac-----acac-atggcgcagcagacctctc
ctgt--ctcacc----------tactgct-------------cccctcagcagtgtattt
ca-tcat------------tctgcctg-ttctgttcccc-------------actctgt-
ccctggtgaatcc-tctca-----cc--------ctc------ccacatatctg-gccta
tacccc-aattcttgt------ataaataaat------------aaa----------tct
ttaaaaataaagcatagaaaAAATACAGCT-GATGATAGATTA------AGATACAGTAT
AAA---------------
>NW023603184.1:28071761-28072127(+)
ATGTtcatctagaaaaataaataaacctactttttaaaataacttattctgggcctcccc
t------ggtggcgcaggca--gttg----------agcgccacgctgtgaa--------
------gctgtgc-gcagcttctg---cagtgc-tggttcga-----------------t
cccggccgacc------ggcgag----ggtc-----ccac-atggtg-agcagacctctc
ctgt--ctcgcc----------cactgct-------------cccctcagcagtgtattt
cg-tcag------------tctgcctg-ttctgttcccc-------------gctctgt-
ctccagtgaatcc-tctca-----cc--------ctc------ctgcacatctg-gcctg
tacccc-ggtttttgt------ataaataaa--------------------------tct
ttaaaaaaataaaataacttattttaacaT-GAAACTAGAATA------GACAACAAATG
CATGGTGGGCT-------
>NW023602073.1:139088464-139088823(-)
-CATAGAGATCTATAGAGGATAAAGCAGAGATTTTAAGAACAttcaaatgagggcctccc
t------gttggcgcaggcg--gttg----------agcgccgctctgtgaa--------
------gctgtct-gcagcctctg---cagtgc-aggtttga-----------------t
cccggccggct------ggcgag----ggtc-----ccac-atggcacagcagacctctc
ctgt--ctcgtc----------tgctcct-------------cccctcagcagtgttttt
ca-tcag------------tctgtctg-ttctttacccc-------------actctgt-
ctccggtgaatcc-tctca-----cc--------ctc------ctgtgcatctg-gcctg
tacccc-aactcttgt------ataaataaaa-------taaataaa-------------
-taaaaaagaacattcaaatgagagaaggg-aaaagacaatAA-----------------
--------TTCAGGGCAA
>NW023601653.1:77324501-77324862(-)
AGTGATGGTTCTCACTGtacatgaattttctttaaaaaacaaccctgatggggcctcccc
t------ggtggcgcaggag--gttg----------agcacagcgctgtgaa--------
------gctgtcc-acagcctctg---cagtgc-gagttcca-----------------t
cccggccagcc------agggag----aatc-----ccac-atag-gcagcagacctctc
ctgt--cttgcc----------cgctgct-------------cccctcagcagtgtattt
ca-tcag------------tctgcctg-ttctgttcccc-------------gctctgt-
ctctggtgaatcc-tctca-----gc--------ct-------ccacacatctg-gcctg
aacccc-agttcttgt------ataaataaat------------aaa----------tct
ttaaaaagaaaaaacaaccctGGTGAATTT-AAGGTAGGGTTT------CCATTGttgta
tat---------------
>NW023604861.1:124358507-124358870(-)
-TAGAAGCCCTCGCAAGTTCATTCAGAACTCCTTTTAAAAGTatctgtgttgggcctccc
t------ggtggcacaggcc--gttg----------agcgccgcattgtgaa--------
------gctgtcc-gcagcctctg---cagcgt-gggtttga-----------------t
cccagcctgcc------agagag----aatc-----cca--atggtgcagcagacctctc
ctgt--ctcgcc----------tgctgct-------------cccctcagcagtgtattt
ca-tcag------------tctgcctg-ttctattcccc-------------gctctgt-
cttcggtgaatcc-tctca-----cc--------ctc------cctcacatctg-tcctg
taccct-ggttcttgt------ataaa--aat--------aaataaa----------tct
ttaaaaaaaaaaaaagtatctgtgtTCCTG-GCTTCTGCACAT------AGTAGGCGCCA
AGT---------------
>NW023601322.1:85581617-85581980(-)
-GTATCTGCTGATACTTGAGAATCAGGGCAGATTTTCTAAACACAagagcagagcctccc
t------ggtagcacaggtg--gttg----------agctctgcactgtgaa--------
------gctgtct-gcagcctctc---cagcgt-gggtttga-----------------t
cccgaccggcc------ggcgag----aatc-----ccag-atggtgcagcagacctctc
ctgt--ctcgcc----------ctctgct-------------cccctcagcagtgtattt
cggtcag------------tctgcctg-ttctgctcccc-------------gctctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccacacatctg-gccta
tacccc-ggttcttgt------ataaataaat------------aaa----------tct
ttaaaaaaaataaaaaaataaaaccacagg-agCAGGCATAGC------TACAGAGCTGC
AGG---------------
>NW023605083.1:24818055-24818414(-)
-GAAGTAAATGACACAAATGGATTCTATCacccaattagaaaatgaaacaagggcctccc
c------ggtggcacagggg--gttg----------agtgcagcactgtgaa--------
------gctgtcc-acagcctctg---tagcat-gggctTGA-----------------T
CCTGGACGGCC------Agaggg----atac-----ccac-atggtgcagcagacctctc
ctgt--ctcacc----------cgctgat-------------cccctcagcagtgtgttt
cagtcag------------tttgcttg-ttctgttccct-------------gctctgt-
cactagtaaatcc-tctca-----cc--------ctc------ccacacatctg-gccta
tacccctggttcttgt------ataaataaat------------aaa----------tct
aaaaaaaaaaaaaaaaaaagaaaagaaaat-gagaaacaagaC------AGGAAGAAT--
------------------
>NW023602073.1:113981553-113981915(+)
-AATGCAGAGCTTTACCATTATaagaattccatttttaaaaaagttgtctggggcctccc
t------ggtggcgcaggtg--cttg----------agcgccacactgtaaa--------
------gctgtct-acagcctctg---cagcac-gagtttga-----------------t
ccctgccggcc------catgag----aatc-----ccac-atggcatagcagacatctc
ctgt--cttgcc----------cactgct-------------cccctcagcagtgttttt
tg-tcag------------tctgcctg-ttctgttccct-------------gctctgt-
ctctggtaaatcc-tctca-----cc--------ctc------ccgcacatctg-gcctg
taccac-ggttcttat------ataaataaat------------aaa----------tct
ttaaaaaataaaaataaatttaaaaataaa-aataaaaaagtt------gtcTGGGGCAT
AGA---------------
>NW023602617.1:5372-5738(+)
TAATCTTTAAATTGTAAAgattctacttttttaaaaaaatatttatttaggggcctcctc
t------ggtggggcaggca--gttg----------agtgccacgctgtgaa--------
------gctgtct-gcagcctttg---cagcgc-cggtttga-----------------a
cccggccagcc------ggtgag----ggtc-----ccac-atggtgtggcagacctctc
ctgt--ctcacc----------cgctgct-------------cccctcagcagtgcattt
ca-tcag------------tttgcctg-tcctgttcccc-------------actctgt-
ctctggcgaatcc-tctca-----cc--------ctc------ccatgaatctg-gcctg
taccct-ggatcataa------ataaacaaac--------aaataaa----------taa
ataaacaaaaaataaataattaaaatattt-tttaaaagattt------atttagggcct
cc----------------
>NW023604972.1:94529099-94529438(+)
ATACTCTTAGTGTATaagatctttttttcccccaaaagatttattttattgggcctcccc
t------ggtggcgcaggtg--gtta----------agtgcagcgctgtgaa--------
------gctgtcc-gcagcctctg------------------------------------
-----ccggcc------agcaag----ggtc-----ccac-atggtgcggcagacctctc
ctgt--cgctcc----------tgctgct-------------cccctcagcagtgtattt
ct-tcag------------tctgcctgtttctgttccct-------------gctctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ctgcgaatctg-gccta
tacccc-ggttcttgt------ataaataaat--------aaacaaa----------caa
acaaacaaacaaacaaataaataaataaat-attttttaaaaa------gata-------
--------t---------
>NW023601754.1:6074875-6075237(+)
ACATCAAATACTCAGGTGTATGGATACtggtttaaaaattttaatttttagggcctcccc
t------ggtggcgcaggtg--gttg----------agtgcagcgctgtgaa--------
------gctgttt-gcagcctctg---cagcgc-cggttcaa-----------------t
cccggcctgtc------agagag----ggtc-----ccac-atggcacggcagacctctc
ctgt--tgcgcc----------cgctgct-------------cccctcagcagtgtattt
cg-tcaa------------catgcctg-ttctgttcccc-------------actctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccacacagctg-gcctg
tacccc-ggtt-ttgt------agaaataaat------------aaa----------tct
taaaaaaataaaaataaaaagtttaatttt-taaagttttcat------aaagTAGCTCA
TTT---------------
>NW023601104.1:93453909-93454275(+)
CCCTCCTCaccttcatttaaaactttttattcttttaaatatttagttgggggcctcccc
t------ggtggcacaggct--gttg----------agtgcagtgctgtgaa--------
------gctgtcc-gcagcctcta---cagcgc-cggtatta-----------------t
cccggccggcc------cgggaa----ggtc-----ccac-atggtgcagcagacctctc
ctgt--ctcgcc----------tgctgct-------------cccctcagcagtgtattt
tg-tcag------------tctgcctg-ttctgttccct-------------gctctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ctgtgcatctg-gcctg
tacccc-agttat-gt------ataaataaat--------aaataaa----------tct
taaaaaaaaataaacatttagttgGGTAAA-TTGTTAATGGGG------AGTCCCAGGGG
ACA---------------
>NW023602073.1:91496075-91496439(+)
ctgtattcccgtgcttgtataaataaatctttaaaagaaaacaaaaaactgggcctctcc
t------agtggcacaggca--gttg----------agcgctgtactgtgaa--------
------gctgtcc-acagcctctg---cagcgc-tggttta------------------t
cccggccagcc------agcgag----gttc-----ccac-atggcatagcagacctctc
ctgt--cgcgcc----------cgctgct-------------gccctcagcagtgtattt
ca-tcag------------tctgcctg-ttctgttcccc-------------actctgt-
ctctggtgaatcg-tctca-----cc--------ctc------ccgcgcatctg-tccta
taccct-ggttcttgt------gtaaaataaa-------taaataaa----------tta
aaaaaaaaaaaaaaaacttttttcctaaac-atattgttcttc------atatataaaat
------------------
>NW023605083.1:1582320-1582681(+)
--AGCCCTCCTAGACTGGCATGAGACTGGTCTGCCAAGAAATCCATCCTccaggtcttcc
t------ggtggcgcaggca--gttg----------agcgccacactgtgaa--------
------gctgacc-acagcctctg---cagcgt-cggttcaa-----------------t
cctggccggcc------ggcgag----aatc-----ccac-atggcgcggcagacctctc
ctgt--ctcgcc----------tgctgct-------------cccctcagcagtgtattt
cg-tcag------------tcagcctg-ttctgctcccc-------------gctctgt-
ctccagtgaatcc-tttca-----cc--------ctc------ccgcgcatctg-gcctg
caccct-ggttcttgt------gtaaataaat------------aaa----------tct
taaaaaaaaaaaatccatcttccAACTCCC-CGGGCCCCTCCT------GGAGCCGTGCC
GCT---------------
>NW023601322.1:8835074-8835438(-)
-ATTCTTAGGTTTTCAAacttatttgatatttattttttaaaatcacatgagggcctccc
c------catggtgcaacgg--gttg----------agcgcagcgctttgaa--------
------gctgtcc-acagcctctg---cagtgc-gggtttga-----------------t
ccccaccggcc------agtgag----aatc-----ccac-atggcacggcagaccgctc
ctgt--cgcgcc----------cgctgct-------------cccctcagcagcgtattt
ca-tcag------------tttgcctg-ttctgttcccc-------------actctgt-
ctctggtgaatcc-tctca-----cc--------ctc------cttcgcctctg-gcctg
tacccc-agctcttgt------ataaa--aat--------aaataaa----------tct
ttaaaaaaaataaaatcacacgaGGAATCG-GAACTAATAAAA------CATGTGAAAGC
GGA---------------
>NW023605305.1:43349145-43349508(-)
-ATCTGCTTTCTGATCACCAGAAAGAATCTATGTTCAAAATCTAaataatcgggcctccc
c------ggtggcacagtgg--gttg----------agcgccacgctttgaa--------
------gctgtcc-gcagcctctg---cagtac-aggtttga----------------tt
cctggccagcc------agggag----atac-----acac-acggtgcggcaaacctctc
ctgt--cttgac----------ccctgtt-------------cccctcagcaatgtcttt
gg-tcgg------------cctgcctg-ttctgctcccc-------------gatctgt-
ctctggtgaatct-gctca-----cc--------ctc------ccatgcctctg-gtctc
tacccc-agctcttgc------ataaataaat------------aaa----------tct
taaaaaaaaaaaaaaaaaaaaaaaactaag-aaaccCCACtta------gtttcttttat
aaa---------------
>NW023601543.1:47752963-47753328(+)
-ggtcatccaGACAAGCTAGTGGTAAGGTCAGGATTAAAATCCagctcattgggcctccc
c------tgtggcacagtgg--gttg----------agtgcagcactgtgaa--------
------gctgtcc-atagcctctg---cagcac-tagtttga----------------tt
cctggccggcc------agggag----attc-----ccac-atggcatggcagacctctc
ctgt--ctctcc----------cgctgta-------------cccctcagcagtgtattt
tg-tcag------------tctgcctg-ttctgttcccc-------------actctgt-
ctctggtgaatcc-tctca-----cc--------ctt------ctgcacctctg-gcctg
tacccc-gg-tcttgt------ataaataaaa----------aataa----------taa
aataaaatccagctCAGTAGTGGGGTAGCT-AGGATGGATAGGA-----GATTTTCACCT
TCT---------------
>NW023603184.1:54513976-54514347(-)
-CCCTAAATAAAacagatgctaaaatcctcattaaaatcttagcaaatcaggggcctccc
c------ggttgtgcagccg--gttg----------aatgcagcactgtgaa--------
------gctgtcc-gcagcctctg---cagctc-gggttcca----------------tt
cctggccagcc------aggaag----atac-----ccac-atggcacggcagacctctc
ctgt--tgtgcc----------cgctgct-------------cccctcagcagtgtattt
ca-tcaa------------tctgcctg-ttctgttcccc-------------actctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ctgcacatctg-gcctg
taccct-ggttcttgc------ataaataaat---ctttaaaaaaaa----------ttt
taaaaaaagcaaggcTTCAGAAATATGAAC-ATAGCATATCTC------TCAATTTATTA
AG----------------
>NW023604972.1:124401993-124402337(-)
ataaaatattttcctggtattatacttagtgaaaaaatcagacagagaaagggcctcccc
t------gctggcgcaggca--gttg----------agcacagcgctctgaa--------
------gctgtcc-gaggcctctg---cagcgc-tggtttaa-----------------t
cccagctggca------ggcgag----ggtc-----ccac-atggtacagcagacctctc
ctgt--ctcgcc----------cgctgct-------------cccctcagcagagtattt
ca-tcag----------------------tctgttccct-------------gctctat-
ctctggtgaatcc-tctca-----cc--------ctc------ccgtgcatcta-gcctg
tacccc-ggttcttgt------ataaataaat--------aagcaaa----------caa
acaaacaaacaaacaaataaatctttttaa-aaaatcagacag-----------------
------------------
>NW023605305.1:30611091-30611461(-)
AAATTATGTAGCTTCTCTAAGCtgttattttctcatctttaaagtagtaggggcctctcc
t------ggtggtgcaggcg--gttg----------agcgcagtgtaatgaa--------
------gctgtct-gtagcctctg---cagcgc-tggtttga-----------------t
cccggctggcc--agcaggcaag----ggtt-----ccac-atggtgctgcagacctctc
ctgt--cttgcc----------tgctgct-------------ccccttagcagtatattt
ca-tcag------------tctgcctg-ttctgttcccc-------------gctctat-
ctctggtgaatcc-tcttg-----cc--------ctc------ccttgcatctg-gcctg
taccct-ggttcttgt------ataaataaat--------aaataaa----------taa
ataaataaatcttttaaaaaaatagagata-actTCTCCCCCA------TAATGTCATCA
TA----------------
>NW023604972.1:9145704-9146062(-)
-TTTGTTGAGCATTCTACTTTGCCTTGAGCGTTAGAAATACATacacaaaggggcctccc
t------gatggcacaggca--gttg----------agcaccacactgttta--------
------gctgtct-gcagcctctg---cagagc-gggttcga-----------------t
cccggccagcc------ggcgag----aatc-----caac-atggtgaagcagacctctc
ctgt--ctcgtc----------cgctgct-------------cccctcggcagtgtattt
tg-tcag------------tctacctg-ttctgttcccc-------------gctctgt-
ctctggtgaatct-gctca-----ac--------ctc------ctgcgcatctg-gcctg
taccac-agttcttgt------atatataaaa--------aagtaaa----------taa
atacatacacaaagaAAGATACCCTTAAGC-TTTTTACACTTG------CCTG-------
----------------GG
>NW023600993.1:48904921-48905283(+)
-tgtataaatataagaAAACCCTAATCGCGTAAAGCCATAATAGTAATAATGGggctccc
t------ggtagtgcaggtg--gttg----------agctctgcactgtgac--------
------gctgtca-gcagcctctg---cagtgt-gggttcga-----------------t
ccctgcaggcc------aggaat----aatc-----ccac-atggtgcagcagacctctc
ctgt--ttcgcc----------cgctgct-------------cccctcagcagtgtattt
tg-tcag------------tctgcctg-ttctgttcccc-------------actctgt-
ctctggtgaatac-tctca-----cc--------ctc------cggcgcctctg-gccag
tacccc-ggttcttgt------ataaataaat------------aaa----------tct
tgaaaaataataataataatgtgtggTTTC-AATTAGATCAAA------GAAAATCCCTG
TGA---------------
>NW026555331.1:25677520-25677879(+)
-cacccctccctttcctAATGATGTAATATGTCTTAAAAATTGGGgctggggggtctccc
t------ggtggcacaggct--gctg----------agcgccacactgtgaa--------
------gctgttc-gcagcctctg---cagcgt-gggtttga-----------------t
cctggccggcc------agcaag----aatc-----acac-atggcgtggcagacctctc
ctgt--cttgcc----------tgctgct-------------cccctcagcagtgtgttt
cagtcag------------tctgcctg-ttctgttccct-------------gctctga-
ctctggtgaatcc-tctca-----cc--------ctc------ccatgccactg-gcctg
ttcccc-agcacttgt------ataaataaaa-------taaataaa----------caa
acaaaccaataaataaataaaattggagct-gggaggaaagagaagca------------
------------------
>NW023601653.1:23143693-23144057(-)
GGTGTCTCTAAACAATAAAGTAGCATCTTTCCCCAAAAACtaacatttgggggcctcccc
t------ggaggcacaggcg--gttg----------agtggagcactgtgaa--------
------gctggct-gcagtctctg---cagcat-gggtttga------------------
tccggccggct------ggcaag----aatc-----ccac-atggcgcagcagacctctc
ctgt--cgcgcc----------cacagct-------------cccctcagcagtgtattt
tg-tcag------------tctgccta-ttctgttcacc-------------gctctgt-
ctctggtgaatcc-tctca-----cc--------ctt------ccgtgcatctg-gtctg
taccct-ggttcttgt--------aaataaat--------aaataaa----------tct
taaaaaaaaaaaaaacactaacatttGGTG-AGCATTTATCAG------TCTAATAAACA
TTA---------------
>NW023601653.1:20129963-20130326(-)
--ACATAACACATGTCATATTGGCTTATTTTATACTAACAGTAAtaaaacaaggcctccc
t------ggtggcgcaggca--gttg----------aacagaGTGCTGtaga--------
------gctgtct-gcagcctctg---cagtgt-ggcttTGA-----------------T
GCCAgctggcc------gtggag----atac-----ccac-atggcacagcagacct---
ctgt--ctcgcc----------tgctgct-------------cccctcagcagtgtagtt
cactcag------------tctgcctg-ttctgttcccc-------------gctctgt-
ctctggtgaatcc-tctca-----ac--------ctt------ctgcacatctg-gcctg
tacact-ggttcttgt------atgcatgaat--------aaataaa----------tct
taaaaaagtaataaaacattaatttaatgG-CATTCATCTATT------TGGGACCAGTT
CAT---------------
>NW023605305.1:66469119-66469486(-)
-CAACTCTATGGAAATTCAGCTTCCAAAGCTTCCATCAAAAACcattcagagggcctccc
t------ggtggcacaggca--gttg----------aacgcagtgctgtgaa--------
------gctgtcc-gcagcctctg---cagtgc-cagttcga-----------------t
cccagctggcc------gcagag----atac-----ccac-atggcgtggcagacctctc
ctgt--ctctcc----------cgctgct-------------cccctcagcagtgtattt
caatcag------------tcttcctg-ttctattctcc-------------tctctct-
ctctgatgaatcc-tctca-----cc--------ct-------ctacacatgtg-gcctg
tatccc-ggttcttgt------atgcatgaaa-------aaaataag----------tct
caaaaaaaaaaaattcagagacgTTTTCCC-AGGCCAGTGCAA------ACATGTTTCCA
GTG---------------
>NW023600993.1:48183454-48183822(+)
-TATACTTGTATAGTTTGGACTTGCATTTTTCTTGTTAAGAGtgaggtcaggggcctccc
t------ggtggcgcaggtg--gttg----------agcacaatgctgtgaa--------
------gctgtct-gcaacctctg---cagtgt-gggtttga-----------------t
ccccaccggct------ggGGAG----ATAC-----TCAG-ATGGTGCaaaggacctctc
ctgt--cacgcc----------cgctgct-------------cccctcagcagtgtattt
caatcag------------tctccctg-ttctgttcccc-------------tctctgt-
ctatggtgaatcc-tctca-----cc--------ctc------ctgcacatcta-gcctg
taccct-ggttctttt------atgcatgaat--------aaataaa----------atc
ttaaaaaaaaatttaaaaaaagagtgaggc-CAAACATCTTTT------AATATGGGTAA
Cagc--------------
>NW023601653.1:75244533-75244900(-)
--ggcacACGAATATTTGTTCCAAGTATTCTTTTATCAGATTGTTTAaaagaggcttccc
t------ggtggcccaggca--gttg----------agtgcaatgctgtgaa--------
------gctgtcc-gcagcctctg---cagcgc-gggttcaa-----------------t
tctggccggcc------gcggag----atac-----ccac-atggcgcagcagacctctc
ctga--ctcacc----------tggtact-------------ctcctcagcagtgtattt
cagtcag------------tctgcctg-ttttgtttcct-------------gctctgc-
ctctggtgagtcc-tctca-----tc--------ctc------ccgcacctctg-gcctg
taccct-ggctcttgt------atgcatgaat-------aaaataag----------tct
ttaaaaaaaaaaaagaaaaggaatgtttAA-GAGACTTCCATA------GGTAAAACTGA
GTC---------------
>NW023605305.1:62658902-62659266(-)
-CCTCAAAGACTAACAAGCTGTCAGGTCAAATCCCTGAAGATGTGAGTCTGGGGCTTCCC
G------TGTGgaacaggca--gttg----------agcacagcaccgtgaa--------
------gctgtcc-gcagcctctg---cagtgc-cagtttga-----------------t
ccccgccggcc------acggag----atac-----ccac-atggtgaggcagacctctc
ctgt--ctcacc----------tgctgct-------------cccctcagcagtgtattt
cagtcag------------tctgcctg-ttctgttcccc-------------actctgt-
ctttagtgaatcc-tctca-----cc---------cc------ctgcacatctg-gcctc
tacccc-agttcttgt------ataaa--aat--------aaataaa----------tct
ttaaaaaaaaaatgtgactctgATTAAAAT-CACGCCCATCCA------GGAATTATCTG
AAA---------------
>NW023604972.1:110769418-110769782(+)
gtaaagtaaatctATTCTATGTAAACTATACCTCATTAAAcctcattttagggcctcccc
t------ggtggtgcaggca--gttg----------agtacagcgctgtgta--------
------gctgtcc-gcagcctctg---cagcac-gggttcaa-----------------t
cccggcccgcC------TGGGAG----TTaa-----ccac-atggcgagacagacctctc
ctgt--cttgcc----------cactgct-------------cccctcagcagtgtattt
cagtcag------------tctgactg-ttctgttccct-------------actctgt-
ctctggtaaatcc-tctca-----ct--------ccc------ccacacatctg-gcctg
tacccc-agttcttat------atccataaat------------aaa----------tct
ttacaaataaataaaaataaacctcatttt-aaaatgggcTCA------TGCCCCATTAA
AAA---------------
>NW023601212.1:100060974-100061336(-)
tgcaccaacggggaggccctggttcccttatttttaaagttaaggtttttgggcctcccc
t------ggtggcgcaggcg--tttg----------agcacagcgttgtgaa--------
------gctgtct-gcagcctctg---cagcac-gggtttga-----------------t
cctgaatggcc------atggag----atac-----ccac-gtggcacagcagacctgtc
ctgt--ctggcc----------cgctgct-------------cccctcagcagtatattt
cagtcca------------tctgcctg-ttctgttcccca---------------ctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccacgcatctg-gcctg
tacccc-ggttcttgc------atatatgaat------------aca----------tct
ttaaaaaaaaaataaagttaaggcTTTAAT-ATGGACCAGATG------GAGGAGCCGTC
AGC---------------
>NW023601322.1:66075041-66075406(-)
-gaggaaaaataaaacagggtggGATAGAGTGGTTAAGATAGTgcggggtagggcctccc
t------ggtggcgcaggcg--gttg----------agtgctgcactgtgaa--------
------gctgtct-gcagcctctg---cagtgc-cggttcta-----------------t
ccctactggcc------gcagag----caac-----ccac-atggcg-agcagacctctc
cttt--ctcgcc----------cactgct-------------cccctcaacagtgtattt
ca-tctg------------tctgcctg-ttctgttaccc-------------gctctgt-
ctctggtgaatcc-tctca-----tc--------ctc------ccgcacatctg-gcctg
tacccc-ggttcttgt------ataaataaat--------aagtctt----------ttt
tttaaaaaagagagattgcGGGGTGTTAGC-AAGCTCTGTTTA------GGGAGATGTTT
TCA---------------
>NW023601212.1:69937287-69937660(-)
-GAGAAGTCTCCCTGTGCCTAAAGTTCTTTTAATAGGAAAAGAGAgtctgcgggcctccc
t------ggtggcgcaggcg--gttg----------agcgcagggctgtgaa--------
------gctgtcc-gtagcctctg---cagtgt-gggttggg-----------------t
ccccgccggcc------tcagag----caac-----ccac-atggcg-agcagacctctc
ctgtccctcgcc----------tgctgct-------------cccctcagcagtgtattt
tg-tcag------------tctgcctg-ttctgtttcct-------------gctctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccgcccatctg-gcctg
tacccc-ggttcttgt------ataaataaga--gaaaattaaaaaa----------tct
taaaaaaaaaggaaaaaaagagtttgAGGG-AGCATCCAGATC------CCTAGTGTCGT
GGG---------------
>NW023601433.1:43486105-43486471(+)
-Cagtggtggggaggagaggattttttttccatgggaaaaaaaaagaaacagggcctccc
t------ggtggcgcaaggg--gttg----------agcgcagtgctgtgaa--------
------gctgtct-gcagcctctg---cagtgc-cggttcga-----------------t
ccccaccagcc------tcggag----caac-----ccac-atggcg-agcagacctctc
ctgt--catgcc----------cgctgct-------------cccctcagcagtgtattt
ca-tcag------------tctgcctg-ttctgttctcc-------------gctctgt-
ctctagtgaatcc-tctca-----cc--------ctc------ccgcacatctg-gccca
tactct-ggctcttgt------ataaataaaa-------aataaaaa----------tct
ttaaaaataaaaaagaaaaaagaaacagct-gaGCCCCACTGG------GAAGGGGAATA
AAA---------------
>NW023604295.1:86804459-86804824(-)
-GTACAACTAGGAAAACTAAATTTTGCTTACAATAAAATTCACTGGgtaatgggcctccc
t------gagggcacaggtg--gttg----------agcgcagcactataaa--------
------gctgtcc-acagcttctg---cagtgc-cagttcga-----------------t
ccccactggcc------tcggag----caac-----ccac-atggcg-agcagacctctc
ctgt--ctcgcc----------cgctgct-------------cccctcagcagtatattt
cagtcag------------tctgcctg-ttctgttcccc-------------actctgt-
ctctggtgaatcc-tctca-----ct--------ctc------ccacgcatctg-gcctg
tacccc-aactcttgt------ataaataaaa---------aataaa-------------
tcaaaaaaaagaaaagaaaattcactggGT-AATGTGGGAATG------GTCCATGGATC
TTTTGC------------
>NW023604861.1:76561225-76561588(-)
-tgggaAAGACTAAAATAATCTAttgtcattttttcaaaattaacttgtaggggcctccc
t------ggtggtgcaggtg--gttg----------agcgcagtgctgtgat--------
------gctgtcc-gcagcctctg---cagtgc-cggttcga-----------------t
ccccaccggcc------tcggag----caac-----ccac-atggca-agcagaccgctc
ctgt--ctcgcc----------cgctact-------------cccctcagcagtgtgttt
cagtcag------------tctgcctg-ttctgttcccc-------------actttgt-
ctctggtgagtcc-tctca-----tg--------ttc------ctgcacgtctg-gcctg
tacccc-agttcttgt------atacataaat------------aaa----------tct
tttaaaaaaaattaacttgtaaatacaaaa-agaaagaaaagaa-----aaagacagggc
CAC---------------
>NW023600993.1:62869864-62870228(-)
-aaaaacaaaaacaaacaaacaaacaacaacaacagcaatactagtggcatgggcctccc
t------ggtggcgcaggcg--gttg----------agcacagtgctgtgaa--------
------gctgtcc-gcaggctctg---cagtgc-cagttcta-----------------t
ccccgcgggcc------tcagaa----caac-----ccac-atggca-agcagacctctc
ctgc--cttgcc----------cgctgct-------------cctctcagcagtgtattt
tg-tcag------------tctgcttg-ttctgttcccc-------------gttctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccgtgcatctg-gactg
taccca-ggcTCTcgt------acaaatgaaa--------aaaaaaa-------------
-taaataaactagtgGCAGGCAAAGCAATC-AAAGTGACACAA------GAAGAGAGCTC
ACACAA------------
>NW023601543.1:52182768-52183122(+)
-caaaatcaacacacgaaaatcagtagccttcctatgcacaaactgaagaagggcctccc
t------agtggcgcaggtg--gttg----------agtgcagtgctgtgaa--------
------gctgtcc-acagcctctg---cagggc-gggttcaa-----------------t
ccccaccagcc------ttggag----caac-----ccat-atgttg-agcagaccactc
ctgt--cctgcc----------tgctgct-------------cccctcagcagtgtattt
at-ttgg------------tcagtcag---------cct-------------gttctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccgcacatccg-gcctg
taccct-ggttcttgt------ataaataaaa-----------taaa----------tct
ttaaaaaaaaatctgaagaagaagaaattt-aaaaaagtccct------tttattattga
aac---------------
>NW023605083.1:52386833-52387195(-)
-TTGAGGGTGCATTCAAACCATCTGGAGGGCTGATCAAAAGACAgattgctgggcctccc
a------gggggcGCAGGCA--GTTC----------AGTGcggtgctgtgga--------
------gctgtcc-gcagcatctg---cagtagcaggttcca-----------------t
cctggctggcc------gcggag----atac-----ccac-atggcgcagcagacctctt
ctgt--cttgcc----------cactgct-------------cccctcagcagtgtatct
cactcag------------tctgcctg-ttctgttccccg---------------ctgt-
ctctggtgaatcc-tctca-----ct--------ctc------ctgcacatctg-gcctg
taccct-ggttcttat------atgcatgaat--------aaataaa----------tct
tttttttaaaaaaaagacagattgcTGGGC-CCCGTCCCAAGG------TTTCTGACA--
-----------------A
>NW023601653.1:55683440-55683803(-)
-GAAataggaggagaaggaggaggagggaaggtcAAGAAATGgacactgtggggcctccc
t------ggtggtgcaggcg--gttg----------agcacagcactgtgaa--------
------gctgtct-gcagcctctg---cagtgc-ctgtttga-----------------t
cctgactggcc------agggag----ataa-----ccac-atggcgcggcagaactctc
ctgt--ctcacc----------tgctgct-------------cccctcagcattttattt
cagtcag------------tctgcctt-ttctgttccct-------------gct-----
ctctggtgaatct-tctca-----cc--------ctc------ccacacatctg-gccta
tacccc-ggttcttgt------atgcatgaat--------aaataaa----------tct
ttaaaaaagagaaagaaatggatacTGAGC-ACTTGAAGGATT------AGTGTCATCAA
CAC---------------
>NW023602073.1:33675260-33675625(+)
-aagaaaagcacagcagcaagcaggaaatggttgtgaaaaatgagaaattagggcctccc
t------gatggtgcagaag--gttg----------agcgcagcactgtgta--------
------gctgtct-gcagcctctg---cagtgc-cggttcga-----------------t
cctcgccagcc------acagag----caac-----ccac-atggcatggcagacttctc
ctgt--ctcgcc----------cgctgtg-------------cccctcagcagtgtattt
cg-tcag------------tctgcctg-ttctgttccct-------------gctctgg-
ctctggtgaatct-tctca-----c---------ctc------ccatgcatctg-gcctg
tgcccc-ggttcttct------gtgcatgaat------------aaa----------tct
ttcaaaaaaagagagagagaaattattcaatgctgactttaca------aagactgagca
cattat------------
>NW023601653.1:70052579-70052943(-)
aaaggaaGTCACAGAGGAGCACATAAGATAAGTAAGAGTGTGAAGTCcatgggactcccc
t------ggtggtgcaggtg--gctg----------agcgcagcgctgtgaa--------
------gctgtct-gcagcctctg---cagcgc-cggttcga-----------------t
cccagc--ttc------agcgag----ggtc-----ccac-atggcgcagcagacctctc
ctga--ctcgcc----------ctcttct-------------cccctcagcaatgtattt
cc-tcag------------tctgcctg-ttctgttcccc-------------actctgt-
ctctggtgaatcc-tctca------c--------ctc------ccgtgtatctg-gcctg
tacccc-agttcttgt------ataaataaat--------taataaa----------tct
taaaaaaaaaaaaactttaaaaaaaggagt-gtAAAGTCCAAG------AATGCAAGTTG
AGA---------------
>NW023605194.1:23471979-23472327(-)
TACTGTAAGtataagaaaacatattttctacCCTTAAACAAggggagagagggcctcccc
t------ggtggcgcaggtg--gttg----------agcgctgcactgtgaa--------
------gctgtcc-acaacctctg---cagtgt-gggttaga-----------------t
cccagccggcc--ggctggtgag----aatc-----ccac-atggcacggcagacctctc
ctgt--cgcgcc----------tgctgct-------------cccctcagcggtgttttt
cc-tcag------------tctgcctg-ttctgtttccc-------------gctctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccac--------acctg
tacccc-tgttcttgt------ataagtaaa--------------------------tct
taaaaaaaaaaaaagaaggggagagaaatt-ATTTGCCTGGGATGATAC-----------
------------------
>NW023604295.1:147632076-147632438(+)
-AAATTATAAAGATCCAATTATGAAGAATTCAAGCTACAGGTTGTATTGTGGGGCCTCCT
C------GCTGGCGCAGCgg--gttg----------ggcgcagcactgtgaa--------
------gctgtcc-gcagcctctg---cagcgc-cggttcga----------------tt
tccggccggcc------agggag----cagc-----ccac-atggcgc-gcagacctctc
ctgt----cgcc----------cgctgct-------------cccctcagcagtggattt
cagtcag------------tctgcctg-ttctgctcccc-------------gctctgt-
ctccggtgaatcc-tctca-----cc--------ctc------ccgcacatctg-gcctg
tacccc-ggctcttgc------ataaataaat------------aaa----------tct
tttaaaaaataaggttgTATTGTGGAAAAC-CACTTAGGAGCA------GGTTGTTCACC
AGAA--------------
>NW023605083.1:58452502-58452872(+)
-TTATGTTTATTTGACTCAGTtgttcagctattttaaaaagtcaaagaacagggcctccc
c------ggtgtcacagcag--gttg----------ggcacagcactgtgaa--------
------gctgtcc-gcagcctctg---tggtgc-aggttcga----------------tt
cctggctgtcc------agggag----ctac-----ccac-atggagtggc--atgtctc
ttgt--ctcgcc----------tgctgct-------------cctctcagcagtgttttc
ag-tccg------------tctgcctg-ttctgttccct-------------gctctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccacacctctg-gccag
tacccc-agctattgt------ataaataaaa---taaataaataaa----------tct
ttaaaaataaataaaatgaaatatcagaGA-ATCAATATTGAT------ATCAATAATGG
CAA---------------
>NW023604295.1:57522377-57522740(+)
-tcccCCCCTCTTTTGGCATAATAGAACAAGTTATTAAATTTAGCATTtgagggccaccc
c------ggtggcgcagtgg--gttg----------agtacaAAGCTCTGAA--------
------GCTGtaa-gcagcctctg---caatgt-gggttcaa----------------tt
cccggccggca------agggag----aaac-----ccac-atggtgcgacagacctctc
ctgt--ctctcc----------cgctgct-------------cccctcagcagtgtgttt
ca-gtcg------------tctgcctg-ttctactccca-------------gctctgt-
ctctggtgaattc-tctcg-----cc--------ttc------ttgtgcctctg-gtctg
tacccc-agttcttgt------ataaataaat--------aaataaa----------tct
ttttttaaaataaataaatttagcatTTGA----AAGATTTGT------AGAATACAGCC
AA----------------
>NW023603184.1:50054610-50054970(-)
-CCTCAATCAGCCCTTACTATCTTACCCTTCATAAAAAGTTTCcaaccttggggcctccc
t------ggtggcacaggca--gttg----------cgtgcagcgctgtgaa--------
------gctgtac-acagcctctg---cagcac-tggttcga-----------------t
ccccgct--ct------gcggag----cagc-----ccac-atggcacggcagacctctc
ctgg--atcgcc----------cactgct-------------cccatcagcaccatattt
tg-tcag------------tctgccta-ttctgctccct-------------gctctgt-
ctctggtgaatct-tctca-----cc--------ctc------ccgcgcatctg-gcctg
tacccc-agttcttgt------ataaataaat------------caa----------tct
tcaaaaaaaagtttccaaCCTTGGCTTAGA-ACAATTCTATCA------CTCTTCCATTT
CTT---------------
>NW026555331.1:43693313-43693677(-)
-gaaactaaaaaaagggaaacaaattcTCTTACATATAAAATCAACATGAGGGCcccccc
t------ggtgacgcag-----gttg----------agcccagcgctgtgaa--------
------gctgtat-gcagcctctg---cagtgt-gggttcga-----------------t
cccagcctgct------ggggag----caac-----ccac-atggtgcagcagcagactt
ctgt--ctcgcc----------cgctgct-------------ccccttagtagtgtattt
ccgtcag------------tctgcctg-ttctgtactct-------------gctttgt-
ctctggtgaatct-tctca-----cc--------ctc------ccatgcatttg-gccta
tacccc-agttcttat------atgcatgagt--------aaataaa----------tct
ttaaaaaaaataaataaaatcaacaggaaa-aatctcaaaaaa------attacagtaca
aca---------------
>NW023605305.1:58205546-58205911(-)
ttgaaatctgattaaaagaacaaaatatatccATAAAAAGAACCAcaatagggccttccc
t------ggtggcgcaggct--gtt-----------agCGCCGCACTTTGaa--------
------g-tgtct-gcagcctctg---cagcgt-tggttcaa-----------------t
cccggccggca------ggtgag----aatc-----ccac-atggcacaacagatcgctc
ctgt--ctcgcc----------cgctgct-------------cccctcagcagtgctttc
ag-tcca------------tctgcctg-ttctgttccct-------------gctctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccatgcatctg-gcctg
tacccc-agttcttgt------ataaataaat--------aaataaa----------cct
taaaaaaaaacccacaaaagcaAGGTGATG-ATAGCTAAATGT------TAAATAGCACT
TAA---------------
>NW023605194.1:10201917-10202275(+)
-GCAAGTTGTAataattcttttctcatttttgttaaaaaaaaccacctctggggcctccc
t------ggtggcacaggca--gttg----------agcgccgca-ggtaaa--------
------gctgtct-acagcctctg---tagtgc-cggttcga-----------------t
ccctgccagcc------agggag----caac-----ccac-atagcatgtcagacctctc
ctgt--tccgcc----------tgctgct-------------cccctcagtagagtaTTA
Tagtcac------------cctgcctg-ttctgtttccc-------------tctctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccacacctctg-gcctg
tacccc-agttcttgt------ataaataaa--------------------------tct
ttaaaaaaaaaaaaaaaccctcctcaaggg-cctccctggtga------cacaggggcta
aag---------------
>NW023604295.1:493805-494176(+)
-CTGTGAGAAATCCaagttaaatataaaacacagatttaaagtgtaaagatgggcctccc
c------ggtggcacagcag--gttg----------agcgcagcgctgtgaa--------
------gctgtct-acagtctctg---cagcat-gggttcga----------------tt
cccagccggcc------agggag----atac-----ccac-atggcacggcagacctctc
ctgc--cctgcc----------cgctgct-------------ccccccagcagtgtcttc
ag-tcca-------------tcgcctg-ttctgctcccc-------------actctgt-
ctctggcgaatcc-tctca-----cc--------ct-------ccacacctctg-acctg
tacctc-agttttttttattttataaataaaa--------acataaa----------tct
ttttaaaaatataataaagtataaagATGA-GGGGAAAAGTTA------TTCCACTTAGT
CAC---------------
>NW023601754.1:23954548-23954912(+)
-CAGACCCCCCAGAGCCTAGCAGGACTACATTCATTCACTCTTAGAAaaatgggcatccc
t------ggtggtgtggagg--gttg----------agtgctgtgctgtgaa--------
------gctgtcc-acagcctcca---cagcgc-cggcttga----------------tt
cccggctggcc------agggag----atgc-----ccac-atggcgaggcagacctctc
ctgt--gtcgcc----------cattgct--------------ccctcagcagtgcattc
gg-tccg------------tctgcctg-ttctgctcccc-------------gctctgt-
ttctggtgaatcc-tctca-----cc--------ctc------ccgcgactctt-gcctg
tacccc-agctcttgt------ataaataaaa----------ataaa----------cct
taaaaaaaatgagcccCAACTTAGAAATAA-GTCAAAGTACTT------TCTTTGCCCTT
TCA---------------
>NW023600993.1:62809728-62810092(+)
-TTCCAGATTTATGTCATCTCTTTGACTTCTTGTTAGTCATTggaaaacatgggcctccc
t------ggtggcgcagcgg--gttg----------agcaccataccgtgaa--------
------gctgtcc-acagcctccg---cagtgc-tggtttga----------------tt
cccagcctggt------agggag----aatc-----ccac-atggtgaggcagaactctc
ctgt--ctcacc----------tgttgct-------------cccctcagcagtgccttt
tg-cccc------------tctgccta-ttctgctcccc-------------actctgt-
ctgtggtgaatcc-tctca-----ca--------ctc------ccatgactctg-gcctg
tacccc-agctcttgt------ataaataaaa----------ataac----------tat
taaaacaAATCATTGGAAAACATGGATTAA-TCCAGTGGGGGT------ATACAGAGCTA
GA----------------
>NW023605305.1:111582965-111583312(-)
--------------------CTGCAGTTGCTCTTCAAGAGCCAGAGCTCCAAGGTCTACA
G---------GAGggagcgg--gttg----------agcacagtgctatggc--------
------gctgtcc-acagcctcgg---cagcac-gggttcga----------------tt
cccagccagcc------agggag----attc-----ctgc-atggcagagcagacctctc
ctct--ctcgcc----------cactgct-------------cccctcaccagtgttttc
aa-tcca------------tctgcctg-ttctgctcccc-------------actcagt-
ctctggtgaatcc-tctca-----cc--------ctc------ccgtgcctctg-gcctc
tacccc-agctcttct------ataaataaaa----------ataaa----------tct
ttttttaaaaaagaaaaagagccgGAACTT-CAAAGGGGAGAT------GGGGCGCCCCT
GTTTTGG-----------
>NW023601653.1:17746001-17746372(+)
-ACATCTTGCAATTTGTTTTCAATGTTGCCTCATTTAAAGCTAAATcctagggacctccc
t------ggtggtgcatcgg--gttg----------agcgcagcactgtgaa--------
------gctgtcc-acagcgtcgg---cagtgc-gggtttga----------------tt
cctggtcagcc------agggag----attcatCTGtggc-acagcacagcagacctctc
ctgt--ctcgcc----------cgctgct-------------cccctcagcagtgatttt
cagtcat------------cctgcctg-ttctgctcccc-------------gctctgt-
ctctggtgaatct-tctca-----cc--------ctc------ctgcacctccg-gccca
tacccc-agctcttat------ataaa--aac--------aaataaa----------tct
tttaaaaaaatagcagaaaacatcactttt-tttttgtttgtt------ttgttttgttt
tgt---------------
>NW023604861.1:3699916-3700280(+)
TTTAACCAGAGATTTTGGGTAGGTAGCTGCCTATGCAAGTTGggattgcagggcctcccc
t------ggtggtgctgcag--cttg----------agctcagtgctgtgaa--------
------gctgtcc-ccagcctctg---cagcac-aggttcca----------------tt
cctggccggcc------agggag----cttc-----ccac-atggcgcggcaggcccctc
ctgt--ctcgcc----------tcctgtt-------------cccctcaacagtgctttc
ag-tctg------------tctacttg-ttctgctcccc-------------actctgt-
ctctagtgaatc--tctca-----gc--------ctc------ctgcgcctctg-gcctt
tacccc-agttcttgt------ataaataaat------------aaa----------tct
tttaaaaaaaaaaagtgttgggaTATCTGC-AGAGAAGTTGTG------TTAACATTATA
CATT--------------
>g6 Consensus of sequences 7-30
---------------------------------------------------GGGCCTCCC
T------GGTGGCCTAGGGG--TTAA----------GTCTCAGCGCTATACA--------
------AGCTTCC-GCAGCCACTG-----GCCT-GAGTTCGA-----------------T
CCCCGCCGCCA------CGGGAGCTAAACCC-----ACAT-ATGGC-CAGCAGACCTCTC
CTGT--CTCGCC----------CGCTGCT-------------CCCCTCAGCAGTGTATTT
CA-GTAA------------TCTGCCTG-TTCTGCTCCCC-------------ACTCTGT-
CTCTGGTGAATCC-TCTCACCCCCCC--------CCC------CCTCACCTCTG-GCCTA
CACCCC-AGTTCTTCT------ATGCAAAATA----------AAAAA----------TAA
ATAAAAAATA--------------------------------------------------
------------------
>NW023601653.1:24576680-24577043(-)
-taccccagctcttgtacaaataaaaaataaatcttaaaaaaaaaattaaagggcctccc
a------cgttgcacag-cg--gttg----------agcgccatgctgtgaa--------
------gctatct-gcagcctcta---ctgtga-gggttcga-----------------t
cccggccggct------ggcgag----aatc-----ccac-atggtgccgcagatttctc
ctgt--ctcgcc----------cgcagct-------------cccctcaccagtgtattt
ct-gtta------------tctgcctg-ttctgttcccc-------------actctgt-
ctctggttaaacc-tatca-----cc--------ctc------ccgcgcctctg-gcctg
tacccc-agctcttgt------ataaa--aat--------aaataaa----------tct
tcaaaaaaattttttaaattaaaaaaatgt-ccaaTGAAAAGT------GAAGATATGAT
GTA---------------
>NW026555331.1:97376038-97376390(+)
-tgttGTTTCATATTGGGGATTTGAATAGAGGCTTAAAAATCctgaatatagggcctccc
c------agtggcgcattGG--GTta----------agcgctgcgctgtgaa--------
------gctgtcc----------------atgt-gggttgga-----------------t
cccagctggcc------ggcaag----aatc-----ccac-atggtgtggcagaccacCC
CTgt--cgcgcc----------agctgct-------------cccctcggcagtgtactt
ct-aTTG------------TCTGCATG-TTGTGCTCCCt-------------gctgtat-
ctctggtgaatcc-tcttt-----cg--------ctc------tcgtgcctctg-gcctg
tacccc-agcccttgt------ataaa--aat--------aaataaa----------tct
taaaaaaaaaatctcaaactttaaaaaaat-aatcctgaaTAT------AGCTATATTCC
TGA---------------
>NW023601653.1:51302941-51303308(+)
-GAACAGGTAAGAATGTGCAACTACAGAAGAATTACAGAAGAgaagatagagggcctccc
c------ggtggcacagcgg--gttg----------agcacagtgctgtgaa--------
------gctgtct-gcagcctcca---cagcgt--gcttcga----------------tt
cccggctggcc------agagag----ataa-----cccc-atggcagaacagacctctc
ctgt--ctcacc----------cgctgct-------------cccttcagcagtgctttc
tg-tccg------------tctgcctg-ttctgttcccc-------------gctctgt-
gtctggtgaatcc-tctca-----cc--------cccaccccgccatgcctctg-acctg
tacccc-agttc-tgt------acaaataaat------------aaa----------tct
ttaaaaaaaaagagagagataagatAGAAA-GGAggggggcat------ggggaggggga
TGG---------------
>NW023601322.1:68724026-68724394(+)
-CTTCAAACCTTGAAACGAGCTGatatttttgaagagaaaatgtcctctctggacctccc
tggtggcggtggcacagtgg--gttg----------agcacagcactgtgaa--------
------gctgtct-gcagcctgtg---tagtgt-gggttcaa----------------tt
cctggccagcc------agggtg----atac-----ccac-atggcgcagtggacctctc
ctgt--ctc-cc----------cgctgct-------------cccctcagcagtgctttt
gg-tcag------------tctgcctg-ttctgttccct-------------gctctgt-
ctctggtgaatcc-cctca-----cc--------ctc------ctacacctctg-gcctg
taccct-agctcttgt------ataaataaat------------aaa----------tct
ttaaaaaaaaatgtcccctcAAACCTGTTC-TCATGGCAGTAT------TGGGAAGTTTT
CAG---------------
>NW023605194.1:68054041-68054403(+)
-accaaagtacactgctgaggggccagcagttatttaagtagatctgcctggggcctccc
t------ggcggtgcagcgg--gTTG----------ATTGCAGGgatgtgaa--------
------gttgtct-gcagtctctg---cagcac-gggttcga----------------tt
tccagccagcc------agggag----atac-----ccac-atggcacggcagacctctc
cttt--ctcgtc----------tgctgct-------------cccctcagcagtgttttc
ag--tgg------------TCTGCCta-ttc---tccct-------------gctctgt-
ttctggtgaatta-tctca-----cc--------ctc------ccatgcctctg-gcctg
tacccc-agttcttgt------ataaataaat------------aaa----------tct
tttttaaaacaaaaaaggagatcTGCCTAT-TTggttgtctgtct----gttctgctccc
cact--------------
>NW023604974.1:16869-17246(+)
-TCAGAAAATGTATCACAGAACAGAAATCcactatttaaaaagataaaacagggcctccc
c------ggtggtgcagcag--gttg----------agtgcagctctgtgaa--------
------tctgtct-gcagcctctg---cagcacagggtttga----------------tt
cccagccagtc------agggag----atat-----acac-atggtgcggcagacctctc
ctgt--gtctcc----------cgctgctctcctcagctactcccctcagcagtgtcttc
gg--tca------------tctgtctg-ttctgttccct-------------gctctgt-
ctctggtgaattc-tttca-----cc--------ctc------ctgcgcctctg-gcctg
tacccc-agttcttgt------ataaataaat------------aaa----------tct
tttaaaaaaaagataaaacatagaAAGAGG-AGTGATGTTTGG------AACCAATTTTG
TAAC--------------
>NW023601212.1:99692426-99692776(+)
-AGAGGTGGTGCAGGCAAGAGTGATGCTTTTcgaaagaagacatacaggtagggcctccc
c------agtggcacagcag--gttg----------agtgcagcgctgtgaa--------
------gctgtcc-acagcctctg---cagcga-aggttcga----------------tt
tctggccagcc------agggag----attc-----ccac-----------agacctctc
ctgt--ctcgcc----------cacggct-------------cccctcagcagtactttc
ag-tca-------------tctgcttg-ttctgctccc--------------gatctgt-
ctctggttagtcc-tctca-----cc--------ctc------cggtgcctctg-gcctg
taaccc-agttcttgt------ataaataaat------------aaa----------tct
taaaacaaaaagaagatatGCAGGTGGCCT-ACAGGCTTAGGa------gaaatgttcac
ca----------------
>NW023601653.1:33280689-33281048(-)
-AACAGTTccattttttattcataaaattactAATCAAAACAgcaaaagtagggcctccc
t------gttggcgcaggca--gttt----------aatgcagcgctgtgaa--------
------gctgtct-gcagcctctg---cagtgt-gggttcga-----------------t
ccct-ctggcc------agggag----caaa-----ccac-atggc--tgcagacctctc
ctgt--ctctct----------ggctgct-------------cccctcagcagtgtcttt
gg-ttca------------tctgcctg-ttctgttccct-------------gctgtgt-
ctctggtgaatcc-tctca-----cc--------ctc------ctgtgcatctg-gcctg
tacccc-agtgatagt------ataaataaat------------aaa----------tct
taaaaaacaaaataaaacccagcaAAAGTA-GATATTCAGAGT------GACATGTCAGG
ATT---------------
>NW023605194.1:64053636-64054000(-)
-ACCAATACGAAGTCAAAGTCCCTTGTGGATGCAAAATTTTAAcctctctagggcctccc
t------ggtggtgcagtgg--gttg----------agcgccatgctgtgaa--------
------gctgtcc-gcagcctctg---cagtgt-gggatcga----------------tt
cccagcccgcc------agggag----aaac-----ccac-atggcatggctgacctctc
ctgc--ctcacc----------tgctgct-------------cccctcagcagtgtattt
tggtctg------------tctgcttg-ttctgctccct-------------gctct---
ctctggtgaag---tctca-----cc--------ctc------ctgagcctctg-acctg
tacccc-agttcttgt------ataaataaat------------aaa----------tct
ttgggaaaaaaatactatgttaattcttta-aaaaaaaaaaaa------tctaacctctA
AAACCCT-----------
>NW023601653.1:44461161-44461521(+)
GGATTTCCATCATagttacttttctttcaaaaatggggggaaaattctgggggcctcccc
t------ggtggcacaggtg--gttg----------agtgtagtgctgtgaa--------
------gctgtcc-acaggctctg---cagtgt-gggttcaa-----------------t
cctgg------------caggaG----AATt-----gcac-atggcaaggcagacctctc
ctgt--ctcacc----------cgctgct-------------cccttaagcagtgtattt
cg-tcag------------tctgcctg-ttctgctcccc-------------gctct-t-
ctctggtgaatcc-tctca-----tc--------ctc------ccacacatctg-gcctg
taccct-ggttcttgc------atgcatgaat--------atatgaa----------tct
ttagaaaaaaatgagggaaaattctggaaa-attgtTTTTATC------AGAGATGGACT
GCT---------------
>NW023600993.1:81021699-81022078(+)
ATAGTCATTCCTGATGTAAAGCAGAAAGTTTGATAAAAATCCAtcgacaagggcctcccc
t------ggtggcacaggcg--gtta----------agcacagcgctgtgaactgttgag
cgcagcgctgtcc-atagcctctg---cagagc-cggtttga-----------------t
cccgaccagc-------ggggag----ggtc-----tcac-atggtagggcagacctctc
ctgt--ctcgcc----------cactgct-------------cccctcagcagtgtattt
tg-tcag------------tctgcctg-ttctgttcccc--------------ctctgt-
ctctgctgaatcc-tctca-----cc--------ctc------ccacatatctg-gcctg
tacccc-ggttcttgt------ataaataaat--------aaataaa----------tct
taaaaaaagaaaaaatacccatCAACAAGC-TTAAGTATCCCT------TCTCCAATAAA
TTC---------------
>NW023602073.1:121218057-121218403(+)
--ACACAGGTTTACTGTGCATTTAAAACTAACAAGATAACAATAAAGGGTAAGGCCTCCC
T------Gttgacacaggtg--gttg----------agtgccatgctacgaa--------
------gctgtcc-gcagcctctg---cagcgt-gggtttga-----------------t
c--------------------------ttac-----ccac-atggtgcagcagacctctc
ctgt--ctcgcc----------tgctgct-------------cccctcagcagtgtattt
cagtaga------------tctgcctg-ttctgtt-----------------gctgtgt-
ctctggtgaatca-tctca-----tc--------ctc------ccacacatctg-gccta
tacgcc-tgttcttgt------atgcatgaat--------aaataaa----------tct
ttaaaaaataaacaaacaagaaaggatcag-aaaaatcaagaa------accaGTCTGCT
ATC---------------
>NW023601543.1:63000781-63001160(-)
GACTGTTTTACTGATCCAAATAAAAGATGACTGGCTAAAAGTATGGTAGTGGGCCTCCtc
t------tgtggcgcaggca--gttg----------agcgcagcgctgtgaa--------
------gctgtcc-acagtctctg---cagcgc-cagttcga-----------------t
cccagccggcc------ggtgag----ggtc-----ccac-atggtgtgccagacctatc
ctga--cttgcc----------cgctgct-------------cccctcagcagtgtattt
caggcag------------tctgcctg-ttctgttccccgctttgtctctgggctttgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccgcgaatctg-gcctg
tacccc-ggttcttgt------gtaaataaat--------aaataaaaatcttttttttt
ttaataaataaaagtatggtGGTGGTAGTA-GAAATGGTAAGA------AA---------
------------------
>NW023600993.1:70497597-70497966(-)
--TGGTCTCATCTAATGCTGACAACAGCTAAAGAGAACAAGAATTagttccaggcctccc
c------ggtggcccagcgg--gttg----------agcgccatgctgtgaa--------
------gctgtcc-gcagcctctg---cagttc-aggttcga-----------------t
ccca----gcc------agcaag----aatt-----ccat-atggcacagcagacctctc
ctgt--tgcgccggctgctcctggctgct-------------cccctcaggagcgtattt
ct-gtca------------tctgcctg-ttctgctccct-------------gttgtgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccatgcctctg-gccct
taccct-agctcttgt------ataaa--aat--------aaataaa----------tct
taaaaaaaaaaaaaaagagttcctcGATCA-ATATTTAttgtg------cacctactatg
tgc---------------
>NW023601322.1:63887754-63888127(-)
-TATGCAGGGCACCATCTGTTGATCACAGGCTCATTAGAAACaaaatatctgggcctccc
c------agtggtgcagcca--gttg----------agcacaacgctgtgaa--------
------gctggct-ggagcctctg---tagcgc-gggttcaa-----------------t
tccagccggcc------agggag----atac-----ccac-atggcatggcagacttctc
ctgc-cctcgcc----------cactgct-------------cccctcaatggtgtcttc
gg-tctg------------tctgcctg-ttctgctccct-------------gctctgt-
ctctggtgaatcc-tctca-----ccagagaggattc------ccgtgcctctg-gcctg
tatccc-agctcttgt------ataaaaataa----------atata----------tac
taaaaaaaaaatctggataatTCTCAGTGA-AATTTAGGAGCC------CTAATTTATAT
TTG---------------
>NW023601433.1:14915679-14916030(+)
-CCTCTGGTCCTACATCAACATTCATAATTGACTATAAAAGTGttatggcagggcctccc
t------ggtggcacagcgg--gctg----------agcgccatgctgtgaa--------
------gctgtct-gcagcctctg---cagggc-agtttgat-----------------t
cctggctggcc------agggag----aatc-----ccac-atggcatggcagacctttt
ctgt--accacc----------cactgct-------------cccctcagcagtg-----
-------------------tcttcctg-ttctgttccct-------------gctctgt-
ctctgatgaattc-tctca-----cc--------ttc------c--tacctctg-acctg
tacccc-agttcttgc------ataaaaaata----------aataa----------tct
taaaaaaagtgttaTGGGCAGTAACTCCAA-CATACTTAAGAA------ACGAAAACTAT
TGG---------------
>NW023601543.1:7962367-7962735(+)
-------ACAAACCCATGGAGTTAAGGCATAGGAAACAAGAATCGGGCCGGTGGCAATtc
c------tgtggcacagtgg--gttgagggcagtgcagtgcaacgctgtgaa--------
------gctgtta-gcagcctctg---cagcgc-gggtttga----------------tt
cccggccggcc------agggag----attc-----ccac-atggtgc-gcagaccaatc
ctgt--ctcgc-----------cgctgct-------------cccctcagcagtgtattt
cagtccg------------tctgcctg-ttctgctcccc-------------gctctct-
ctctggtgacttc-tctca-----tc--------ctc------ctgtgcctctg-gcctg
tacccc-agctcttgt------ataaa--aat--------aaataaa----------tct
taaaaaaaaaaaaagaaagaaacaagaatc-aATTCAACTTCA------AAACAGAAAAC
AGG---------------
>NW023601104.1:72680590-72680950(-)
-------agagagtgaAAGTGAGAGTGAAAAGGTGAagccgcccacccccaccccaccca
g------ggtggcgcaggca--gttg----------agcacagcattgtgaa--------
----aagctgtcc-tcagcctctg---cagggc-aagttcga-----------------t
ac---ccagct------agggag----caac-----ccac-atggcacagcagacctctc
ctgc--ctcgcc----------cgctgct-------------cccctcagcagtgtattt
ca-tcag------------tctgcctg-ttctgttcccc-------------gctctgt-
ctccggtaaatcc-tctca-----cc--------ctc------ctgtgcatctg-gactg
tacccccggttcttgt------aggcatgaat--------acataaa----------tct
ttaaaaaaaaaaaaagaaagaaagcgaagg-tggaaggaggga------aaagaagggag
gga---------------
>NW023603184.1:100823656-100824028(+)
-ctttattgtattttcttataGTAATAAAGTCATTACTAAATACAtttatgggacctccc
t------ggtggcgcaggtg--gttg----------agtacagtgctgtgaa--------
------g-ggggc-gcagcctctg---cagcgt-gggttcaa-----------------t
cctggctggcc------tgacag----atac-----ccac-atggtgcagcagacctctc
ctgt--ctcgcc----------cactgct-------------cccctcagcagtgtactt
cg-tcac------------tctgcctg-ttctgttccccg---------------ctgt-
ctctggtgaatcc-tctca-----tc--------ctc------ccacacatctgaacctg
taccca-ggttcttgt------atacatgagt------------aaa----------tct
taaaataaatatttacaatgacATTTCTCT-Catatgttaagt------tttttttttct
tttttttttttt---taa
>NW023604295.1:60332601-60332971(+)
-acaaagaccacaacagacaataaataaaaaagtactcaaaaatatttttggggcctcct
t------ggtggtgcaggtg--gttg----------agcacagcattgtgaa--------
------actgtcc-acagcctctg---caccac-aagttTGA-----------------T
TCCTACTGGCa------acggag----atgc-----ccac-atggcgagacagacctctc
ctgt--ctcgcc----------tgctg------------------ctcagcagtgtattt
cagtctg------------tctgcctg-ttctgttcccc-------------actctgt-
ctctggtgaatccttctta-----cc--------ctc------ccacatatctg-acctg
tacctg-ggttcttgt------ataaataaatctttaaaaaaatata----------ttt
ttaaagatagctagggatttcaaaataaat-aaataaaactaa------ctgAGCACACA
CC----------------
>NW023602073.1:145473710-145474085(-)
--TCAACATTCTTGCTATGGATTAAAAACATCGCTACTATGGATTAAActgtgtcctccc
t------ggtggcgcagcgg--gttg----------agcgcagcgctgtgaa--------
------gctgtcc-acagcctctg---cagtgt-gggtttga----------------tt
cctggctggcc------agggag----atac-----ccac-gtggcgcagcagacctctc
ctgt--ctcacc----------cgctgct-------------cccctcagcagtgtagtt
cagtaga------------atctccgg-ttctgctcccc-------------actcagt-
ctctggtggatcc-tctca-----ccaccccta-cTCTACC--CCTCATAGGTG-GCCTG
GActc--agttcctct------atgcaaaaat--------aaacaaa-------------
-taaaactaacaGTTGCTAAGTGTTTtttg-tcaggcactgtt------ctaaactCTAG
GGT-------------GC
>NW023604295.1:14368405-14368783(-)
AAGTGtaatctcaaaatatttatgttgtctttaaagagataaaacaaagagggcctcccc
t------ggttgcacgggta--gttg----------agtgcagcgctgtgaa--------
------gctgtcc-acagcctct----cagtgt-cggttcga-----------------t
cctggctggcc------ggcgag----ggcc-----ccac-atggta-aGCAGACTTCTC
CAgt--tgtgcc----------ccctgct-------------cccctcggcattgtattt
cagtcaacgtCTGTTCTGtcctgtctg-ttctgtccccc-------------actctgt-
ctctggtggattc-tctta-----tc--------ccc------ccacacatctg-gcctg
taccac-agttcttgt------ataaataata--------aaatctt----------ttt
taaaaaagttaaaacaaagaGACATATTGT-TTAATTTCAtct------cattaatttaa
tta---------------
>NW023600993.1:48225596-48225949(+)
--------------ACAACAGAATTAGGAACTTTAAAGAATGTATATGTTAGGTCCTACT
TGG----GCCAGTTGAGGCGGTGCTG----------AGTGCCGGACTGTGAT--------
------ACTGTCC---AACTCTGT---CAGCAC-GGTGTCAC-----------------T
CCCGGCag--------cggtgag----aatc-----ccac-atggagaagcagacctctc
ctgt--ctcgcc----------cgctgct-------------cccctcagcagtatattt
tg-tcag------------tctgcctg-ttctgctccct-------------gcgctgt-
ctctggtgaatcc-tctca-----cc--------ctc------ccgcacatctg-gcctg
taccct-ggttcttgt------ataaataaat------------aaa----------tct
taataaaaaaagagtGTATATGGTACCTAG-AAGAATAGCAGT------Taacagtcctc
cctggtg-----------
>NW023601754.1:39575865-39576239(-)
-TCATCATCTCAGACCAAGCACAGTGGGTcagaaaaacaataatgaaaatggggcctccc
tgag---ggtggcgcggggg--gttg----------agcacagcactgtgaa--------
------gctgtcctgtaGCCTCTGCcacagcac-gagttgga----------------tc
ccccacTAGCC------AGAggg----caac-----ccac-gtggcacagcacacctctc
ctgt--ctcacc----------ttctgct-------------cccctcagcagtgtattt
aggtaca------------tctgcctg-ttctgcttccc-------------gct-----
gtctggtgaatcc-tctca-----cc--------ccc------tcccaactcta-gcctg
tacccc-acttcttaa------aaaaat--------------------------tttttt
taaataaataatgaaaatggctAGTCTCTT-GAACAGGCAGAA------CACGTGTATCC
CAGCTAGGAAGG----GA
>NW023603184.1:53858580-53858921(-)
---TCCCGCCGCTGCGCCCATCAAAACGTCTTGGCAAAAACGTGT----GTTTCAACCCC
T------GGCGGCGCGGAGG----TG----------AAGGCGCAGCCTATGA--------
------ACcgtcc-tcagcctctg---cggcgc-gggttccg-----------------T
CCTGG---GCC------AGGGAG----CCGC-----CCAC-GCGGCGCGGCAGAAcccct
gtct--cccgct---------------gc-------------tccctcagccctGTGTTT
CC-Tcca------------tccgcctg-ctctgctcccc-------------gctctgt-
ctctggggagtcc-tctcg---------------ccc------ccgcgcctctg-gcctg
cacccc-agctctcgt------gtgcataaat--------acatGTA----------TCG
CCGGGCAGGGCGGGTCCGCGTGTCCTCTAC-GTTTTATCACTT------AGGACAC----
------------------
