>g1 Consensus of sequences 2-71
------------------------------------------------------------
---------GGGCCTCCCCGG-----TGGCGC----AGCGGTT-GAGCGCTG-G-GT--T
GCGAAGCT-G----CCCGCAGCCTCTGCA--------GCGCCGGTT-CGA-------TCC
C---C-------------------------------GGCTG--CTCCCCGGCCACCGG--
-AGGAGGGTCC----------CACAT-GGCGCAGC--AGACCTCTCC-TGCC--------
GCCCGCTGCTCC-CCTCAGCAGTG------------------------------------
-------------------------------------------TACTTCGGTCCTTCTG-
CCTGCTCTGCT--------CCCCGC----TCTGGCTCTGGTGAA-TTCTCTCA-------
-------------CCCTCC----------------CGCGCTTCTGACTGTA-CCCAG-TG
CTTGTAT-----------------------------------------------------
------------------------------------------------------------
--------------------------------------ATAAAAATAAAA----AAT---
------CAATCAATAATAAAAAATAAATAAAATAAATAAATAAATATAAT----------
-----AAATCTTTAAAA---------------
>g2 Consensus of sequences 3-49
------------------------------------------------------------
---------GGGCCTCCCCGG-----TGGCGC----AGCGGTT-GAGCGCTG-G-GT--T
GCGAAGCT-G----CCCGCGGCCTCTGCG--------GCGCCGGTT-CGA-------TCC
C---C-------------------------------GGCTG--CTCCCCGGCCACCGG--
-AGGAGGGTCC----------CACAT-GGCGC-GC--AGACCTCTCC-TGCC--------
GCCCGCTGCTCC-CCTCAGCAGTG------------------------------------
-------------------------------------------TACTTCGGTCCTTCTG-
CCTGCTCTGCT--------CCCCGC----TCTGGCTCTGGTGAA-TTCTCTCA-------
-------------CCCTCC----------------CGCGCTTCTGACTGTA-CCCAG-TG
CATGTATAA---------------------------------------------------
------------------------------------------------------------
--------------------------------------ACAAAAACAAAC----AAA---
------CAAACACAAAAAATAAATAAATAAAAAACATGCCTCTATAAAA-----------
--------------------------------
>g3 Consensus of sequences 4-102
-------------------GG---------------------------------------
---------------CCCCGG-----TGGCGC----AGCGGTT-GAGCGCTG-G-GC--T
GCGAAGCT-G----CCCGCAGCCTCTGCA--------GCGCCGGTT-CGA-------TCC
T---C-------------CCC---------------GGCCGCCCTCCCCGGCCACCGG--
-GCGAGGGTCC----------CACAT-GGCGCGAC--AGACCTCTCC-TGCCGC------
GCCCGCTGCTCC-CCTCAGCAGTG------------------------------------
-------------------------------------------TA-TTCGGTCAGTCTG-
CCTGTTCTGT---------CCCCGC----TCTGGCTCTGGTGAA-TTCTCTCA-------
-------------CCCTCC----------------CGCGCTTCTGACTGTA-CCCAG-TG
CTTGTAT-----------------------------------------------------
------------------------------------------------------------
--------------------------------------AAATAAATAAAT----AAA---
------TAAATCTTTAAAA-----------------------------------------
--------------------------------
>NW023602073.1:46089236-46089744(+)
-------------------TTGTAAAGGAATGGTAAGTGAATaaaacttgattaaaaata
aatgtttcagggcctccctgg-----tggct-----ggtggtt-aagtctca-gtgc--t
atcacc-----------------actaag--------gcctgagtt-tga-------tcc
c---c-------------------------------t----------------gccag--
-ggagctaacc----------catat-ggcgcagc----acctctct-tgtctc------
tcccactgctcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtaaatcca-
cctgttctgtt--------ccccac----tctgtctctggtaaaatcctctcatg-----
-------------cctcct----------------gcatctctgtcctaAACCCCA--TT
CTTctacctgtgagggtcccacatggtggggcaacctctcctatcatgcctgctgctccc
ctcagcagtgtattcgtcagtctgcctgttctgttccccgctctgtctatgatgaatcct
ctcaccctcctgcgcatctgtcctataccccagttcttgtataaataaataaataaa---
------tatttttaaaaaattaggtatTTTAATGTTAGTTTGTTAAGATT----------
---------GTTAACAATATTGACTA------
>NW023601754.1:28576417-28576761(+)
-------------------TGAGGAAGCAGGTATACAGATTGTGTTTCAGTTTAAAGTGG
AAAGTacaggggtctctctgg-----tggcct----gggggtt-aagactca-gtgc--t
atcacc-----------------cctgtg--------gcctgagtt-cga-------tct
c---c-------------------------------a----------------atcag--
-ggagctaacc----------cacat-ggctcagc-------------agttTC------
GCCcccttctcc-ccttagcagtg------------------------------------
-------------------------------------------tatttcagtggatcca-
cctgttctgct--------ccccac----actgtctctggttaa-tcctctcacccgccc
ccac------acaccacct----------------gcacctctggcctacaccccca-tt
cttctac-----------------------------------------------------
------------------------------------------------------------
-----------------------------------------aaaataaat----aaa---
------gtggaaaGTGCATACCAGAGCTATGCAAGCATGCTATGAGAGTTTACCCA----
--------------------------------
>g4 Consensus of sequences 5-248
------------------------------------------------------------
---------GGGCCTCCCTGG-----TGGCGCA---AGGGGTT-AAGTCCC---CAC--T
ATGAAGCT-A----TCCGCAGCCACTGCA---------GCAGAGTT-CGA-------TCC
C---CC--------------------GGCCGGCCGCA----------------GCAGG--
-GGAGCTACCC----------ACAAT-GGCGCAGC--AGACCTCTCC-TGTCTC------
GCCCGCTGCTCC-CCTCAGCAGTG------------------------------------
-------------------------------------------TATTTCAGTC-ATCTG-
CCTGTTCTGT---------CCCCAC----TCTGTCTCTGGTGAA-TCCTCTCACCCCC--
-------------CCCCCC----------------CCACCTCTGGCCTGTACCCCAG--T
CTTGTAT-----------------------------------------------------
------------------------------------------------------------
--------------------------------------GCATAAATAAAA-AATAAAAAT
A-----AATCTTTAAAA-------------------------------------------
--------------------------------
>g5 Consensus of sequences 6-121
------------------------------------------------------------
---------GGGCCTCCCTGG-----TGGCGC-----AGGGTT-GAGTCGCA-GCGC--T
GTGAAGCT-G----TCCGCAGCCTCTGCA--------GCGCG-GTT-CGA-------TCC
C---C-------------------------------G----------------GCCGG--
-CCGGAGACCC---------ACATAT-GGCGC-GC--AGACCTCTCC-TGTCTC------
GCCCGCTGCTCC-CCTCAGCAGTG------------------------------------
-------------------------------------------TATTTCAGTC-GTCTG-
CCTGTTCTGTC--------CCCC------TCTGTCTCTGGTGAA-TCCTCTCA-------
-------------CCCCCTC---------------CCGCCTCTGGCCTGTACCCCG--TT
CTTGTAT-----------------------------------------------------
------------------------------------------------------------
--------------------------------------ATAAATATAAAT----AAATAA
AAAT-AAATCTTTAAAA-------------------------------------------
--------------------------------
>g6 Consensus of sequences 7-30
------------------------------------------------------------
---------GGGCCTCCCTGG-----TGGCCT----AGGGGTT-AAGTCTCA-GCGC--T
ATACAAGC-T----TCCGCAG--CCACTG--------GCCTGAGTT-CGA-------TCC
C---C-------------------------------GCC------------GCCACGG--
-GAGCTAAACCC--------ACATAT-GGC-CAGC--AGACCTCTCC-TGTCTC------
GCCCGCTGCTCC-CCTCAGCAGTG------------------------------------
-------------------------------------------TATTTCAGTA-ATCTG-
CCTGTTCTGCT--------CCCCAC----TCTGTCTCTGGTGAA-TCCTCTCACCCCCC-
-------------CCCCCC----------------TCACCTCTGGCCTACACCCCAG-TT
CTTCTAT-----------------------------------------------------
------------------------------------------------------------
--------------------------------------GCAAAATAAAAA----ATA---
------AATAAAAAATA-------------------------------------------
--------------------------------
>NW023601543.1:82673623-82673979(+)
-------------------agcaaaagaacCAACTCATGACTACATTTCTATGATTATAA
Aaacaactggggcctccctgg-----tggcct----aggagtt-aagtctca-gcac--t
ataact-----------------gctgca--------gcctgggtt-cga-------tcc
c-----------------------------------g----------------gccag--
-agagctgaccc--------ccatat-ggtgcggca-agacctctcc-tgtctc------
gcccgctgctcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtcagtctg-
cctgttctgtt--------ccccac----tctgtctctggtgaa-tcctctca-------
-------------ccccct----------------acacctccagcctacaccctag-tt
cttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaaa----ata---
------aatctttaaaaaatatataaaaacagttCTACATGGGCCACATC----------
-----GTGCTTTTGTGGAAGAA----------
>NW023605083.1:25368465-25368824(-)
-------------------CACTATGCTGAATGTACACTAAAATTTAGACAGTAAAAGAT
aggaccccagggcctccctgg-----tggcat----aggggtt-aagtctca-gcac--t
ctcact-----------------gttaag--------gcctgagtt-caa-------tcc
c---c-------------------------------t----------------gccag--
-ggatctaccc---------acatat-ggcacagg--agacctctcc-cgtctt------
gcccgctgctcc-ccttagcagtg------------------------------------
-------------------------------------------catttcagtagatctg-
cctgttttgct--------cccctc----tctctctctggtgaa-tcctctca-------
-------------ccccct----------------atacctctggcctatgccccat-tt
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aaaaat
a-----aatcttttaaaaaatacaggacCCCAGATTAACTCTGGTCtaat----------
-------tttccacaaatatttct--------
>NW023601543.1:56882462-56882814(-)
-------------------ATGTGCATGTCTTATTATAACcatctttttgcttttaatac
tgttttctggggcctccctgg-----tggtgt----aggggtt-aagtctca-gcac--t
atcatt-----------------gttgtg--------gcctgagtt-tga-------tcc
c---t-------------------------------g----------------gccag--
-ggagctgacc----------catat-ggcacagt--agacctctcc-tgtctc------
gcccgctgctcc-cctcagcagtg------------------------------------
-------------------------------------------tgtttcagtcagtctg-
cctgttctgtt--------ccccac----tctgtctctggtgaa-tcctctca-------
-------------cctcct----------------acacctctggcctgtaccccag-tt
cttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----taa---
------aaaataaaaaatcttttgaaaatactgttttctgTCTTCATTCA----------
------GTCACCACAAGTATT-----------
>NW026555331.1:23440015-23440364(-)
-------------------ATGAGGACATGTTTTGTAAATGCATGTCAACAATAAAACCA
CAACTtctagggcctcactgg-----tggcct----agtggtt-aagtctaa-GTGC--T
GTCATT-----------------ACTAta--------gcctaagtt-tga-------tcc
c---t-------------------------------a----------------gccag--
-ggagctaacc----------cacat-ggcacagc--agacctcttc-tgtctc------
acctgctgctcc-tcttagcagtg------------------------------------
-------------------------------------------tatttcagtaaatttg-
cctgttctgcc--------ccccac----tctgtctctggtgaa-tcttctca-------
-------------tcccct----------------gcaatgctggcctacaccccag-tt
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------ggaaaaagaaat----aaa---
------atctttttcgAAAAACACAACTTCTAGCCTTGATAAACTATATT----------
------GTGCTCTATTAC--------------
>NW023603184.1:120329075-120329453(+)
-------------------TGGAATTAATAAGGTTAACCCTAAGACACCTAGACCAAGAA
TGTTatactgggcctccttgg-----tgcccg----agagatt-aagtctca-gtgc--t
attaccatgA----CAGCCCACCTcaatg--------acctgagtt-caa-------tct
c---c-------------------------------a----------------gccag--
-ggagctatccc--------acacat-ggcgcagc--agacttctcc-tgtctc------
acctgctgctct-ccttagccatg------------------------------------
-------------------------------------------tatttcagtaaatcca-
cctgctttgct--------tcccac----tctgtatctggtgaa-ttctctcacccccc-
-------------atcccc----------------gcatctctggcctacatcccaa-tt
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaataaaaaat----aaataa
a-----atctttaaaaaaaaatgttattcttagGCTGAAAACTATATAGT----------
---AGATAACCCTAGGATA-------------
>NW023600993.1:32037435-32037797(+)
-------------------AGAGGGACTTGGGGGACTCTGTGAATAGCCTGCCTTTAACT
TTTCtggtagggcttccctgg-----tggcgt----agaggTT-AAGTCTAA-GTGC--T
ATCACT-----------------GTTACA--------GCTTAAGTT-Cga-------gcc
c---c-------------------------------a----------------gctag--
-ggagctaaccc--------acatat-ggcacagc--agacctctcc-tgtctc------
atcagctgcatc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtcagtctg-
cctgttctgct--------ccctac----tctgtctctagtgga-tcctctcaccacccc
c------------atccct----------------gcacctctgacctataccccag-tt
cttctac-----------------------------------------------------
------------------------------------------------------------
--------------------------------------acaaaaataaaa----aaa---
------aattttaaaaaaacaagttaaaaaaaatcttctctggTAGTCTC----------
--------ACTAAGAAGTCTTCC---------
>NW023601104.1:63348528-63348876(+)
-------------------TATCTAATTTATCCATACATATCTCTATGTCTAATTAGAAT
Accagtctagggcctccctgg-----tggctt----aggggtt-gagtctca-gggc--t
atcacc---a---------------------------gcttcagtt-caa-------tcc
c---t-------------------------------g----------------gccag--
-ggaggtgacc----------cacat-ggggtggc--agacctctcc-tgtctc------
gcccgctgctcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtcagtctg-
cctgttctgtt--------ccccac----tttatctctggtgaa-tcctttcac------
-------------tctccc----------------acatctctggcctgtacgccag-tt
cctgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----ata---
------tctttaaaaaaaagatatcttgttataaatgttaatcacatcta----------
-----------AAGAAATACTATCAC------
>NW023601653.1:20909857-20910210(-)
-------------------TCATTggttatttttaaggaaagacatttctctaaataagc
aaaactttggggcctccctgg-----tggcct----aggggtt-aagtctca-gtac--t
atcatc-----------------GCTatc--------acctgagtt-caa-------tcc
c---c-------------------------------t----------------gccag--
-gaagctaaccc--------acatat-ggcacagc--cgacctctcc-tgtctc------
tcctgctgctcc-tctcagcagtt------------------------------------
-------------------------------------------tatttaagtagctcca-
cctgttcttct--------ccccac----tctgtatctggtaaa-ccctctcc-------
-------------ccctgc----------------tcacctcttgcctataccccaa-tt
cttctac-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaaataaaa----taa---
------aatttaaaggaagaaaactttGGAGAActttttctggtattttt----------
-----ctatttatgaaacA-------------
>NW023605083.1:79237923-79238269(+)
--------------------ACTGAGTATTTGAAACAGggaaaagtttgatttttaaaaa
cgtGACAAAAGGGCCTcgtag-----tggcct----aggggtt-aagtctca-tcgc--t
atcact-----------------gctatg--------gcctgagtt-cga-------tcc
c---c-------------------------------a----------------gccag--
-ggaactaaccc--------acatat-ggtgcagc--agacctctcc-tgtctt------
gcctgctgctcc-cctcagcaata------------------------------------
-------------------------------------------tatttcagtaagtcca-
cctgttcttct--------ccccac----tctatctctggtgaa-tcctctca-------
-------------ccccct----------------gaacctctggcctacaccccag-tt
ctac--------------------------------------------------------
------------------------------------------------------------
--------------------------------------ataaaaataaat----tat---
------aagataaaGAAGGTGAGGTGATGGGAGCCCAACCTCAAATCTAC----------
------AACCCTGAAAA---------------
>NW026555331.1:8763486-8763822(-)
-------------------caaatacaggctgatttcactcatatgtgacatataaagaa
acaaaacaggggcctccctgg-----tagagt----aGGTGTT-AAGTCTCG-GCGC--T
ATCACC-----------------ATTACG--------acctgagtt-caa-------tgc
c---c-------------------------------t----------------gTCAG--
-GAATCTGACC----------AACAT-GGCTCAGC--Taatgtctcc-tgtctc------
gcctgctgcttc-cctcagcagtg------------------------------------
-------------------------------------------tatttcggtagatctg-
cctgttctgct--------ccccac----tctgtctctggtgaa-gcctctca-------
-------------ccccct----------------gcacctctgggccacaccccag-tt
gttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaaatttaa----caa---
------aagaaacaaagaaagagtcaagcaaaaacaaacccttaaacCC-----------
--------------------------------
>NW023605305.1:18709596-18709946(+)
-------------------AAACCACTAGTCTATTCGATTCAATGTGGAGATCAACATTt
gaaatacaggggcctccctgg-----tggcct----aagggtt-aagtctca-gctt--t
atcact-----------------gctatg--------gcctgagtt-aga-------tcc
t---t-------------------------------g----------------gccag--
-ggagctgaccc--------acatat-ggcgcagc--ggacctctcc-tgtctc------
actcactgctcc-ccttaacagtg------------------------------------
-------------------------------------------tatttcagtaaatcca-
ccaattctgct--------ccccat----tctgtctctggtgaa-tcgtctca-------
-------------ttcccc----------------gcacctctggcctacaccccaa-tt
cctctac-----------------------------------------------------
------------------------------------------------------------
--------------------------------------acaaataaaatgtattaaa---
------attttttgatatatgtatgtatatatgtatgtatgtatattccccccaccc---
--------------------------------
>NW023605305.1:78064296-78064638(+)
--------------------acaaatcttttaaaaaaaaatcacttaaaaaaaaaaaagc
atttttttcaggtctccctgg-----tggcct----acgggtt-aaatctca-gtgc--t
atgacc-----------------tctgca--------gcctgagtt-caa-------tcc
c---t-------------------------------g----------------gtcag--
-ggagctaaccc--------acttat-ggcacagc--agacctctcc-tgtctt------
acccactgctcc-ccttagcagtg------------------------------------
-------------------------------------------tatttcagtaaatcca-
tctgtactgct--------ccccac----tctgtatctgatgAA-TCATCTGa-------
-------------ccacct----------------ccacctctggcctacaccatag---
-ttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaaatcaat----caa---
------tcaaattaaatgtgtgtgtgtgtgtgtgtgtataaagaattttttcataCT---
--------------------------------
>NW023604295.1:78973068-78973412(+)
-------------------AAAACCCAAAGACACATTACattagtaaaaattaataaaaa
taaaagatagagtctccctag-----tggcct----agaggtt-aagtctca-gcac---
----------------------cactgct--------gcctgagtt-tga-------tcc
c-----------------------------------a----------------gccag--
-ggaattaaccc--------acatat-ggcacagc--agacccctcc-tggctt------
gtctgctgctcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtagatctg-
cctgttctgca--------ccccac----tctgtctctagtgaa-tcctctca-------
-------------cccact----------------ggacctctggcctacactccat-tt
cttctac-----------------------------------------------------
------------------------------------------------------------
--------------------------------------acaagaaaataa----ata---
------aataaaaacaaaaaataaagtgccCCCAAAAAGTTTAATGTTGG----------
-----------TTAAGAAGGGAT---------
>NW023602073.1:77930689-77931042(-)
-------------------TTTTGTCTCATAGTCTCTAGGctgttgaaagaaagaaaaac
ttgctctgagggcctccttgg-----tgtcct----aggggtt-aagtctca-gcaa--t
aatacc-----------------accaca--------gcctgagtg-cca--------cc
c---a-------------------------------g----------------gccag--
-ggagctaaccc--------acatat-gtcacagc--agacctctcc-tgtctc------
acctgctgctcc-ctgcagcagtg------------------------------------
-------------------------------------------tacttcagtagatctg-
cctgttctgct--------ccccac----tctgtctctggtgaa-tcctctaa-------
-------------ctcccc----------------aaacctctggcctacaccttag-tt
tttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------aaaaaaaaataa----taa---
------tcttaaaaaagaaggaaaaacatgcAGAAGTTTTGGAATCAAGG----------
--------AGCTCACAATCACTG---------
>NW023601104.1:71295630-71295973(+)
-------------------GCCTTTTCACTCTAGCTTTTTTTAGCATAAAGGTTAGAAAt
aagaaacaggggcctccctgg-----tggcct----acgggtt-aagtctca-gtgc--g
atcacc-----------------tctgtg--------gcctgagtt-cca-------tcc
c---c-------------------------------a----------------gccag--
-ggagctgaccc--------acatat-ggcacagc--agacctctcc-tgttca------
ggctattgctcc-tctcagcagtg------------------------------------
-------------------------------------------ttttgtagtaaatcca-
tctgttctgct--------ccgtAC----TTtctctttggtgga-tcctcttacctctc-
-------------ctcccc----------------ccacttctggcctacatccctg-tt
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaaaagacc----cca---
------aaaaacaaaacaaaaaaaaaaaccaccacacacacaaaatag------------
--------------------------------
>NW023601104.1:51688089-51688462(-)
-------------------ATTACATATACAATATGCAATCCTGCTTTTTTAAAAGGTTG
ACAAAGCAGGGGCCTACCTGG-----TGCTGA----GGAgtta-aagtctta-gcgc--t
atcaaggt-a----tcaccagcctCTGgg--------gcatgagct-tga-------tcc
c---c-------------------------------c----------------accag--
-ggaggtaaccc--------acatat-ggcaccgc--agacctctcc-tgtctc------
tcccgcagctcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtagagctg-
cctgttctgct--------ccctac----tctgtctctggtgaa-tcttctcac------
-------------acccct----------------ccacatctggcctacatcccag-tt
cttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aaaaat
a-----aatctttaaaaaattaaaattttacaaagcATCTGAAATACTTT----------
---------CTTTGACATGGTTTTTC------
>NW023605083.1:65943353-65943705(-)
-------------------AGTAAAAATGCTGCATGTtcaaggaaactttttaaaaacat
gtctttttagggcctccctgg-----gggcct----aggggtt-aaatctca-gcac--t
atcatc-----------------agtatg--------gcctgagtt-caa-------ccc
c---t-------------------------------g----------------gccag--
-ggagct-acc----------cacat-ggtgcagc--agacctctcc-tgtctc------
acccgctgctcc-cctcagcag-g------------------------------------
-------------------------------------------tatttcagtagatcca-
ccagttctgct--------ccccac----tctgtctctggtaaa-tcctctcaca-----
-------------tacccT----------------GTCCCTTTAGctgacaccccag-ct
cttctac-----------------------------------------------------
------------------------------------------------------------
--------------------------------------acagaaataaat----aaa---
------attttaaaaaatctttaaaatatttatctttttaggaagaaagg----------
------------aaaagcaaatttgTT-----
>NW023601754.1:40497472-40497824(-)
-------------------ggaggcccaataaataaataaatcttaaaaaaaaaaagtaa
aaaggtggggggcctccccag-----tggctc----aggagtt--agtctca-gcgc--t
atcacc-------------agctactgcg--------gcctgagtt-gga-------tcc
c---c-------------------------------a----------------gccag--
-ggagctgacc----------catgt-ggtgcagc--agacctctcc-tgtctc------
acccactgctcc-taccagcaatg------------------------------------
-------------------------------------------tatttcagtcaataca-
tctgttcttct--------ccccaa----tctgtctctggtgaa-tcctctca-------
-------------ccccct----------------gcacctctagcctacaccccag-tt
cttctac-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaagaaaaat----aat---
------aatatcaaagAAGATTTCAGAACAAGGACTACTGGGAGGGAGAG----------
-----GTTATTTCATAA---------------
>NW023601754.1:33801165-33801503(+)
--------------------TAAgagattcattttattaaaaacccTGGTTTGGTTGAAA
GTTggactgaggcctccctgg-----tggcct----aggggt--aagtctca-gcac--t
atcacc-----------------actgcc--------acatgagtt-cta-------acc
c---c-------------------------------a----------------gccag--
-ggagct-acc----------cacat-gtcacagc--agacctctcc-tatctc------
actcactgctcc-cctcagcagtg------------------------------------
-------------------------------------------tacttcagtccttctg-
cctgttctgct--------ccccac----tctgtctctggtgaa-ttctttca-------
-------------ccccct----------------gtacctctgacctataccccag-tt
tctctac-----------------------------------------------------
------------------------------------------------------------
--------------------------------------ataaaaaaatct----aaaaaa
g-----aaagttggaatgaaaggaaggaatgttatggaaagaaaggaagc----------
--------------------------------
>NW023604295.1:138672683-138673040(+)
-------------------attacctcaataaaaagaaagagaaaaaatttaaaaataaa
acaaatttggggcctccatga-----tggcct----aagggtt-aagtctca-gtgc--t
atcatc------------------ctacg--------gcctgagtt-tga-------tgc
c---c-------------------------------a----------------gcaaa--
-ggagctgact----------cacat-ggcacagc--agacctctcc-tgtctt------
gccctctgctcc-ccacagcagtg------------------------------------
-------------------------------------------tatttcagtagatcca-
cctgttttgct--------ccccac----tctgtctctgaagag-tcctctca-------
-------------ccccca----------------acatctctggcctgcaacccag-ta
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaatttaat-tttaaa---
-----aaatctctaaaacaaTTTAATTGATTTATATCATTATGTACTCAG----------
-----------CAATGATCCTGGCTAAC----
>NW023603184.1:135703683-135704029(-)
--------------------GTGGGAAAGCTGAGAGAGAGATTCCCTTCCCTCAAGAAAG
TCATCcttgaggcctccctga-----tggcct----aggagtt-aagtctca-gtg----
-----------------------gctatg--------gcctgaatt-caa-------tcc
c---c-------------------------------a----------------gccag--
-agaggtgact----------catac-ggcacagc--aggcctctcc-tgtctc------
acctgctgctcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtagatccg-
cctattttgct--------ccccac----tctgtctctggtgaa-tcctctca-------
-------------cccctt----------------acacctctggcttacacgcCAG-Tt
cttcaaa-----------------------------------------------------
------------------------------------------------------------
--------------------------------------tataagaaaaaa----aga---
------aactcattacAATTGGGAAGTCGGCCTATATCTATCAGGGTCCC----------
-----------CAGAAAAGCAGCTCTCTC---
>NW023601433.1:60905163-60905514(-)
--------------------ACATGCTTTTTGAGCAACAGTTTGAAGACTGGCTTTTAAT
AACCAGaacaggtctccctgg-----tggctc----aggagtt-aagtctca-gcac--t
ttcact----------------tatgatg--------gcctgagtt-caa-------ttc
c---c-------------------------------t----------------gccag--
-ggaactaaccc--------acatat-ggcacagc--aggcctcacC-TGTTtt------
gtccgctgttcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtagattgg-
catgttctgct--------ccctac----tctgtctctggtgaa-tgtgctca-------
-------------accccc----------------acacctctggcctacaccccag-tt
cttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaaa----------
--------tcctaaaaaaaaaacaaaccagaacacTGATGGGAGGGAAAA----------
-----------CAATAAAGGCAATCTAA----
>NW023604861.1:136849010-136849369(-)
-------------------ATGCTCTGGTTTCTAAGGtaatgctttgtttttttgtttaa
agaaaaagagggcctcccagg-----tgacct----aggggtt-aagtctca-gtgc--t
agcacc-----------------accacg--------gcctgagtt-cca-------tcc
c---c-------------------------------a----------------gccag--
-ttTGCTGACCC--------ACACAT-TGTGCAAC--atacctctcc-tgtgtc------
-cccactgctcc-cctcagcagtc------------------------------------
-------------------------------------------tatttcagtagatctg-
cctgttctgtt--------ccccat----tctgtcgctggtgaa-gcttctcactccccc
-------------ctcccc----------------acacctctggactacaccccag-tt
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaaatagat----tat---
------attaaaaaagagggaaaggaataaTTGAGACTTAAGAACTTACT----------
---------ATTTAAACTCACAT---------
>NW023601543.1:17888897-17889248(+)
-------------------GATTTTCCCCTCTTgacttttctattgtttttccttagaaa
gaaaaaacagggcctccttgg-----tggcct----aggggtt-aaggttct---gc--t
atcacc-----------------actatg--------gcctgagtt-cga-------tcc
c---c-------------------------------g----------------gccac--
-gtaGTTACCC---------ACATAA-GGCATAGC--AGagctctct-tgtctc------
acccactgctcc-ccttagtagtg------------------------------------
-------------------------------------------tatttcagtagatctg-
catgttttgct--------ccccac----cctgtcgctggtgaa-tgctctca-------
-------------ccccct----------------gcacctctggcctacaccccag-tt
cttctgt-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcatacataaat----aaa---
------attttaaaaagaaaggaagaacaagtaaaagtaaaacatttGAC----------
------------TGGGACACCAATCCC-----
>NW023605305.1:34944497-34944853(+)
--------------------gcgccaccggggaggccccggaatgtcttttttaaaacaa
cttggccctaggccaccctgg-----tggcaa----aggggttaaagtccca-gtgc--t
TACAAGCT-A----TCGGCAGttactgtg--------gcctgagtt-cga-------tcc
c---c-------------------------------a----------------gccag--
-ggagttaacc----------cacat-ggcacagc--ggacctttcc-tgtctc------
gcccactgctcc-cctcagctgtg------------------------------------
-------------------------------------------tatttcggtcagtctg-
cctgttctgct--------ccccac----tctgtctatggtgaa-tcttttca-------
-------------tccccc----------------acacctctggcctaaaccccag-tt
tttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----acataa
agtc--atccttactgtttaaaaataaacaacttggTCCCTAAAAGCTCA----------
--------------------------------
>NW023601104.1:72304966-72305327(-)
-------------------AGCAGAACTAGTCATGTTCCTAGAAGACCTGTTTGCATATA
TTAAGACAGGGGCCTACCTCA-----tgaccc----aggggttaaagtctca-gtgc--t
atgaagct-a----ttgccagccattgtg--------gcctgagtt-caa-------tcc
c---c-------------------------------g----------------gccag--
-ggagttgacc----------catat-ggcacagc--agacctctcc-tgactg------
gcccactgctcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtcagtctg-
cctgttctgct--------ccccac----tctgtctctggtgaa-tcctctca-------
-------------cccccc----------------acacctctggcctacatcccag-tt
cttgttt-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----------
---------ctttaaaaaaaaaaaaaaagatatactccCAGGAAGTCCAA----------
---------CAACAGAGCAGAAGAAC------
>NW023603184.1:140528451-140528817(-)
-------------------AACATagtattttggttaaaaaaaaaaaaacaaaacaaaac
agaaaaccaggacctccctgg-----tggcac----aggggttaaagtctca-gcgc--t
atcaagct-a----tcaccagtcactgtg--------gcatgagtt-cga-------agc
c---c-------------------------------a----------------gccag--
-ggagctaagg----------cacat-ggcacagc--agacctctcc-tatctc------
gcccgctgctcc-cctcagctgtg------------------------------------
-------------------------------------------tatttcagtcagtctg-
cctgttctgct--------ccccac----tctgtctctggtgaa-tcatctca-------
-------------cacccc----------------gcacctctggcctagaccccag-tt
cttgtct-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaattaat----aaa---
------atctttagaaaacaacaacaacaaaaaaggaccCTCTGGGGAAA----------
------------AGTGGTTTCTTCCTCA----
>NW023604861.1:51563274-51563632(-)
-------------------AGCTAGTCATTGTCCCTGaaatttctatgtaaaaaaaaaaa
ctgaactgagggcctccctta-----gggtgc----aggggttaaagtatca-gcac--t
atcaagct-t----tggccagccactgca--------gcatgagtt-cta-------ttc
c---t-------------------------------g----------------gccag--
-ggagctgacc----------cacat-ggtgcagc--agacctctcc-tgtctc------
gcctgctgctcc-cctcagcagtt------------------------------------
-------------------------------------------tatttcag----tttg-
cctgttctgct--------ccctac----tctgtctctggtgaa-tcctctta-------
-------------accccc----------------acacctctggcctacacctcag-tt
cttttat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaaaaaaa----------
-------actttaaaaaaaagaagcgtCAGAAtaatcatcttaaaaaaaa----------
--------aatctgcgtTATTGAC--------
>NW023604861.1:39369169-39369539(-)
--------------------TGCACttagttctttctttgcttttgattaattctttaaa
attatttacaggcctccctgg-----tggcac----aggggttaaagtctca-gcgc--t
atcaagct-a----tcagtagccactgtg--------gcatgagtt-caa-------tta
c---c-------------------------------a----------------gccag--
-ggagctaacc----------catat-ggcatagc--agacctttcc-tgtctc------
acctgctgctcc-cctcagcagtgc-----------------------------------
-------------------------------------------tatttcagtagatctg-
cctattccgct--------tcccac----tctgtctctggtgaa-tcctctcc-------
-------------cctcct----------------gtgcctaaggcctacaccccag-tt
cttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaattaaa----aaaaaa
------aatctttaaaaaaataaaattatttatagaagTGTGATTAAATC----------
-----------TAAAGAAACAGGTAGGT----
>NW023603184.1:39976497-39976861(+)
---------------------TACCACAAGAGAGGCCAGGTTGAGACATAAAGTCAAAGA
GATCATTTagaggcctcctgg-----tggcac----aggggtt-aagtctca-gtgc--t
atcaagct-a----tgaccagccactgag--------gcatgagtt-taa-------tgc
c---t-------------------------------g----------------gccag--
-ggagctgact----------cacat-ggtccagc--agatctctcc-tgtctc------
-accgctgctcc-cctcagcagtg------------------------------------
-------------------------------------------gatttcagtcagtctg-
cctgctctgct--------ccctac----tctgtctctggtgaa-tcgtctca-------
-------------cctcccccc---------accaacacttctggcctacacctcag-gg
cttttat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aaa---
------tctttttttaaaaaaaggagataattTAGGGCCAAATGAGGGGA----------
-------AACTATTAAGT--------------
>NW023602073.1:135926174-135926550(+)
-------------------aaataataaacatgagGCAAGGAAGGGTCATAAATTTAAGA
AGgggtaaagggcctccctgg-----tggtac----aggggttaaagtctca-gtgc--t
attaagct-a----tcaccaaccactgag-----------actatt-caa-------tcc
c---t-------------------------------g----------------gccag--
-agagctgacc----------cacgt-ggcacagc--agacctctcc-tgtcac------
acctgatactcc-cctcagcagtg------------------------------------
-------------------------------------------tatctcagttaatcca-
cctgttctgtt--------ccccgc----tctgtctctggtgac-tcatcTCACataccc
ct-----------ccacac----------------acacctctggcctacacaccag-tt
cttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gtgtaaataaat----aaa---
------ataaatcttgaaaaaatataataataaaataaaaaggggtaCAA----------
---------AGAGAAAGTCTCATGTGGCA---
>NW023601543.1:11005984-11006361(-)
-------------------CAATTCCCACAGATTCCAGCACTGTGTTGCTGGTTAAAAAG
accatttgggggcctccctgg------ggcac----aggggttaaagtctca-gcac--t
atcaagtt-a----tcagcagtcactgtg--------gcatgagtt-tga-------tcc
c---t-------------------------------g----------------gtcaa--
-gGAACTGAAC----------cttat-ggcagagc--agacctctcc-tgtctg------
gcccaatactct-cttcagcagtg------------------------------------
-------------------------------------------tgttgcaatggatcca-
cctgttctgct--------ccccac----tctgtctctggcgaa-tcctttcaacc----
-------------cccccc----------------acacctctgacctacaccccag-tt
cttgtac-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aaaata
aat---cctttttttaaaaaaagaacactttggGCTAAGAGTAGGCCTGC----------
---TTTTTTCTCCCTGGCCCAC----------
>NW026555331.1:24847020-24847383(+)
-------------------TCTGGTAATAAATAACAGATgagttcattcattaaaaaaaa
aaaatgtaggggtctccctag-----tggcac----aggggttaaagacacacaAGC--T
ATCAAGat-a----ccgccagccactgca--------acatgagtt-caa-------tcc
c---c-------------------------------g----------------gccag--
-ggagata-------------catat-gaggcagc--atacctctcc-tgtctc------
acctactgctcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtaggtctg-
cgtgttctgct--------ccccac----tctgtctctggtgaa-tcctctca-------
-------------cccctc----------------acacctctagcgtataccccag-tt
cttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aaa---
------tctttttaaaaaagtagtcaTACTGGTGACTTGGCATTTTTAGT----------
-------TAATTAGAAGGGAGA----------
>NW023605305.1:46669551-46669920(-)
--------------------CTGCTAATAGAACACTGAAAAGACATTatattataaaagt
taaaaaatgaggtcttccttg-----tggcac----aggggttaaagtctca-gagctat
atcaagct-a----tcactggcCACTGGG--------GCATGTGTTCcag-------tcc
c---c-------------------------------t----------------gccag--
-ggagctaacc----------cacaa-ggcgcagc--agacttctct-tgtcta------
acctgctgctcc-cctaagcagtg------------------------------------
-------------------------------------------tatttcagtagaccca-
cttgttctgct--------ccccat----tctgtctctggtgaa-tcctctta-------
-------------ctcccc----------------acacctctagcctacacctcag-tt
cttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----gaaaat
aaatcttttttttttaaaaaaaagtcagaggcaagttcattattttttac----------
-----------tgaaaacT-------------
>NW023605194.1:80017175-80017545(+)
-------------------ACCATTAACCTCactgtgtttcagtttctttgttttgaaaa
tgggaccaggggcctccctag-----tgttac----agaggttaaagacaca-gcgc--t
gttaagct-a----ttgccagccactgca--------gcatgagtt-cta-------tct
ctggc-------------------------------g----------------gccag--
-ggagctaacc----------cacaa---agcagc--agacctcctc-tgtctt------
gctcactgtgcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcactagatctg-
cctgttctgct--------ccccac----tctgtctctggtgaa-tcctctta-------
-------------ttcccc----------------acacctctggcctacaccccag-ct
cttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----gaa---
------tatttttttaaaaagtgggaacAAAACACATAAGATTTAATAAA----------
-------GACACAATAACAGCATAAC------
>NW023605194.1:81249481-81249839(+)
-------------------TTCTCCCTACCCACAACCAGGTTTTCTCTTCTAAGTGAAAA
AGCAAACTGGGTCCTCCTtgt-----tggcac----aggggtgaaagtctca-gcgc--t
attaagct-a----tcaccagcaactgtg--------gcatgagtt-tga-------acc
c---c-------------------------------g----------------gccag--
-gga-tcaacc----------cacat-ggctccgc--agacctcttc-tgcctc------
gcctgctgcagc-cctcagcagtg------------------------------------
-------------------------------------------tattacagtagatctg-
ccagttctgtt--------ccccac----tctg--tctggtgaa-tcctctca-------
-------------tccact----------------gcacatctggcttataccccag-tt
cttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aaa---
------tcttttttaaaagatttatctatttatttatttatacaagaact----------
-------------ggagtacaggc--------
>NW023601322.1:93066079-93066447(+)
-------------------AAACCACTGGTAATAACTAAGTCTAAATCTACAGTTGAAAT
gttcagtgagggcctccctgg-----tggcac----aggagttaaagtctca-gtgc--t
atcaaact-a-----tgccagccacagca-gcatgagctatgagtt-cga-------tcc
c---t-------------------------------g----------------gccag--
-ggagctgacc----------catat-gggacagg--agacctctcc-tgtctt------
gcccactgctcc-cctcagcagtg------------------------------------
-------------------------------------------catctcgGTAGATCtga
cctgttctact--------ccccac----tctgtctctggtgaa-tcctctca-------
-------------cccccc----------------acacctctggcctgcaccctag-tt
cttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----gaa---
------tctttttggggaaaaaaagcgAATCAGATGCTTGACATTGATCC----------
------------TGGAATCCATT---------
>NW023601104.1:80078622-80078987(-)
-------------------GCCTCACACCCTCTTCTTTGTTGGGCCCATGTAGTGAAATg
taattttcagggcctccctgg-----tgatcc----aGGGCTTAAAGTCCCA-ACGC--G
ATCAAGTt-a----tc-ccagccactgct--------gcatgagtt-cag--------cc
c---g-------------------------------g----------------gccag--
-agagctgacc----------cacat-ggcgcagc--aaacctctcc-tgactc------
acccgctgctcc-cctcagcagtgt-----------------------------------
-------------------------------------------aatttcagtcagtctg-
cctgttctgct--------ccccac----tctgcctctggtgaa-tcctctca-------
-------------tccccg----------------acacctctggcctacacccccg-tt
cttatat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------acacaaataaaa----ata---
------aatctttaaatatatatatataatttccaaaAACTTAAAATCAT----------
-------AACTCAGATATttagt---------
>NW023604861.1:54786862-54787213(+)
-------------------aaaaagaaacctaCATATTAGTACAAAATGATTGAGATACT
TGGAAATAAGAGCCTTCCTgt-----tggtgc----agggattaaagtctca-gtgc--t
gtcaagct-a----tcaccagc---------------ccctgagtt-cca-------tcc
a-----------------------------------g----------------gccag--
-gaagctgacc----------cacat-ggcgcagc--agacctctcc-tgtctt------
gcccactgctcc-cctcagcaatg------------------------------------
-------------------------------------------tatttcagtagatctg-
tctgttctgct--------ccccac----tctgtctctgctaaa-tcctctca-------
-------------ccccct----------------gcacctctggcatagatcccag-tt
ctt-tat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataatttttttaa---
------ttttttttaaatgatggagaTATTTAGAAGTAGATACTTTAATACTAAAG----
--------------------------------
>NW023600993.1:45800800-45801176(+)
-------------------GGGAAGAGAGTGGTCTCTTCTTCATAGACTGTCAAGAACTC
tccaaagtggggcctccctgg-----tggtgc----atggatTAAAATCTCG-gtgc--t
atcatgct-a----ttgctagccactgtg--------gcatgagtt-gga-------tcc
c---t-------------------------------g----------------gccag--
-ggagctaacc----------cacat-agtgcagc--agacctctcc-tgtctc------
cccagctgctcc-ccttagcagtg------------------------------------
-------------------------------------------tatttctgtagctctc-
cctgttctgct--------ccccac----tgtggctcc-atgaa-tcctctcaccct---
-------------ctccct----------------acacctctggcctacaccccag-tt
cctgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcatagataaat----aaaaat
a-----aatctttttaaaataataattaaaaaaatctccaaagtGGAGAA----------
-------ATCCTCATAGTAGAGGTTC------
>NW023601212.1:18571939-18572306(-)
-------------------GCTCAGCAAAGCTCTTCTGAAGttaacactatttaaaaaat
aggtgacctgggcctccctgg-----tggcac----tggggttaaagtttca-gcgc--t
atcaag-----------------ttagcg--------gcaggagtt-cca-------tcc
c---c-------------------------------a----------------gccag--
-ggagctgacc----------cacat-gacacagc--agacctctcc-tgtctc------
acccactgctgc-cctcagcagtg------------------------------------
-------------------------------------------tgttttagcagatctg-
tctgttctgct--------ccccac----tttgtctctggtcaa-tcctctcattcctcc
c------------acccct----------------gtacctctggcctacaccccag-ct
tttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aaaaat
a-----aatcttaaaaaaaataggtgaacCTGTTGCCTGCCAGCGTCCAT----------
-------CACATGAGAAGAGTATG--------
>NW023604295.1:71844165-71844537(+)
-------------------GCCTTCAAACAATCCCTTTCAAGAACCCCTGTCAAGAATAG
GCTGGCcgtgggcatccctgg-----tggcac----aggggttaaag--aca-gcgc--c
atcaagct-a----tcaccagccactgca--------gcatgagtt-cga-------tcc
c---c-------------------------------c----------------gctgacc
acggagaaacc----------cgcat-ggcgcagc--aggcctctcc-tgcctt------
gcccgctgctcc-cctcaacagtg------------------------------------
-------------------------------------------tatttcgatagatctg-
cctgctctgct--------ccccac----tctatctctggtgaa-ttatctcaacCCTC-
-------------ctcccc----------------acatatctggcctacaccccag-tt
cttctac-----------------------------------------------------
------------------------------------------------------------
--------------------------------------acaaaaataaat----aaa---
------attttaaaaagtaggctCTTCTCAATAAAATGCTCCCCCCTACT----------
-----------TTCTGGTATGGCCAA------
>NW023601104.1:15092768-15093137(+)
--------------------AAACAGACTTTATGGTACAAGGCAATTATGTTTCAGAAAT
CCCtatggcaggcctccctgg-----tggcgc----agggtttaaagacata-gtgt--t
atcaagct-a----tcactagccactgca--------gcacgagtt-tga-------ttc
c---t-------------------------------g----------------gccag--
-ggagc-aacc----------cacat-ggtacagc--agacctctcc-tgtctt------
accctctgctcc-cctcagcagtg------------------------------------
-------------------------------------------tattgcagtagatctg-
cctcttctgct--------ccctactctgtctgtctttgatgaa-tcctctcacc-----
-------------tcccct----------------gcaactctggcctacaccccag-tt
cttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------acataaataatt----aaa---
------tcttaaaaaataaagaagtcccTATGTCATCAAACTGAAGCTAG----------
----ATGCTGCCTGAAATC-------------
>NW023605194.1:27896804-27897148(-)
-------------------CCAAAATTTTAGTAGAAGAGGTTCTGATTCCTTTAAAATTG
ataactcttgggcctccctgg-----tggtgc----aggggtt-aaagat-a-gtgc--t
atcaagct-a----tcaccag--------------------------cca-------ctt
a---c-------------------------------a----------------gccag--
-ggtgctgacc----------cacat-ggcacaac--agacttctcc-tgtctt------
acctgctgctcc-cctcagcagtt------------------------------------
-------------------------------------------tatttccatagatctg-
cctgttctgct--------ccccac----tc--tctctggtgaa-tccgctca-------
-------------cctccc----------------gcatctctggcttacaccccag-tt
ctggtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcacaaataaat----aaa---
------tctttaaaaaataaaataaaattgataactCTCTCTAATGGCAC----------
-----------CTGTGATAGTAGATT------
>NW023605194.1:93560446-93560806(+)
-------------------cacacaggaTTTAGACTCTGACTAGGATACAGAGCAAGAAA
Gagtgttgtgggcctccctgg-----tggtgc----aggggtt-aaa-caca-gcgc--t
atcaagct-a----tcaccatccactgaa--------gcatgagtt-tga-------tgc
c---c-------------------------------gac------------ctgccag--
-agagctaacc----------cacat-ggtgcagc--tgacctctcc-tgcctt------
-gccactgctcc-tctcagcagtg------------------------------------
-------------------------------------------tatttcaatagatctg-
cctgttctgct--------tcctac----tc--tctcTTGTACA-CCCTTTCA-------
-------------CCCcat----------------gcacttctggcttacaccccag-tt
cttgcat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aaa---
------cttttttttaaaggaggggtGCCAGAAACCTCTCTATATTGCTA----------
-------------AAAGTCATCTC--------
>NW023601433.1:43985743-43986102(+)
-------------------TTATCATATATATTCTCATCAGGAGGTTCATGTTGTAAATG
tgaaacttggggcctccctgg-----tgaccc----tcgggtt-aagtctta-gcac--t
atcacc-----------------tccATG--------gtctgaatt-cga-------tcc
c---c-------------------------------g----------------gctag--
-ggagctaacc----------cacat-ggcacaac--agacctctcc-tgtctc------
acccgctgctcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcaataaatctg-
tctgttctgct--------ccccat----tctgtctct-gtgaa-tcgtCCCTTCCCTga
a------------cccccc----------------acatctctgaactacaacccag-tt
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaaatgaat----aaa---
------tcttaaaaaaactggaaacttAACCTATTTCTAGGGTGGGAACC----------
-----------TGACCTTATTATCTA------
>NW023602407.1:15447-15805(+)
-------------------ttctattattttaaataatatcaaaagatgtaaaaaatata
ttaaaaacaggacctccctgg-----tggcat----aaagttt-aagtctga-gtgc--t
atcact-----------------gcttag--------acctgagtt-tga-------tcc
c---t-------------------------------g----------------gccag--
-ggagc-aacc----------cacat-ggggcagc--agacctctcc-tgtctc------
acccacccgtcc-cctcagcagtg------------------------------------
-------------------------------------------gatttcagtggatcag-
cctgttctgct--------ccctac----tctgtgtctggtgaa-tcctctcc-------
-------------ccctct----------------gcccctctggcccatgccccag-tt
cttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaacaaat----aaa---
------aaatgaatcttaaaaaacaaacaaaaaaattacatgcagcatca----------
--------agtacaagatccatctcagacc--
>NW023605305.1:113813838-113814195(+)
-------------------TCCGTGCATTAAAACTTGTTTTTCATCCTGTTAGAACGACT
CTCAgtcctgggcctgcctgg-----tggcat----aggggtt-aagtctca-gcac--t
atcacatt-A----TCA----CCGCttca--------gcctgagtt-cga-------tcc
c---c-------------------------------g----------------accag--
-ggagctggcc----------cacat-ggtacagc--aga-ctctcc-tgtctc------
-cccgctgctcc-cctcagcagtg------------------------------------
-------------------------------------------gatttcagtagatcct-
cctgttctgct--------ccccac----tctgtctctagtgaa-tcctctca-------
-------------cctccc----------------gcatctctggcctacaccccac-tt
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaaa----aaa---
------taaataaataaaaaagaaccatttTCATTCCCACGAAGGATGCC----------
-----------------TGACCTATCGGAC-T
>NW023601212.1:70877523-70877863(+)
--------------------ATGGTATGGATTCCCAGTAGGTGGAAATAAACTGTAGAAA
GGCaaaaggaggcctccctgg-----tggtct----aggggtt-aagactca-gcac--t
gtcact-----------------gctaag--------gcctgagtt-caa-------tcc
c---t-------------------------------a----------------gtcag--
-ggggctaacc----------cacaa-ggcgcagc--aga-ctctct-tgtctc------
tcccgctgctcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtagatcca-
cctgttctgtt--------ccccac----tctgtctctggtgaa-tcctctca-------
--------------ctgct----------------gtgcatctggcctacactccag-tt
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------acacacacacac----aca---
------cacacacacacactaactaactaaacaaacaaacaaacaaacaa----------
-----------catgaa---------------
>NW023605083.1:127642454-127642814(-)
--------------------GGGTGGAAGCCTGCATGAgacataaatgaaagaggaagac
ATATATCTCAGgggtccctgg-----tggcct----aggggct-aaggctca-gcgc--t
gtcacc-----------------actgtg--------gactgagtt-caa-------tcc
c---c-------------------------------a----------------gccag--
-ggagct-acc----------tacat-ggtgcggc--agacctctcc-tgtctt------
accctctgctcc-cctcagcagtg------------------------------------
-------------------------------------------tgtttcagtcagtctg-
cctgttctgtt--------tcccac----tctgcctctggcgaC-CCCTCTCACCCCT--
-------------ACTTTC----------------GCTCCttgggcctgcaccccag-tc
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aaataa
a-----atccttaaaaaataaagaaaacataaaaatacactTTAACTTGA----------
----------CTCAACATCATGAAGG------
>NW023604861.1:81867313-81867651(-)
-------------------agaaatgtttaagtcctttgtccattttttaatcaagttgt
ctttctgggggacctccctgg-----tggcct----ttgggtt-aagactca-gcac--t
atc--------------------actacg--------aCCTgggtt-cga-------tgc
c---t-------------------------------g----------------gccag--
-agagctaacc----------cacac-ggcacagc--agacctctcc-tgtctt-----a
acccgctgctcc-ccttagcagtg------------------------------------
-------------------------------------------tatttcgataaatcaa-
tctgttttgct--------cccctc----tctgtctctggtgaa-tcctc----------
-------------accccc----------------acacctctggcctacaccctca-tt
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaaaaaaaa----aaa---
------aaaaaaaagtcttgtagTTTCAGGAATTCCCTATATATTCTGGATGCTAT----
--------------------------------
>NW023605305.1:97530836-97531185(-)
-------------------CTCAATTTCTATTACACTGCACATCaaatttggcttttaaa
atattatggggccctccctgg-----tggcct----aggagtt-aaatctca-gtgc--t
atcccT-----------------GCTAAg--------tcctgagtt-aga-------tcc
c---t-------------------------------g----------------gagag--
-ggaggtaacc----------cacat-ggcacagc--agacctctcc-tgtctc------
gcctggtgCTTC-ctttagcagca------------------------------------
-------------------------------------------tatttcagtaaatctg-
cctgttctgct--------cctca--------gtctctggtgaa-tcctctca-------
-------------gccccc----------------acatctctggactataccccag-tt
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaaaaaaaa----aaa---
------aaaaattacaggttaTGCTAAAAGTACggaaaaaatctgaagaa----------
-----------aggaaataagcatCAA-----
>NW023605193.1:15286-15633(+)
-------------------AGAGCCTGTATGCATCCACATATATAAGActtctaaaatag
tcaaattcagggcctccctgc-----aggcct----ATGGGTt---atctca-gtac--t
atcact-----------------gctaca--------gcctgagtt-caa-------tcc
c---a-------------------------------g----------------gccag--
-ggagataaccc--------atacaa-ggtgcagc--cgacctctcc-tgtttt------
gccccctgcttc-ctttagcagtg------------------------------------
-------------------------------------------tatttcaatagatctg-
cctgttctgtt------tcccccac----tctgtctctggtgaa-tcctttca-------
-------------tctccc----------------acacctctggcctacaccccaa-tt
ctgctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaaaaaaaa----aaa---
------taaaaagatcgggcttccccggtggcgcagcggttgagcgctgg----------
---------------------gttgcgaa---
>NW023605083.1:16060754-16061092(-)
-------------------ggaaatggtgttacttttatttaagaacaatatgaaatatt
aaaactcTTGGGCCTTCCTAG-----TGtcat----aggggtt-aaatctca-aaGC--T
GTCACT-----------------GCAgat--------gcctgagtt-caa-------tcc
c---c-------------------------------a----------------gccag--
-ggagctgacc----------cacat-ggtgtggc--agacctcttc-tgtctc------
ccctattgctcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtagagccg-
cccgttctgct--------cccaat----tctgtctctggtgaa-tcctctct-------
-------------tccccc----------------atg--------------cccag-tt
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aaa---
------tctttaaaaatatattagggcctccccggtggcgcagtggttga----------
------gcgctgggttgtgaa-----------
>NW023602073.1:25869-26218(+)
----------------------gaaggaggtaacatcagtttaacaCATTAAAAGGTAAA
GTGCAGCCTCCCCCcgcccag-----tggcct----aggggtt-aaagctca-gtgc--t
gtcacc-----------------acaatg--------gtctgagtt-caa--------gc
c---t-------------------------------g----------------gctgg--
-ggagct-acc----------cacat-ggtgtagc--agacatttcc-tgtctc------
gcctgatgctcc-cctcagctgtg------------------------------------
-------------------------------------------tttctcggtagatctg-
cctgttctact--------ccctac----tttgtctctggtgaa-tcctctcac------
-------------cctccc----------------acacccctggcctgcaccccag-tt
cttctatta---------------------------------------------------
------------------------------------------------------------
--------------------------------------aaaaaaataaac----aaa---
------agcttcaataataaaaaagataaagtggggcctccccggtggca----------
-----------cagcggttgagcgc-------
>NW023601104.1:49824107-49824480(+)
-------------------CTATAGCACCTTCTAGTAAAACCAgtgactttaaaattttc
ttaccaggggggcctccctgg-----tggcat----agaagttaaagtctca-gtgc--t
atcaagct-a----ctgtcaGC-TAcggg--------gcatgagtt-cga-------tcc
c---t-------------------------------g----------------gccag--
-gaagctgacc----------cacat-gatgcagc--agacctctcc-tatctt------
gcctgcggctcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtagatctg-
cctgttctgct--------ccccgc----tctgtctctggtgaa-tcctctcatactccA
TACT--------cccaccc----------------tcatctctggccCTGACCCGagttt
cttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcacaaataaat----------
-------cttaaaaaaaaaaaaatttcttaccaCCTTGTAGTCAAGTTCA----------
--------------TGATACCTATCCACT---
>NW023602322.1:4928-5290(+)
-------------------TGAGGAGTCAAATACCCCACAACAGCATGAACCAAGAAACC
CCATGAGGGGGGCCCCTCTgc-----tggcct----aggagtt-aagtctca-gggt--T
ATCACC-----------------ACCATG--------GCACAAGTG-TGAAGtgtggtcc
c---c-------------------------------a----------------gccag--
-ggagctgacc----------cacat-ggcagagc--agacctctcc-tgtctc------
gcccgctgctcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtagatccc-
cctgttctgct--------ccccac----tctgtctctggtgaa-tcttctcagcc----
-------------ccctcc----------------ccatatctggcctgcacccaag-ct
cttatgt-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aaa---
------atcttttaagaatattttaaagaaaaaaaaaccagaagcaGAAC----------
-----TCCAGGCAGAAATAT------------
>NW023605289.1:24123-24474(+)
-------------------ACTTTACACCACATGCTTACCATAGGCTGGGCAGCAAAATT
CTagaactcgggcctccctgg-----tggtgt----aggggtt-aattctca-gcac--t
atcatg-----------------ggGAGg-------tgtctgagtt-tga-------tcc
c---t-------------------------------g----------------gccag--
-ggagctgacc----------cacat-ggtgcagc--tgacctcacc-tgtctc------
tcccgctgctcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcactaggtctg-
cctgttgtgct--------cctcaa-----ttgtctctggtgaa-acctcttaccc----
-------------accccc----------------ccaagtctggcctataccccag-tt
cttccat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gtataaataaat----ata---
------ttttttttaaatctagaactTGGTACAAACTGCACTCTGACCTC----------
--------CTCACACAGTG-------------
>NW023601653.1:79368333-79368681(-)
---------------------aaaatgtgatatcACAGTATTAAGATGACTCACtagggc
ctaggggttaagtctccctgg-----tggcct----aggaagt-aagtctca-gtgc--t
gtcatc-----------------attact--------gcctgagtt-caa-------tcc
c---c-------------------------------a----------------gccag--
-ggagctggcc----------cacat-ggtgcagc--ggacc------tgtgtt------
gcccgctgctct-cctcagcagtgt-----------------------------------
-------------------------------------------tatttcagtcacccca-
tctgttctgct--------ccccac----tctgtctctggtgaa-tgctcttg-------
-------------cccctt----------------gcatctctggtctatactccag-ct
cttgtgt-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aag---
------tttttttaaaaaataataaataaataataagatggCTCACTAGA----------
----CGAGTGTTAAGAAAAAC-----------
>NW023605305.1:74746324-74746694(-)
-------------------aaaacacaacaacaaaaccctccTATACTCTGCAGTTGACA
TATAGTGgtgcgcctccctggtggaatGGCCt----agagttt-aagtctca-gtgc--t
atcaccaagA----CAACCCACAAacaag--------gcctgagtt-caa-------tcc
c---c-------------------------------a----------------gccag--
-ggagctgacc----------cacat-ggcacagc--agacctctcc-tgtctc------
acccactgagac-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtagatctg-
cctgttctgct--------ccccac----tctatcgctggtgaa-tcctctca-------
--------------ccccg----------------acacctctggcctacatcacag-ct
tttctac-----------------------------------------------------
------------------------------------------------------------
--------------------------------------acaaaaataaat----aga---
------atctttaaaaaaaaatatatatagtggtTACCAGGGGGAATGGG----------
------GCTGTGGAAGGGAAGG----------
>NW023603184.1:54463734-54464083(-)
gtagtC-------------T-------------TTTACAAGTTTATAtcttacaaaatag
aaatatccTGGACCTCCGCAG------TGCCT----AGGGGTT-GGGTCTCA-GCCC--t
gtcact-----------------gctgag--------gcctgagtt-cct-------tcc
c---t-------------------------------g----------------gctag--
-ggagctggc-----------cacag-ggcccagc--agacctctcc-tgtcac------
-cgtgctgttcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtagatccg-
cctgttctgct--------ccccac----tctgtctctggtgtg-tcctctaacac----
-------------acaccc----------------ccacctctggcctgcaccccag-tt
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaactaAGC----AAA---
------ctaatcttgaaaaaaaaaagaagtacccAATAATGAGTTTAAAT----------
-------------AAGGTGCTGTATCAGAGGA
>NW023602073.1:692196-692543(-)
--------------------GACTTTAGCTAATGTTGCTTGAAAGTTGTGAAAATTGTTT
GAAACATCTGGGGCCTCcgag-----tggcct----aggggtt-gagtctca-g-gc--t
atcacc-----------------actGGG--------Gccttagtt-tga-------tcc
c---c-------------------------------a----------------gccaa--
-gtatctgacc----------cacag-ggcgcagc--agacctctcc-tgtctc------
-cccgctgctcc-cctcagaagtg------------------------------------
-------------------------------------------tgtctCAGTGTATCCA-
CCTGTTcggct--------ccctac----tctgtctctggggag-tcctctca-------
---------------cccc----------------gcacctctggcccgcaccccag-tt
catctgt-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataagtaaat----aaa---
------taaatagaacatctCTGTTATAGTTAAATGACCTTCATGTGACC----------
-----------AAAAAGGACAGACAC------
>NW023604972.1:57761503-57761860(+)
-------------------tCTCCTTTTTTCATaacattgaaaaattattttaaaagtct
agttttaggggtcctccctgg-----tggtgt----aggggtt-caGCCTCA-GCCC--T
ATCACT-----------------CCTATG--------GTCTGAGTt-aca-------tcc
c---t-------------------------------g----------------gtcag--
-ggagataacA----------CACAT-GGCAAATC--AGACCTCTCT-AGtctg------
gcctgctgttcc-cctcagcagtg------------------------------------
-------------------------------------------tatttccatcagtctg-
cctgttccttt--------ccccac----tctgtctctggtgaa-tcctctcac------
-------------cctcct----------------gcacctctgataTGCACCCCca-tt
cttcttt-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaaataaat----aaa---
------tgaatcttaaaaaagtaaaagtctgattttaataaatgaaactt----------
----------taGGAGATGTACGCTCTTG---
>NW023604972.1:87226508-87226862(+)
--------------------catgttatTAAGACCCTCTGTGTATACTTTCATTAAGTAT
AAtattgtcaggcctccctgg-----tggcct----agggatt-aagtctca-gagc--t
tccacc-----------------actatg--------gcctgagtt--gg-------ctc
c---t-------------------------------g----------------gccag--
-ggagctaacac--------acatat-ggcgcagc--agatctctcc-tgtctc------
acccgctgctcc-cattactagtg------------------------------------
-------------------------------------------tatttcagtaaatcca-
cttgttctgct--------ccccac----tctgtctctggtgaa-tcctc----------
------------accccct----------------gcaactctcgcctacaccccag-tt
cttctac-----------------------------------------------------
------------------------------------------------------------
--------------------------------------tcaaaaaataaa---tgta---
------taatattgaAAACTAATCATACTTTACACTGCTCAAAACATCAT----------
----------TTCATCCCGGCCCCCAAA----
>NW023602073.1:21496064-21496418(+)
--------------------TAGTTTTCCTACACTGTGGATTAAGATGGGCTGTGAATAA
ATCtctttgaggcctccctgg-----tggcct----aggggtt-atgcctca-gtgc--t
gtcacc-----------------actatg--------gcctgagtt-cga-------tcc
c---c-------------------------------g----------------gccag--
-gcagctgacc----------cacatttggccagc--agacctctct-tgtctt------
gcccgctgctcc-ccttagcaatg------------------------------------
-------------------------------------------tgttTCCagagatctg-
cctgttttgtc--------gcTGAC----TTTGTCTCTgg-aaa-tcctctta-------
-------------cccccc----------------tcacctctggcctacaccctag-tt
ctttggc-----------------------------------------------------
------------------------------------------------------------
--------------------------------------tcaaaattaaaa----ata---
------aaaaaattaaaaaaaaatctctttgaggctgggaggtgggattc----------
-----------tggcaacacatttttttt---
>NW023605083.1:76359846-76360202(+)
-----------------------atactttaaataaatgtattctctAAAAACATAGTAC
AGTTACTGGGAATCTGtctgg-----cggcct----aggggtt-aagtctca-gcat--t
atcatgct-a----tca----ctgctacg--------ACCAGAGTT-CGA-------CTC
a---a-------------------------------a----------------gccag--
-agagctaacc----------caaaT-CGCGctgc--aggcttctcc-tgtctc------
-cccgctgctcc-tctcagcagtg------------------------------------
-------------------------------------------tatttcagtagatccg-
cctgttctgct--------ccccac----tatg----tggtgaa-tcctctcacccct--
-------------cccccc----------------aaacctctggcctacaccccag-tt
attctgt-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcagaaataaat----gaa---
------tctttaaaagatacGTATTTAAAGCATGgtagagttgggcctcc----------
---------cctggtggcacaggc--------
>NW023601212.1:60762764-60763104(+)
-------------------cataaaaataaatcttttaaaaataaataaaataaaatgct
atattacgggggcctccctgg-----tggcct----agaggtt-aagtctca-gcgt--t
gtCATC-----------------ACTACA--------GCCTGAGTC-TGA-------TGc
c---c-------------------------------------------------------
-agagctaaccc--------acacat-ggtatagc--agacctctcc-tgtctc------
gcctactgctcc-tct---tagtg------------------------------------
-------------------------------------------tatttcagtcagtcca-
tctgttctgct----------ccac----tctgtctctggtgaa-tcctctta-------
--------------caccc----------------gcacctctggcctacaccccag-tt
cttctac-----------------------------------------------------
------------------------------------------------------------
--------------------------------------acaaaaataaat----ttt---
------tttaaaactctatatTAGTTTGTTTCTCAGATCAGCATTCCTAG----------
---------------ATTGGGTTCTCAG----
>NW026555331.1:128758678-128759037(-)
--------------------TTTCCCCTTTAAGAAATGGTGTGACTATTAGTTGTTAAAA
CAACATTTAGGGGCCTTCTGG-----TGGCGA----AGGGCtt-aggtctca-gtgc--t
gtcaagct-a----tca----ccactgcg--------ccctgagtt-tga-------ttc
c---t-------------------------------g----------------gtcag--
-ggagctagccc--------acatat-ggtggagc--agacctctcc-tgtctc------
actcgctgctcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtaaatcca-
tctgttctgct--------tgcCAC----TCTGTGGt--gagaa-tcctctta-------
-------------cctcct----------------gcacctctggcttacaccctag-tt
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aaa---
------tcttttaaaaaaacatttatcagAATATAGGGTACCTCCTGTCA----------
--------------ATATATGGCTTCAGA---
>NW023604861.1:78197431-78197783(+)
-------------------caattgggaaaaataaaaccaaaaataaacaagttaaagAG
ATTTTACAGGGGCCTTCATGG-----TGgtgt----agaggtt-aagtctca-gtac--t
agcaagct-a----tca----ccacgaag--------gcctgagtt-tga-------tcc
c---c-------------------------------g----------------gacag--
-ggagctaaccc--------acatat-ggtatagc--agacctcctc-tgtctt------
gcccactgctcc-ccttagcagtg------------------------------------
-------------------------------------------tatttcaataaatc---
----acctgct--------ctccac----tctatatctggtgaa-tcctctta-------
-------------ctaccc----------------gcacctctggcctataccccag-tt
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaaataattttttaaaaga
g-----cttttatacagtgaaagaaaatacaagaataaaAGGATACTCTacga-------
--------------------------------
>NW023605305.1:28396444-28396787(+)
----------------------------------------AATACTAGGGTTGAAAAAAC
TAAACTTGTGGGTCTCAGCAA-----GTTAAg----tcaggtt-aagtctca-gcac--t
actatgct-a----tca----ccactgca--------gcctgtgtt-tga-------tcc
t-----------------------------------g----------------gccag--
-ggagctaaccc--------acatat-agtgcatc--agacctctcc-tctctt------
gcccactgctca-ccttagcagtg------------------------------------
-------------------------------------------tattttagtagatctg-
cctgttttgct--------ccccac----tctgtctcttgtaaa-tcctctcactc----
-------------catcct----------------gcatctctggcctaaaccccag-tt
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcacaaataaat----aaa---
------taatttttttttttttttaatttatttgtttgctcatgcactgg----------
----gtacagtcagaagcg-------------
>NW023602073.1:123300082-123300444(-)
--------------------TAACAGACAATTGTCAGGGATTTTAATTATTCTTAACAAT
GGCAAAGGcagacctccctgg-----tgccct----aggggtt-aaatctta-gcgc--C
ATCATACT-A----TCAC-----CCTGTC-------TACCTGGATA-aga-------tcc
c-----------------------------------a----------------gccag--
-gaagctatcc---------acatat-ggtgcagc--agacctctcc-tgtctt------
gctcgctgctcc-ccagagcagtg------------------------------------
-------------------------------------------tattgcagtacatctg-
cctgttctgct--------ccccac----tctgtctctggtgaa-gtctctca-------
-------------ccaccc----------------gcacctctggcctatatcccag-tt
gttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaaacaaat----aca---
------atattttaaaaaacaatagcaaaGGCTAGGAGAATCTTGCTTAT----------
------------CATAATGTTTCCATGAGA--
>NW026555331.1:19043241-19043604(+)
-------------------TGAGGCAGAATGAAGACAGAGAGAGGACTCAGTAATTTGTT
Gatcagaaagggcctccctgg-----tggcct----atgggtt-aagttcta-gtgc--t
gtcacc-----------------tctgtg--------gcccaagtt-tga-------ttc
c---t-------------------------------g----------------gccag--
-gaagctaatcc--------acatgt-ggcacagc--agacctctcc-tctttt------
gcccactgctcc-cctcagcaatg------------------------------------
-------------------------------------------tatttcagtaaatcta-
cctgttctgtt--------ccccac----tctgtctccggtgaaatGTGCTCACACACAC
TG-----------CTCCCC----------------CATCCCCTGGCCTACACTCCTG-TT
CATCTAT-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcgaaaataaaa----att---
------cacaaaaaatcaCACAGAAAGAGAAAACGAGAAGCTGGTTTTCC----------
------------agaagttttcttct------
>NW023605083.1:98105155-98105493(-)
-------------------CGAAAGCATGTGCTGTGAAATTTATGGTCTGGCTGGGGAAG
Agacttggagggcctccctgg-----tgttct----aggggtt-aagtctca-gcac--t
atcact-----------------gctatg--------gcctgactt-cga-------tcc
c---c-------------------------------a----------------gccag--
-ggagctaaccc--------acctaa-ggcacagc--agacctcccc-tgtctc------
ccctgctgctct-ccttagcagtg------------------------------------
-------------------------------------------tatttcagtaaatctg-
cctg-tctgct--------ccccac----tctgtctctggtgag-tcctctca-------
-------------ccccct----------------gca---ctgaCCTATACTActa---
-cccaat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------aaataaataaat----ataaaa
ag---acttgtaatcaaataaatgaaataaagtatgaTAGAGACTGAGAC----------
--------------------------------
>NW023605083.1:34970500-34970839(+)
-------------------AAAATGCATATATCTACTATATTTATGCAGTACAATGAAAC
ATAAAtaaggggcctcactgg-----tggcct----aggtgtt---gtctca-gcac--t
attacc-----------------actatg--------gcctgagtt-cga-------tac
c---t-------------------------------g----------------gccag--
-ggagttaaccc--------atatat-ggcacagt--ggacctctcc-tgtctc------
acccattactcc-cctcagcagag------------------------------------
-------------------------------------------tatttcagtagatctt-
cct----------------ctctac----tctgtctctattgaa-tcctctca-------
-------------ctgctc----------------aaacttctggtctacaccccag-tt
tttccac-----------------------------------------------------
------------------------------------------------------------
--------------------------------------acataaataaat----ctt---
------aaaagaaacataaatggCACTTACTATTACAATACATATTGTAA----------
--------------GTATATTATC--------
>NW023603184.1:144279666-144280008(-)
-------------------TACAAAATTTCAGTCTGCCCAGAACGcaactttaaaacact
ggaaataCAGAGccgccctgg-----tggcct----agggttt-aagtctca-gcac--t
atcacc-----------------tctaca------aagcctgagtt-caa-------tcc
a-----------------------------------g----------------gcccg--
-ggagctaacc----------tacat-agcacagc--agacctctcc-tgtctc------
gcccactgctccttctcagtagtg------------------------------------
-------------------------------------------aatttcagtagatcct-
cctgttcggct--------ccctac----tctatctc---tcaa-tcctctca-------
-------------cgcccc----------------acacctctggcttataccccag-tt
cttctac-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaaattaaa----aaa---
------aaaaaagaaaaaaaaaaacgaacaacaaaaaacactggaaatacaaacat----
--------------------------------
>NW023602073.1:97334346-97334685(-)
-------------------ACATAGCTGTATTTACCCAATGGAATTGTCATAAAGATTAG
Tgagttggggggcctccctgg-----tggtgcta--aggggtt-aaatctca-gcac--t
a------------------------------------gtTCCAGta-tga-------tcc
c---t-------------------------------g----------------gctag--
-ggagctgacc----------cacat-gacacagc--agacctctcc-tgtctc------
gcccgctgctcc-cctccacagtg------------------------------------
-------------------------------------------tatttcagtcaatctg-
cctgttctgtt--------cctcac------catctttggtgaa-tcctctca-------
-------------ccccct----------------gcacctctggcctataccttgg-tt
tttgcat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aaa---
------tctttaattaaaaaaataattagttgaCAAGTAAAAGATTTGGG----------
------ATGGTTCATGGCA-------------
>NW023602073.1:16189284-16189648(+)
-------------------GAGCAGTTTAGTAAGCTTCAGATCccttcttttgaaaatgt
gagAGATGGGTGGCTTCCTGG-----TGGCACT---GGgtttc-aagtctca-gtgc--t
atcaagct-a----tccccagccactgca--------gcatgagtt-cga-------tct
c---t-------------------------------g----------------gccag--
-ggag-aaacc----------cacat-ggccc-----agacctctcc-tgtcta------
ccctgctactcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtcaatctg-
cctgttctgtt--------ccccac----tctgtctctggtgaa-tattctca-------
-------------tgctcc----------------acacctctgacctacactccag-tt
cttgtaa-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaataaata----aaaaat
aa---atctttagtaaaagaaaaaagacagtgtGAGAAACTTTTGAATAA----------
-------ATCCTAGAGATG-------------
>NW023603184.1:124844254-124844607(+)
-------------------TAGTGAAACTAAAAAcgttttaaatattaattcactCTAAA
ATAACATTAGGAcatccctag-----tggcgc----aggggttaaagtctca-gtac--c
atcaagct-a----tcaccagccactgca--------gcatgagtt-cta-------tct
c---t-------------------------------g----------------gccag--
-agagctaacc----------tacat-gg---aga--agacctctcc-tgtcat------
---------gcc-cctcagtagta------------------------------------
-------------------------------------------tatttcagtagatctg-
cctgttttgct--------ccccac------tgtctctggtgaa-tcctctca-------
-------------agcccc----------------acacctctggcctacaccccag-tt
cctgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcatatataaaa----ata---
------agcctttaaaataacattaaactcTATAATAGCaagcaatattt----------
-------ttattaaaaatatttca--------
>NW023601322.1:33328904-33329280(-)
-------------------GCCAAAGTAGGAGTAACACATATtagctatatttaaaatgt
gttgcatacgggcctccctgt-----tggctca---aggggtt-gggTTGCA-GCCC--T
aagaagct-g----tcggcagccactgca--------gcatgagtt-cca-------ttc
c---t-------------------------------g----------------gccag--
-agagctgacc----------cacat-ggc-cagc--agacctctcc-tgtctt------
gtctgttgcttc-tctcaacagtg------------------------------------
-------------------------------------------tatttcagtagatcc--
cctgttctgca--------tcccac----tctgtctctggtgaa-tcctctcaccgccct
cccc-------CCCTCCCG----------------Gcaactctggcctttaccccag-tt
cttgtag-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aaa---
------tctttaaaaaaataaataaaatgtgttgcaTAAAGTCCAAATAT----------
--------TCCCTGCAGTCATTC---------
>NW023601104.1:85304119-85304457(-)
--------------------ACATGAGGATTTTTGAGAGAAGTAGGTCTTCAAAAATACA
TTGAAGTGGAGGCCTCGCTGA-----TGACcc----aggggtt-cagtctca-gtgc--t
agcaagct-a----tcaccagccactgca--------gcctgattT-CAA-------TCT
C---T-------------------------------G-----------------------
----GGTGAca----------cgcat-ggtgcagc--agacatctcc-tgtctt------
gcccgctgctcc-actaaccagtg------------------------------------
-------------------------------------------tattttagtagatttg-
cctgttctgct--------ccctac----tgtgtctctggtgaa-tcctctca-------
-------------------------------------gcccctggcttacaccctag-tt
cttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aaa---
------aataaatgtcataaataaataaaaataagtaaaaattaatgtaaacaaAT----
--------------------------------
>NW023604295.1:100347981-100348348(+)
-------------------AGTGGTATTGGGTAGCCaagaaattttccttaaaataaagc
tcaaaatatgggcctccctgg-----tggcct----aggagtt-caGTCTTA-GTGA--T
ATCACTGTCA-----------CTGCTGTG--------GCTTGAGTTATCa------accg
c-tgc-------------------------------a----------------gcctg--
-agttccatccc-------cacatag-agtgcagc--aga--tctct-tgtTTT------
gcttactgctcc-ccttagcagtg------------------------------------
-------------------------------------------tatttcagtaaatcca-
cctcttctgtt--------ccctgc----tttgtctctggtgaa-ttctctca-------
-------------cccctt----------------gtacctctggtctacatcccag-tt
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aaa---
------taaatcataaaaaatataaagctcCAAGTAGTCATATAAATGTA----------
AAGCAAGGCTTTATAAATA-------------
>NW023605083.1:2869700-2870068(+)
-------------------cttgaatgtatttttttctacattccaTCTTAAGAAACTTG
agaaatcaggggcctccctgg-----tggcgcc---aggggtt-aagtctca-gagc--t
atcaaact-a----ttgg-----ctggtg--------gcctgagtt-cga-------tcc
c---c-------------------------------a----------------gccag--
-ggagctgacc----------------cacacagc--agacctctcc-tgtctccccgct
gctcccctcacc-cctcagcagtg------------------------------------
-------------------------------------------tatttcaatagatcca-
cctgttctgct--------tcccac----tctgtctctggtgaa-ccttttcac------
-------------ccccct----------------gcacttctggtctacacccctg-tt
cttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----aaa---
------ataaatcttataaaaaaagaaagaaacttgagAAATCAGTAAGG----------
------CTATTTATCAGTGAATTAAAG-----
>NW023603184.1:39009179-39009531(+)
-------------------cacccCATACAAccgataagggactgatcacaaagatcaac
aaagagcttgggcctccctgg-----tg----------------aagtctta-gcac--t
atcaagct-acagcccaccagccactgta--------gcacaagtt-caa-------tcc
c---c-------------------------------a----------------gccag--
-gga-ctaatc----------cacat-ggcgcagc--agacgcctcc-tgtctt------
acctactgctca-cctcagcagtg------------------------------------
-------------------------------------------tatttcagtagatcca-
cc-attctgct--------ccccac----tctgtctttggtgaa-tcctctca-------
-------------cccccc----------------acacctctggccaacaccccag-tt
cttatat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----taa---
------atcttttttaaaaagctcacacAATTCAAtataaacaaagtaaacaatccagtc
aa------------------------------
>NW023604295.1:122802979-122803340(+)
-------------------AGAATGATTTCAATTTGGATAAAGTTGAGGGATATAGATCT
ACAAGTGCTGGACCTTCCTCC-----TGGTGT----AGGGATT-AAGTCTGA-GGGC--T
AATATGCT-A----TCA----CCATTGTG--------GCCTAAGTT-Cta-------tgc
c---t-------------------------------g----------------gccag--
-ggagtt-acc----------cacat-ggcacagc--aggcctctcc-tgtctt------
gcccgctgctc--cctctgcagtg------------------------------------
-------------------------------------------tatttcagtcagtctg-
cctgttctgct--------ccccac----tctgtctctggtgaa-tcctctca-------
---------------cccc----------------acacctctgg-ttacacccctg-tt
cttgtat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcattaatagaa----aaa---
------aataaatctaagaaaaatgaTACAACTGCTGATGGAACAGCTGG----------
-------AAGTTGAGGATGATCTTTCTA----
>NW023604861.1:121945466-121945847(-)
-------------------TGACCAAACCCTGATCTAAAatttttgattattaaaatacc
tgtgattttgggcctccctgg-----tggcaca---aggtgtt-aagtctca-gcac--t
atgaaact-a----cccACAGCcgctgca--------gaatgagtt-cga-------ccC
C---CC------------------------------A----------------CCCAG--
-GGACCTAACA----------CAtag-agtgcagc--agacctctct-ggtcta-----t
acccgctgctcc-cctcagcagag------------------------------------
-------------------------------------------tatttcagtggatctg-
cctgttctgct--------ctcaac----tctgtctctggtgaa-tcctctca-------
-------------cctcctttccctccctcgcccggaacctctggtctacaccccag-ct
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gtaaaaataaat----aaa---
------attaaaaattttaaaaatacttgtgatttttttttaacaattaa----------
----atgtaatggaaaa---------------
>NW023605083.1:53413867-53414228(+)
-------------------AAATAAGCATGTCAACATTTTATTGGTGTTCCTTAAGAAAC
TAGAatcaagggcctctctgg-----tggcct----acgaatt-aagtctca-gcac--t
accaccatga----aggcccacaGCTaaa--------gtctgagtt-tga-------tcc
c-----------------------------------g----------------gctag--
-ggagctaacc----------cacat-ggtgcagc--agacctctcc-tgtctc------
gcccgctgctcc-cctcagtag-g------------------------------------
-------------------------------------------tattatagtagatctg-
cctgttccact--------ccccac----tctgtctctagtgaa-tcctctca-------
-------------cccccc----------------acatctctagcctacaaATAAA--A
CTTGAGT-----------------------------------------------------
------------------------------------------------------------
--------------------------------------GTACAAATAAAA----TCA---
------TACCTATATGGACAACAAGTTTACAACAAATAAACCAAAGAGCA----------
------------TAAAGTCTCTCCAA------
>NW023605083.1:30567304-30567647(+)
------------------------------------------------ATGCAGCACAAA
AGCACCCagaatcctccacca-----tagaccact---------gtgCCTTC-TCAC--C
ACtatgct-----cccctcccccactatgcatgtggtgcaagggtt-aaa-----gataC
AGGGC-------------------------------T----------------ATCAG--
-GCAgctaacg----------cacat-ggcacagc--agatctctcc-tgtctc------
gtccactgctcc-cctcagcaggg------------------------------------
-------------------------------------------tatttcagtagacctg-
tgtgttctgct--------ccccag----tctgtctctggtgaa-tcctctcacc-----
-------------tccccc----------------acacctctggcctacaccccag-tt
cttatat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcatgaataaat----aaa---
------ggtttattaaaaaaacccacaatgagataccaactcacacttgt----------
------------gagaatagCCTC--------
>NW023600993.1:85955636-85955980(+)
-------------------AAAGCTACAATTTTGAACTTGTTTGTCCCaggttacaaaaa
caaaaacttgggcctccctga---------------ggggtta-aagtctca-gcgc--t
atcaaact-ac--cTTGACCGCCactgca--------gctcgggtt-caa-------ttc
c---c-------------------------------g----------------gc-----
---------------------cacac-ggcgcagc--ag-cctctcc-tgcctc------
acccgctgctcc-cctcagcagtg------------------------------------
-------------------------------------------tatctcagcagctctg-
cctgttctgct--------ccccgc----tctgtctctggtgag-tcctctca-------
-------------cccctc----------------acacctctggcctgcaccccag-ct
cttgtatt----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcacaaatttaa----aaa---
------atatatagattgacagagacattctgcaggggaggaggaggtag----------
------aggaatgaaaat--------------
>NW023602530.1:2750-3099(+)
-------------------TAGAAAATTACAATTGCAAGttagaaagttttattaaaatc
attactgttgggcctcccttt-----TGTCTGATAGAGGGGTTGAAGAcaaa-gtgc--t
atcaagct-a----tcaccagccactaca--------gcctgagtt-cta-------tcc
c---c-------------------------------a----------------tccag--
-gg------------------------agcacacc--agacctctcc-tctttt------
ggccactgctcc-cctcagcagtg------------------------------------
-------------------------------------------tatttcagta-actcg-
cctgttctgct--------ccccac----tctgtccctggtaaa-tccta----------
-------------cccccc----------------acacctctggcctataccccaa-tt
cttgtatt----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcataaataaat----------
-------cttttaaaaaagcattattgttaatcaaagttttaaattatta----------
----aaaaaaaaaaaaacg-------------
>NW023604972.1:17906182-17906531(-)
-------------------atttgtagtcAAAACTGAGTTTATTCTGCTCATCTTATAAA
ATggtcactgggcctccctgg-----tggcta----gggATTA-AGTTCTCA-GTAC--C
Attacc-----------------actata--------gcctgagtt-tga-------tcc
c---c-------------------------------a----------------gccag--
-ggagctaaccc--------acatat-ggagccgG--AGACCTC----TCTGTC------
ACcagctgctcc-tttcagcagta------------------------------------
-------------------------------------------catttcaataaatcca-
cctgttctgct--------ccccac----tctgtctctggtgca-acTTCTCA-------
--------------CCTTC----------------AAACtactggcctacactccag-tt
gtcccat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gtgcaaaataaa----tat---
------ttttaaaaaataaaaaaaaattgtgagcgTACTGCTTAAAATGA----------
-----------ACAGGGTAGTATTT-------
>NW023604972.1:98614758-98615122(+)
-----------------------ttttaattttgttacattattttttttaattttgtat
atttatttgtgaacTCCCTGC-----TGGCAT----AGGGGTT-AGGTTTCA-ATGC--T
ATAATGCG-A----TCCC---TTACTGTG--------gtctgagtt-cca-------tct
c---c-------------------------------a----------------gcgaG--
-GGAGTTAACC----------CAAAT-GGtg------agatgtctcc-tgtctc------
acccactgctc--ccttagcagtg------------------------------------
-------------------------------------------tatttcagtagatctg-
cctgttctgct--------ccccac----tctgcctctggtgaa-tcctctcaccactcc
ag-----------CCCCCT----------------GTACCTATAGCCTACACCTCat-tt
cttctgt-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaaataaat----aat---
------acaacttttaaaaacattttgtttttttaaatgtttatttttta----------
-------aaattgaggttactatt-------g
>NW023604295.1:23617055-23617411(-)
-------------------gCCTAAAGCTGTCTTGGACAtttaatagatgctcaataaat
agtaactatgtgtctccctgg-----tggtgc----aggggttaaagacaca-gtgc--a
aTCAAGAT-A-------------------------------------TTA-------CCC
CCGAC-------------------------------A----------------GCCAG--
-GGAGAtggcc----------cacag-ggcacagc--agatctctca-tGTCTC------
AACCACTACTCC-CCTCATTAGTG------------------------------------
-------------------------------------------CATTTaggtagttctg-
cctgttctgct--------ccccac----tctgtctctggtgaa-tcctctaactgcCCC
TCCC----AGACCACCCCC----------------Agaactctggcctatatcccag-tt
cttgtac-----------------------------------------------------
------------------------------------------------------------
--------------------------------------acataaatcaat----------
-------ctttgaaaaaatatataaataactgtgCTTAGACAGTTTTGCA----------
--------------AGGTGTTTGTTCTAC---
>NW023601851.1:9493920-9494263(-)
-------------------GTTGAGGTCTGCAGATGTCTTTACCTACCTTTCATGATGAA
ggttttttggggcctccctgg-----tggcct----gggggtt-aagtctca-gcac--t
attgcc----------------TTCTCTG--------GCCAGGGTT-TCA-------GCC
C---C-------------------------------A----------------GCTAG--
-GGAGCCGCCCC--------ACATATggccgcagc--aggcctctcc-tgtgtc------
acccactgctcc-cgttagccagg------------------------------------
-------------------------------------------tatttcagtggttctg-
cctgtttgtca--------ccacac----tcagtatctggtgaa-tcctaaca-------
--------------ccccc----------------aaacctctggtctacaccccag-tt
ctacaaa-----------------------------------------------------
------------------------------------------------------------
--------------------------------------ataagg----------gaa---
------ttttgttggaagattaattctgcatacaagatctggggtacaag----------
----------ccggaggta-------------
>NW023601653.1:45869871-45870229(+)
-------------------ATACCTGAAAAAGTCAAATGTAGGCTGTCAGAAAATCCTTT
GTTttacgggggcctccctgg-----tggcct----aggggtt-aagcctcc-cTAG-GC
ACTGTT-----------------ACcaca--------gtgtgagtt-caa-------tcc
c---c-------------------------------a----------------gctagac
agggagaaacc----------cacat-gtcgcagc--agacctcttt-tgtctc------
gccagctgctcc-cctcagcagtg------------------------------------
-------------------------------------------gatttcagtagatctg-
cctgttctgct--------tcccac----actgcctctggtgag-tcctctca-------
-------------cacacc----------------cacctctggccttatACCCCAG-TT
CATTTAT-----------------------------------------------------
------------------------------------------------------------
--------------------------------------GGCagtataaat----aaa---
------tttctttggaattcattgttttacatattttatcaagAAATTTC----------
------------AGAAGTCTTTAATTTAG---
>NW023605305.1:104729594-104729968(+)
-------------------gcaataaaaaataatgctagCTGATATTATATGTGAAAAGA
ATTGctcttgagcctccctgg-----tggcct----aagggtt-aagtctga-GGGC--T
ATCACC------------------CTAta--------gcctgagtc-aca-------cac
a---cacacacacacacacacacacacacacacag-a----------------gccag--
-ggagctaacct--------acacat-ggcacagc--agacatcccc-tgtctc------
acctgctgctcc-ccttaagcgta------------------------------------
-------------------------------------------tatttcactagatctg-
gctgttctgctcccctctctctcac----tctgtctctgttgaa-tcctctca-------
-------------ctccct----------------gtacctctggtctacaccccag-tt
cttctat-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaatagtcca----aaa---
------aaaaaaaaaacaaaaacaaaaaaacctgttcTTGCTTTCATT------------
--------------------------------
>NW023601322.1:53755187-53755532(+)
-------------------AACCACACAATTGAGGCAGTATACATGGTATCTGTCCATTT
GGGTTGGTTGGACCTCCGTGG-----TGGCCt----tggggta-aagtctca-gcac--t
gtcacg-----------------gCTGAG--------TACTGAGT--CAA-------GCC
c---a-------------------------------t----------------gccag--
-ggagcaaaccc--------atcTAT-ATTGCAGC--AGACCCCCCCATGTCTT------
GCCCACaattcc-cctcagcggtg------------------------------------
-------------------------------------------taattcagtcaatctg-
cctgttgtgaa--------tcacac----tctgtctctgctgaa-tcctgaaat------
-------------ccctcc----------------acacctctggcctacaccccag-tt
cttctac-----------------------------------------------------
------------------------------------------------------------
--------------------------------------acccaaagaaaa----atg---
------attatttgtgATCTCTTGAAATTTAGGTATACAGTAGAGTAGGGTAAAT-----
--------------------------------
>NW023601322.1:50756556-50757005(+)
-------------------tatttccaatactTAACCACCGTCAGGCCCATAAAGACTAC
AAAtaaaaggggccttcctgg-----tggcct----aggggtt-aggtctca-gcac--t
atcact-----------------tctaca--------gcctgagtt-caa-------tcc
c---t-------------------------------g----------------gccag--
-tgagctaaccc--------acatat-ggtgcagc--aga-ctctcc-tgtctt------
gcccactgcttc-cttcagcagtggtgatgatggtgatgatagtggATGTAGCAGTTCTG
GGTCAGTAGGTGAGTCAGTTATGACCCAGTTATGGGTCAGTTATGAgtcattagatcca-
cctgttctgat--------ccctac----tctgcctctggtgaa-tcctctcaacccctc
tcCC-------CATcaccc----------------acacctctagcctgcaccccag-tt
cttctac-----------------------------------------------------
------------------------------------------------------------
--------------------------------------gcaaaaataaat----aaa---
------atctctattaaaataaaagactacaaacaaaaatcatatttaat----------
-----tttcattaaatatgtgTGA--------
>NW023600993.1:84509998-84510336(-)
GCGCTCCCTCCAGAGAAGTAC-------------------TAGTAGCCTTATAAGCCAGG
Tagtgagaagggcctccccag-----tggccta---gtgGGTT-AAGGCGCA-GTGC--T
ACtgct-----------------gctacg--------gcctgagtt-cga-------tac
c---c-------------------------------a----------------gcctg--
GGGAGCCAGCCCGCCCGCCCACGTAA-GGTGCAGTTGGGCCTACTct-cctctt------
gcccactgctcc-ccttagtggtgtaaA--------ATAATG------------------
-----------------------------------------TTCACTTCTTCCATCCTG-
TGTGTTGTGCccatt----cccctc----cccctccctcgtctagtcctcccctccccct
cgtctagtcctcccctccc----------------cctcgtCTAGTCTTtccccccc-tt
ccttccc-----------------------------------------------------
------------------------------------------------------------
--------------------------------------ccaaacAAC-------------
------------------------------------------------------------
--------------------------------
