>input_001.bnk
-----------------cGgAGGTGGcACAGTGG------TAAAGcatTGGACTtTCAAG
CATGAG---GTCCTgAGTTc-ATCCCTGGCATT-CATGTGCCAGAGTGATGCTCTGgTTC
TCTCtctcTcT--------------------------cTATtAATAAATA----------
AATtTTTaAAAaAa-------
>input_143.bnk
---------------gcgGGAGGTGGCgCAGTGG-----ATAgAGCAcTGGACTcTCAAG
CATGAG---GTCCtGAGTTt-ATCCCTGGCATc-CATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCTCCtc---------------------------tAtaAATAAATA----------
AATcTTTaaAaaaaa------
>input_072.bnk
--------------gcCgGGAGGTGGTgCAGTGG-----aTAAAGtaTTGGACTCTCAAG
cATgAg---GTCCTGAGTT--ATCCCTGGCATT-CATGTGCCAGAGTGATgCTCTGGTTC
TcTCTtCTcTt-------ctCt---------------ttATAAATAAATA----------
AATcTTTtAAAAAaa------
>input_006.bnk
---------------gcaGGAGGTGGCACAGTGG-----AtAAAGCAcTGGACTcTCAAG
cATGAG---GTCCtGAGTTcaATCCC---cGCATCATGTGCCAGAGTGATGCTCTGGTTC
TCTCTcTcctt---------------------------aATAAATAAATA----------
tTtTTAAAAAaAaa-------
>input_193.bnk
------------------ggaGGTGGcaCAGTGG-----ATAAAGcaTTGgaCTcTCAAg
CATGAG---GTCC-AAGTTTaATCCCTgGcATc-CATGTGCCAGAGTGATGCTCTgGTTc
tCTcTcCTCTC--------------------------cTcATaaaAaAtA----------
AAtataAaa------------
>input_040.bnk
-----------------cGGAGGTGGcACAGTgG-----ATAAAGcaTTGGACTCTCAAG
CATGAG---GTCC-GAGTTT-ATCCCTGGcATtgCATGTGCCAGAGTGATgCTCTGGTTC
TCTCTCtctct---------------------------cATAAATAAATA----------
TTTttAAaAa-----------
>input_055.bnk
---------------gcgGGAGGTGGa-CAGTGG-----aTAAAGcATTGGACTCTcAAG
CATGAG---GTCCCAAGTT--ATCCCtaGCATTACATGTGCCAGAaTGATGCTCTGGTTC
TCTCTCtctCT-------------------------CTcATaAATAAATA----------
AATattTaAAAAAaaa-----
>input_117.bnk
------------------GGAGGTGGA-cAGTGG-----aTAAAGCatTGGACTttCAAG
CATGAG---GTCCCAAGTTCAATCCCtgGCATtgCATgTGCCAGAGTGATGcTCTGgTTt
ttcTCTTTCtc----------------------------TatAatAAATa----------
AAtatTTataaAaa-------
>input_002.bnk
----------------cGGGAGGTGGcaCAGTGG-----ATAAAGCATTGGACTCTCAAG
CATGAG---GTCC-gAGTTtaATCCCTGGCATCACATGTGCCAGAgTGATGCTCTGGTTC
TCTCTctctcc--------------------------TCATAAATAAATA----------
AATTttAAAaAaa--------
>input_018.bnk
----------------cgGGAGGTGGcACAGTGG-----ATAAAGcATTGGACTCTCAAG
CATGAG---GTCC-cAGTTTGATCCCCAGCATCACATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCTCTct--------------------------taATAAATAAATA----------
AAttTTTaAAAaaa-------
>input_051.bnk
--------------gccgGGAGGTGGCACAGTGG-----ATAAAGCATTGGACTCTCAAG
CATGAG---GTCC-GAGTTCAATCCCTGGCATCACATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCcttCt-------ctct-------------cTtaATAAATAAATA----------
AAtatTaaaAaAa--------
>input_023.bnk
---------------cCaGGAGGTGGCACAGTGG-----ATAAAGTGTTGGACTCTCAAG
CATGAG---GTCC-GAGTTCAATCCCTgGCATCACATGTGCCAGAgTGATGCTCTGGTTC
TCTcTctcTCT-------CTCT------------CATAAATAAATAAATA----------
AATtTaAaa------------
>input_026.bnk
-----------------cGGAGGTGGcgCAGTGG-----ATAaAGtaTTGGACTCTCAAG
CATGAG---GTCCtGAGTT-gATCCCTgGCATTgCATGTGCCAGAGTGATGCTCTGGTTC
TCTCTctcttc----------------------------ATAAATAAATA----------
AATTTtAaAAAaa--------
>input_166.bnk
-----------------gGGAGgTGGCaCAGTgG------TAAAGCACTGGACTcTCAAG
CATGAG---GTCCTGAGTTc-ATCCCTAGCATCaCATaTGCCAGAGTGATGCTCTGGTTc
TCTcTctctTc----------------------------ATAAATAAATA----------
AATTTtaAaaaa---------
>input_082.bnk
------------------ggAGGTGGcACAGTGG-----ATAAAGTaTTGGACTcTCAAG
CATGAG---GTCCTGAGTT-AATCCCtAGCATCACATGTGCCAGAGTGATgCTCTG-Ttc
TcTcTCttttt-------cT-----------------TaATAAATAAATA----------
AATtTTaAAAAa---------
>input_050.bnk
--------------gCcaGGAGGTGGcACAGTGG-----ATAAAGcaTTGGACTCTCAAG
CATGAG---GTCCTGAGTT-AATCCCcaGCATCACATaTGCCAGAGTGATGCTCTGGTtc
TtcTCtTCTCT-------CTC--------------ATTAATAAATAAATa----------
atttTTTaAAAAaa-------
>input_004.bnk
----------------cgGGAGGTGGtACAGTGG-----ATAAAGTaTTGGACT-tCAAG
CATGAG---GTCCtgAGTTCAATCCCTgGCATcACATgTGCCAGAGTGATGCTCTGGTTC
TCTCTCTctCt-------taT----------------tAATAAatataTA----------
AAat-----------------
>input_028.bnk
--------------gccgGGAGGTGGCACAGTGG-----ATAAAGCATTGGACTCTCAAG
CATGAG---GTCCTGAGTTCAATCCCtGGCATCACATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCtCtcT-------cAT----------------aAATAAATAAAta----------
atAttTTTaAAaAa-------
>input_096.bnk
---------------ctGGGAGGTGGcACAGTGG-----ATAAAGC--TGGACTCTCAAG
CATGAG---GTCCTaAGTTCaATCCCTgGCAtTGCATGTGCCAGAGTGATGCTCTgGTtC
TcTCTCTcCTt-------CAT----------------TAATAAATAAata----------
aAatttTtaAAAAaA------
>input_020.bnk
----------------ccGGAGGTGGcaCAGTGG-----ATAAAG--TTGGACTCTCAAG
CATGAG---GTCCTGAGTTTGATCCCTAGCATTGCATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCTCTCt-------tTc----------------tcATtAATAAATA----------
AATTTTTtAAAAAAaa-----
>input_064.bnk
-----------------cGGAGGTGGcAcAGTgG-----ATAAAG--TTGGACTCTCAAG
CATGAG---GTCCcaAGTTtaATCCCTGGCATCaCATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCTtct-----------------------------ATAAATAAATA----------
AAttttTTaAAAAaAa-----
>input_013.bnk
gt----------ggcCtGGGAGGTGGCACAGTGG-----ATAAAGCATTGGACTCTCAAG
CATGAG---GTCCTGAGTTtgATCCCTgGCATtgCATGTGCCAGAGTGATGCTCTGGTTC
TcTCTcTCTCT-------cTCtT-----------CTCTCATTAATAAATA----------
AATtTTTaAaa----------
>input_035.bnk
--------------ggcgGGAGGTGGCaCAGTGG-----ATAAAGcAtTGGACTCTCAAG
CATGAG---GTCCTGAGTTTGATCCCTGGCATcgCATATGCCAGAGTGATGCTCTGGTTC
TCTCTCTtcct-------ctCt------------cTCTCATtAATAAATA----------
aAtttTTAAAAaa--------
>input_014.bnk
----------------cgGGAGGTGGTGCAGTGG-----ATAAAGtATTGGACTCTCAAG
CATGAG---GTCCTGAGTTCAATCCCtAGCATCaCATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCTCTCT-------CTc----------------tcaTAAATAAATA----------
AATTTTaAAAAa---------
>input_037.bnk
gt----------ggcCcgGGAGGTGGcACAGTGG-----ATAAAGcaTTGGACTCTCAAG
CATGAG---GTCCTGAGTTTGATCCCTGGCATTgCATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCTCTCT-------CTc----------------TcATAAATAAATA----------
AATTTtaaAaAaaaa------
>input_016.bnk
----------------cgGGAGGTGGCACAGTGG-----ATAAAGCATTGGACTCTCAAG
CATGAG---GTCCTGAGTTTGATCCCTGGCATCACATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCTCTCtC-------------------------taATAAATAAATA----------
AaTTTtAAAAAAa--------
>input_022.bnk
-----------------gGGAGGTGGcaCAGTgg-----ATAAAGtgTTGGACTtTCAAG
CATGAG---GTCCTGAGTTtgATCCCTgGCATcaCATGTGCCAGAGTGATGCTCTGGTTC
TCTCTcTCTCT-------CTtt-------------aTTAATAAATAAATA----------
AaTaTTTAAAaaAaa------
>input_054.bnk
------------------GGAGGTGGcACAGTGG-----aTAAAGCaTTGGACTcTCAAG
CATGAG---GTCCTGAGTTCAATCCCcAGCATTgCATGTGCCAGAGTGATGcTCTGGTTC
TCTCTCTCtCT-------ctcc-------------aTTAATaAATAAAtA----------
AaTttTAAAaAaa--------
>e1-3consensus_32seqs_CONSENSUS
---------------GCGGGAGGTGGCACAGTGG-----ATAAAGCATTGGACTCTCAAG
CATGAG---GTCCTGAGTTCAATCCCTGGCATCACATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCTCTCT-------TTCT-------------CATAATAAATAAATA----------
AATTTTTAAAAAAAA------
>input_053.bnk
---------------ccgGGAGGTGGCACAGTGG-----ATAAAGCATTGGACTCTCAAG
CATGAG---GTCCTgAGTTCAATCCCTgGCATCACATGTGCCAGAGTGATGCTCTGGTtc
TCTCTCTCTCT-------CTCT---------------CTAtAAATAAATA----------
AATctttAAAAaaaa------
>input_025.bnk
-----------------gGGAGGTGGtaCAGTGG-----ATAAAGCAtTGGACTCTCAAG
CATGAG---GTCCTGAGTTcAATCCCTgGCATCaCATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCTttC-----------------------------ATAAATAAATA----------
AAtTTTTAAAAAa--------
>input_015.bnk
----------------cgGGAGGTGGCACAGTGG-----ATAAAGcATTGGACTCTCAAG
CATGAG---GTCCTGAGTTCAATCCCTGGCATCACATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCttcTC-------TCAT---------------AAATAAATAAATA----------
AAttttaAAaAa---------
>input_029.bnk
------------------GGAGGTGGCACAGTGG-----ATAAAGcaTTGGACTCTCAAG
CATGAG---GTCCTGAGTTCAATCCCTGGCATCACATGTGCCAGAGTgATgCTCTGGTTC
TCTCTCTcctc-------tCTCTC----------taTaAATAAATAAATA----------
AATTTtAAaaaa---------
>input_047.bnk
------------------GGAGGTGGcACAGTGG-----ATAAAGtaTTGGACTCTCAAG
CATGAG---GTCCTGAGTTtaATcCCcAGCATCaCATGTGCCAGAGTGATGCTCTGGTTC
TCTtTttTcTC-------TCTCa--------------TaATaAATAAATA----------
AATtTTTAAAAAAaa------
>input_017.bnk
--------------gcCgGGAGGTGGCACAGTGG-----ATAAAGCATTGGACTCTCAAG
CATGAG---GTCCtgAGTTCAATCCCTGGCATt-CATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCttttc-------TcTc---------------taATAAATAAATA----------
AATttTaaAaaa---------
>input_063.bnk
---------------ccgGGAGGTGGtaCAGTGG-----ATAAAGCaTTGGACTcTCAAG
CATGAG---GTCCtgAGTTTGATCCCTaGCATc-CATGTGCCAGAGTGATGCTcTGGTTC
TCTCTCTcttc--------------------------taATaAATAAATA----------
AATtTTAAAaAAaa-------
>input_039.bnk
----------------caGGAGGTGGcACAGTGG-----ATAAAGcatTGGACTCTCAAG
CATGAG---GTCCTgAGTTCAATCCCTGGCATcgCATGTGCCAGAGTGATGCTCTGGTTC
tcctctCTcTC-------TctC-------------ATtAATAAATAAATA----------
AATttTtAaAaaa--------
>input_019.bnk
-----------------cGGAGGTGGtaCAGTGG-----ATAAAGcATTGGACTCTCAAG
CATGAG---GTCCCaAGTTTGATCCCTGGCATtgCATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCTCTCt-------ctctCT----------caTtAATAAATAAATA----------
ATTTTTAAAaAaa--------
>input_032.bnk
---------------gccGGAGGTgGtaCAGTgG-----aTaAAGcaTTGGACTctCAAG
CATGAG---GTCCCaAGTTcaATCCCTGGCATcaCATGTGCCAGAGTGATGCTCTGGTTC
TCTCTtCttct-------cTcTct----------cATaAATAAATAAATa----------
aAtttttaaAAAAAa------
>input_052.bnk
---------------ccgGGAGGTGGCACAGTGG-----ATAAAGcATTGGACTCTCAAG
CATGAG---GTCCTGAGTTCaATCCCtaGCAttgCATGTGCCAGAGTGATGCTCTGGTTC
TCTCtcTCTct-------CTcTCT----------CatTaataaATAAATA----------
AATAttTTTTAAAAaa-----
>input_030.bnk
----------------gcGGAGGTGGt-CAGTGG-----ATAAAGcaTTGGACTCTCAAG
CATGAG---GTCCtgAGTTcaATCCCTGGCATCaCATGTGCCAGAGTGATGCTCTGGTTC
TCTCTcTCTCT-------ctcTcT----------CATTAATAAATAAATA----------
AATcTTaAAAAaaa-------
>input_041.bnk
------------------GGAGGTGGtACAGTGG-----ATAAAGCATTGGACTCTCAAG
CATGAG---GTCCTGAGTTCaATCCCTGGCATT-CATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCTCTCt-------CTC-------------------tttatAAATA----------
AATaTtAAAAAaAaa------
>input_027.bnk
-----------------cgGAgGTGGcaCAGTGG-----ATAAAGC-ATGGACTCTCAAG
CATGAG---GTCCcaAGTTCAATCCCTGGCATTGCATGTGCCAGAGTGATGCTCTGgTTC
TCTCTCTctcT-------CTct---------------TAATaAATAAATA----------
aATTTTaAAAaAa--------
>input_036.bnk
---------------gccGGAGGTGGCACAGTGG-----ATAAAGc-TTGGACTCTCAAG
CATGAG---GTCCTGAGTTCAATCCCCAGCATCACATGTGcCAGAGTGATGCTCTGGTtc
TCTCTCTCtCT-------cTc----------------TcATaAATAAATA----------
AATTTTAAAAAaaa-------
>input_091.bnk
-----------------ggGAggTGGtacAgtgG-----aTAAAGc-cTGGACTTtCAAG
CATGAG---GTCCTgAGTTTgATCCCTgGcATcaCATGTGCCAgAGTGATGCTCTGGTTC
TCTCTCtctcT-------CTc----------------TcaTtAATAAATa----------
AAtatTTAAAAAAa-------
>input_058.bnk
-----------------cGGAGGTGGCACAGTGG-----aTAaAGtaTTGGACT-ttAAG
CATGAG---GTCCTGAGTTTaATCCCTGGCATCACATGTGCCAGAGTGATGCTCTGGTTc
TcTCTCTCTCt-------cTCT-------------CTcTATAAATAAATA----------
AATCTTtAAAaAaa-------
>input_085.bnk
----------------cgGGAGGTGGCACAGTGG-----aTAaAGcatTGGACT-TCAAG
CATGAG---GTCCtaAGTTTAATCCCTGGCAtcaCATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCTcctc-------tctT------------CTcTAATAAATAAATA----------
AAttTTTaAAaa---------
>input_043.bnk
-----------------cGGAGGTGGCaCAGTGG-----ATAAAgt-aTGGACTtTCAAG
CATGAG---GTCCTGAGTTCAATCCCTgGCATtaCATaTGCCAGAGTGATGCTCTGGTTC
TCTCTCTCtct-------ctcT-----------------aTaAATAAATA----------
AATTTTtTTaAAAAaa-----
>input_012.bnk
-----------------gGGAGGTGGCACAGTGG------TAgAGcATTGGACTTtCAAG
CATGAG---GTCCTGAGTTTGATCCCCAGCATCACATGTGCCAGAGTGATGCTCTGGTTC
TCTCtcttTtT-------ct-----------------ttaTAAATAaAta----------
aatttttaa------------
>input_045.bnk
----------------cgGGAGGTGGcaCAGTGG------TAaAGtatTGgACTcTCAAG
CATGAG---GTCCtgAGTTCAATCCCcaGCATCaCATGTGCCAGAGTGATGCTCTGGTTc
TCtcTcttcTc-------TCTc-------------ATtAATAAATAAATA----------
AATTTTAAAAaaaa-------
>input_046.bnk
-----------------cGGAGGTGGCACAGTGG-----aTAaAGT-tTGGACTtTCAAG
CATGAG---GTCCTGAGTTtgATCCCTAGCATCACATGTGCCAGAGTGATGCTCTGGTTc
tctttcCTCTC-------TCTC-------------ATaAATAAATAAATA----------
AATaatTaAAAaaa-------
>input_007.bnk
-------------ggccgGGAGGTGGcACAGTGG------TAaAGcaTTGGacTcTcAAG
CATGAG---GTCCTGAGTTcgATCCCTgGCATCACATGTGCCAGAGTGATGCTCTGGTTC
TCTtctcTcTC-------TCTC------------TCTTaATAAATAaaTA----------
AAtatattaAAaa--------
>input_033.bnk
-----------------cggAGGTGGtACAGTGG-----ATAAAG-acTGGACTCTCAAG
CATGAG---GTCCt-AGTTTGATCCCTGGCATCaCATgTGCCAGAGTGATGCTCTGGTTC
TCTCTCTCTCT-------Cttt---------------ctATAAATAAATA----------
AATtttTAAAAaa--------
>input_068.bnk
------------gGcctGGGAGGTGGcACAGTGG-----ATAAAGC-TTGGACTCTCAAG
CATGAG---GTCCTgAGTTt-ATCCCTGGCATCACATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCTCTct-------tCT----------------CtTataAtaAATa----------
aaTTTTtaAAAaa--------
>input_021.bnk
----------------cgGGAGGTGGcACAGTGG-----aTAAAGtATTGGACTctCAAG
CATGAG---GTCCTgAGTTTgATCCCTGGCATc-CATGTGCCAGAGTGATGCTCTGGTTC
TCTCTctctcT-------AT-----------------AAATAAATAAATA----------
AATAAATAAATAAAtAaaa--
>input_024.bnk
g-----------tgcCtGGGAGGTGGTACAGTGG-----ATAAAGcaTTGGACTCTCAAG
CATGAG---GTCCTGAGTTTAATCcCTGGCATT-CATATGCCAgAGTGATGCTCTGGTTC
TCTCTCTCTCt-------TC-----------------TcATaAATAAATA----------
AtttAaAaAAat---------
>input_066.bnk
----------------cGGGAGGTgGCACAGTGG-----aTAaAGcacTGGACTctCAAG
CATGAG---GTCCTGAGTTcAATCCCTGGCATt-CATaTGCCAGAaTGATGCTCTGGTTC
TCTCTcCtCtT-------ct-----------------taATAAATAAATA----------
atTTtttAAAa----------
>input_084.bnk
-----------------cGGAGGTGGA-CAGTGG-----ATAaAGcatTGGACTCTcAAG
CATGAG---GTCCtGAGTTcgATCCCTaGCATc-CATGTGCCAGAGTGaTGCTCTGgTTc
TcTctcctTcT-------Ct-----------------tTATaAATAAATA----------
AATCTTTAAAAAtAa------
>input_074.bnk
----------------ccGgAgGTGGcACAGTGG-----aTAaAGt-TTGGACTcTcAAG
CATGAG---GTCCcaAGTTtgATcCCTGGCATT-CATGTGCCAGAGTGATGCTCTGGTTC
TcTCtctCTcT-------CTCT------------CATaAATAAATAAATA----------
aAttTTTAAAAaAa-------
>input_003.bnk
---------------CcaGGAGGTGGcACAGTGg-----ATAAAG-aTTGGACTctcAAG
CATGAG---GTCCtgAGTTTGATCCCTGGtATCACATGTGCCAGAGTGATGcTCTGGTTC
TCTCTCTcttt-------tttc------------------AtaaTAAATA----------
AATatTtttAAAAa-------
>input_031.bnk
--------------gccgGGAGGTGGtaCAGTGG-----ATAAAG-aTTGGACTCTCAAG
CATGAG---GTCCTGAGTTcAATCCCTGGCATT-CATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCTCTct-------ctt------------------attAATAAATA----------
AATaaTaAaaa----------
>input_044.bnk
----------------cgGGAGGTGGt-CAGTGG-----ATAaAg--TTGGACTCTCAAG
CATGAG---GTCCTaAGTTCAATCCCTgGCATcaCATGTGCCAGAGTgATGCTCTGGTTC
TCTCTCtctct-------cttC-------------ATTAATAAATAAATa----------
aatTTTtAAAAAa--------
>input_073.bnk
----------------cgGGAGGTGGt-CAGTGG-----ATAAAG--TTGGACTcTCAAG
CATGAG---GTCCTGAGTTCAATCCCtgGCATtgCATGTGCCAgAGTGATGCTCTgGTTC
TCTCTCtCTCT-------CTct--------------tTaATaAATAAATA----------
AATTTTaAAAAAa--------
>input_102.bnk
-----------------gggAgGTGgt-CAGTgG-----aTAaaG--tTGGACTCTCAAG
CATGAG---GTCCTGAGTTCaATCCCTgGCATc-CATGTGCCAGAGTGATGCTcTGGtTc
tCtctctCTCT-------cTCT------------ctTTAATAAATAAATa----------
atTTTTaAAAAa---------
>input_093.bnk
-----------------gGGAgGTGGc-CAGTgG------TAaAg-AtTGGACTTgCAAG
CATGAG---GTCCCAAGTTCAATCCCTGGCATTgCATATGCCAGAGTGATGCTCTGGTTC
TCTCTCtctct-------tc-----------------taAtAAATAAAtA----------
Aaaat------a---------
>input_150.bnk
----------------cgGGAGGTGGa-CAGTGg------TAaAGc-aTGGACTTaCAAG
CATGAG---GTCCTGAGTTcaATCCCTGGCATCACATgTGCCAGAgTGATGCTCTGGTTC
TCTcTctCtcc-------tc-----------------aataaAAaAAAtA----------
AAAaattaaaa----------
>input_092.bnk
------------------gGAgGTggc-CAGTgG-----aTAAAGtgtTGGACTtTCAAG
CATGAG---GTCCTGAGTTtAATCCCTggCATtaCATGTGCCAGAGTGATGCTCTGGtTC
TCTCTcTcTct-------TCT----------------cTtaaaATAAAtA----------
AATTTTaaAaaa---------
>input_048.bnk
----------------cgGGAGGTGGA-CAGTGG------TAAAG-atTGGACTttCAAG
CATGAG---GTCCTGAGTTTGATCCCTGGCATCACATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCTctct-------cTtT------------cttttaTaAaTAAATA----------
AaTAttTtTaaaAaa------
>input_042.bnk
-----------------cGGAGGTGGc-CAGTGG-----ATAAAGc-TTGGACTCTCAAG
CATGAG---GTCCtgAGTTt-ATCCCtgGCATcACATGTGCCAGAGTGATGCTCTGGTTC
TCTCTccctct-------CTcT------------CATaAATaAATAAATA----------
aATtTtaaAaa----------
>input_153.bnk
-----------------cGGAGGTGGcACAgTGG-----aTAAAGt-TTGGACTTtcAAG
CATGAG---GTCCTGAGTTcAATCCCTGGCATcACATgTGCCAGAGTGATGCTCTGGTTC
TCTcTCTCTct-------ctta------------tATATATATATATATA----------
TATATATATATATATATAt-a
>input_034.bnk
---------------gCcGGAGGTGGA-CAGTGG-----ATAAAGcaTTGGACTCTCAAG
CATGAG---GTCCTGAGTTTGATCCCTGGCAT--CATGTGCCAGAGTGATGCTCTGGTTC
TCTCTctcTct-------------------------ttAATAAATAAATa----------
atTTTTaAAAaa---------
>input_097.bnk
---------------gcgGGAGGTGGT-CAGTGG-----atAAagCAcTGGAC--TcAAG
CATGAG---GTCCTGAGTTtgATCCCtGGCATt-CATGTGCCAGAGTGATgCTCTGGTTc
TCTCTCTCttC-------TCtT---------------TAATAAATaAata----------
AattTtaaAAaa---------
>input_010.bnk
------------------GGAGGTGGCACAGTGG------TAaAGtatTGGACT-TcAAG
CATGAG---GTCCcAAGTTTGATCCCTAGCATt-CATGTGCCAGAGTGATGCTCTGGTTc
tctTctctCTC--------------------------TCAtAAATAAATA----------
aATTTTaAAAaA---------
>input_104.bnk
----------------cgGGAGGTGGCAcAGTGG------TAAAgCAcTGgACT-tCAAG
CATGAG---GTCCTGAGTTTGATCCCTaGCATt-CATGTGCCAGAGTGATGCTCTGGTtT
cTCTTcttctT-------------------------cttATAAATAAATA----------
AATAtTTTAAAAAAAA-----
>input_049.bnk
----------------cgGGAgGTGGcACAGTGG-----ATAAAGcATTGGACT-ctAAG
CATGAG---GTCCTGAGTTTGATCCCtgGCATa-CATaTGCCAGAGTGATGCTCTGGTTC
TCTcTCTctct--------------------------tcATtAATAAAta----------
aattttTTAAaAaa-------
>input_057.bnk
-------------ggcCgGGAGGTGGc-CAGTGG-----ATAAAGcaTTGGACTCTCAAG
CATGAG---GTCCTGAGTTCaATCCCTGGCATCaCATGTGCCAGAGTGATGCTCTGTT-C
TCTCTCTCtct-------cTCTcT----------CTcTaATAAAtAAAtA----------
AAat-----------------
>input_167.bnk
-----------------cGGAGGTgGc-cAGtGG-----gTAGAGcActGGACTTgCAaG
CATGAG---GTCCtGgGTTCAATCCCtGGCAtcACATATGcCAGAGTGaTGCTCTGGTtt
CTcTcTCtcTc-----------------------------atAATAAATA----------
AaaTAaAAaaa----------
>input_121.bnk
------------------GGAgGTGgC-CAgtG-------TAGAGCActGGACTTgcAaG
CATGAG---GTCCTaAGTTCAATCCCTGGCACTgCATgTGCCAGAGTGaTGCTCTGGTTt
tTCTCTCTcat-----------------------------taAATAAATA----------
AATcTTTtaaAAa--------
>input_005.bnk
---------------gcgGGAGGTGGCACAGTGG-----aTAaAGt-CTGGACT-tcAAG
CATGAG---GTCC-aAGTTtgATcCCTGGCATTGCATGTGCCAGAGTGATGCTCTGGTTC
TcTctctcctc---------------------------tattAATAAATA----------
AATTTtaAAaAaa--------
>input_189.bnk
-----------------gGgAGGTGGCaCAGTGG-----aTAaagc-cTgGACT-tCAaG
CATGAG---GTCCTGAGTTC-ATcCCtaGCATtgCATgTGCCAGAGTGATGcTttcTcTc
CtCtctCtcTt---------------------------AaTAAATAAATA----------
AATtttaaaaa----------
>input_076.bnk
------------------gGAGgTGGCaCAGTGG------TAGAGcactgGACT-TcAAG
CATGAG---GTCCTgAGTTc-ATCCCtaGCATCACATATGCCAGAGTGATGCTCTGgTTC
TCTCTTct-----------------------------taatAAATAAATA----------
AATaTTTAAAaAAA-------
>input_103.bnk
----------------cgGGAGGTGGcaCAGTGG------TAGAGtAtTGGACT-TCAAG
CATGAG---GTCCTGAGTTc-ATCCCtgGCAtcACATATGCCAGAGTGATGCTCTGgTTC
TCTCTCtCtat--------------------------tAaTAAATAAATA----------
AATTTTaaaaaa---------
>input_083.bnk
-------------gtgCaGGAGGTGgCACAGTGG-----aTAAAGc-TTGGACT-ttAAG
CATGAG---GTCCTGAGTTC-ATCCCTgGCATCaCATGTGCcAGAGTGATGCTCTGGTTC
TCtCTctcctt-------cTcA---------------AaATAaAtAataa----------
aatttTaaAAaaa--------
>input_062.bnk
----------------ccGGAGGTGGcACAGTGG-----ATAAAGt-gTGGACT-tCAAG
CATGAG---GTCCTGAGTTcAATCCCTgGCATcaCATGTGCCAGAGTGATGcTCTGGTTc
tTcttcTtCTC-------Tt-----------------cTATAAATAAAta----------
AAAaTTtaAAAAAa-------
>input_070.bnk
-----------------cGGAGGTGGcACAGTGG------ATAAgcaCTGGACT-TCAAG
CATGAG---GTCCTGAGTTCAATCCCTaGCATTaCATGTGCCAGAGTGATGCTCTGGTTC
TCTTCttcT------------------------------ATAAATAAATA----------
AATAataaAAAaaaa------
>input_038.bnk
---------------gccGGAGGTGGCACAGTGG-----aTAAAGTgTTGGACT-CTAAG
CATGAG---GTCCTGAGTTCaATCCCTGGCATTgCATGTGCCAGAGTGATGCTCTGGTTC
TctcTCTTccc-------cctc---------------TctATAATAAATA----------
taTaaTTTAAAaaaa------
>input_067.bnk
------------ggcCtgGGAGGTGGCACAGTGG-----ATAAAG--TTGGACT-CTAAG
CATGAG---GTCCtaAGTTtgATCCCtaGCATtgCATGTGCCAGAGTGATGCTCTGGTTC
TCTCTTcTCTC--------------------------ttttaaaatAAta----------
AAtAtTTTtaAAa--------
>input_137.bnk
----------------cggGAgGTGGcaCAGTGG------TAaAG--tTGGACT-TCAAG
CATGAG---GTCCcaAGTTTgATCCCTgGCATtaCATaTGCCAGAGTGATGCTCTGGTtC
tctcTCTTcTT--------------------------TAATAAATAAATA----------
aAtATtTtTaaAaAaa-----
>input_116.bnk
----------------cGGGAGGTGGt-CAGTgG-----aTAaAGCACTGGACT-TCAAG
CATGAG---GTCCtGAGTTCaATCCCTgGCACTGCATaTGCCAGAGTGATGCTCTggTTc
TCtctCTcTAt---------------------------aataAATAAAtA---Aaaa---
AtTTttaaAaa----------
>input_118.bnk
-----------------ggGAGGTGca-CAGTGG-----aTAaAGcATTGGACT-tCAAG
CATGAG---GTCCTgAGTTTGATcCCTgGCATcaCATaTGCCAGAGTGATGCTCTGgTTc
TtTcTcTcttt-------------------------cTTAtTAATAAATA----------
AATttaaatttttaa------
>input_148.bnk
---------------gcGGGAGGTGGC-CAGTGg-----aTAgAGcActGGACT-TCAaG
CaTGAG---GTCCt-aGTTcgATCCCTGGCATCaCATATGCCAGAGTGaTGCTCTGgtTC
TCTCTCTctct-------ttta---------------tAATAAATAAata----------
tAAatt---------------
>input_139.bnk
--------------gccaGGAgGTGGg-CAGTGG-----aTAAAGcatTGGACT-tCAaG
CA-GAG---GTCCTGAGTTCAATCCCTggCAtCACATGTGCCAGAGTGATGCTCTGgTTc
tcTctCTCTCT---------------------------CattAATAAATA----------
AATtaAAAtaaaa--------
>input_155.bnk
-----------------ggGAGGTGGCaCAGTGG-----aTAgAGcacTGGACT-TCAaG
CATGAg---GTCCtGAGTTc-ATCCCtGGCAtcaCAT-TGCCAGAGTGATGCTCTGGTTc
TtTcTcTCTCT-------------------------TttcttaATaAaTA----------
AAttaaAAaa-----------
>input_120.bnk
-----------------gGGAGGTGGCACAGTGG-------TAAGCACtGGACT-TCAAG
CATGAG---GTCCtaAGTTCaATCCCtgGcAtcACATATGCCAGAGTGATGCTCTGgtTc
tttTttctTTC---------------------------ATaAAttAaatA----------
AATattTaAaAa---------
>input_128.bnk
--------------cccgGGAGGTGGcACAGTGG-----ATAAAGcAtTGGACTcTCAAG
CATGAG---GTCCTGAGTTt-ATCCCTGGCATtgCATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCTCTCT-------CTCTCTCTCT--C--TCTC-----------------------
TCTCtCtcaaaatta------
>input_130.bnk
t-----------ggcCtGGGAGGTGGCACAGTGG------TAaAGCaTTGGACTCtcAAG
CATGAG---GTCCTGAGTTCaATCCCTAGCATCACATGTGCCAGAGTGATGCTCTgGTTC
TCTCTCTCTCT-------CTCTCTCTCT--C--TCTC-----------------------
Tctctt--aatataa------
>input_156.bnk
-----------------gGGAGGTGGCACAGTgG------TAGAGCACTGGACT-tCAAG
CATGAG---GTCCTgAGTTcaATCCCTAGCAtTgCATgTGCCAGAGTGATGCTCTGGTTc
ctTTCttcTTC-------TTCT-------------aTcTATctATaATct----------
ATcTTTa--------------
>input_146.bnk
------------------gGGAGGTGCaCAGTGG------cTAAG--ttGGACT-TgAAG
CATGAG---GTCCTGAGTTTaATCCCcgGCATtaCATgTGCCAGAGTGATGCTCTGGTTT
CTcttc-------------------------------tAATAAATAAATA----------
AAtTTtAAAaa----------
>input_110.bnk
------------------gGAgGTGGcaCAGtgG------TAAGc--aTGGACT-tcAAG
cATGAG---GTCctGAGTTcaATcCCcgGCATtGCATaTGCCAGAGTGAT-CTCTGGTTC
TtTCTCTcc----------------------------aaATaAATAAATA----------
AATTTaAAAAAAaa-------
>input_144.bnk
------------------GGAGGTGGA-CAGTGG------TAGAGTgCtGGACT-TCAAG
CATGAG---GTCCTGAGTTcgATCCCTaGCActgCATaTGCCAGAGTGaTGCTCTgGTCT
CTtttTCTttt-------tta----------------tAttAAAtAAAtA----------
AATTttaaa------------
>input_059.bnk
-----------------gGGAGgTgGc-CAGTgg------TAGAGc-AaGGACTTGCAAG
taTGAG---GTCCTGAGTTcaATCCCCaGCAcCaCATATGCCAGAGTGATGCTCTGGTTc
TCTCTCTCt-------------------------------AAAATAAATA----------
AATTTTAAAAAAA--------
>input_095.bnk
----------------cgGGAGGTGGt-CAgTGG------TAAAGT-TTGGACTtTCAAG
CATGAG---GTCCcAAGTTCaATCCCTGGcAT-gCATGTGCCAGAGTGATGCTCTGGTTC
TCTCTCTcct-----------------------------AaAAATAAATA----------
AaTtTTaaAAAaAaa------
>input_069.bnk
----------------cgGGAGGTGGA-CAGTGG-----ATAAAGa-TTGGACTCTCAAG
CATGAg---GTCCg-AGTTCAATCCCCAGCATCaCATGTGCCAGAGTGATaCTCTGGTTC
TCTCTCTc------------------------------aatAAATAAATA----------
AATaTtTtAAAAAAaAa----
>input_087.bnk
-----------------gGGAGGTgGC-CAGTgG------TAgAGCAcaGGACTTgCAaG
CaTGAG---GTCCc-AGTTCAATCCCcAGCAttaCATaTGCCAGAGTGATGCTCTGGTTc
tctcTCTCTCt------------------------------ATaAAAAAA----------
AAtcttAAAAAAAAAAaaaaa
>input_065.bnk
----------------cgGGAGGTGac-cAGtgG------tAgAgcAcaGGACTTgCAAG
CATGAG---GTCCTgAGTT-AATCCCCAGCAcTgCATATGCCAGAGTGaTGCTCTGgttt
ttCTcTCTcTC-------T------------------cataaAATAAATA----------
AATtTTTAAAAAAAa------
>input_075.bnk
-----------------gGGAgGTGGc-CAGTGG------TAaAGTgctGGACTTgCAAG
CATGAG---GTCCTGAGTTCAATcCC-agCAtCACATaTGCCAGAGTGaTgCTCTggtTc
tctTCTcTccA-------T------------------AAATAAATAAATA----------
AATAAATAAATAAatAaaa--
>input_098.bnk
-----------------GGGAGGTGGc-CAGTGG-----gTAGAGTgtaGGACTTgCAaG
cATGAG---GtCCt-AGTTtgATcCCtgGCAT--CATGTGCCAGAGTGATGCTCTGGTTc
TctctcTcTcT-------cTCTA-------------TTAATAAaTAAATA----------
AATTTTaAAAaaa--------
>input_147.bnk
-----------------GGgAGGTGCA-CAGTGG------TAgAGcACTGGACTTgcAAG
CATgAG---GTCCT-AGTTtaaTCCCTAGCAt--CATaTGCCAGAGTGATgCTCTGgTTC
tttcTCTCTct-------a-----------------TTaATAAATAAATA----------
AaTtTTTAAAAAa--------
>input_185.bnk
----------------cgGGAGgTgGc-CAGTGG-----gTAgAga-ctGGACT--TcAG
CaTGAG---GTCCt-AGTTcaATCCCtgGcAt--cATaTGCcAGAGTGgTGCTCTggttc
tcTCTCTTTCT-------c------------------TcaTAAATAAATA----------
aATTTTaaAAaA---------
>input_192.bnk
-----------------gGGAGGTGGc-CAGTGG------TAgAGtactGGACT-TCAaG
CATGAG---GTCCt-AGTTCaATcCCTGacA--acATaTGCCAGAGtgatGCTCTGgttt
tCtcttcTttc-------T------------------cAaTaAATaaATa----------
aattttaa-------------
>input_111.bnk
-----------------gGGAGGTGGcACAGtGG------TAGAGcActGGACTTgCAAG
cATGAG---GTCCA-AGTTCaATCCCTgGCAcTGCATATGCCAGAGTGATGCTCTGGttt
ttttCtcTtTc-------TAT----------------TAATAAATAAAtA----------
Aatttaaaaa-----------
>input_113.bnk
-----------------gGGAGGTggCTCAGtgG------TAGAGCAcagGACTTGCATG
CcTGAG---GtCCC-aGTTTaATCCCTGGCActgCATgTGccaGAGTgaTGCTCTGGTtt
cTCTCTCTCTC-------tat----------------ttTAAaAAAaAttt---------
---------------------
>input_090.bnk
---------------gcgGGAGGTgGc-CAgtgg------TAGAGcActGGACTTgcAtG
CaTGAG---GTCCtgAGTT--ATCCCTGGcActgCATgTGcCAGAGTgaTGCTCTGgTTC
TCTCTCtTCTC-------TCtca--------------aaAaaaatAAATA----------
AATTTaAAaaaaa--------
>input_119.bnk
------------------GGAggTgGcTCAGtGG------TAGAGCACaGGACTTGCAtG
CatgAG---GtCCtaAGTTc-ATCCCTaGCACtaCATATGCCAGAgTGATGCTCTGTTtt
ttttaat------------------------------AAATAAATAAATA----------
AATTtTtAAAAaa--------
>input_008.bnk
-----------------GGGAGGTGGt-CAGTGG------TA-AgcAcTGGACT-TgcAG
CaTGAG---GTCCTGAGTTtgATCCCTGG-AtTgCATgTGCCAGAGTGATGCTCTGGTTC
TCTCtcttTcT-------cc-----------------TaATAAAtAAATA----------
aATTTTAAAaAa---------
>input_009.bnk
-----------------cGGAGgTGGa-CAGTGG------TAaaGc-ttGGACT-TcAAG
CATGAG---GTCCTGAGTTTGATCCCTGGCATT-CaTGTGCCAGAGTGATGCTCTGGTTC
TCTcttctTcT-------cT-----------------taATaAATAAATA----------
AATcTtTAAAAaaaa------
>input_101.bnk
---------------gcgGGAGGTGGT-CAGTGG------TAAAGg-tTGGACTTgCAAG
CATGAG---GTCcTGAGTTcaATcCCT-GCATc-CATGTGCCAGAGTGATGCTCTGGTTc
tTcTcTctctt-------ta-----------------tAaTAAATAAATA----------
AAaTTTTtAAAaa--------
>input_114.bnk
-----------------gGgAggTGGCtCAGtG-------TAGAGa-ctGGACTTtCAAG
CaTGAG---GTCCTgAGTTTGATCCCTgGCAct-CATaTGCcAGAGTGATGCTCTGGTtT
ctTtTCTctCT-------CT-----------------CtaAaaaaAAATA----------
aaTTtttAAAAAA--------
>input_138.bnk
----------------cgGGAGGTGGCACAGTgG------TAaAg--cTGgACT-TcAaG
CATGAG-----TCCgAGTTtgATCCCt-GCATcaCATgTGCCAgAGTGATgCTCTgGTTC
TCTCTcTcTcT-------ct-----------------taataAATAAAtA----------
aATcTTtAAAAAAaa------
>input_122.bnk
-----------------GGGAGGTGGCTCAGtGg------TAGAGcacaGGACT-TCAtG
c-TGAG---GTCCCaGGTTCaATCCCTGGCAC-ACATATGCCaGAGTGGTGCTCTGGttT
ttctcTCTCTc-------ct-----------------ataAaAatAAATA----------
AATTTTAAAAaa---------
>input_126.bnk
-----------------gGGAGGTgGCTCAGtGG------TAGAGCACAGGACTTGcAtg
c-TGAG---GTCCC-gGTTcaATCCCTGGCACcaCATATGCCAGAGtGaTGCTCTGGTct
tccccttcttTc-------------------------TaaaAAATAAAtA----------
aat----aaaaa---------
>input_145.bnk
------------------gGGAgTGGCTCAGTgg------TAGAGTGCAGGACTTgcAtG
c-TGAG---GTcCt-aGTTt-ATCCCTgGCACtAcATaTGCCAGAGTGGTGCTCTGGtTc
TCTCTCTCTCt-------ctaTt--------------atAtAAATAAATa----------
aaTtttaaa------------
>input_158.bnk
-----------------GGGAGGTgGCtCAGtGG------TAGAGCACAgGACTTGCATG
-ATGAG---GTCCTGGGTTCAATCCCTgGCACCACATATGCcAGAGTGaTGCTCTGGTTt
TTcTtctt--------------------------------AAAATAAATA----------
aATatTTaAaa----------
>input_159.bnk
------------------GGAGGTGGCtCAGTGG------tAGAGTACAGGACTTGCATG
c-TGAG---G-CCTGaGTTCAATCCCTgGCActgCATATGcCAGAGTG-TGCTCTGgTTT
CTCTctTCTct-----------------------------TaaATAAATA----------
AattTtaaaaatt--------
>input_177.bnk
-----------------gGGAggTGGCtCAGtGG------TAGAGCACaGGaCTTGCATG
C-TGAG---GTCCg-aGTTC-ATCCCTGGCACCaCAT-tGCCAGAGtggTGCTCTGgtTT
ctcTCtCttct-------tTtaa--------------tAATAAAaAatta----------
aa-------------------
>input_200.bnk
-----------------gGGAggTGGCtCAGtgG------TAGAGCaCaGGACT-tgcAG
CaTGAG---GTCCtgaGTTt-ATCCCtgGCACcACATgTGCCAGAGTGATGCTCTGTcct
TctccTTTCTc---------------------------taATAATaATaA----------
aattaaa--------------
>input_060.bnk
---------------gCcGGAgGTGGG-CAGTGG------TAGAgCATTGGACT--TAAG
CATGAG---GTcCTGAGTTCaATCCCcaGCATCaCATGTGCCAGAGTGATGCTCTGGTTC
TCTCTctCtcT-------tctcT------------cTatgTtAATAAATA----------
ATtttaaTttaaa--------
>input_100.bnk
------------------GgAGgTgGt-CAGTGG------TAaAGT-tTGGACT-TCAAG
CATGAG---GTCCcgAGTTCAATCCCtAGCATCaCATgTGCCAGAgTGATGCTcTGTtTc
TcTCTCTCTca-------ttaaT--------------taAtAAATtaaTA----------
taaTttaaaa-----------
>input_086.bnk
-----------------GGgAGGTGG--CAGTgG------TAGAGC-ACGGACTTGCAaG
-aTGAG---GtCCTGAGTTCAATCCCTGGCAccaCATATGCcAGAGT-aTGCTCTGGtTC
TCTCTCTccta------------------------------aAATAAATA----------
AATaTTTTAAAAAaa------
>input_161.bnk
-----------------cGGAGgTGG--CAGtgG------tAaAGc-AcGGACT-TgcAG
CATGAG---GTCCTGAGTTCAATcCCTGGCACtAcATATGCCAGAGTGATGCTCTGTTCT
cTcCtTCTctt---------------------------aAtAAATAAAtt----------
tAattttaaa-----------
>input_170.bnk
--------------------gGGAGGTGCAgtgg------TAGAgC-AtGGACT-tgCAG
cATGAG---GTCCTGaGTTCAATCCCtAGCAtCaCATATGCcAGAGTGATGCTCTgtttT
cTCTCTCT-----------------------------taaaaaatAAATA----------
AAttataa-------------
>input_149.bnk
----------------caGGAGGTGGc-CAGTGG------TAGAGt-atGGACT-TcAaG
CaTGAG---GTCCTGAGTTTaATCCCTAGCATCAT---TGcCAGAgTGATGCTCTGGTtT
tcTcTCTCTCT-------CT-----------------CttttaatAAATA----------
AATtAAAAa------------
>input_081.bnk
------------------ggAggTggctCAgttG-----gTAgAGC-AcGGACTTgCATG
CCTGAG---GcTCCgAGTTTgATCCCtGGCAtCaCATGTGCCAGAGTGaTGCTCTGGTTc
tcTcttTCTCT-------CA-----------------taaaaAATAAATA----------
AAttTtaAAaAaa--------
>input_061.bnk
-----------------cGGAGGTGGt-CAGtG-------TAgAG--AtGGACTTgCAaG
CaTGAG---GTCCT-AGTTT-ATCCCt-GCAtCACATATGCCAGAGTGATGCTCTGGTTC
TcTcTCTcTCT-------ctcTA-------------TAAATAAATAAATa----------
aattTTTAAAAAAaA------
>input_182.bnk
-----------------gGgAGGTgGcCaag---------TAGAgc-atGGACTTgcAaG
CATGAG---gTcCt-AGTTc-aTCCCTaGcAtcaCATGTGCCAGAGTgATGCTCTGgTTc
tcTcTCTCTCT-------cTCT---------------CataAaATAAAtA----------
AAttTttAAAaa---------
>input_142.bnk
-----------------gGGAGGTGGC-CAGTGG------TAGAGc-acGgACT-TcAaG
caTGAG---GTcCt-AGTTc-ATCCCTGGCATTgCATgTGCCAGAGTGATGCTCTGGTTC
TctTCTCTCTCac------------------------tataAAATAAata----------
aatattttaaAa---------
>input_176.bnk
----------------gggGAGgTGGcaCAGTGG------TAAAGc-CTGGACT-tcAAG
CATGAG---GTCCtAG--TTgATCCCTGGCATcACATGTGCCAgAGTGATGCTCTTTCTc
tcttTTcTttT-------ctTcA-------------TtAATAAATAAATA----------
aatTtaaAaaa----------
>input_056.bnk
---------------gcgGGAGGTGGTaCAGTGG------TAAAGT-cTGGACTttCAAG
CATGAG---GTCCCAAGTTc-ATCCCtaGcATc-CATGTGCCAGAGTGATGCTCTGGTTC
TCTCtcTCTCTC-------------------------TCttatTAAAATA----------
AATAtttTtaaa---------
>input_154.bnk
-----------------gGGAgGTGGcaCAGtGg------TAGAgc-AtGGACTTgcAag
CATGAG---GTtCT-AGTTcAATCCCTGGCATc-CATGTGCCAGAGTGATGCTCTGGtTt
tcTCtctCTCTc-------------------------tTCATaATAAata----------
aaaTTtTAaAAAa--------
>input_174.bnk
-----------------gggAgGTGGCACAGTGG------TAgAGt-tTGGACT-TcAaG
CATGAG---GTCCT-AGTTtgATCCCTgGCA--aCATaTGCCAGAGTGATGCTCTGGttT
CTCTCttt-------------------------------AtAAttAAAaA----------
tatTtTtaaaaa---------
>input_199.bnk
-----------------GGGAGGTGGC-CAGTGg------taaAGC-aCgGAcT-tCaag
CaTGAG---GcCCT-AGTTtaAtcCCTGGCAC--CAtaTGCCAGAGtGATGCTcTTctcc
ccctTct--------------------------------aaaaATAaAtA----------
AatTtttaa------------
>input_197.bnk
-----------------gGGAGGTGGCaCAGTGg------TAG----ctGGACT-TCAaG
CATGAG---GTCCt-AGTTCAATCCCtgGCATCACATgTGCCAGAaTGATgCTCTGTTct
ttctcTTcTctA-------------------------tAAtAaaaAttta----------
---------------------
>input_099.bnk
------------------GGAGGTGGcACAGTgG------ATAAGTgTtGGACT-TcAAG
CATGAG---GTCCcAAGTTtaATCCCtAGCATt-CATaTGCCAGAGTGATGCTCTGgTTt
TTTCTCTcTtA----------------------------ttAAATAAATA----------
aaaAATAaAtttta-------
>input_188.bnk
--------------gccgGGaGGTGGcaCAGTGG-----aTAgAGt-tTGGACT-TCAAG
CATGAG---GTCCTGAGTTtaATCCCtgGCATt-CATaTGCCAGAGTGATgCTCTgtctt
TCTCtcTCTCT----------------------------------aacta----------
aaaTTTtaAAAAaa-------
>input_129.bnk
----------------cgGGAGGTGGcACAGTGG------TAaAGtacTGGACT-TcAAG
CATGAG---GTCCTGAGTTCAATCCCTGGCATT-CATGTGCCAGAGTGATGCTCTGGttc
ttcTCTCTCTCT------CTCTCTCTCT--CTCTCTCTCttcaATAAATA----------
Aattt----------------
>input_175.bnk
------------------GGAGGTGGTACAGTGG------TAAAGt---ggAcT-TcAAG
CATGAG---GTCCtgAgTTcaATCCCTGGCATc-AATaTGCCAGAGTGATGCTCGtttct
TcTcTCAT----------------------------------AATAAATA----------
AAtttTTtTaAAAAaa-----
>input_152.bnk
------------------GGAGGTgGc-CAGTgG-----ATAaAGTaTTGGACT-tCAAG
C-TGAG---GTCCTgAGTTTGATCCCTgGCATt-CATgTGCCAGAGTGATgCTCTGgttt
cTCTCTCTctC----------------------------aTtAaTaAATa----------
aaaTTTTtAAAAAAAa-----
>input_181.bnk
------------------GGAGGTGG--CAGTGG------TAAaGCActGGACT-TCAAG
CATGAG---GTCCTGAGTTtGATCCCTGGCAtT-CATaTGCCAGAGTGaTGCTCTGTTcT
tTtTcttttTt----------------------------aATtATAAATa----------
ATtttTtta------------
>input_198.bnk
-----------------gGGAGgTGG--CAGtgg------TAgAGa-ttGGACT--TaaG
c-TGAG---GtCCtgAGTTTaATCCCTGGCACt-CATgTGCcAGAGTGATGCTCtGttct
tttTCTcTcTc--------------------------------atTAATA----------
AatTaaAaaaa----------
>input_195.bnk
-----------------gGGAgGTgG--cAGTGg------TAaAgC-ACGgAcT--TcAG
cATGAG---GTCCTaAGTTTGATCCCTgGCAC-ACATgTgCCAGAGTgaTgCTCTGGTTt
tTctcTcT-----------------------------------aAAaATA----------
aAttTtTTaAAAaa-------
>input_172.bnk
-----------------ggGAGGtGGCaCAGtgg------tAGAGc--agGAcT--TCAG
CaTGAG---GtCCTGAGTTCaATCCCTGGCACCaCATgTGcCAGAGTGATGCTCTGTcTc
TCTTCTCTCTTc-------------------------taaaaAaAaAAAA----------
AAtaTtTttaaa---------
>input_078.bnk
----------------cgGGAagTGC--CAGTGG-----GTAGAGc-CaGGACTTGCATG
C-TGAG---GTcCC-AGTTCaATCCCTgGCACtGCATaTGCCAGAGTGGTGCTCTGGTTC
TCTCTCTCTCT-------Ct-----------------tttTtAatAAAta----------
aattTAAAAaaa---------
>input_125.bnk
-----------------gGGAGgTgGc-CAGtgG------tAgAGC-AAGGACTTGCATG
c-TGAG---GtCCg-AGTTtaATCCCtGgCACTgCATATGCcAGAGTGaTgcTCTgGttT
CTCTCtttctt---------------------------ttaAAATAAATA----------
aTTTTTAAAAAaa--------
>input_186.bnk
------------------GGAgGTGGc-CAGTgG------TAGAGA-TtGGAcTTgtAAG
t-TGAG---gTCtG-AGTTCAATCCCTgagcacaCATaTGCCAGAGTGATGCTCTGGtTC
TCtctctTTTt--------------------------------ATtaaAA----------
aatTTTAAAaAaaa-------
>input_094.bnk
-----------------gGGAGGTgGc-cAGTGg------TAgAgA-taGGACTTGC-AG
CATGAG---GTCCT-AGTTCAATCCCTgGcAT--cATATGCCAGAGTg-TgcTcTgtttc
cTCTCTCTCTC---------------------------TCAtAATAAATA----------
AATaatAAAAaa---------
>input_173.bnk
-----------------ggGAGGTGG--cAGtgg-----gTAgAgA-CTGGAcTTgcAG-
-CTGAG---GTCCt-AGTTtgATCCCTgGCAaCAT---TGCCAGAGTGATGCTCTGgTtt
TctCTCTCTcT--------------------------cattaAtaAAaAA----------
AataTTTaAaaaaa-------
>input_164.bnk
-------------------GGAGTgGA-CAGTgG-----aTaaaga-tTgGACTTTCAAG
CATGAG---GTCCtgAGTTtaATCCCTaGCATcgCATGTGCcAgAGTGATGCTCTGtTcT
CTCTCTtcTCTt-------------------------TtttAATAAaAtA----------
aaAaattaaaAAaaa------
>input_077.bnk
-----------------gGGAgaTGct-CAGTGG------TAaAGCACtGGACTTgCAtG
CATGAG---GTtC--gGTTTgATCCCTGGCATT-CATATGCCAGAGTGaTGCTCTGGtTt
ttctCTCTCTCTc------------------------aTATAAaTAAATA---AaaAATA
AaTttttAAa-----------
>input_136.bnk
------------------ggAGGTggc-CAGG--------TAGAgtACAGGACTTgCAtG
CATGAG---GTCCtgAGTT--ATCCCtAGCAc-gCATgTGCCAGAGTgATGCTCTGGTtT
tTcTcTcTCtc-------ttAT---------------aAAtaAATAaAtA----------
AATtTtaaaa-----------
>input_088.bnk
-----------------gGGAGGTGGCTCAGTgG-----gTAGAGCACAGGACTTGCATG
C-TGAG---GcCCc--GTTCaATCCCcaGCACcaCATATG-caGAGtgGTGCTCTGttcT
tcttcTCTC------------------------------AtAAATAAATA----------
AATtTTaAaaaa---------
>input_135.bnk
-----------------gGGAGGTGGCTCAgTGG-----GTAgAGCacAGGACTTGCATG
taTGAG---GcCTg-gGTTt-ATCCCTGGcAc-aCATGTGCtaGAgTggTGcTcTGttTT
TCTCTCTCTCT---------------------------CTcTcAtaAatA----------
aaaaTtaAAAAaa--------
>input_141.bnk
------------------gGAggTggCTCAGctG-----GTAGAGcAcagGACTTgCATG
C-TGAG---GTtCa-GGTTt-ATcCCTGGCACcgCATATacCAGAGTGGTGCTCTgttTt
tcTCTCTCTCT---------------------------cataaattattA----------
AAAAAAAAAaa----------
>input_179.bnk
-----------------ggGagGTgGcTCAGTgg-----gTaaAGtataGGACTTgCAtG
CATGAG---GttC--agTTa-ATCCCTGGCAccACAtaTGCcAGAGTggTGCTCTGGtTc
tccctcCtttt---------------------------aataAaTAAATA----------
AAAaaaTTaAaAAAaa-----
>input_140.bnk
-------------------GGGATgGCtCAgGG-------TAGAgC-acGGACTTgCATG
c-TGAg---GTCc--aGTTC-ATCCCTaGCAccaCATGTgCCAGAGTGGTGCTCTGtTTC
TCTCTCTCTCT-----------------------------tAAATAAATa----------
aatTaAAAaaaa---------
>input_178.bnk
-------------------GGagTgGc-CAGG--------TAGAGCAcaGGACTTGC-AG
ccTGAG---GcCC--AGTTCaATCCC-aGCATcacATgTgCCAGAGTGATGCTCTGGtTc
TCTcTcttttt-------cc------------------------tAAATA----------
AATTTTaaaAaaa--------
>input_112.bnk
-----------------gGGAGGTgGCtCAGtG-------tAGAGC---GGACTTgC-AG
CaTGAG---GcCCc-GGTTc-ATCCCTgGCAcTgCATATGCCAGAGTGATGCTCTGGTTC
TCTCTcTCt---------------------------------aaaaaata----------
TttTTAAAaaa----------
>input_162.bnk
-----------------gGGAGgTgGC-CAGTgg------TAgAGCACAGGACT--TCAG
CATGAG---GTCC--AGTTt-ATCCCtggCACc-CATATGCCAGAGtgaTGCTCTGGTtt
cctCTCTTcatta------------------------AAATAAAtAAAtA----------
aaTtTtAaaaa----------
>input_171.bnk
g----------------gGGAggTGGctCAGtG-------TAGAGtataGGacTT---CA
gcTGAG---GTCCg-aGTTt-ATCCCTaGCAttaCATATGCCAGAgTgATGtTCTggTTC
TtcTttctttt--------------------------aAaTAAatAAAaA----------
TtTtTtAAAAaAa--------
>input_127.bnk
-----------------gggAggTgGc-cAGTGg------TAGAGCAcAGgACTTGCAaG
CATGAG---GTCCg-aGTTTGATCCC-aGCACcgCATaTG-CAGAGTgATGCTCTGgtTC
TCTctcTcaaaa-------------------------taAtAAATAAATA----------
AAtttTtaaAAAA--------
>input_183.bnk
------------------ggAggTggc-cAGTGg------TAgAGCAtaGgACTTGCAtG
cATGAG---GTCCTgaGTTc-ATCCCTCAc---CCATATGCtAGAGTG-TaCTCTGgTTC
TCTtTCTcTtcT-------------------------aaatAAATAAATA----------
AAtctttaaAaA---------
>input_131.bnk
g----------------gGGAgGTGgc-CAGTGG------TAgAG--atGGACTt-CAAG
CATGAG---GTCCtgAGTTc-ATCCCtAGCATCACATATGCCAGAGTGATGCTCTGGttc
TCTCTCTCTCT-------CTCTCTCTCTCTCTCtctctcctaatTaaAAa----------
a--------------------
>input_132.bnk
-----------------gGGAgGTGGc-CAGTGG------TAgAGt-atGGACTTgCAAG
CATGAG---GTCCtgAGTTt-ATCCCTgGCAttaCATgTG-CAGAGTGaTGcTCTGgtTC
TCTCTCTCTCT-------CTCTCTCTCTCTCtCtc--tctaaAataaata----------
-----------------atta
>input_180.bnk
------------------gGAgGTGGc-cAGtgg------tAgAgT---gGACTTgcAag
C-TGAg---GtCCTGaGTTa-ATCcCTGGCATCACATGTgCCA-AGTGATGCTCTGGttc
TCTCTttt---------------------------------aAAtAAATA----------
AATtAaAtaaaaa--------
>input_133.bnk
------------------GGAGgTGGc-CAGtgG------TAGAG--tCGgACT--TCAG
CATGAG---GtCCTgAGTTt-ATCCCT-gCAtcaCATATgccAGAgtGgTGCtcTctTCT
CTCTCTCTCTCTC------------------------tttaAAAAAAAtA----------
AATtattTAAAaaaa------
>input_134.bnk
------------------GGAGGTGGC-CAGTGG------TAAGc--AcGGACT--TCAG
CATGAG---GTCCt-GGTTTGATCCC-aGcActaCATgTGCCAGAT--aTGCTcTCTCTC
TCTCTCTC-----------------------------TATaAAAtAAAtA----------
taaattTAAAAAAa-------
>input_187.bnk
-----------------GGgAGgTggc-CAGtGG-----gTAAAG----aGACT--TCAG
CaTGAG---GTCCTgAGTTt-ATCCc-aGcAccaCATATGCCAGAGTGATGCTCTGGTTc
TTctCtCttct--------------------------tAAtaAAtAAAta----------
atttTTaAaa-----------
>input_163.bnk
-----------------gGGAaGTGGC-CAgTGG-------AaAGcAcAgGAcTTgC-AG
CATGAG---GTCCcaGGTTt-ATCCC-AGCAccACATATGCCAgAGTGaTGCTCTGTcTc
Tctcttcca----------------------------aAatAAATAAAtA----------
AATcTTTTTAAAAAAA-----
>input_194.bnk
-----------------gGGAGGtgGc-CAGgGG------tAgAg--CAggacttgCAg-
-cTGAG---GtCCt-gGTTCAATCCCtGGCAcCACAT-TGCCAGAGTGgTGCTCTGGttt
ctCTCtCtctA------------------------------aaataaAtt----------
tttTtAAAAaAa---------
>input_184.bnk
------------------ggaggTGGC-cAGTGG------TAaAGc--ATGaCTt----c
aGTGAG---GTCCTgaGTTtAATCCCTgGCAtcaCATaT-ccAGAGTgaTGTcTgTttTC
tcTctttt---------------------------------AAatAAATA----------
AAtaTttTaAAAaa-------
>input_190.bnk
-----------------gGgAggTGgC-CAGTGG-----GTAGAGc---tGACTT-cAaG
--tgAG---GTCCcagGTTTgaTCCCTGGCAcTGCATATGCCAGAGTGATGCTCTGgttT
cTccTctCttT--------------------------CTtTtAATaAAAA----------
aaaAttttaa-----------
>input_115.bnk
---------------ccgGGAGGTGGc-CAGTGG-----ATAAAG--cTGGACTCTCAAG
CATGAG---GcCCTGAGTTC-ATCCCcGGCATCACATGTGCCAgAGTGATGCTCTGTTCT
CTCTCTc-----------------------------------aATaAATA----------
ATAtTTAAaAAat--------
>input_089.bnk
-----------------GGGAGGTGGCTCAGTGG-----gTAGAG--ACAGaCTTGCAtg
TgTGAG---GCCCTGGGTTtgATCCCTgGCACcACATATa-taGAGTgGTGCTCTGgtcT
cTCTCTCTCTC--------------------------AtAAAAAaaaaTA----------
aaTTTAAAaAAA---------
>input_168.bnk
-----------------gGGAGGTGGctCAGTgG-----aTAGAGA-CaGGACTTgCAtg
caTGAG---GtCCt-AGTTtgATCCCtaGCACcaCATATGCCAGAGTG-TGCTCTGGttt
tTcTCTCTTcT-------CtcAT--------------TaAtAAATAAAtT----------
AAATctTtaaa----------
>input_169.bnk
-----------------gGGAGGTGGCtCAGTGG-----gTAGAGcACAgGAtTT-CATG
CATGAG---GcCCtgGGTTcaATCCCTGGcACCaCATaTg--aGAgT-ATGCTCTGGTcT
cTTCTcTTCTCTta-----------------------AAAtAAaTaAATa----------
AAaTtTaaaa-----------
>input_160.bnk
-----------------GGGAGGTGGCTCAGtgg-----gtAGAGCACAGGACTTGCA--
-GTGAG---G--CCaGGTTCAATCCCtgGCACtaCATATGcCaGAGtG-TGCTCTGGttC
TCTCT--------------------------------CATaaaaaAaAta----------
AAtaaataaaAaa--------
>input_123.bnk
-----------------gGGAggTGCT-CAGGG-------TAGAGt-cAGGACTTGCATG
CATGAG---GCCCc--GGTTaATCCCTGGCAcc-CATaTG-cAGAGtGgTGCTCTGGTCT
CTCTCTct-------------------------------aaAAAtAAAta----------
AAttTTAAAAAAAAa------
>input_191.bnk
-----------------ggGAGgTgGCtCAGtgG-----gTAGAGt-cAGGACTT-CATG
CaTGAG---GCCCc-aGTTA-ATCCCt-GCActaCATATgccagAGTGGTGtctggtttt
tctCtCtc--------------------------------aAaAtAAATa----------
AtaattTtAaAAaAAa----a
>input_011.bnk
-------------gggCcGGAGGTGGCACAGTGG-----gTAGAGcactGGACTTgCAAG
CaTGAG---GTCCTgAGTTtgATCCCt-GCActaCATATGCCAGAGTGATGCTCTtcttc
cTCTCtCTCTCtCT--CTCTCTCT-------------cttaaAAtAAATA----------
aatta----------------
>input_151.bnk
-----------------cGGAGGTGgCaCAGTgG-----gTAAAGCAcTGGACTcTCAAG
CaTGAG---gTCCTGAGTTC-ATCCCTGGcATtgcAT-TGCCAGAGTgaTgTCTGTtTCT
CtTCTCTT-----------------------------aAATAAATAAATA----------
Attt-----------------
>input_080.bnk
-----------------GgGAAaTagcTCAcTGG------TAGAGCAcAGGACTTGCATG
CCTGAG---GTTCC-gGTTtaATCCCTGGtgCCACATGTA-CAGAGTGGTGCTCTGCTTC
TCTCTcTCTcttgaaatcTTCTCA-------------TATGAAATAAAtA----------
AaAattttaaaAaa-------
>input_124.bnk
-----------------gGGAGgTaGCTCAGTgG------TAGAGCAcAGGACTT-CATG
c-TGAG---GtCCTggGTTtgATCCC-AGCAccaCATaTG-cAGAgtg-tgcTCTgttTc
TCTcTctcTcT-------cTCTcac---------AtaaAatAAATAAAtA----------
ATtTTtAAAaaa---------
>input_071.bnk
-----------------------TTGC-AAATGG-----CTAGGGC-ATGGATCTGTAaG
CATTAA---GTCCTGAATTCAATCCCCAGCATTGCATGTGCCATAGTCATGCTCTGCTTC
TCTTTTTT-----------------------------GTATTAATAAATA----------
ACATTTTT-------------
>input_157.bnk
-----------------gcGggGTGt--CAGtaG------TAGAgtACAGGACTTGtAaG
CATGAG---gTtCTaAgTTcAAtCtCTAaCACcAtATataaCAGAGTaATGCTCTGgTtc
TCTTTtcTCTt------------------------------taatAAAta----------
AATTtaAAtAAAtattaaa-a
>input_079.bnk
-----------------gGGAaATaGCTCAaCTG-----GTAGAGC-AcGGACTT-CATG
CCTGAG---GTTCCtGGTTcgATCCCTGGCAccACATGTACCAGAGTGGTGCTCTGGCTT
CTCTCtCtctC--------------------------ctcTcatTGAAactctctttCTc
AATgtAATAAATAAAA----a
>input_105.bnk
---------------ccaGgAGGTggA-cAATgG-----gTAaATA-TtGGacTT---aa
gATGAG---GTTCTGAGTTcaATCCCTagCATC-cATGtGttaGAgTGaT-cTCTgGTTT
TCTtTTt------------------------------TaATAAATAAATA----------
AATtTTTaAAAAAAa------
>input_196.bnk
-----------------gGGaGgtGc--CAGtG-------TAgAGt---GgACTTgcAGC
--TGAG---GCCt--AGTTc-ATCCCtAGCAcCA-ATaTgCCAGAGtgATGCTCTGGttT
ctCTCtcTCTTt-------------------------taaTaAttAAAtA----------
ATAAtTTTAAAaaa-------
>input_165.bnk
-----------------GGtAGGTtGCACAaTGG------AAgAAT-taGAaCTTctAAA
TTTtAG---GTCCTGAGTcCAATCCCaAGCACTGCATATGCTAGAGTGcTGCTtctGTgC
cCcTTACcCCC-------TTcTGT----------ATTCATgAAattaAAA----------
ATaATTAAAAAaa--------
>input_106.bnk
CAGAGGGATAAAGAATAGGAAAGCTAT-CAGGGGAGGGGATGGGATACGGAGTTCTGGTG
GTGGGAATTGTGTGGAGTTGTACCCCT-------CTTATCCTATGGTTTTGTCAATGTTT
CCTTT--------------------------------TTATAAATAAAAa----------
AATTTTTAAAAAAAa------
>input_108.bnk
CAGAGGGATAAAGAATAGGAAAGCTAT-CAGGGGAGGGGATGGGATACGGAGTTCTGGTG
GTGGGAATTGTGTGGAGTTGTACCCCT-------CTTATCCTATGGTTTTGTCAATGTTT
CCTTT--------------------------------TTATAAATaAAAA----------
AATTTTTAAAAAAAA------
>input_107.bnk
CAGAGGGATAAAGAATAGGAAAGCTAT-CAGGGGAGGGGATGGGATACAGAGTTCTGGTG
GTGGGAATTGTGTGGAGTTGTACCCCT-------CTTATCCTATGGTTTTGTCAGTGTTT
CCTTT--------------------------------TTATAAATAAAaA----------
AATTTTTAAAAAAAa------
>input_109.bnk
CAGAGGGaTAAAGAATAGGAAAGCTAT-CAGGGGAGGGGATGGGATACaGAGcTCTGGTG
---------GTGtGGAATTGTACCCCT-------CTTATCCTATGGTCTTGTCAGTGTTT
CCATT--------------------------------TTATAAATAAATA----------
AATTTTtAAAAAAAA------
